import 'server-only';
import {randomUUID} from 'node:crypto';
import {admin,rpc} from './supabase';
import {qboConfig,seal,unseal,tokenData,verifyCompany,apiUrl,type QboConfig,type QboTokens} from '../qbo-security';
import {readPath,queryRows,reviewCsv,reportCsv,type QboKind} from '../qbo-exchange';
const config=()=>{const c=qboConfig(process.env);if(!c)throw Error('QuickBooks connection is disabled; CSV review remains available');return c;};
async function row(workspace:string,create=false){if(create){const r=await admin().from('og_qbo_connections').upsert({workspace_id:workspace},{onConflict:'workspace_id',ignoreDuplicates:true});if(r.error)throw Error('QuickBooks private connection table has not been prepared');}const r=await admin().from('og_qbo_connections').select('*').eq('workspace_id',workspace).maybeSingle();if(r.error)throw Error('QuickBooks private connection storage is unavailable');return r.data;}
export async function connectionStatus(workspace:string){let c:QboConfig|null;try{c=qboConfig(process.env);}catch{return {configured:false,connected:false,status:'Hosting configuration requires review'};}if(!c)return {configured:false,connected:false,status:'Administrator registration required'};const r=await row(workspace);return {configured:true,connected:r?.status==='Connected'&&r.realm_id===c.realm&&r.environment===c.environment,status:r?.status??'Disconnected',company:r?.company_name??c.company,environment:c.environment};}
export async function beginConnection(workspace:string){config();return (await row(workspace,true)).generation as string;}
async function claim(workspace:string,generation:string){const lease=randomUUID();if(!await rpc('og_claim_qbo',{p_workspace:workspace,p_generation:generation,p_lease:lease}))throw Error('QuickBooks connection is busy or changed; refresh and try again');return lease;}
async function update(workspace:string,generation:string,lease:string,values:Record<string,unknown>){const r=await admin().from('og_qbo_connections').update({...values,updated:new Date().toISOString()}).eq('workspace_id',workspace).eq('generation',generation).eq('lease_token',lease).gt('lease_until',new Date().toISOString()).select('workspace_id');if(r.error||r.data?.length!==1)throw Error('QuickBooks connection changed; reconnect before another download');}
async function release(workspace:string,generation:string,lease:string){await admin().from('og_qbo_connections').update({lease_token:null,lease_until:null}).eq('workspace_id',workspace).eq('generation',generation).eq('lease_token',lease);}
async function jsonResponse(r:Response){if(!r.ok)throw Error('QuickBooks request failed (HTTP '+r.status+'); review connection or subscription');const content=await r.text();if(content.length>8000000)throw Error('QuickBooks response is too large for a review download');const p=JSON.parse(content);if(p.Fault)throw Error('QuickBooks could not provide this record or report');return p;}
export async function exchangeToken(c:QboConfig,params:Record<string,string>){const r=await fetch('https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(c.clientId+':'+c.secret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body:new URLSearchParams(params),signal:AbortSignal.timeout(15000),cache:'no-store',redirect:'error'});return tokenData(await jsonResponse(r));}
async function get(c:QboConfig,t:QboTokens,path:string){return jsonResponse(await fetch(apiUrl(c,path),{headers:{Authorization:'Bearer '+t.access,Accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(15000),redirect:'error'}));}
export async function finishConnection(workspace:string,generation:string,code:string){const c=config(),lease=await claim(workspace,generation);try{const t=await exchangeToken(c,{grant_type:'authorization_code',code,redirect_uri:c.origin+'/api/qbo/callback'}),name=verifyCompany(c,await get(c,t,'companyinfo/'+c.realm));await update(workspace,generation,lease,{ciphertext:seal(c,workspace,t),realm_id:c.realm,company_name:name,environment:c.environment,status:'Connected',generation:randomUUID(),lease_token:null,lease_until:null});return name;}finally{await release(workspace,generation,lease);}}
export async function disconnect(workspace:string){config();const r=await row(workspace);if(!r)return;const lease=await claim(workspace,r.generation);try{await update(workspace,r.generation,lease,{ciphertext:null,status:'Disconnected',generation:randomUUID(),lease_token:null,lease_until:null});}finally{await release(workspace,r.generation,lease);} // Local access is removed. The administrator can also revoke OG in Intuit Connected Apps.
}
export async function downloadReview(workspace:string,kind:QboKind,month:string,basis:'Cash'|'Accrual'){
 const c=config();readPath(kind,month,basis);const r=await row(workspace);if(!r||r.status!=='Connected'||!r.ciphertext||r.realm_id!==c.realm||r.environment!==c.environment)throw Error('Connect the approved QuickBooks company first');const lease=await claim(workspace,r.generation);try{let t=unseal(c,workspace,r.ciphertext);if(t.expires<=Date.now()+60000){try{if(t.refreshExpires!==null&&t.refreshExpires<=Date.now())throw Error('Refresh permission expired');await update(workspace,r.generation,lease,{ciphertext:null,status:'Reconnect required'}); // Durable quarantine also covers a process crash during token rotation.
 t=await exchangeToken(c,{grant_type:'refresh_token',refresh_token:t.refresh});await update(workspace,r.generation,lease,{ciphertext:seal(c,workspace,t),status:'Connected'});}catch{await update(workspace,r.generation,lease,{ciphertext:null,status:'Reconnect required'});throw Error('QuickBooks permission needs reconnection; no download or financial update was applied');}}
 const company=verifyCompany(c,await get(c,t,'companyinfo/'+c.realm));const raw:Record<string,unknown>={};
 async function all(k:Exclude<QboKind,'profit-loss'>){const rows:any[]=[];for(let page=0;page<4;page++){const payload=await get(c,t,readPath(k,month,basis,1+page*1000));raw[k+'-page-'+page]=payload;const entries=queryRows(k,payload);rows.push(...entries);if(entries.length<1000)return rows;}throw Error('Download exceeds 4,000 records; use a filtered QBO report export. Partial results were discarded');}
 let csv='',count:number|null=null;if(kind==='profit-loss'){const report=await get(c,t,readPath(kind,month,basis));raw.report=report;csv=reportCsv(report);}else{const rows=await all(kind),customers=kind==='payments'?await all('customers'):[];count=rows.length;csv=reviewCsv(kind,rows,company,month,customers);}
 return {csv,source:{provider:'QuickBooks Online',realm:c.realm,company,environment:c.environment,kind,month,basis:kind==='profit-loss'?basis:null,downloadedAt:new Date().toISOString(),records:count,complete:true,raw},fileName:'OG_QBO_'+kind+'_'+month};
 }finally{await release(workspace,r.generation,lease);}
}

export async function qboAudit(workspace:string,actor:string,event:string,detail:string){const r=await admin().from('og_app_logs').insert({id:randomUUID(),workspace_id:workspace,actor,category:'Integration',level:'Info',event,detail});if(r.error)throw Error('QuickBooks access could not be logged; review admin logs before continuing');}
