import 'server-only';
import {createClient} from '@supabase/supabase-js';
import {createServerClient} from '@supabase/ssr';
import {cookies} from 'next/headers';
export function serverConfig(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SERVER_KEY,workspace=process.env.OG_WORKSPACE_ID;if(!url||!secret||!workspace)throw Error('OG server configuration is incomplete');const parsed=new URL(url);if(parsed.protocol!=='https:'||!parsed.hostname.endsWith('.supabase.co'))throw Error('Invalid Supabase URL');return {url,secret,workspace};}
export function admin(){const {url,secret}=serverConfig();return createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function sessionClient(){const store=await cookies();const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw Error('OG sign-in configuration is incomplete');return createServerClient(url,key,{cookieOptions:{sameSite:'lax',secure:process.env.NODE_ENV==='production',httpOnly:true},cookies:{getAll:()=>store.getAll(),setAll:(list)=>{try{for(const {name,value,options} of list)store.set(name,value,options);}catch{/* Page rendering cannot write; proxy refreshes cookies. */}}}});}
export async function rpc(name:string,input:Record<string,unknown>){const {data,error}=await admin().rpc(name,input);if(error)throw Error('Database operation failed');return data;}

export async function registerSession(client:Awaited<ReturnType<typeof sessionClient>>,authId:string){const claims=await client.auth.getClaims();const sid=claims.data?.claims.session_id;if(claims.error||typeof sid!=='string')throw Error('Unable to verify login session');const {workspace}=serverConfig();const {data:member,error:memberError}=await admin().from('og_app_users').select('auth_id,status').eq('auth_id',authId).eq('workspace_id',workspace).maybeSingle();if(memberError||!member||member.status!=='Active')throw Error('No active OG access');const {error}=await admin().from('og_app_sessions').upsert({session_id:sid,auth_id:authId,workspace_id:workspace,active:true},{onConflict:'session_id'});if(error)throw Error('Session registration failed');}
