import 'server-only';
import {load,save} from '@/lib/storage';
import {audit} from '@/lib/pool';
import {WORK_MAILBOX,acceptWorkReply} from '@/lib/work-mail-model';
import {mailConfigured} from './mail-config';
export {mailConfigured} from './mail-config';
async function token(){if(!mailConfigured())throw Error('Outlook connection is not configured');const tenant=process.env.MS_TENANT_ID!;if(!/^[a-f0-9-]{36}$/i.test(tenant))throw Error('Invalid tenant configuration');const r=await fetch('https://login.microsoftonline.com/'+tenant+'/oauth2/v2.0/token',{method:'POST',body:new URLSearchParams({client_id:process.env.MS_CLIENT_ID!,client_secret:process.env.MS_CLIENT_SECRET!,scope:'https://graph.microsoft.com/.default',grant_type:'client_credentials'}),signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw Error('Outlook authentication failed');const j=await r.json();if(typeof j.access_token!=='string')throw Error('Outlook authentication failed');return j.access_token as string;}
const base='https://graph.microsoft.com/v1.0/users/'+encodeURIComponent(WORK_MAILBOX);
export function continuationAllowed(value:string){try{const u=new URL(value),b=new URL(base+'/mailFolders/inbox/messages');return u.origin===b.origin&&u.pathname===b.pathname&&!u.username&&!u.password&&!u.hash;}catch{return false;}}
export async function processWorkMail(workspace:string){if(!mailConfigured())return {configured:false,accepted:0,replies:0};const accessToken=await token();let accepted=0,replies=0;
 for(let i=0;i<2;i++){const current=await load(workspace),n=structuredClone(current.data),notice=n.workMail?.notifications.find(n=>n.state==='Pending'||n.state==='Pending connection');if(!notice)break;notice.state='Delivery uncertain';notice.attemptedAt=new Date().toISOString();audit(n,'Work email attempted',notice.id);try{await save(workspace,current.revision,crypto.randomUUID(),n,true);}catch{break;} // CAS claim before sending prevents two workers sending the same item.
 let state:'Accepted by Outlook'|'Rejected'|'Delivery uncertain'='Delivery uncertain',error='';try{const r=await fetch(base+'/sendMail',{method:'POST',headers:{Authorization:'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify({message:{subject:notice.subject,body:{contentType:'Text',content:notice.text},toRecipients:[{emailAddress:{address:WORK_MAILBOX}}],replyTo:[{emailAddress:{address:WORK_MAILBOX}}]},saveToSentItems:true}),signal:AbortSignal.timeout(20000)});if(r.status===202){state='Accepted by Outlook';accepted++;}else if(r.status>=400&&r.status<500){state='Rejected';error='Outlook rejected the request (HTTP '+r.status+').';}else error='Delivery result is uncertain; check Sent Items before retrying.';}catch{error='Delivery result is uncertain; check Sent Items before retrying.';}
 for(let tries=0;tries<3;tries++){const current=await load(workspace),n=structuredClone(current.data),entry=n.workMail?.notifications.find(n=>n.id===notice.id);if(!entry)break;entry.state=state;entry.error=error;audit(n,'Work email result',notice.id+' / '+state);try{await save(workspace,current.revision,crypto.randomUUID(),n,true);break;}catch{if(tries===2)throw Error('Email result could not be saved; queue retains uncertain delivery');}}
 }
 const initial=await load(workspace);if(!initial.data.workMail?.notifications.length)return {configured:true,accepted,replies};const runStart=new Date().toISOString();let next=initial.data.workMail.nextLink;const since=initial.data.workMail.cursor??initial.data.workMail.notifications[0].created;const query=new URLSearchParams({'$select':'id,subject,receivedDateTime,from,body,bodyPreview','$filter':'receivedDateTime ge '+since,'$top':'100'});const messages:any[]=[];
 for(let page=0;page<2;page++){const url=next??base+'/mailFolders/inbox/messages?'+query;if(!continuationAllowed(url))throw Error('Invalid Outlook continuation');const r=await fetch(url,{headers:{Authorization:'Bearer '+accessToken,Prefer:'outlook.body-content-type="text"'},cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Outlook replies could not be read');const j=await r.json();if(!Array.isArray(j.value))throw Error('Invalid Outlook response');messages.push(...j.value);next=j['@odata.nextLink'];if(!next)break;}
 for(let tries=0;tries<3;tries++){const current=await load(workspace),n=structuredClone(current.data);if(!n.workMail)break;for(const m of messages)if(acceptWorkReply(n,m))replies++;n.workMail.nextLink=next;if(!next)n.workMail.cursor=new Date(Date.parse(runStart)-60000).toISOString();audit(n,'Outlook reply review',messages.length+' inbox messages reviewed; matched replies retained');try{await save(workspace,current.revision,crypto.randomUUID(),n,true);break;}catch{replies=0;if(tries===2)throw Error('Reply review conflicted; retry synchronization');}}
 return {configured:true,accepted,replies};
}
