import assert from 'node:assert/strict';
import {fixture} from './model-loader.mjs';
await fixture();
const {postInvoiceBatch,validateInvoiceImports,linkPendingInvoices}=await import('./.mock-runtime/invoice-import.mjs');
const {validate}=await import('./.mock-runtime/pool.mjs');
const {qboBillRows,incomeRows}=await import('./.mock-runtime/accounting-model.mjs');
const {postPartIssue,partStock,stockValue}=await import('./.mock-runtime/procurement-model.mjs');
const old=await fixture(),unit=old.units[0].number;
const row={sourceId:'source-1',unit,qboClass:unit,kind:'Labor',vendor:'QA vendor',reference:'QA-1',date:'2026-10-01',description:'QA labor',cents:10000,gl:'81200',accountName:'OTHER CONDO EXPENSE:Repairs and Maintenance',paymentState:'Paid',paymentMonth:'2026-09',notes:'Source payment recorded separately',source:'QA workbook row 2'};
const source={period:'2026-10',fileName:'QA-source.json',rows:[row,{...row,sourceId:'source-2',kind:'Materials',reference:'QA-2',cents:2000},{...row,sourceId:'source-3',unit:'9999',qboClass:'9999',reference:'QA-3',cents:3000},{...row,sourceId:'source-4',unit:'',qboClass:'',kind:'Stock',gl:'12000',accountName:'Inventory of Supplies',reference:'QA-4',cents:26570,quantity:5,stockName:'QA contactor',sku:'QA-STOCK',paymentState:'Unpaid',paymentMonth:''},{...row,sourceId:'source-5',unit:'',qboClass:'',kind:'Operating',gl:'61100',accountName:'Prospective Tenant Research',reference:'QA-5',cents:6495,paymentState:'Unpaid',paymentMonth:''}]};
const next=structuredClone(old),input={...source,hash:'source-test',reviewer:'QA reviewer'};
const b=postInvoiceBatch(next,input);validate(old,next);
assert.equal(b.rows.length,5);assert.equal(next.statements.find(s=>s.id===b.rows[0].statementId).expenses.find(e=>e.id===b.rows[0].recordId).classification,'Unit repair labor');assert.equal(b.rows.reduce((n,r)=>n+r.cents,0),48065);
assert.deepEqual(b.rows.filter(r=>r.status==='Held').map(r=>r.unit).sort(),['9999']);
assert.equal(b.rows.filter(r=>r.status==='Posted'&&r.statementId).length,2);
assert.equal(b.rows.filter(r=>r.statementId).reduce((n,r)=>n+r.cents,0),12000);
assert.deepEqual(next.accounting,old.accounting);assert.deepEqual(next.operations,old.operations);assert.deepEqual(next.poolAssumptions,old.poolAssumptions);
const p=next.procurement.parts[0];assert.equal(partStock(next.procurement,p.id),5);assert.equal(stockValue(next.procurement),26570);assert.equal(p.priceConfirmed,false);
assert.throws(()=>postPartIssue(next,{partId:p.id}),/unit price/);
assert.equal(qboBillRows(next,'2026-10').filter(r=>b.rows.some(s=>s.recordId===r.id)).length,0);
assert.equal(incomeRows(next,'2026-10').find(r=>r.id===b.rows[0].recordId).gl,'81200');
assert.throws(()=>postInvoiceBatch(next,input),/already recorded/);
const changed=structuredClone(next);changed.invoiceImports[0].rows[0].cents++;assert.throws(()=>validateInvoiceImports(next,changed),/immutable/);
const missing=structuredClone(next);missing.statements.find(s=>s.id===b.rows[0].statementId).expenses.find(e=>e.id===b.rows[0].recordId).cents++;assert.throws(()=>validateInvoiceImports(next,missing),/match its QBO source/);
const locked=structuredClone(old);locked.statements.find(s=>s.unitId===locked.units.find(u=>u.number===unit).id&&s.period==='2026-10').status='Approved';assert.throws(()=>postInvoiceBatch(locked,input),/draft/);
const withUnit=structuredClone(next),newUnit={...withUnit.units[0],id:'pending-unit',number:'9999'};withUnit.units.push(newUnit);withUnit.statements.push({...withUnit.statements.find(s=>s.unitId===withUnit.units[0].id&&s.period==='2026-10'),id:'pending-statement',unitId:newUnit.id,expenses:[]});const priorLink=structuredClone(withUnit);assert.equal(linkPendingInvoices(withUnit,'2026-10','QA reviewer'),1);validateInvoiceImports(priorLink,withUnit);assert.throws(()=>linkPendingInvoices(withUnit,'2026-10','QA reviewer'),/missing unit/);assert.equal(qboBillRows(withUnit,'2026-10').filter(r=>withUnit.invoiceLinks.some(l=>l.recordId===r.id)).length,0);
console.log('PASS invoice batch: source rows, unit postings, pending owner link, stock, duplicate guard, immutable source and unchanged bank/tenant records');
