import assert from 'node:assert/strict';
import {fixture} from './model-loader.mjs';
await fixture();
const {validateLeasing,guestCardsFromCSV,renewalCandidates,leasingActivity}=await import('./.mock-runtime/leasing-model.mjs');
const {validateOperations,emptyOperations}=await import('./.mock-runtime/operations-model.mjs');
const units=new Set(['u1']),ops=emptyOperations();
validateOperations(ops,units);
const imported=guestCardsFromCSV([['name','email','unit','phone','source','agent','notes'],['Jane Doe','jane@example.test','101','210-000-0000','Referral','Miguel','Tour requested']],ops,[{id:'u1',number:'101'}],'2026-10-04');
assert.equal(imported.length,1);assert.equal(imported[0].unitId,'u1');assert.equal(imported[0].stage,'Inquiry');ops.prospects.push(...imported);
assert.throws(()=>guestCardsFromCSV([['name','email','unit'],['Jane','jane@example.test','101']],ops,[{id:'u1',number:'101'}],'2026-10-04'),/Duplicate/);
assert.throws(()=>guestCardsFromCSV([['name','email','unit'],['Jane','bad-email','101']],emptyOperations(),[{id:'u1',number:'101'}],'2026-10-04'),/Invalid/);
assert.throws(()=>guestCardsFromCSV([['name','email','unit'],['Jane','','999']],emptyOperations(),[{id:'u1',number:'101'}],'2026-10-04'),/Invalid/);
ops.rentalApplications=[{id:'a1',prospectId:imported[0].id,unitId:'u1',name:'Jane',email:'jane@example.test',phone:'',date:'2026-10-04',moveIn:'2026-11-01',status:'In review',fee:5000,decisionReference:'',notes:''}];
ops.leases=[{id:'l1',unitId:'u1',tenant:'Jane Doe',signedDate:'2026-01-01',start:'2026-01-01',end:'2026-10-31',rent:100000,status:'Active',notes:''}];
ops.leaseTemplates=[{id:'t1',name:'Supplied lease template',kind:'Renewal',source:'Office document reference',content:'',active:true}];
ops.leaseRenewals=[{id:'r1',leaseId:'l1',start:'2026-11-01',end:'2027-10-31',rent:101000,status:'Draft',templateId:'t1',externalReference:'',notes:''}];
ops.showingSlots=[{id:'s1',unitId:'u1',date:'2026-10-05',time:'10:00',agent:'Agent',status:'Available',notes:''}];
ops.vacancyListings=[{id:'v1',unitId:'u1',available:'2026-11-01',advertisedRent:100000,description:'',photoReference:'',status:'Prepared',notes:''}];
ops.leasingSettings=[{id:'settings1',name:'Application version 1',fee:5000,questions:'Contact details',instructions:'Office review',screeningCriteria:'External criteria'}];
validateOperations(ops,units);const old=structuredClone(ops);
assert.equal(renewalCandidates(ops.leases,'2026-10-01','2026-10-31').length,1);assert.equal(renewalCandidates(ops.leases,'2026-11-01','2026-11-30').length,0);
ops.rentalApplications[0].status='Decision recorded externally';assert.throws(()=>validateLeasing(ops,units),/decision reference/);ops.rentalApplications[0].decisionReference='Office evidence';
ops.leaseRenewals[0].status='Signed externally';assert.throws(()=>validateLeasing(ops,units),/evidence/);ops.leaseRenewals[0].externalReference='Signed document ref';
ops.leaseRenewals[0].start='2026-10-31';assert.throws(()=>validateLeasing(ops,units),/term/);ops.leaseRenewals[0].start='2026-11-01';
ops.showingSlots.push({...ops.showingSlots[0],id:'s2'});assert.throws(()=>validateLeasing(ops,units),/Duplicate/);ops.showingSlots.pop();
ops.rentalApplications[0].unitId='other';assert.throws(()=>validateLeasing(ops,units),/Unknown/);ops.rentalApplications[0].unitId='u1';
ops.leaseTemplates=[];assert.throws(()=>validateLeasing(ops,units,old),/history/);ops.leaseTemplates=old.leaseTemplates;
validateOperations(ops,units,old);assert.equal(ops.leases[0].rent,100000);assert.equal(ops.communications.length,0);assert.equal(ops.tenantEntries,undefined);
let activity=leasingActivity(ops,'2026-10-01','2026-10-31');assert.equal(activity.guests.length,1);assert.equal(activity.applications.length,1);assert.equal(activity.agents[0].name,'Miguel');assert.equal(activity.sources[0].name,'Referral');
activity=leasingActivity(ops,'2026-11-01','2026-11-30');assert.equal(activity.guests.length,0);assert.equal(activity.applications.length,0);
assert.equal(leasingActivity(ops,'2026-11-01','2026-10-01').valid,false);
ops.prospects.push({id:'legacy',name:'Old guest',email:'',unitId:'',stage:'Inquiry',tour:'',notes:''});assert.equal(leasingActivity(ops,'2026-10-01','2026-10-31').undated,1);
console.log('PASS Leasing: legacy compatibility, guest import deduplication, unit links, renewal dates and evidence, showing collisions, preserved history and original lease');

