import assert from 'node:assert/strict';
import {fixture} from './model-loader.mjs';
await fixture();
const {generateRecurringWork,nextRecurringDate,validateMaintenanceRecords}=await import('./.mock-runtime/maintenance-model.mjs');
const {emptyOperations,validateOperations}=await import('./.mock-runtime/operations-model.mjs');
assert.equal(nextRecurringDate('2026-01-31',1),'2026-02-28');
assert.equal(nextRecurringDate('2028-01-31',1),'2028-02-29');
assert.equal(nextRecurringDate('2026-12-15',3),'2027-03-15');
assert.throws(()=>nextRecurringDate('2026-02-30',1));assert.throws(()=>nextRecurringDate('2026-01-01',0));
const ops=emptyOperations(),units=new Set(['u1']);
validateOperations(ops,units);
ops.recurringWork=[{id:'r1',kind:'Inspection',unitId:'u1',title:'Filter inspection',description:'Check filter',assignee:'Tech',vendor:'',nextDate:'2026-10-01',intervalMonths:1,active:true,notes:'Monthly check'}];
const w=generateRecurringWork(ops,'r1','2026-10-04');
assert.equal(w.kind,'Inspection');assert.equal(w.scheduled,'2026-10-01');assert.equal(w.status,'New');assert.equal(w.permissionToEnter,'No');assert.equal(w.ownerApproved,false);assert.equal(w.estimate,0);assert.equal(ops.recurringWork[0].nextDate,'2026-11-01');
assert.throws(()=>generateRecurringWork(ops,'r1','2026-10-04'),/not due/);
ops.recurringWork[0].nextDate='2026-10-01';assert.throws(()=>generateRecurringWork(ops,'r1','2026-10-04'),/already/);ops.recurringWork[0].nextDate='2026-11-01';
validateOperations(ops,units);
ops.recurringWork[0].active=false;assert.throws(()=>generateRecurringWork(ops,'r1','2026-12-01'));ops.recurringWork[0].active=true;
ops.purchaseOrders=[{id:'p1',number:'PO-1',unitId:'u1',workOrderId:w.id,supplier:'Vendor',description:'Filters',date:'2026-10-04',expectedDate:'',amount:12345,status:'Draft',approvedBy:'',notes:''}];
ops.fixedAssets=[{id:'a1',tag:'AC-1',name:'HVAC',unitId:'u1',serial:'123',acquired:'2026-01-01',cost:100000,status:'In service',nextService:'2027-01-01',notes:''}];
validateOperations(ops,units);const old=structuredClone(ops);
ops.purchaseOrders[0].status='Approved';assert.throws(()=>validateOperations(ops,units),/approval/);ops.purchaseOrders[0].approvedBy='Manager';validateOperations(ops,units);
ops.purchaseOrders[0].amount=-1;assert.throws(()=>validateOperations(ops,units),/purchase order/);ops.purchaseOrders[0].amount=12345;
ops.fixedAssets[0].unitId='other';assert.throws(()=>validateMaintenanceRecords(ops,units),/Unknown/);ops.fixedAssets[0].unitId='u1';
ops.fixedAssets=[];assert.throws(()=>validateMaintenanceRecords(ops,units,old),/history/);ops.fixedAssets=structuredClone(old.fixedAssets);
delete ops.workOrders[0].recurringKey;assert.throws(()=>validateMaintenanceRecords(ops,units,old),/source/);ops.workOrders[0].recurringKey=old.workOrders[0].recurringKey;
validateOperations(ops,units,old);
console.log('PASS Maintenance recurrence, approval, validation, legacy data and history preservation');

