import assert from 'node:assert/strict';
import {fixture} from './model-loader.mjs';
const d=await fixture();
const {emptyAccounting,validateAccounting}=await import('./.mock-runtime/accounting-model.mjs');
const {payableState,payableAging,postPayableDocument,prepareRecurringPayable,recurringPayablesDue,parsePayableBatch,importPayableBatch,approvePayableBatch,payableBatchHeaders}=await import('./.mock-runtime/payables-ledger.mjs');
const {emptyNativeAccounting,ledgerBalance}=await import('./.mock-runtime/native-accounting.mjs');
d.accounting=emptyAccounting();d.accounting.native=emptyNativeAccounting();d.accounting.payablesLedger={documents:[],decisions:[],applications:[],rules:[]};
d.glControls={charts:[{id:'chart',company:'Synthetic QA Company',accounts:[['bank','Bank'],['ap','Accounts Payable'],['expense','Expenses'],['equity','Equity']].map(([key,type])=>({key,name:key,number:key,type,active:true}))}],mappings:[]};
const actor={reviewer:'QA',created:'2026-10-09T00:00:00Z'};
d.accounting.native.books.push({...actor,id:'book',company:'Synthetic QA Company',chartId:'chart',openingDate:'2026-09-30',source:'Synthetic opening',opening:[{accountKey:'bank',debit:100000,credit:0,unitId:'',memo:''},{accountKey:'equity',debit:0,credit:100000,unitId:'',memo:''}]});
const bill={...actor,id:'bill',bookId:'book',kind:'Bill',payee:'Synthetic Supplier',date:'2026-10-01',due:'2026-10-28',reference:'QA-BILL',source:'Verified synthetic invoice',payableKey:'ap',recurringId:'',lines:[{accountKey:'expense',unitId:d.units[0].id,cents:10000,description:'Synthetic repair labor',serviceFrom:'2026-10-01',serviceTo:'2026-10-01'}]};
const base=structuredClone(d);d.accounting.payablesLedger.documents.push(bill);validateAccounting(d,base);assert.equal(payableState(d,bill).status,'Pending approval');assert.throws(()=>postPayableDocument(d,'bill','2026-10-02','QA',true),/Approve/);
d.accounting.payablesLedger.decisions.push({...actor,id:'approve',documentId:'bill',date:'2026-10-02',action:'Approved',reason:'Invoice reviewed'});const posted=postPayableDocument(d,'bill','2026-10-02','QA',true);validateAccounting(posted,d);assert.equal(ledgerBalance(posted,'book','ap','2026-10-31'),-10000);assert.equal(payableState(posted,bill).status,'Open');assert.throws(()=>postPayableDocument(posted,'bill','2026-10-02','QA',true),/Approve/);
const paid=structuredClone(posted);paid.accounting.native.entries.push({...actor,id:'paid',bookId:'book',date:'2026-10-05',reference:'QA-CHECK',memo:'Verified synthetic supplier payment',lines:[{accountKey:'ap',debit:4000,credit:0,unitId:'',memo:''},{accountKey:'bank',debit:0,credit:4000,unitId:'',memo:''}],reverses:'',recurringId:'',sourceSystem:'',externalId:''});paid.accounting.payablesLedger.applications.push({...actor,id:'apply',billId:'bill',date:'2026-10-05',cents:4000,paymentEntryId:'paid',creditId:''});validateAccounting(paid,posted);assert.equal(payableState(paid,bill).status,'Partially settled');assert.equal(payableState(paid,bill).remaining,6000);assert.equal(ledgerBalance(paid,'book','bank','2026-10-31'),96000);assert.equal(payableState(paid,bill,'2026-10-04').applied,0);
const over=structuredClone(paid);over.accounting.payablesLedger.applications.push({...actor,id:'over',billId:'bill',date:'2026-10-05',cents:1,paymentEntryId:'paid',creditId:''});assert.throws(()=>validateAccounting(over,paid),/exceed/);
const credit={...bill,id:'credit',kind:'Credit',reference:'QA-CREDIT',lines:[{...bill.lines[0],cents:6000}]};paid.accounting.payablesLedger.documents.push(credit);paid.accounting.payablesLedger.decisions.push({...actor,id:'credit-approve',documentId:'credit',date:'2026-10-05',action:'Approved',reason:'Verified credit'});const credited=postPayableDocument(paid,'credit','2026-10-05','QA',true);credited.accounting.payablesLedger.applications.push({...actor,id:'credit-applied',billId:'bill',date:'2026-10-05',cents:6000,paymentEntryId:'',creditId:'credit'});validateAccounting(credited,paid);assert.equal(payableState(credited,bill).status,'Settled');assert.equal(ledgerBalance(credited,'book','ap','2026-10-31'),0);assert.equal(ledgerBalance(credited,'book','bank','2026-10-31'),96000);
const dup=structuredClone(d);dup.accounting.payablesLedger.documents.push({...bill,id:'duplicate'});assert.throws(()=>validateAccounting(dup,d),/Duplicate/);const immutable=structuredClone(d);immutable.accounting.payablesLedger.documents[0].lines[0].cents=1;assert.throws(()=>validateAccounting(immutable,d),/immutable/);
const hold=structuredClone(posted);hold.accounting.payablesLedger.decisions.push({...actor,id:'hold',documentId:'bill',date:'2026-10-05',action:'On hold',reason:'Changed'});assert.throws(()=>validateAccounting(hold,posted),/locked/);
const closed=structuredClone(base);closed.closeControls={events:[{period:'2026-10',kind:'Closed'}]};assert.throws(()=>validateAccounting(d,closed),/Reopen/);
const rule={...actor,id:'rule',ruleId:'rule',version:1,active:true,name:'Monthly synthetic bill',start:'2026-10',end:'',day:31,dueDays:15,document:{bookId:bill.bookId,kind:bill.kind,payee:bill.payee,source:bill.source,payableKey:bill.payableKey,lines:bill.lines}};d.accounting.payablesLedger.rules.push(rule);const prepared=prepareRecurringPayable(d,'rule','2026-10','QA');validateAccounting(prepared,d);assert.equal(recurringPayablesDue(prepared,'2026-10').length,0);assert.throws(()=>prepareRecurringPayable(prepared,'rule','2026-10','QA'),/current due/);assert.equal(prepared.accounting.payablesLedger.documents.at(-1).due,'2026-11-15');assert.equal(payableState(prepared,prepared.accounting.payablesLedger.documents.at(-1)).status,'Pending approval');
console.log('Itemized payable approval, posting, partial settlement, credits and recurring tests passed.');

assert.equal(payableAging(paid,'book','2026-10-31')[0].days30,6000);assert.equal(payableAging(credited,'book','2026-10-31').length,0);

const combinedHold=structuredClone(posted);combinedHold.accounting.payablesLedger.decisions.push({...actor,id:'same-payload-hold',documentId:'bill',date:'2026-10-05',action:'On hold',reason:'Invalid later hold'});assert.throws(()=>validateAccounting(combinedHold,{...d,accounting:{...d.accounting,payablesLedger:{...d.accounting.payablesLedger,rules:[]}}}),/locked/);

const header=payableBatchHeaders.join(','),bulk=header+'\nBill,Synthetic Supplier,2026-10-01,2026-10-28,QA-BULK,Verified source,ap,expense,,20.00,Repair labor,,\nBill,Synthetic Supplier,2026-10-01,2026-10-28,QA-BULK,Verified source,ap,expense,,30.00,Repair parts,,';const parsed=parsePayableBatch(base,'book',bulk,'QA');assert.equal(parsed.length,1);assert.equal(parsed[0].lines.length,2);const imported=importPayableBatch(base,'book',bulk,'QA',true);validateAccounting(imported,base);assert.equal(imported.accounting.native.entries.length,0);assert.throws(()=>importPayableBatch(imported,'book',bulk,'QA',true),/Duplicate/);assert.throws(()=>parsePayableBatch(base,'book',bulk.replace('Repair parts','Repair parts').replace('ap,expense,,30','ap,unknown,,30'),'QA'),/Unknown/);assert.deepEqual(base.accounting.payablesLedger.documents,[]);const approved=approvePayableBatch(imported,[imported.accounting.payablesLedger.documents[0].id],'2026-10-01','All original line evidence verified','QA',true);validateAccounting(approved,imported);assert.equal(payableState(approved,approved.accounting.payablesLedger.documents[0]).status,'Approved');assert.equal(approved.accounting.native.entries.length,0);assert.throws(()=>approvePayableBatch(approved,[approved.accounting.payablesLedger.documents[0].id],'2026-10-01','Retry','QA',true),/awaiting/);console.log('Bulk itemized payable imports validate atomically; grouped approvals preserve source and create no payments.');
