import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
const model=await import('data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(await readFile(new URL('../lib/subscription.ts',import.meta.url),'utf8'),{mode:'transform'})));
assert.equal(model.subscriptionTotal(0),999);assert.equal(model.subscriptionTotal(96),11559);assert.equal(model.subscriptionTotal(2),1219);assert.throws(()=>model.subscriptionTotal(-1));assert.throws(()=>model.subscriptionTotal(1.5));
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema og_private;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create table og_private.workspaces(user_id text primary key,revision integer,operation text);
create table og_private.revisions(user_id text,revision integer,operation text,payload jsonb);
create table public.og_companies(workspace_id text primary key references og_private.workspaces(user_id),name text,login_slug text unique,email_domain text,status text default 'Active');
create table public.og_app_users(auth_id uuid primary key,workspace_id text,name text,email text,role text,property_ids text[],status text,must_change_password boolean,updated timestamptz default now());
create table public.og_app_sessions(auth_id uuid,workspace_id text,active boolean);
create table public.og_platform_owners(auth_id uuid,email text,active boolean);`);
const owner='00000000-0000-4000-8000-000000000001',client='00000000-0000-4000-8000-000000000002',newClient='00000000-0000-4000-8000-000000000003',unverified='00000000-0000-4000-8000-000000000004';
await db.query("insert into auth.users values($1,'owner@example.test',now()),($2,'client@example.test',now()),($3,'new@example.test',now()),($4,'unverified@example.test',null)",[owner,client,newClient,unverified]);
await db.query("insert into public.og_platform_owners values($1,'owner@example.test',true)",[owner]);
await db.exec("insert into og_private.workspaces values('company-a',0,'initial');insert into public.og_companies values('company-a','Company A','company-a','','Active');");
const payload={units:[{id:'unit-a',number:'101'},{id:'unit-b',number:'102'}],owners:[],statements:[],properties:[{id:'property-a'}]};await db.query("insert into og_private.revisions values('company-a',0,'initial',$1)",[JSON.stringify(payload)]);await db.query("insert into public.og_app_users values($1,'company-a','Admin','client@example.test','Global Admin',array['property-a'],'Active',false,now())",[client]);
await db.exec(await readFile(new URL('../supabase/platform-billing.sql',import.meta.url),'utf8'));
const month=model.billingMonth();
await assert.rejects(db.query('select public.og_draft_subscription_invoice($1,$2,$3)',[owner,'company-a',month]),/Activate company/);
await db.query("select public.og_manage_subscription($1,'company-a','status','Active',null)",[owner]);
await assert.rejects(db.query("select public.og_manage_subscription($1,'company-a','status','Active',null)",[client]),/Super Admin/);
await db.query("select public.og_manage_subscription($1,'company-a','unit','disabled','unit-b')",[client]);
let invoice=(await db.query('select public.og_draft_subscription_invoice($1,$2,$3) as invoice',[owner,'company-a',month])).rows[0].invoice;
assert.equal(invoice.total_cents,1109);assert.deepEqual(invoice.unit_ids,['unit-a']);
await db.query("select public.og_manage_subscription($1,'company-a','unit','enabled','unit-b')",[client]);
const repeat=(await db.query('select public.og_draft_subscription_invoice($1,$2,$3) as invoice',[owner,'company-a',month])).rows[0].invoice;assert.deepEqual(repeat,invoice);assert.equal((await db.query('select count(*)::int as n from public.og_subscription_invoices')).rows[0].n,1);
await assert.rejects(db.query('select public.og_billing_overview($1,null)',[client]),/Billing access denied/);
await assert.rejects(db.query("select public.og_manage_subscription($1,'company-a','unit','disabled','foreign-unit')",[client]),/Select a company unit/);
const blank={units:[],owners:[],statements:[],properties:[{id:'new-property'}]};
await assert.rejects(db.query('select public.og_onboard_company($1,$2,$3,$4,$5,$6)',[unverified,'Other','other','','Other',JSON.stringify(blank)]),/Verified client identity/);
const args=[newClient,'New Company','new-company','','New Admin',JSON.stringify(blank)];const workspace=(await db.query('select public.og_onboard_company($1,$2,$3,$4,$5,$6) as id',args)).rows[0].id;assert.equal((await db.query('select public.og_onboard_company($1,$2,$3,$4,$5,$6) as id',args)).rows[0].id,workspace);
await assert.rejects(db.query('select public.og_billing_overview($1,$2)',[client,workspace]),/Billing access denied/);
await assert.rejects(db.query("select public.og_manage_subscription($1,$2,'unit','disabled','unit-a')",[newClient,'company-a']),/Billing access denied/);
assert.equal((await db.query('select status from public.og_subscriptions where workspace_id=$1',[workspace])).rows[0].status,'Pending activation');
assert.deepEqual((await db.query('select payload from og_private.revisions where user_id=$1',[workspace])).rows[0].payload,blank);
await assert.rejects(db.query("select public.og_platform_manage_user($1,'company-a',$2,'Admin','Global Admin','Disabled')",[owner,client]),/Keep one active Company Admin/);await assert.rejects(db.query("select public.og_platform_manage_user($1,'company-a',$2,'Admin','Global Admin','Active')",[client,client]),/Super Admin/);await db.exec('set role authenticated');await assert.rejects(db.query('select * from public.og_subscription_invoices'),/permission denied/);await assert.rejects(db.query('select public.og_billing_overview($1,$2)',[client,'company-a']),/permission denied/);await db.exec('reset role');
await db.query("select public.og_manage_subscription($1,'company-a','cancel',null,null)",[client]);
assert.equal((await db.query("select status from public.og_subscriptions where workspace_id='company-a'")).rows[0].status,'Cancelled');
await assert.rejects(db.query('select public.og_draft_subscription_invoice($1,$2,$3)',[owner,'company-a',month]),/Activate company/);
const cancelledAudit=(await db.query("select count(*)::int as n from public.og_platform_audit where event='Subscription cancel'")).rows[0].n;
await db.query("select public.og_manage_subscription($1,'company-a','cancel',null,null)",[client]);
assert.equal((await db.query("select count(*)::int as n from public.og_platform_audit where event='Subscription cancel'")).rows[0].n,cancelledAudit);
await db.query("select public.og_manage_subscription($1,'company-a','restart',null,null)",[client]);
assert.equal((await db.query("select status from public.og_subscriptions where workspace_id='company-a'")).rows[0].status,'Pending activation');
await assert.rejects(db.query("select public.og_manage_subscription($1,'company-a','status','Active',null)",[client]),/Super Admin/);
assert.equal((await db.query('select count(*)::int as n from public.og_subscription_invoices')).rows[0].n,1);
await assert.rejects(db.query("select public.og_manage_subscription($1,'company-a','cancel',null,null)",[newClient]),/Billing access denied/);
await db.query("select public.og_manage_subscription($1,'company-a','status','Active',null)",[owner]);
await assert.rejects(db.query("select public.og_manage_subscription($1,'company-a','restart',null,null)",[client]),/Only cancelled/);
const billingClient='00000000-0000-4000-8000-000000000005';
await db.query("insert into auth.users values($1,'billing@example.test',now())",[billingClient]);
await assert.rejects(db.query('select public.og_onboard_company_billing($1,$2,$3,$4,$5,$6,$7,$8)',[billingClient,'Billing Company','billing-company','','Billing Admin',JSON.stringify(blank),'bad-email','ACH']),/valid receipt email/);
assert.equal((await db.query('select count(*)::int as n from public.og_app_users where auth_id=$1',[billingClient])).rows[0].n,0);
const billingArgs=[billingClient,'Billing Company','billing-company','','Billing Admin',JSON.stringify(blank),'Accounts@Example.test','ACH'];
const billingWorkspace=(await db.query('select public.og_onboard_company_billing($1,$2,$3,$4,$5,$6,$7,$8) as id',billingArgs)).rows[0].id;
let billingRow=(await db.query('select receipt_email,payment_method from public.og_subscriptions where workspace_id=$1',[billingWorkspace])).rows[0];
assert.equal(billingRow.receipt_email,'accounts@example.test');assert.equal(billingRow.payment_method,'ACH');
const retryArgs=[...billingArgs];retryArgs[6]='other@example.test';
assert.equal((await db.query('select public.og_onboard_company_billing($1,$2,$3,$4,$5,$6,$7,$8) as id',retryArgs)).rows[0].id,billingWorkspace);
assert.equal((await db.query('select receipt_email from public.og_subscriptions where workspace_id=$1',[billingWorkspace])).rows[0].receipt_email,'accounts@example.test');
await assert.rejects(db.query("select public.og_manage_subscription($1,$2,'receipt_email','foreign@example.test',null)",[client,billingWorkspace]),/Billing access denied/);
await db.query("select public.og_manage_subscription($1,$2,'receipt_email','updated@example.test',null)",[billingClient,billingWorkspace]);
assert.equal((await db.query('select receipt_email from public.og_subscriptions where workspace_id=$1',[billingWorkspace])).rows[0].receipt_email,'updated@example.test');
await db.exec('set role authenticated');await assert.rejects(db.query('select public.og_onboard_company_billing($1,$2,$3,$4,$5,$6,$7,$8)',billingArgs),/permission denied/);await db.exec('reset role');
await db.close();console.log('Platform billing: exact cents, disabled units, frozen monthly drafts, duplicate prevention, verified blank onboarding and tenant isolation passed');
