import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import {fixture} from './model-loader.mjs';
await fixture();
const root=new URL('./.mock-runtime/',import.meta.url);
let code=stripTypeScriptTypes(await readFile(new URL('../lib/profitability.ts',import.meta.url),'utf8'),{mode:'transform'});
code=code.replace(/from '(\.\/[^']+)'/g,(_,p)=>"from '"+p+".mjs'");
await writeFile(new URL('profitability.mjs',root),code);
const {monthlyProfitability}=await import(new URL('profitability.mjs',root));
const {seed}=await import(new URL('seed.mjs',root));
const {applyExpectedAllocation}=await import(new URL('allocation.mjs',root));
const {refreshPoolDrafts,latest}=await import(new URL('pool.mjs',root));
const {emptyAccounting}=await import(new URL('accounting-model.mjs',root));
const d=seed(),period='2026-10',poolId=d.pools[0].id;
d.accounting=emptyAccounting();
const units=d.units.filter(u=>u.participating);
d.operations={tenants:units.map(u=>({id:'t-'+u.id,unitId:u.id,firstName:'Test',lastName:u.number,rent:100000,start:'2026-10-01',end:'',notes:''})),tenantEntries:[],occupancy:[],workOrders:[],events:[],communications:[],prospects:[],leases:[],bankRecords:[]};
const before=JSON.stringify(d);
let r=monthlyProfitability(d,period,poolId,'Contract rent');
assert.equal(r.rows.length,95);assert.equal(r.complete,false);assert.equal(r.net,null);assert.equal(JSON.stringify(d),before);
d.settings[0].electricTotal=9500;d.settings[0].electricConfirmed=true;
refreshPoolDrafts(d,d.settings[0]);
applyExpectedAllocation(d,poolId,period,[],'Test reviewer',{total:9500000,source:'Verified expected total'});
r=monthlyProfitability(d,period,poolId,'Contract rent');
assert.equal(r.complete,true);assert.equal(r.totals.rent,9500000);assert.equal(r.totals.pool,9500000);
assert.equal(r.totals.electricity,9500);assert(r.totals.contribution<0);
assert.equal(r.net,r.totals.contribution-r.operatingExpenses);
const feeTest=structuredClone(d),feeStatement=feeTest.statements.find(s=>s.unitId===units[0].id);feeStatement.expenses=feeStatement.expenses.filter(e=>e.gl!=='80300');assert.equal(monthlyProfitability(feeTest,period,poolId,'Contract rent').complete,false);
const first=d.operations.tenants[0];first.rent=0;
r=monthlyProfitability(d,period,poolId,'Contract rent');assert.equal(r.complete,false);assert.equal(r.rows.find(x=>x.unitId===first.unitId).rent,null);assert.equal(r.net,null);
first.rent=100000;
d.operations.tenants.push({...first,id:'duplicate'});assert.equal(monthlyProfitability(d,period,poolId,'Contract rent').rows.find(x=>x.unitId===first.unitId).rent,null);d.operations.tenants.pop();
r=monthlyProfitability(d,period,poolId,'Actual collected');assert.equal(r.complete,false);assert.equal(r.totals.rent,0);
const current=latest(d,period).find(s=>s.unitId===first.unitId);
current.rent=120000;
const old={...structuredClone(current),id:'old-version',version:0,allocated:99999999};d.statements.push(old);
assert.equal(monthlyProfitability(d,period,poolId,'Actual collected').rows.find(x=>x.unitId===first.unitId).rent,120000);
const fee=current.expenses.find(e=>e.gl==='80300');
d.accounting.classifications.push({id:'fee-class',sourceKind:'Owner charge',sourceId:fee.id,cents:fee.cents,treatment:'Expense',gl:'80300',created:'2026-10-01',recipient:'DLA',accountName:'MAINT',invoiceRef:'fee',date:'2026-10-01',dueDate:'',reviewer:'Test'});
assert.equal(monthlyProfitability(d,period,poolId,'Contract rent').operatingExpenses,0);
current.expenses.push({id:'expense',label:'DLA operating cost',cents:2500,recipient:'Vendor',classification:'Expense',gl:'90000'});
d.accounting.classifications.push({...d.accounting.classifications[0],id:'expense-class',sourceId:'expense',cents:2500,gl:'90000'});
assert.equal(monthlyProfitability(d,period,poolId,'Contract rent').operatingExpenses,2500);
const panel=await readFile(new URL('../app/accounting-panel.tsx',import.meta.url),'utf8'),app=await readFile(new URL('../app/pool-app.tsx',import.meta.url),'utf8');
assert(panel.includes('management?profitabilityTabs:[]'));assert(panel.includes('management&&profitabilityTabs.includes(tab)'));assert(app.includes("management={user.role==='Global Admin'||user.role==='Management'}"));
console.log('PASS profitability: roster, unknowns, contract/cash separation, negative results, latest statements, fees deducted once, management view gating, no data mutation');
