import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import './qbo-exchange.mjs';
const root=new URL('./.mock-runtime/',import.meta.url);
await writeFile(new URL('qbo-store.mjs',root),`let value=null;export function setup(v){value=structuredClone(v);}export function snapshot(){return structuredClone(value);}export async function rpc(name,p){if(name!=='og_claim_qbo')throw Error('Unexpected RPC');if(!value||value.workspace_id!==p.p_workspace||value.generation!==p.p_generation||value.lease_until&&Date.parse(value.lease_until)>Date.now())return false;value.lease_token=p.p_lease;value.lease_until=new Date(Date.now()+300000).toISOString();return true;}export function admin(){return {from(table){if(table!=='og_qbo_connections')throw Error('Unexpected table');let changes=null,filters=[],mode='read',input;const q={select(){return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},gt(k,v){filters.push(r=>r[k]>v);return q;},update(v){mode='update';changes=v;return q;},upsert(v){mode='upsert';input=v;return q;},async maybeSingle(){return {data:value&&filters.every(f=>f(value))?structuredClone(value):null,error:null};},then(resolve,reject){try{if(mode==='upsert'&&!value)value={...input,generation:crypto.randomUUID(),status:'Disconnected'};const match=value&&filters.every(f=>f(value));if(mode==='update'&&match)Object.assign(value,changes);return Promise.resolve({error:null,data:match?[{workspace_id:value.workspace_id}]:[]}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}};return q;}};}`);
let code=stripTypeScriptTypes(await readFile(new URL('../lib/server/qbo.ts',import.meta.url),'utf8'),{mode:'transform'}).replace("import 'server-only';",'').replace("'./supabase'","'./qbo-store.mjs'").replace("'../qbo-security'","'./qbo-security.mjs'").replace("'../qbo-exchange'","'./qbo-exchange.mjs'");await writeFile(new URL('qbo-server.mjs',root),code);
const store=await import(new URL('qbo-store.mjs',root)),server=await import(new URL('qbo-server.mjs',root)),sec=await import(new URL('qbo-security.mjs',root));
const env={OG_QBO_ENABLED:'true',OG_QBO_CLIENT_ID:'test-client',OG_QBO_CLIENT_SECRET:'test-secret',OG_QBO_EXPECTED_REALM_ID:'12345',OG_QBO_EXPECTED_COMPANY_NAME:'DEVONSHIRE LEASING AGENCY INC.',OG_QBO_ENVIRONMENT:'sandbox',OG_QBO_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64'),OG_APP_URL:'https://og.example.test'},previous=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]])),originalFetch=fetch;Object.assign(process.env,env);const c=sec.qboConfig(process.env),initial={access:'old-access',refresh:'old-refresh',expires:Date.now()+3600000,refreshExpires:null};let mode='normal',refreshes=0,reads=0,writes=0;function setup(t=initial){store.setup({workspace_id:'workspace',generation:crypto.randomUUID(),realm_id:c.realm,company_name:c.company,environment:c.environment,status:'Connected',ciphertext:sec.seal(c,'workspace',t),lease_until:null,lease_token:null});}
globalThis.fetch=async(url,options={})=>{const u=new URL(url);if(u.hostname==='oauth.platform.intuit.com'){assert.equal(options.method,'POST');assert.equal(options.headers.Authorization,'Basic '+Buffer.from('test-client:test-secret').toString('base64'));assert(!String(options.body).includes('old-access'));refreshes++;if(mode==='refresh-fail')throw Error('Simulated ambiguous token result');return Response.json({access_token:'new-access',refresh_token:'rotated-refresh',expires_in:3600,token_type:'bearer'});}assert.equal(options.method??'GET','GET');assert.equal(u.hostname,'sandbox-quickbooks.api.intuit.com');assert(u.pathname.startsWith('/v3/company/12345/'));reads++;if(u.pathname.endsWith('/companyinfo/12345'))return Response.json({CompanyInfo:{Id:'12345',CompanyName:mode==='wrong-company'?'OTHER COMPANY':c.company}});const q=u.searchParams.get('query')??'';if(mode==='overflow'&&q.includes('Account')){const start=Number(/STARTPOSITION (\d+)/.exec(q)[1]);return Response.json({QueryResponse:{Account:Array.from({length:1000},(_,i)=>({Id:String(start+i),Name:'Account '+(start+i),AccountType:'Income',Active:true}))}});}if(q.includes('Customer'))return Response.json({QueryResponse:{Customer:[{Id:'c1',DisplayName:'# 106 Tenant',Active:true}]}});if(q.includes('Payment'))return Response.json({QueryResponse:{Payment:[{Id:'p1',CustomerRef:{value:'c1'},TxnDate:'2026-10-05',TotalAmt:900}]}});if(q.includes('Account'))return Response.json({QueryResponse:{Account:[{Id:'a1',Name:'Management',AcctNum:'80300',AccountType:'Income',Active:true}]}});throw Error('Unexpected API path');};
try{
setup();let result=await server.downloadReview('workspace','payments','2026-10','Cash');assert.match(result.csv,/QBO-ID-p1/);assert.equal(result.source.complete,true);assert.equal(result.source.records,1);assert(!JSON.stringify(result).includes('access'));assert.equal(store.snapshot().lease_token,null);console.log('PASS server payment download, provenance, secret exclusion and lease release');
setup({...initial,expires:Date.now()-1});result=await server.downloadReview('workspace','accounts','2026-10','Accrual');assert.equal(refreshes,1);assert.equal(sec.unseal(c,'workspace',store.snapshot().ciphertext).refresh,'rotated-refresh');console.log('PASS rotating refresh token persisted before provider download');
setup({...initial,expires:Date.now()-1});mode='refresh-fail';await assert.rejects(()=>server.downloadReview('workspace','accounts','2026-10','Cash'),/reconnection/);assert.equal(store.snapshot().ciphertext,null);assert.equal(store.snapshot().status,'Reconnect required');const before=refreshes;await assert.rejects(()=>server.downloadReview('workspace','accounts','2026-10','Cash'),/Connect/);assert.equal(refreshes,before);console.log('PASS ambiguous token refresh quarantined without blind retry');
mode='normal';setup();const both=await Promise.allSettled([server.downloadReview('workspace','accounts','2026-10','Cash'),server.downloadReview('workspace','accounts','2026-10','Cash')]);assert.equal(both.filter(r=>r.status==='fulfilled').length,1);assert.equal(both.filter(r=>r.status==='rejected').length,1);console.log('PASS overlapping provider requests serialize under durable lease');
setup();mode='wrong-company';await assert.rejects(()=>server.downloadReview('workspace','payments','2026-10','Cash'),/approved company/);console.log('PASS company name mismatch blocks download');
setup();mode='overflow';await assert.rejects(()=>server.downloadReview('workspace','accounts','2026-10','Cash'),/Partial results were discarded/);assert.equal(store.snapshot().lease_token,null);console.log('PASS pagination limit rejects partial chart');
mode='normal';store.setup(null);const generation=await server.beginConnection('workspace');await server.finishConnection('workspace',generation,'auth-code');assert.equal(store.snapshot().status,'Connected');assert(!store.snapshot().ciphertext.includes('rotated-refresh'));await assert.rejects(()=>server.finishConnection('workspace',generation,'stale-code'),/changed/);await server.disconnect('workspace');assert.equal(store.snapshot().ciphertext,null);assert.equal(store.snapshot().status,'Disconnected');console.log('PASS OAuth finalize, encrypted storage, stale callback rejection and local disconnect');
assert.equal(writes,0);console.log('7 QBO server scenarios passed; no financial API writes or OG ledger mutation');
}finally{globalThis.fetch=originalFetch;for(const k of Object.keys(env))if(previous[k]===undefined)delete process.env[k];else process.env[k]=previous[k];}
