import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
const root=new URL('./.mock-runtime/',import.meta.url);await mkdir(root,{recursive:true});
for(const name of ['microsoft-login','personal-settings','settings-catalog'])await writeFile(new URL(name+'.mjs',root),stripTypeScriptTypes(await readFile(new URL('../lib/'+name+'.ts',import.meta.url),'utf8'),{mode:'transform'}));
const {microsoftLoginConfig,azureIdentityVerified,oauthUrlAllowed}=await import(new URL('microsoft-login.mjs',root)),{personalSettings,preferenceKey}=await import(new URL('personal-settings.mjs',root));
const env={OG_APP_URL:'https://og.example.test',OG_MICROSOFT_LOGIN_ENABLED:'true',OG_MICROSOFT_TENANT_ID:'11111111-1111-4111-8111-111111111111',NODE_ENV:'production'};assert.equal(microsoftLoginConfig(env).origin,'https://og.example.test');for(const override of [{OG_MICROSOFT_LOGIN_ENABLED:'false'},{OG_MICROSOFT_TENANT_ID:'common'},{OG_APP_URL:'http://og.example.test'},{OG_APP_URL:'https://evil.test/path'},{OG_APP_URL:'https://user:password@og.example.test'}])assert.equal(microsoftLoginConfig({...env,...override}),null);
const verified={id:'fixture-auth',email_confirmed_at:'2026-10-04',identities:[{provider:'azure',identity_data:{email_verified:true}}]};assert.ok(azureIdentityVerified(verified));assert.equal(azureIdentityVerified({...verified,identities:[{provider:'azure',identity_data:{email_verified:false}}]}),false);assert.equal(azureIdentityVerified({...verified,identities:[{provider:'email'}]}),false);assert.equal(azureIdentityVerified({...verified,email_confirmed_at:null}),false);assert.equal(azureIdentityVerified({user_metadata:{role:'Global Admin',email_verified:true}}),false);
assert.ok(oauthUrlAllowed('https://fixture.supabase.co/auth/v1/authorize?provider=azure','https://fixture.supabase.co'));assert.equal(oauthUrlAllowed('https://evil.test/auth/v1/authorize?provider=azure','https://fixture.supabase.co'),false);assert.equal(oauthUrlAllowed('https://fixture.supabase.co/auth/v1/authorize?provider=google','https://fixture.supabase.co'),false);
assert.equal(personalSettings({rows:999,startPage:'admin-logs',font:'unsafe',striped:'true'}).startPage,'home');assert.equal(personalSettings({rows:100,striped:true}).rows,100);assert.notEqual(preferenceKey('user-a'),preferenceKey('user-b'));
await writeFile(new URL('sso-mocks.mjs',root),`export let state;export function setup(overrides={}){state={pending:'pending',exchangeError:false,user:${JSON.stringify(verified)},allowed:true,updates:[],filters:[],registered:0,signedOut:0,revoked:0,exchanges:0,logError:false,oauthUrl:'https://fixture.supabase.co/auth/v1/authorize?provider=azure',...overrides};}export async function cookies(){return {get:()=>state.pending?{value:state.pending}:undefined,set:(name,value)=>{state.pending=value;}};}export function serverConfig(){return {workspace:'test',url:'https://fixture.supabase.co'};}export function admin(){return {from:()=>({update(value){state.updates.push(value);if(value.active===false)state.revoked++;return this;},eq(k,v){state.filters.push([k,v]);return this;}})};}export async function sessionClient(){return {auth:{signInWithOAuth:async input=>{state.oauthInput=input;return {data:{url:state.oauthUrl},error:null};},exchangeCodeForSession:async()=>{state.exchanges++;return {error:state.exchangeError?Error('bad'):null};},getUser:async()=>({data:{user:state.user},error:null}),getClaims:async()=>({data:{claims:{session_id:'fixture-session'}},error:null}),signOut:async()=>{state.signedOut++;}}};}export async function registerSession(){if(!state.allowed)throw Error('Denied');state.registered++;}export async function getChatGPTUser(){return state.allowed?{authId:'fixture-auth',userId:'test',displayName:'Fixture',role:'Maintenance',propertyIds:['p1']}:null;}export async function systemLog(){if(state.logError)throw Error('log failed');}export async function rpc(){return true;}export function access(user){if(!user)throw Error('Denied');return user;}export async function body(request){return await request.json();}export function sameOrigin(request){if(request.headers.get('origin')!=='https://og.example.test')throw Error('Invalid origin');}`);
for(const [source,name] of [['../app/api/auth/microsoft/route.ts','microsoft-start'],['../app/auth/microsoft/callback/route.ts','microsoft-callback'],['../app/api/my-profile/route.ts','my-profile']]){let code=stripTypeScriptTypes(await readFile(new URL(source,import.meta.url),'utf8'),{mode:'transform'}).replace(/from '[^']+'/g,match=>match.includes('microsoft-login')?"from './microsoft-login.mjs'":"from './sso-mocks.mjs'");await writeFile(new URL(name+'.mjs',root),code);}
const mock=await import(new URL('sso-mocks.mjs',root)),{POST}=await import(new URL('microsoft-start.mjs',root)),{GET}=await import(new URL('microsoft-callback.mjs',root));const prev=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]]));Object.assign(process.env,env);
try{mock.setup();let response=await POST(new Request('https://og.example.test/api/auth/microsoft',{method:'POST',headers:{origin:env.OG_APP_URL}}));assert.equal(response.status,200);assert.equal(mock.state.oauthInput.provider,'azure');assert.equal(mock.state.oauthInput.options.scopes,'email');assert.equal(mock.state.oauthInput.options.redirectTo,'https://og.example.test/auth/microsoft/callback');mock.setup();assert.equal((await POST(new Request('https://og.example.test/api/auth/microsoft',{method:'POST',headers:{origin:'https://evil.test'}}))).status,400);mock.setup({oauthUrl:'https://evil.test'});assert.equal((await POST(new Request('https://og.example.test/api/auth/microsoft',{method:'POST',headers:{origin:env.OG_APP_URL}}))).status,400);
mock.setup();response=await GET(new Request('https://og.example.test/auth/microsoft/callback?code=fixture&next=https://evil.test'));assert.equal(response.headers.get('location'),'https://og.example.test/');assert.equal(mock.state.registered,1);assert.equal(mock.state.signedOut,0);assert.equal(mock.state.pending,'');
for(const override of [{allowed:false},{exchangeError:true},{user:{...verified,identities:[{provider:'email'}]}},{logError:true}]){mock.setup(override);response=await GET(new Request('https://og.example.test/auth/microsoft/callback?code=fixture'));assert.equal(response.headers.get('location'),'https://og.example.test/login?microsoft=failed');assert.equal(mock.state.signedOut,1);assert.equal(mock.state.revoked,1);}
mock.setup({pending:''});response=await GET(new Request('https://og.example.test/auth/microsoft/callback?code=fixture'));assert.equal(mock.state.exchanges,0);assert.ok(response.headers.get('location').endsWith('?microsoft=failed'));mock.setup();response=await GET(new Request('https://og.example.test/auth/microsoft/callback?error=cancelled'));assert.equal(mock.state.exchanges,0);
const profile=await import(new URL('my-profile.mjs',root));mock.setup();let pr=await profile.POST(new Request('https://og.example.test/api/my-profile',{method:'POST',headers:{origin:env.OG_APP_URL,'Content-Type':'application/json'},body:JSON.stringify({name:'Updated fixture',phone:'+12105551234'})}));assert.equal(pr.status,200);assert.deepEqual(mock.state.filters,[['auth_id','fixture-auth'],['workspace_id','test'],['status','Active']]);assert.deepEqual(Object.keys(mock.state.updates[0]).sort(),['name','phone','updated']);for(const payload of [{name:'Fixture',phone:'',role:'Global Admin'},{name:'Fixture',phone:'',authId:'other'},{name:'',phone:''}]){mock.setup();pr=await profile.POST(new Request('https://og.example.test/api/my-profile',{method:'POST',headers:{origin:env.OG_APP_URL,'Content-Type':'application/json'},body:JSON.stringify(payload)}));assert.equal(pr.status,400);assert.equal(mock.state.updates.length,0);}mock.setup({allowed:false});pr=await profile.POST(new Request('https://og.example.test/api/my-profile',{method:'POST',headers:{origin:env.OG_APP_URL,'Content-Type':'application/json'},body:JSON.stringify({name:'Fixture',phone:''})}));assert.equal(pr.status,400);assert.equal(mock.state.updates.length,0);
console.log('PASS Own-profile field/scope restrictions; Microsoft PKCE callback gates, verified identities, membership denial, revocation, fixed redirects and per-user preference validation');
}finally{for(const [k,v] of Object.entries(prev))if(v===undefined)delete process.env[k];else process.env[k]=v;}
