'use client';
import {useState} from 'react';
import {type Data} from '@/lib/pool';
import {emptyAccounting} from '@/lib/accounting-model';
import {emptyNativeAccounting} from '@/lib/native-accounting';
import BankWorkflow from '../bank-workflow';
import BankAccountSetup from '../bank-account-setup';
import NativeAccounting from '../native-accounting';
const actor={reviewer:'Synthetic QA',created:'2026-10-10T12:00:00Z'},line=(accountKey:string,debit:number,credit:number)=>({accountKey,debit,credit,unitId:'',memo:''});
const account=(key:string,type:string,name=key)=>({key,type,name,number:key,active:true,detail:'',qboId:''});
function initial():Data{const accounting=emptyAccounting();accounting.native=emptyNativeAccounting();accounting.native.books.push({...actor,id:'book',company:'Example Property Management',chartId:'chart',openingDate:'2026-09-30',source:'Synthetic verified opening',opening:[line('bank',100000,0),line('equity',0,100000)]});accounting.native.entries.push({...actor,id:'deposit',bookId:'book',date:'2026-10-02',reference:'EXAMPLE-DEPOSIT',memo:'Synthetic bank deposit',lines:[line('bank',12000,0),line('income',0,12000)],reverses:'',recurringId:'',sourceSystem:'',externalId:''});return {schema:1,properties:[],pools:[],units:[{id:'unit',number:'101'}],owners:[{id:'owner',name:'Example Owner'}],periods:[{id:'oct',month:'2026-10'}],statements:[],settings:[],audit:[],accounting,operations:{tenants:[{id:'tenant',unitId:'unit',firstName:'Example',lastName:'Resident'}],tenantEntries:[]},glControls:{charts:[{id:'chart',company:'Example Property Management',fileName:'synthetic.csv',accounts:[account('bank','Bank','Example operating bank'),account('card','Credit Card','Example credit card'),account('funds','Other Current Assets','Undeposited Funds'),account('income','Income','Other income'),account('expense','Expenses','Bank fees'),account('equity','Equity','Owner capital'),account('liability','Other Current Liabilities','Security deposit liability')]}],mappings:[]}} as unknown as Data;}
export default function Preview(){const [data,setData]=useState(initial),[page,setPage]=useState('Bank transaction review');return <main style={{padding:24,background:'#faf8f3',minHeight:'100vh'}}><p className="notice">DEVELOPMENT QA · Synthetic records only · no production saves</p><div className="toolbar"><button onClick={()=>{const d=initial();d.properties=[{id:'property-devonshire',name:'Synthetic pool client'}] as Data['properties'];d.pools=[{id:'synthetic-pool'}] as Data['pools'];setData(d);setPage('Bank account setup');}}>Pool client example</button><button onClick={()=>{setData(initial());setPage('Bank account setup');}}>Standard client example</button></div><nav className="people-tabs">{['Bank account setup','Bank transaction review','Additional receipt types','Grouped deposits','Statement reconciliation','Native ledger'].map(p=><button key={p} className={page===p?'selected':''} onClick={()=>setPage(p)}>{p}</button>)}</nav>{page==='Bank account setup'?<BankAccountSetup data={data} period="2026-10" busy={false} persist={async d=>{setData(d);return true;}} onPage={setPage}/>:['Statement reconciliation','Native ledger'].includes(page)?<NativeAccounting key={page} data={data} period="2026-10" busy={false} mode={page==='Native ledger'?'ledger':'reconciliation'} persist={async d=>{setData(d);return true;}} openUnit={()=>{}}/>:<BankWorkflow key={page} data={data} period="2026-10" busy={false} mode={page==='Additional receipt types'?'receipts':page==='Grouped deposits'?'deposits':'review'} persist={async d=>{setData(d);return true;}} onPage={setPage} openUnit={()=>{}}/>}</main>;}
