import {microsoftLoginConfig} from '@/lib/microsoft-login';
import {timingSafeEqual,createHash} from 'node:crypto';
import {admin,sessionClient,serverConfig,rpc,registerSession} from '@/lib/server/supabase';
import {sameOrigin,body,password,access} from '@/lib/server/request';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {systemLog} from '@/lib/system-log';
const digest=(s:string)=>createHash('sha256').update(s).digest();
export async function GET(){try{const {workspace}=serverConfig();const {count,error}=await admin().from('og_app_users').select('auth_id',{count:'exact',head:true}).eq('workspace_id',workspace);if(error)throw Error();return Response.json({setupAvailable:count===0,microsoftEnabled:!!microsoftLoginConfig(process.env)},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Login setup is not configured. Complete the server configuration and SQL setup.'},{status:503});}}
export async function POST(request:Request){try{sameOrigin(request);const p=await body(request);const {workspace}=serverConfig();const action=p.action;if(!['login','setup','password','logout'].includes(action))throw Error('Unknown authentication action');const client=await sessionClient();
 if(action==='logout'){const claims=await client.auth.getClaims();if(claims.data?.claims.session_id){const {error}=await admin().from('og_app_sessions').update({active:false}).eq('session_id',claims.data.claims.session_id).eq('workspace_id',workspace);if(error)throw Error('Session logout failed');}await client.auth.signOut({scope:'local'});return Response.json({ok:true});}
 const window=Math.floor(Date.now()/900000);const ip=request.headers.get('x-forwarded-for')?.split(',')[0]??'unknown';const ipHash=digest(ip).toString('hex');if(!await rpc('og_auth_attempt',{p_bucket:`${workspace}:${action}:${window}`,p_limit:100})||!await rpc('og_auth_attempt',{p_bucket:`${workspace}:${action}:${window}:${ipHash}`,p_limit:15}))return Response.json({error:'Too many attempts. Try again in 15 minutes.'},{status:429});
 if(action==='setup'){const token=process.env.OG_BOOTSTRAP_TOKEN;if(!token||token.length<32||typeof p.token!=='string'||!timingSafeEqual(digest(token),digest(p.token)))throw Error('Invalid setup credentials');if(p.email!=='mmartinez@devonshirecondos.com')throw Error('Use the designated Global Admin email');const {count,error:checkError}=await admin().from('og_app_users').select('auth_id',{count:'exact',head:true}).eq('workspace_id',workspace);if(checkError||count!==0)throw Error('Initial setup is closed');await (await import('@/lib/storage')).load(workspace);const {data,error}=await admin().auth.admin.createUser({email:p.email,password:password(p.password),email_confirm:true,user_metadata:{name:'Miguel Martinez'}});if(error||!data.user)throw Error('Unable to create the administrator. This email may already exist; no existing account was changed.');try{await rpc('og_bootstrap_member',{p_workspace:workspace,p_auth:data.user.id,p_email:p.email,p_name:'Miguel Martinez',p_phone:'+12105761708'});}catch(e){await admin().auth.admin.deleteUser(data.user.id);throw e;}const {error:loginError}=await client.auth.signInWithPassword({email:p.email,password:p.password});if(loginError)throw Error('Account created. Sign in to continue.');await registerSession(client,data.user.id);return Response.json({ok:true});}
 if(action==='login'){if(typeof p.email!=='string'||typeof p.password!=='string'||p.email.length>254||p.password.length>128)throw Error('Invalid sign-in credentials');const {data:loginData,error}=await client.auth.signInWithPassword({email:p.email.trim().toLowerCase(),password:p.password});if(error)throw Error('Unable to sign in. Check your email and password.');if(!loginData.user)throw Error('Unable to sign in');try{await registerSession(client,loginData.user.id);}catch{await client.auth.signOut({scope:'local'});throw Error('Unable to sign in. This account has no active OG access.');}const user=await getChatGPTUser();if(!user){await client.auth.signOut();throw Error('Unable to sign in. This account has no active OG access.');}await systemLog(workspace,user.displayName,'Access','Info','User signed in','Email/password login; SMS not enabled');return Response.json({ok:true});}
 const user=await getChatGPTUser();if(!user)throw Error('Sign in required');const next=password(p.password);if(typeof p.currentPassword!=='string')throw Error('Enter your current password');const verifyClient=admin();const verify=await verifyClient.auth.signInWithPassword({email:user.email,password:p.currentPassword});if(verify.error)throw Error('Current password is incorrect');await verifyClient.auth.signOut({scope:'local'});const {error}=await client.auth.updateUser({password:next});if(error)throw Error('Password update failed');const {error:updateError}=await admin().from('og_app_users').update({must_change_password:false,updated:new Date().toISOString()}).eq('auth_id',user.authId).eq('workspace_id',workspace);if(updateError)throw Error('Password changed, but access confirmation failed. Retry signing in.');await systemLog(workspace,user.displayName,'Access','Info','Password changed','Password value excluded');return Response.json({ok:true});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Authentication unavailable'},{status:400,headers:{'Cache-Control':'no-store'}});}}
