'use client';
import BankCapacity from './bank-capacity';
import OwnerClose from './owner-close';
import QboConnectionPanel from './qbo-connection-panel';
import {Checkbox} from '@/components/ui/checkbox';
import {useState,useEffect} from 'react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Data,cents,money} from '@/lib/pool';
import {emptyAccounting,chargeProgress,officeRent,depositBalance,incomeRows,qboBillRows,recordAudit} from '@/lib/accounting-model';
import {download,csv,qboOfficePackage,simpleReportPDF} from '@/lib/exports';
import ProcurementPanel from './procurement';
import GLMapping from './gl-mapping';
import AllocationPanel from './allocation-panel';
import QboCsvUpload from './qbo-csv-upload';
import RentRoll from './rent-roll';
import {Grid,Pick} from './report-controls';
export default function AccountingPanel({data,period,busy,persist,navigate,openUnit}:{data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;navigate:(s:string)=>void;openUnit:(id:string)=>void}){
 const [tab,setTab]=useState('Tenant rent'),[form,setForm]=useState<any>(null),[kind,setKind]=useState('deposit'),[docs,setDocs]=useState<any[]>([]),[docsReady,setDocsReady]=useState(false);const a=data.accounting??emptyAccounting(),tenants=data.operations?.tenants??[],entries=data.operations?.tenantEntries??[],rows=incomeRows(data,period);useEffect(()=>{setDocsReady(false);fetch('/api/documents').then(r=>{if(!r.ok)throw Error('Documents unavailable');return r.json();}).then(x=>{if(Array.isArray(x)){setDocs(x);setDocsReady(true);}}).catch(()=>{setDocsReady(false);});},[data]);
 const unit=(id:string)=>data.units.find(u=>u.id===id)?.number??id,tenantName=(id:string)=>{const t=tenants.find(t=>t.id===id);return t?t.firstName+' '+t.lastName:'Not found';};
 function create(k:string,r?:any){setKind(k);setForm(k==='classification'?{id:crypto.randomUUID(),sourceId:r.id,sourceKind:r.kind,cents:r.cents,recipient:r.recipient==='Confirm recipient'?'':r.recipient,treatment:'Expense',paymentState:'Unknown',gl:r.gl,accountName:'',invoiceRef:r.invoiceRef,date:r.date,dueDate:period+'-28',reviewer:'',created:new Date().toISOString()}:r?{...r,id:crypto.randomUUID(),draftId:r.id,reference:r.reference+'/approved',approved:false,created:new Date().toISOString()}:{id:crypto.randomUUID(),tenantId:tenants[0]?.id??'',unitId:tenants[0]?.unitId??'',date:period+'-01',kind:'Received',cents:0,reference:'',reason:'',leaseBasis:'',reviewer:'',treatment:'Held liability',recipient:'',gl:'',approved:true,created:new Date().toISOString()});}
 const field=(key:string,label:string,type='text')=><label className="field">{label}<input type={type} value={form?.[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const select=(key:string,label:string,values:string[])=><label className="field">{label}<Pick label={label} value={form[key]} onChange={v=>setForm({...form,[key]:v,...(key==='kind'?{approved:v!=='Deduction',treatment:v==='Deduction'?'Other':'Held liability'}:{})})} items={values.map(v=>({value:v,label:v}))}/></label>;
 const amount=(key:string,label:string)=><label className="field">{label}<input inputMode="decimal" key={form.id+key} defaultValue={((form[key]??0)/100).toFixed(2)} onBlur={e=>{try{setForm({...form,[key]:cents(e.target.value)});}catch(err){toast.error((err as Error).message);}}}/></label>;
 async function save(){try{const n=structuredClone(data);n.accounting??=emptyAccounting();if(kind==='classification')n.accounting.classifications.push(form);else n.accounting.deposits.push(form);recordAudit(n,kind==='classification'?'Accounting classification confirmed':'Escrow event recorded',form.reference??form.sourceId);if(await persist(n,'Accounting record saved'))setForm(null);}catch(e){toast.error((e as Error).message);}}
 async function exportQBO(){try{const ready=qboBillRows(data,period),exported=new Set(a.exports.flatMap(b=>b.sourceIds)),review=rows.filter(r=>r.confirmed&&!exported.has(r.id)&&r.kind!=='Escrow');if(!review.length)throw Error('No new confirmed GL rows ready. Review classifications first.');if(review.some(r=>!r.accountName.trim()))throw Error('Enter exact QBO account names for every confirmed row before export.');const header=['Bill no.','Supplier','Bill Date','Due Date','Account','Line Amount','Description'];const billRows=[header,...ready.map(r=>['OG-'+r.id,r.recipient,r.date,r.dueDate,r.accountName,(r.cents/100).toFixed(2),r.description+' / Unit '+r.unit+' / GL '+r.gl+' / '+r.invoiceRef])];const n=structuredClone(data);n.accounting??=emptyAccounting();const batch={id:crypto.randomUUID(),date:new Date().toISOString(),sourceIds:review.map(r=>r.id),reviewRows:[['source_id','kind','unit','description','amount','recipient','treatment','GL','QBO_account','payment_state','reference'],...review.map(r=>[r.id,r.kind,r.unit,r.description,(r.cents/100).toFixed(2),r.recipient,r.treatment,r.gl,r.accountName,r.paymentState,r.invoiceRef])],receiptIds:docs.filter(d=>review.some(r=>r.id===d.expenseId)).map(d=>d.id),rows:billRows,status:'Prepared' as const,reference:''};n.accounting.exports.push(batch);recordAudit(n,'QBO export prepared',batch.id+' / '+review.length+' mapped sources');const blob=await qboOfficePackage(data,period,review,docs,billRows);if(await persist(n,'Export batch saved; no QBO posting performed'))download(blob,'OG_QBO_Review_'+period+'_'+batch.id+'.zip');}catch(e){toast.error((e as Error).message);}}
 async function uploaded(file:File,target:string,id:string){try{const f=new FormData();f.set('file',file);f.set('linkType',target);f.set('linkId',id);const r=await fetch('/api/documents',{method:'POST',body:f}),j:any=await r.json();if(!r.ok)throw Error(j.error);const dr=await fetch('/api/documents');setDocs(await dr.json());toast.success('Supporting document uploaded');}catch(e){toast.error((e as Error).message);}}
 const income=rows.filter(r=>r.confirmed&&r.treatment==='Agency income').reduce((n,r)=>n+r.cents,0),payables=rows.filter(r=>r.confirmed&&(['Payable','Pass-through'].includes(r.treatment)||r.treatment==='Expense'&&r.paymentState==='Unpaid')).reduce((n,r)=>n+r.cents,0);
 return <><div className="people-tabs" role="tablist" aria-label="Office accounting">{['Tenant rent','Bank balances & checks','Invoices & Received Payments Current Month','Escrow','Agency income & payables','QBO exports','Procurement & inventory','Pool allocation & contracts','Owner bills & monthly close'].map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div><p className="hint">OG manages unit and pool accounting. Bank planning uses manually verified balances; bank reconciliation remains external. No QBO entries or payments are initiated.</p>
 {tab==='Procurement & inventory'&&<ProcurementPanel data={data} period={period} busy={busy} persist={persist} openUnit={openUnit}/>}
 {tab==='Pool allocation & contracts'&&<AllocationPanel data={data} period={period} busy={busy} persist={persist}/>}
 {tab==='Invoices & Received Payments Current Month'&&<QboCsvUpload data={data} period={period} busy={busy} persist={persist} navigate={navigate}/>}
 {tab==='Tenant rent'&&<RentRoll data={data} period={period} navigate={navigate}/>}
 {tab==='Tenant rent'&&<section className="panel"><div className="panel-heading"><h3>Office rent collection · {period}</h3><button onClick={()=>navigate('people')}>Open tenants / apply receipts</button></div><Grid headers={['Unit','Actual rent collected','Source']} rows={data.units.map(u=>{const r=officeRent(data,u.id,period);return [u.number,r.cents===null?'Not entered':money(r.cents),r.source];})}/><h3>Rent charges & payment status</h3><Grid headers={['Tenant','Unit','Charge date','Amount','Applied','Outstanding','Status']} rows={entries.filter(e=>e.kind==='Charge'&&(e.category==='Rent'||a.applications.some(r=>r.chargeId===e.id&&r.chargeCategory==='Rent'))&&e.date.startsWith(period)).map(e=>{const t=tenants.find(t=>t.id===e.tenantId),p=chargeProgress(data,e.id);return [tenantName(e.tenantId),unit(t?.unitId??''),e.date,money(e.cents),money(p.covered),money(p.remaining),p.status];})}/><p className="hint">Matched cash receipts count as actual rent on the receipt date. Credits can settle a charge but do not count as rent collected. Unapplied receipts remain in the tenant ledger.</p></section>}
 {tab==='Bank balances & checks'&&<BankCapacity data={data} period={period} busy={busy} persist={persist}/>}
 {tab==='Escrow'&&<><section className="panel"><div className="panel-heading"><h3>Tenant escrow / security deposits</h3><button disabled={busy||!tenants.length} onClick={()=>create('deposit')}>Record deposit / refund / deduction</button></div><Grid headers={['Tenant','Unit','Held balance']} rows={tenants.map(t=>[tenantName(t.id),unit(t.unitId),money(depositBalance(data,t.id))])}/><div className="notice">Deposits remain held liabilities until a documented deduction is reviewed. Routine make-ready and normal wear are not automatically charged to escrow. Selecting Agency income requires an explicit basis and accounting review; this records treatment, not a bank transfer.</div></section><section className="panel check-summary"><h3>Escrow history & deduction review</h3><button className="secondary" onClick={async()=>{try{download(await simpleReportPDF('OG | UNIT-LINKED ESCROW REGISTER',a.deposits.map(e=>e.date+' / '+tenantName(e.tenantId)+' / Unit '+unit(e.unitId)+' / '+e.kind+' / '+money(e.cents)+' / '+e.reference+' / '+e.reason+' / '+(e.approved?'Recorded / approved':'Draft')+' / '+e.treatment)),'OG_Escrow_Register.pdf');}catch(e){toast.error((e as Error).message);}}}>Escrow register PDF</button><Grid headers={['Date','Tenant / unit','Event','Amount','Reference / reason','Treatment','Review','Documents']} rows={a.deposits.map(e=>[e.date,tenantName(e.tenantId)+' / '+unit(e.unitId),e.kind,money(e.cents),e.reference+' / '+e.reason,e.treatment,e.approved?'Recorded / approved':<button className="text-button" disabled={busy||a.deposits.some(x=>x.draftId===e.id)} onClick={()=>create('deposit',e)}>Review deduction</button>,<div className="toolbar">{docs.filter(d=>d.statementId==='deposit:'+e.id).map(d=><a key={d.id} href={'/api/documents?id='+d.id}>{d.name}</a>)}<label className="upload-button">Attach support<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy} onChange={ev=>{const f=ev.target.files?.[0];if(f)void uploaded(f,'deposit',e.id);ev.target.value='';}}/></label></div>])}/></section></>}
 {tab==='Agency income & payables'&&<>{!data.glControls?.charts.length&&<p className="notice">Import and review the QBO chart in QBO exports before confirming new accounting classifications. <button onClick={()=>setTab('QBO exports')}>Open QBO chart mapping</button></p>}<div className="ops-metrics"><div className="ops-metric"><span>Confirmed agency income</span><strong>{money(income)}</strong></div><div className="ops-metric"><span>Confirmed HOA/vendor pass-through or payable charges</span><strong>{money(payables)}</strong></div><div className="ops-metric"><span>Unconfirmed source lines</span><strong>{rows.filter(r=>!r.confirmed).length}</strong></div></div><section className="panel"><div className="panel-heading"><h3>Income, expenses & payables · {period}</h3><button className="secondary" onClick={async()=>{try{download(await simpleReportPDF('OG | DEVONSHIRE OPERATING-INCOME REVIEW',['Accounting month: '+period,'Confirmed agency charge income: '+money(income),'Confirmed payable / pass-through charges: '+money(payables),...rows.map(r=>r.unit+' / '+r.description+' / '+money(r.cents)+' / '+r.treatment+' / '+r.recipient+' / GL '+r.gl),'Charge-based review, not a cash-income statement or proof suppliers were paid.']),'OG_Operating_Review_'+period+'.pdf');}catch(e){toast.error((e as Error).message);}}}>Report PDF</button><button className="secondary" onClick={()=>download(new Blob([csv([['source_id','kind','unit','description','amount','recipient','treatment','GL','QBO_account','confirmed'],...rows.map(r=>[r.id,r.kind,r.unit,r.description,(r.cents/100).toFixed(2),r.recipient,r.treatment,r.gl,r.accountName,r.confirmed])])],{type:'text/csv'}),'OG_Accounting_Report_'+period+'.csv')}>Export report</button></div><Grid headers={['Unit / source','Description','Amount','Recipient','Treatment','GL / QBO account','']} rows={rows.map(r=>[r.unit+' / '+r.kind,r.description,money(r.cents),r.recipient,r.treatment,r.gl+' / '+r.accountName+' / '+r.paymentState,r.kind!=='Escrow'?<button className="text-button" disabled={busy||!data.glControls?.charts.length} onClick={()=>create('classification',r)}>{r.confirmed?'New classification version':'Confirm classification'}</button>:'Reviewed escrow'])}/><p className="hint">Only explicitly reviewed classifications count as confirmed income or payables. These are charge-based income and payable totals, not cash collected or proof suppliers were paid. Returns appear as separate negative credit lines requiring reviewed GL treatment. Bulk purchase cost and the unit’s list-price charge are separate sources; classify them according to their accounting purpose.</p></section></>}
 {tab==='Owner bills & monthly close'&&<OwnerClose data={data} period={period} busy={busy||!docsReady} persist={persist} openUnit={openUnit} navigate={navigate} docs={docs}/>}
 {tab==='QBO exports'&&<><QboConnectionPanel period={period}/><GLMapping data={data} period={period} busy={busy} persist={persist}/><section className="panel"><div className="panel-heading"><h3>GL-mapped expense and receipt package</h3><button disabled={busy} onClick={exportQBO}>Prepare QBO bills / receipt ZIP</button></div><p>Confirm GL classifications in Agency income & payables and enter the exact QBO account name, GL, supplier, source reference, and due date. The ZIP contains all newly confirmed GL review rows and linked receipts; only explicitly Unpaid Expense rows enter the candidate bills CSV. Paid sources stay in the review CSV for receipt matching.</p><div className="notice">CSV is a bills-import candidate, not Smart Receipts auto-categorization. Use the sample template in your actual QBO company to verify supported fields and tax settings. Upload receipt files separately or match them to imported transactions. Review existing QBO entries before import to prevent duplicates. Paid expenses must not be imported as new unpaid bills.</div><Grid headers={['Created','Batch','Sources','Status','']} rows={a.exports.map(b=>[b.date.slice(0,10),b.id,b.sourceIds.length,b.status,<div className="toolbar"><button className="text-button" onClick={()=>download(new Blob([csv(b.rows)],{type:'text/csv'}),'OG_QBO_Bills_'+b.id+'.csv')}>Download saved bills CSV</button>{b.reviewRows&&<button className="text-button" onClick={()=>download(new Blob([csv(b.reviewRows!)],{type:'text/csv'}),'OG_GL_Review_'+b.id+'.csv')}>Saved GL review</button>}{b.status==='Prepared'&&<button className="text-button" disabled={busy} onClick={async()=>{const ref=window.prompt('Enter the externally confirmed QBO import reference (nothing is uploaded by OG):');if(!ref?.trim())return;const n=structuredClone(data),batch=n.accounting!.exports.find(x=>x.id===b.id)!;batch.status='Imported externally';batch.reference=ref.trim();recordAudit(n,'External QBO import confirmed',b.id+' / '+ref);await persist(n,'External import reference recorded');}}>Record external import</button>}</div>])}/><p className="hint">Previously prepared sources are excluded from new batches. Download the saved batch to retry. Bank reconciliation and opening bank balances remain outside OG.</p></section></>}
 <Dialog open={!!form} onOpenChange={v=>{if(!v)setForm(null);}}><DialogContent className="app-dialog ops-dialog"><DialogHeader><DialogTitle>{kind==='classification'?'Confirm accounting treatment & GL':'Record escrow activity'}</DialogTitle><DialogDescription>Records accounting instructions and externally completed activity. No funds move.</DialogDescription></DialogHeader>{form&&<><div className="input-grid">{kind==='classification'?<><p>{money(form.cents)} source amount</p>{field('recipient','Exact supplier / recipient')}{select('treatment','Accounting treatment',['Agency income','Expense','Payable','Pass-through','Asset'])}{select('paymentState','Supplier payment state',['Unknown','Unpaid','Paid'])}{data.glControls?.charts.length?<label className="field">Verified QBO GL<Pick label="Classification QBO account" value={(data.glControls.charts.at(-1)?.accounts.find(a=>(a.number||a.qboId||a.key)===form.gl&&a.name===form.accountName)?.key)??''} onChange={key=>{const a=data.glControls!.charts.at(-1)!.accounts.find(a=>a.key===key)!;setForm({...form,gl:a.number||a.qboId||a.key,accountName:a.name});}} items={data.glControls.charts.at(-1)!.accounts.filter(a=>a.active).map(a=>({value:a.key,label:a.number+' · '+a.name+' · '+a.type}))}/></label>:<>{field('gl','GL code')}{field('accountName','Exact QBO account name')}</>}{field('invoiceRef','Original supplier invoice / receipt reference')}{field('date','Transaction date','date')}{field('dueDate','Bill due date (unpaid bills only)','date')}{field('reviewer','Reviewed / approved by')}</>:<><label className="field">Tenant / unit<Pick label="Escrow tenant" value={form.tenantId} onChange={v=>setForm({...form,tenantId:v,unitId:tenants.find(t=>t.id===v)!.unitId})} items={tenants.map(t=>({value:t.id,label:tenantName(t.id)+' · Unit '+unit(t.unitId)}))}/></label>{select('kind','Activity',['Received','Refund','Deduction'])}{field('date','Event date','date')}{amount('cents','Amount ($)')}{field('reference','Unique receipt / deduction reference')}{field('reason','Itemized reason / make-ready detail')}{form.kind==='Deduction'&&<>{field('leaseBasis','Lease / deduction basis and supporting reference')}{field('reviewer','Reviewer / responsible broker or CPA')}{select('treatment','Confirmed treatment',['Other','Agency income','Owner expense'])}{field('recipient','Recipient')}{field('gl','Approved GL code')}<label className="check"><Checkbox checked={form.approved} onCheckedChange={v=>setForm({...form,approved:v===true})}/> Deduction basis, amount, documentation, and accounting treatment reviewed</label></>}</>}</div><button disabled={busy} onClick={save}>Save accounting record</button></>}</DialogContent></Dialog></>;
}
