'use client';
import {useState} from 'react';
import type {ChatGPTUser} from './chatgpt-auth';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Pick} from './report-controls';
import PasswordPanel from './password-panel';
import {UserRound,ChevronDown} from 'lucide-react';
export default function AccountMenu({user,onNavigate}:{user:ChatGPTUser;onNavigate:(tab:string)=>void}){
 const [panel,setPanel]=useState<'profile'|'personal'|'general'|'password'|null>(null),[size,setSize]=useState('15');
 function personal(){try{setSize(localStorage.getItem('og.rows.'+user.userId)||'15');}catch{}setPanel('personal');}
 const initials=user.fullName?.split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('')||null;
 return <><DropdownMenu><DropdownMenuTrigger className="account-trigger" aria-label="User account menu">{initials?<span className="account-avatar">{initials}</span>:<UserRound size={20}/>}<span className="account-name">{user.displayName}</span><ChevronDown size={16}/></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{user.displayName}</DropdownMenuLabel><DropdownMenuItem onSelect={()=>setPanel('profile')}>Profile</DropdownMenuItem><DropdownMenuItem onSelect={personal}>My settings</DropdownMenuItem>{['Global Admin','Management'].includes(user.role)&&<><DropdownMenuItem onSelect={()=>onNavigate('general-settings')}>Users & access</DropdownMenuItem><DropdownMenuItem onSelect={()=>onNavigate('general-settings')}>General settings</DropdownMenuItem></>}<DropdownMenuItem onSelect={()=>setPanel('password')}>Change password</DropdownMenuItem>{user.role==='Global Admin'&&<DropdownMenuItem onSelect={()=>onNavigate('admin-logs')}>Admin logs</DropdownMenuItem>}<DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>{void fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})}).then(()=>window.location.assign('/login'));}}>Log out</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Dialog open={panel!==null} onOpenChange={open=>{if(!open)setPanel(null);}}><DialogContent><DialogHeader><DialogTitle>{panel==='password'?'Change password':panel==='profile'?'Profile':panel==='personal'?'My settings':'General settings'}</DialogTitle><DialogDescription>{panel==='password'?'Enter your current password and choose a new password.':panel==='profile'?'Your signed-in account information.':panel==='personal'?'Preferences for this user on this browser.':'Workspace configuration.'}</DialogDescription></DialogHeader>{panel==='password'?<PasswordPanel/>:panel==='profile'?<><dl className="account-details"><dt>Name</dt><dd>{user.fullName||'Not supplied by sign-in provider'}</dd><dt>Email</dt><dd>{user.email}</dd><dt>Access</dt><dd>{user.role}</dd></dl><p className="hint">Your login is managed through OG and Supabase. Use Change password to update your password.</p></>:panel==='personal'?<label className="field"><span>Default rows per page</span><Pick label="Default rows per page" value={size} onChange={v=>{setSize(v);try{localStorage.setItem('og.rows.'+user.userId,v);}catch{}window.dispatchEvent(new CustomEvent('og-row-preference',{detail:Number(v)}));}} items={[15,50,100].map(n=>({value:String(n),label:String(n)}))}/></label>:<div className="download-actions"><button onClick={()=>{setPanel(null);onNavigate('properties');}}>Property profile</button><button className="secondary" onClick={()=>{setPanel(null);onNavigate('settings');}}>Monthly pool settings</button><p className="hint">Staff accounts and role permissions are not configured yet.</p></div>}</DialogContent></Dialog></>;
}
