'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,cents,money} from '@/lib/pool';
import {recordAudit} from '@/lib/accounting-model';
import {native,bookChart,type LedgerEntry} from '@/lib/native-accounting';
import {recordCompletedTransfer,parseJournalBatch,postJournalBatch,journalBatchHeaders,nativeReport,nativeReportNames,type NativeReportName} from '@/lib/accounting-tools';
import {csv,download} from '@/lib/exports';
import {reportTablePDF} from '@/lib/report-pdf';
import {Grid,Pick} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './accounting-connections.css';

type Props={data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;mode:'transfers'|'batches'|'reports'|'accounts';openUnit:(id:string)=>void;onPage:(page:string,context:{bookId:string;bankKey:string})=>void;initialBook?:string;initialReport?:NativeReportName};
export default function AccountingTools({data,period,busy,persist,mode,openUnit,onPage,initialBook,initialReport}:Props){
 const [selected,setSelected]=useState(initialBook??''),[form,setForm]=useState(false),[verified,setVerified]=useState(false),[saving,setSaving]=useState(false),[detail,setDetail]=useState<LedgerEntry|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[unitId,setUnitId]=useState(''),[report,setReport]=useState<NativeReportName>(initialReport??'Trial balance'),[start,setStart]=useState(period+'-01'),[end,setEnd]=useState(new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),0)).toISOString().slice(0,10));
 const [transfer,setTransfer]=useState({fromKey:'',toKey:'',amount:'',date:period+'-01',reference:'',source:'',reviewer:''}),[batch,setBatch]=useState(''),[reviewer,setReviewer]=useState(''),[preview,setPreview]=useState<LedgerEntry[]>([]);
 const n=native(data),book=n.books.find(b=>b.id===selected)??n.books[0],chart=book?bookChart(data,book.id):undefined,banks=chart?.accounts.filter(a=>a.active&&a.type.toLowerCase()==='bank')??[],blocked=busy||saving;
 const accountName=(key:string)=>{const a=chart?.accounts.find(a=>a.key===key);return [a?.number,a?.name??key].filter(Boolean).join(' · ');};
 const open=(page:string,bankKey='')=>onPage(page,{bookId:book?.id??'',bankKey});
 async function save(){if(!book||blocked||!verified)return;setSaving(true);try{const next=mode==='transfers'?recordCompletedTransfer(data,{...transfer,bookId:book.id,cents:cents(transfer.amount),verified}):postJournalBatch(data,book.id,batch,reviewer,verified);recordAudit(next,mode==='transfers'?'Completed bank transfer posted':'Reviewed journal batch posted',mode==='transfers'?transfer.reference:preview.length+' journals');if(await persist(next,'Reviewed accounting entries posted; no funds moved')){setForm(false);setPreview([]);}}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 const transfers=n.entries.filter(e=>e.bookId===book?.id&&e.sourceSystem==='OG bank transfer'&&e.date<=end),batches=n.entries.filter(e=>e.bookId===book?.id&&e.sourceSystem==='OG journal batch'&&e.date<=end);
 let rows:ReturnType<typeof nativeReport>=[],reportError='';if(mode==='reports'&&book)try{rows=nativeReport(data,book.id,report,start,end,filter,unitId);}catch(e){reportError=(e as Error).message;}
 const reportColumns=['Date','Reference','Account','Unit','Debit','Credit','Running / closing balance'];
 const printable=rows.map(r=>[r.date,r.reference,r.label,data.units.find(u=>u.id===r.unitId)?.number??'',money(r.debit),money(r.credit),money(r.balance)]);
 const balance=rows.reduce((a,r)=>({debit:a.debit+r.debit,credit:a.credit+r.credit}),{debit:0,credit:0});
 return <section className="panel accounting-tool-panel"><div className="panel-heading"><h3>{{transfers:'Completed bank transfers',batches:'Journal entry batches',reports:'Company accounting reports',accounts:'Financial account overview'}[mode]}</h3></div><label className="field">Company ledger<Pick label="Accounting tools company" value={book?.id??'none'} onChange={v=>{setSelected(v);setFilter('');setPreview([]);setForm(false);}} items={n.books.length?n.books.map(b=>({value:b.id,label:b.company})):[{value:'none',label:'Initialize a company ledger first'}]}/></label>{!book&&<div className="notice">Initialize verified company opening balances before using this workflow.<button className="secondary" onClick={()=>open('Native ledger')}>Open company ledger</button></div>}
 {mode==='transfers'&&book&&<><p>Record a transfer that was completed and verified outside OG. Both bank sides post together and can be reconciled separately. This action does not transfer money.</p><div className="toolbar"><button disabled={blocked||banks.length<2} onClick={()=>{setVerified(false);setTransfer({...transfer,fromKey:banks[0]?.key??'',toKey:banks[1]?.key??'',reference:'',source:'',amount:''});setForm(true);}}>Review completed transfer</button><button className="secondary" onClick={()=>open('Transfer register')}>External transfer evidence</button></div><Grid headers={['Date','Reference','From bank','To bank','Amount','Review']} rows={transfers.map(e=>[e.date,<button className="text-button" onClick={()=>setDetail(e)}>{e.reference}</button>,accountName(e.lines.find(l=>l.credit>0)!.accountKey),accountName(e.lines.find(l=>l.debit>0)!.accountKey),<button className="text-button" onClick={()=>setDetail(e)}>{money(e.lines.find(l=>l.debit>0)!.debit)}</button>,<div className="toolbar"><button className="secondary" onClick={()=>open('Statement reconciliation',e.lines.find(l=>l.credit>0)!.accountKey)}>Reconcile outgoing</button><button className="secondary" onClick={()=>open('Statement reconciliation',e.lines.find(l=>l.debit>0)!.accountKey)}>Reconcile incoming</button></div>])}/></>}
 {mode==='batches'&&book&&<><p>Upload balanced journals for this company, preview every entry, then approve the whole batch. Unknown accounts, ambiguous units, duplicates and locked periods block the entire batch.</p><div className="toolbar"><button disabled={blocked} onClick={()=>{setVerified(false);setPreview([]);setBatch('');setForm(true);}}>Prepare journal batch</button><button className="secondary" onClick={()=>download(new Blob([csv([journalBatchHeaders,['2026-10-01','YOUR-REFERENCE','Your reviewed source','ACCOUNT_NUMBER','','0.00','0.00','Line memo']])],{type:'text/csv'}),'OG_Journal_Batch_Template.csv')}>Download CSV template</button></div><Grid headers={['Date','Journal','Lines','Source batch','Reviewed by']} rows={batches.map(e=>[e.date,<button className="text-button" onClick={()=>setDetail(e)}>{e.reference}</button>,e.lines.length,e.externalId.split('|')[0],e.reviewer])}/></>}
 {mode==='accounts'&&book&&<><p>Company accounts come from the reviewed chart. Open an account to view its ledger, bank activity or statement reconciliation.</p><input aria-label="Search financial accounts" placeholder="Search account number or name" value={query} onChange={e=>setQuery(e.target.value)}/><Grid headers={['Number','Account','Type','Status','Actions']} rows={(chart?.accounts??[]).filter(a=>(a.name+' '+a.number).toLowerCase().includes(query.toLowerCase())).map(a=>[a.number,a.name,a.type,a.active?'Active':'Inactive',<div className="toolbar"><button className="secondary" onClick={()=>open('Native ledger',a.key)}>Open ledger</button>{a.active&&a.type.toLowerCase()==='bank'&&<button className="secondary" onClick={()=>open('Statement reconciliation',a.key)}>Reconcile</button>}</div>])}/><div className="toolbar"><button className="secondary" onClick={()=>open('Chart & mapping')}>Review chart & account maps</button><button className="secondary" onClick={()=>open('Provider setup')}>Bank / payment provider access</button></div></>}
 {mode==='reports'&&book&&<><div className="leasing-form-grid"><label className="field">Report<Pick label="Native report" value={report} onChange={v=>{setReport(v as NativeReportName);setUnitId('');}} items={nativeReportNames.map(v=>({value:v,label:v}))}/></label><label className="field">From<input aria-label="Report from" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Through<input aria-label="Report through" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="field">Account<Pick label="Report account" value={filter||'all'} onChange={v=>setFilter(v==='all'?'':v)} items={[{value:'all',label:'All company accounts'},...(chart?.accounts??[]).map(a=>({value:a.key,label:accountName(a.key)}))]}/></label>{!['Trial balance','Balance sheet','Income statement'].includes(report)&&<label className="field">Unit<Pick label="Report unit" value={unitId||'all'} onChange={v=>setUnitId(v==='all'?'':v)} items={[{value:'all',label:'All units'},...data.units.map(u=>({value:u.id,label:'Unit '+u.number}))]}/></label>}</div><p>Native OG postings only. External evidence registers and tenant/owner subledgers are not included until they are posted to this company ledger. The check register shows posted bank withdrawals; the deposit register shows posted bank deposits.</p>{reportError?<div role="alert" className="notice">{reportError}</div>:<><div className="toolbar"><button className="secondary" disabled={blocked} onClick={()=>download(new Blob([csv([reportColumns,...printable])],{type:'text/csv'}),'OG_'+report.replaceAll(' ','_')+'_'+end+'.csv')}>Export CSV</button><button disabled={blocked} onClick={async()=>download(await reportTablePDF(report,book.company+' | '+start+' to '+end,'Posted native OG company ledger | Debit total '+money(balance.debit)+' | Credit total '+money(balance.credit),reportColumns,printable),'OG_'+report.replaceAll(' ','_')+'_'+end+'.pdf')}>Print report</button></div><Grid headers={reportColumns} rows={rows.map(r=>[r.date,r.entryId?<button className="text-button" onClick={()=>setDetail(n.entries.find(e=>e.id===r.entryId)!)}>{r.reference}</button>:r.reference,r.label,r.unitId?<button className="text-button" onClick={()=>openUnit(r.unitId)}>{data.units.find(u=>u.id===r.unitId)?.number}</button>:'Company',...[r.debit,r.credit,r.balance].map(value=><button className="text-button" onClick={()=>{if(r.entryId)setDetail(n.entries.find(e=>e.id===r.entryId)!);else open('Native ledger',r.accountKey);}}>{money(value)}</button>)])}/><p>Debits {money(balance.debit)} · Credits {money(balance.credit)}{['Trial balance','Balance sheet'].includes(report)&&!filter?' · Difference '+money(balance.debit-balance.credit):''}</p></>}</>}
 <Dialog open={form} onOpenChange={v=>{if(!saving)setForm(v);}}><DialogContent className="app-dialog native-accounting-dialog"><DialogHeader><DialogTitle>{mode==='transfers'?'Review completed transfer':'Review journal batch'}</DialogTitle><DialogDescription>{book?.company} · Verify original sources. No money moves and nothing is sent to QBO.</DialogDescription></DialogHeader>{mode==='transfers'?<div className="leasing-form-grid">{(['fromKey','toKey'] as const).map(k=><label className="field" key={k}>{k==='fromKey'?'From bank':'To bank'}<Pick label={k==='fromKey'?'Transfer from bank':'Transfer to bank'} value={transfer[k]} onChange={v=>{setVerified(false);setTransfer({...transfer,[k]:v});}} items={banks.map(a=>({value:a.key,label:accountName(a.key)}))}/></label>)}{(['amount','date','reference','source','reviewer'] as const).map(k=><label className="field" key={k}>{{amount:'Amount ($)',date:'Completed / posting date',reference:'Unique original transfer reference',source:'Verified outgoing and incoming source references',reviewer:'Reviewed by'}[k]}<input aria-label={'Transfer '+k} type={k==='date'?'date':'text'} value={transfer[k]} onChange={e=>{setVerified(false);setTransfer({...transfer,[k]:e.target.value});}}/></label>)}</div>:<><label className="field">Reviewer<input aria-label="Journal batch reviewer" value={reviewer} onChange={e=>{setReviewer(e.target.value);setPreview([]);setVerified(false);}}/></label><label className="field">Upload journal CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2000000){toast.error('Maximum journal CSV size is 2 MB');return;}setBatch(await file.text());setPreview([]);setVerified(false);}}/></label><label className="field">Journal CSV<textarea aria-label="Journal batch CSV" rows={8} value={batch} onChange={e=>{setBatch(e.target.value);setPreview([]);setVerified(false);}} placeholder={journalBatchHeaders.join(',')}/></label><button className="secondary" disabled={blocked} onClick={()=>{try{setPreview(parseJournalBatch(data,book!.id,batch,reviewer));}catch(e){setPreview([]);toast.error((e as Error).message);}}}>Validate & preview batch</button><Grid headers={['Date','Journal','Memo','Debit','Credit']} rows={preview.map(e=>[e.date,e.reference,e.memo,money(e.lines.reduce((n,l)=>n+l.debit,0)),money(e.lines.reduce((n,l)=>n+l.credit,0))])}/></>}
 <label className="check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified the company, source records, amounts and existing entries. Approve this posting.</label><button disabled={blocked||!verified||mode==='batches'&&!preview.length} onClick={save}>{saving?'Posting…':'Post reviewed '+(mode==='transfers'?'transfer':'batch')}</button></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="app-dialog native-accounting-dialog"><DialogHeader><DialogTitle>Journal · {detail?.reference}</DialogTitle><DialogDescription>Original posted entry and its accounting source</DialogDescription></DialogHeader>{detail&&<><p>{detail.date} · {detail.memo}</p><Grid headers={['Account','Unit','Debit','Credit','Memo']} rows={detail.lines.map(l=>[accountName(l.accountKey),l.unitId?<button className="text-button" onClick={()=>openUnit(l.unitId)}>{data.units.find(u=>u.id===l.unitId)?.number}</button>:'Company',money(l.debit),money(l.credit),l.memo])}/><p>{detail.reviewer} · {detail.created}</p><button className="secondary" onClick={()=>{setDetail(null);open('Native ledger');}}>Open company ledger</button></>}</DialogContent></Dialog>
 </section>;
}
