'use client';
import {useState} from 'react';
import type {ChatGPTUser} from './chatgpt-auth';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import AccountLogin from './account-login';
import PersonalSettings from './personal-settings';
import {UserRound,ChevronDown} from 'lucide-react';
export default function AccountMenu({user,onNavigate}:{user:ChatGPTUser;onNavigate:(tab:string)=>void}){const [panel,setPanel]=useState<'account'|'personal'|null>(null),[error,setError]=useState(''),[loggingOut,setLoggingOut]=useState(false);const initials=user.fullName?.split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('')||null;function navigate(value:string){if(value==='account-login'){setPanel('account');return;}setPanel(null);onNavigate(value);}async function logout(){setLoggingOut(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!r.ok)throw Error('Unable to log out. Try again.');window.location.assign('/login');}catch(e){setError((e as Error).message);}finally{setLoggingOut(false);}}
return <><DropdownMenu><DropdownMenuTrigger className="account-trigger" aria-label="User account menu">{initials?<span className="account-avatar">{initials}</span>:<UserRound size={20}/>}<span className="account-name">{user.displayName}</span><ChevronDown size={16}/></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{user.displayName}</DropdownMenuLabel><DropdownMenuItem onSelect={()=>setPanel('account')}>Account & Login</DropdownMenuItem><DropdownMenuItem onSelect={()=>setPanel('personal')}>My Settings</DropdownMenuItem>{['Global Admin','Management'].includes(user.role)&&<DropdownMenuItem onSelect={()=>navigate('general-settings')}>General Settings</DropdownMenuItem>}<DropdownMenuLabel>Profile: Property Management · {user.role}</DropdownMenuLabel>{user.role==='Global Admin'&&<DropdownMenuItem onSelect={()=>navigate('admin-logs')}>Admin logs</DropdownMenuItem>}<DropdownMenuSeparator/><DropdownMenuItem disabled={loggingOut} onSelect={()=>void logout()}>Log Out</DropdownMenuItem></DropdownMenuContent></DropdownMenu>{error&&<span role="alert">{error}</span>}<Dialog open={panel!==null} onOpenChange={open=>{if(!open)setPanel(null);}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{panel==='account'?'Account & Login':'My Settings'}</DialogTitle><DialogDescription>{panel==='account'?'Your login and security settings.':'Your report and calendar preferences.'}</DialogDescription></DialogHeader>{panel==='account'?<AccountLogin user={user}/>:panel==='personal'?<PersonalSettings key={user.authId} user={user} onNavigate={navigate}/>:null}</DialogContent></Dialog></>;}