'use client';
import {useEffect,useState} from 'react';
import type {Data} from '@/lib/pool';
import {Grid,Pick} from './report-controls';
type Log={id:string;at:string;actor:string;category:string;level:string;event:string;detail:string};
export default function AdminLogs({data}:{data:Data}){
 const [logs,setLogs]=useState<Log[]>([]),[category,setCategory]=useState('All'),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[limited,setLimited]=useState(false),[connection,setConnection]=useState<{active:number;verified_revision:number;updated:string}|null>(null);
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/admin-logs',{cache:'no-store'}),j=await r.json() as {logs:Log[];limited:boolean;connection:typeof connection;error?:string};if(!r.ok)throw Error(j.error??'Unable to load logs');setLogs(j.logs);setLimited(j.limited);setConnection(j.connection);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 const audit:Log[]=data.audit.map(a=>({id:'audit-'+a.id,at:a.at,actor:'See event details; actor not separately recorded',category:'Financial audit',level:'Info',event:a.action,detail:a.detail}));
 const rows=[...logs,...audit].filter(l=>(category==='All'||l.category===category)&&[l.event,l.detail,l.actor,l.level].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.at.localeCompare(a.at));
 return <><div className="section-heading"><div><h2>Admin logs</h2><p>Read-only financial audit history and system events for this private workspace.</p></div><button className="secondary" disabled={loading} onClick={refresh}>{loading?'Loading…':'Refresh system logs'}</button></div><section className="panel"><div className="toolbar"><Pick label="Log category" value={category} onChange={setCategory} items={['All','Financial audit','Records','Connection','Backup','Access'].map(v=>({value:v,label:v}))}/><input aria-label="Search admin logs" placeholder="Search events" value={query} onChange={e=>setQuery(e.target.value)}/></div>{connection&&<p className="hint">Latest connection status: {connection.active?'Supabase records active':'Original records database'} · verified revision {connection.verified_revision} · {new Date(connection.updated).toLocaleString()}</p>}{error&&<p className="warning">{error}</p>}<Grid headers={['Date / time','Category','Level','Actor','Event','Details']} rows={rows.map(l=>[new Date(l.at).toLocaleString(),l.category,l.level,l.actor,l.event,l.detail])}/><p className="hint">System events begin with this release. Existing financial audit events are preserved. API keys, request bodies and receipt contents are excluded. No delete or edit controls. Logs are stored in private Supabase tables.</p>{limited&&<p className="hint">Showing the latest 1,000 system events plus financial audit history.</p>}<p className="hint">Only Global Admin accounts can access system logs. Financial audit history remains part of the versioned records.</p></section></>;
}
