'use client';
import RecordActions from './record-actions';
import {useState} from 'react';
import {Grid,Pick} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function AgentCalendar({data,disabled,onSaved}:{data:any;disabled:boolean;onSaved:()=>Promise<void>}){
 const [record,setRecord]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/scoped',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'event',record,revision:data.revision,operation:crypto.randomUUID()})}),j=await r.json();if(!r.ok)throw Error(j.error);setRecord(null);await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><h3>Calendar event entry</h3><button disabled={disabled||busy||!data.units.length} onClick={()=>setRecord({id:'',unitId:data.units[0]?.id,title:'',date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago'}).format(new Date()),end:'',kind:'Administrative',notes:''})}>New event</button>{error&&<p role="alert">{error}</p>}<Grid headers={['Date','Event','Unit','']} rows={(data.events??[]).map((r:any)=>[r.date,r.title,data.units.find((u:any)=>u.id===r.unitId)?.number,<button disabled={disabled||busy} onClick={()=>setRecord({...r})}>Edit event</button>])}/><Dialog open={!!record} onOpenChange={v=>{if(!v&&!busy)setRecord(null);}}><DialogContent><DialogHeader><DialogTitle>Calendar event</DialogTitle><DialogDescription>Save the event for an assigned unit. Cancellation and deletion can be requested here; Management reviews them in the Approval center.</DialogDescription></DialogHeader>{record&&<form onSubmit={save}><label className="field">Unit<Pick label="Event unit" value={record.unitId} onChange={unitId=>setRecord({...record,unitId})} items={data.units.map((u:any)=>({value:u.id,label:u.number}))}/></label><label className="field">Title<input required maxLength={200} value={record.title} onChange={e=>setRecord({...record,title:e.target.value})}/></label><label className="field">Category<Pick label="Event category" value={record.kind} onChange={kind=>setRecord({...record,kind})} items={['Administrative','Announcements','Maintenance'].map(v=>({value:v,label:v}))}/></label><label className="field">Date<input required type="date" value={record.date} onChange={e=>setRecord({...record,date:e.target.value})}/></label><label className="field">End date<input type="date" value={record.end} onChange={e=>setRecord({...record,end:e.target.value})}/></label><label className="field">Notes<textarea maxLength={2000} value={record.notes} onChange={e=>setRecord({...record,notes:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<button disabled={disabled||busy}>Save event</button>{record.id&&<RecordActions collection="events" id={record.id} label={record.title} disabled={disabled||busy} onSaved={async()=>{setRecord(null);await onSaved();}}/>}</form>}</DialogContent></Dialog></section>;
}
