'use client';
import {useState} from 'react';
import {Grid,Pick} from './report-controls';
import {cents,money} from '@/lib/pool';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function AgentTenants({data,disabled,onSaved}:{data:any;disabled:boolean;onSaved:()=>Promise<void>}){
 const [form,setForm]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const record={...form,rent:form.rentText.trim()?cents(form.rentText):0,rentConfirmed:!!form.rentText.trim()};delete record.rentText;const r=await fetch('/api/scoped',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'tenant',record,revision:data.revision,operation:crypto.randomUUID()})}),j=await r.json();if(!r.ok)throw Error(j.error);await onSaved();setForm(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const edit=(t?:any)=>{setError('');setForm(t?{...t,rentText:t.rentConfirmed===false?'':(t.rent/100).toFixed(2)}:{unitId:data.units[0]?.id??'',firstName:'',lastName:'',email:'',cell:'',start:'',end:'',signedDate:'',rentText:'',notes:''});};
 return <section className="panel"><div className="panel-heading"><h3>Tenant directory · assigned units</h3><button disabled={disabled||busy||!data.units.length} onClick={()=>edit()}>Add tenant contact</button></div><Grid headers={['Unit','Tenant','Email','Agreement rent','']} rows={data.tenants.map((t:any)=>[data.units.find((u:any)=>u.id===t.unitId)?.number,t.firstName+' '+t.lastName,t.email,t.rentConfirmed===false?'Unverified':money(t.rent),<button disabled={disabled||busy} onClick={()=>edit(t)}>Edit tenant contact</button>])}/><Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Tenant contact & agreement</DialogTitle><DialogDescription>Assigned units only. Rent requires a verified tenant agreement; blank remains unverified. Ledger balances are preserved. Verified rent changes require a dated lease or renewal recorded by Management.</DialogDescription></DialogHeader>{form&&<form onSubmit={save}><label className="field">Unit<Pick label="Tenant unit" disabled={!!form.id} value={form.unitId} onChange={unitId=>{if(!form.id)setForm({...form,unitId});}} items={data.units.map((u:any)=>({value:u.id,label:u.number}))}/></label><div className="input-grid">{['firstName','lastName','email','cell','start','end','signedDate','rentText','pets','specialInstructions','secondFirstName','secondLastName','secondEmail','secondCell','notes'].map(key=><label className="field" key={key}>{({firstName:'First name',lastName:'Last name',email:'Email',cell:'Phone',start:'Tenancy start',end:'Tenancy end',signedDate:'Signature date',rentText:'Verified monthly rent ($)',pets:'Pets',specialInstructions:'Special instructions',secondFirstName:'Co-tenant first name',secondLastName:'Co-tenant last name',secondEmail:'Co-tenant email',secondCell:'Co-tenant phone',notes:'Notes'} as any)[key]}<input disabled={key==='rentText'&&data.tenants.some((t:any)=>t.id===form.id&&t.rentConfirmed!==false)} required={['firstName','lastName','start'].includes(key)} type={['start','end','signedDate'].includes(key)?'date':key.toLowerCase().includes('email')?'email':'text'} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div>{error&&<p role="alert">{error}</p>}<button disabled={busy||disabled}>Save tenant contact</button><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}>Cancel</button></form>}</DialogContent></Dialog></section>;
}
