'use client';
import MonthlyPool from './monthly-pool';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,cents,money,applyContracts,audit,ownerAt} from '@/lib/pool';
import {emptyAccounting} from '@/lib/accounting-model';
import {transferOwnership} from '@/lib/allocation';
import {Grid,Pick} from './report-controls';
export default function AllocationPanel({data,period,busy,persist}:{data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){
 const [amountErrors,setAmountErrors]=useState<Record<string,string>>({});
 const [contract,setContract]=useState<any>(null),[transfer,setTransfer]=useState<any>(null);
 const field=(form:any,set:(v:any)=>void,key:string,label:string,type='text')=><label className="field">{label}<input type={type} value={form[key]??''} onChange={e=>set({...form,[key]:e.target.value})}/></label>;
 const amount=(key:string,label:string)=><label className="field">{label}<input key={contract.id+key} defaultValue={(contract[key]/100).toFixed(2)} onChange={e=>{try{const value=cents(e.target.value);setContract((c:any)=>({...c,[key]:value}));setAmountErrors(errors=>({...errors,[key]:''}));}catch(err){setAmountErrors(errors=>({...errors,[key]:(err as Error).message}));}}}/>{amountErrors[key]&&<span role="alert">{amountErrors[key]}</span>}</label>;
 return <><MonthlyPool key={period} data={data} period={period} busy={busy} persist={persist}/>
 <section className="panel check-summary"><div className="panel-heading"><h3>Contract-specific fees</h3><button disabled={busy} onClick={()=>{setAmountErrors({});setContract({id:crypto.randomUUID(),unitId:data.units[0].id,from:period,managementKind:'Percent',management:0,maintenance:0,hoa:0,source:'',reviewer:''});}}>Add effective contract</button></div><Grid headers={['Unit','From','Management','Maintenance','HOA','Source / reviewer']} rows={(data.accounting?.contracts??[]).map(c=>[data.units.find(u=>u.id===c.unitId)?.number,c.from,c.managementKind==='Percent'?(c.management/100)+'%':money(c.management),money(c.maintenance),money(c.hoa),c.source+' / '+c.reviewer])}/>{contract&&<div className="input-grid"><Pick label="Contract unit" value={contract.unitId} onChange={v=>setContract({...contract,unitId:v})} items={data.units.map(u=>({value:u.id,label:'Unit '+u.number}))}/>{field(contract,setContract,'from','Effective month','month')}<Pick label="Management fee kind" value={contract.managementKind} onChange={v=>setContract({...contract,managementKind:v})} items={['Percent','Fixed'].map(v=>({value:v,label:v}))}/>{amount('management',contract.managementKind==='Percent'?'Management percentage (8.00 means 8%)':'Fixed management fee ($)')}{amount('maintenance','Monthly maintenance ($)')}{amount('hoa','Unit HOA ($)')}{field(contract,setContract,'source','Agreement / source reference')}{field(contract,setContract,'reviewer','Verified by')}<button disabled={busy} onClick={async()=>{try{if(Object.values(amountErrors).some(Boolean))throw Error('Correct invalid contract amounts before saving');const n=structuredClone(data);n.accounting??=emptyAccounting();n.accounting.contracts.push(contract);for(const s of n.statements.filter(s=>(s.unitId===contract.unitId||s.expenses.some(e=>e.linkedUnitId===contract.unitId))&&s.period>=contract.from&&s.status==='Pending'))applyContracts(n,s);audit(n,'Unit contract recorded',contract.source);if(await persist(n,'Contract fees applied to drafts; approved versions retained'))setContract(null);}catch(e){toast.error((e as Error).message);}}}>Save contract</button><button className="secondary" onClick={()=>{setContract(null);setAmountErrors({});}}>Cancel</button></div>}</section>
 <section className="panel check-summary"><div className="panel-heading"><h3>Effective ownership transfers</h3><button disabled={busy} onClick={()=>setTransfer({unitId:data.units[0].id,ownerId:data.owners[0].id,date:new Date(Date.parse(period+'-01T12:00:00Z')+32*86400000).toISOString().slice(0,7)+'-01',source:'',name:'',email:''})}>Record transfer</button></div><Grid headers={['Unit','Owner','Effective from','Through']} rows={data.ownerships.map(r=>[data.units.find(u=>u.id===r.unitId)?.number,data.owners.find(o=>o.id===r.ownerId)?.name,r.from,r.to??'Current'])}/>{transfer&&<div className="input-grid"><Pick label="Transfer unit" value={transfer.unitId} onChange={v=>setTransfer({...transfer,unitId:v})} items={data.units.map(u=>({value:u.id,label:'Unit '+u.number}))}/><Pick label="New owner" value={transfer.ownerId} onChange={v=>setTransfer({...transfer,ownerId:v})} items={[...data.owners.map(o=>({value:o.id,label:o.name})),{value:'new',label:'Create a new legal owner'}]}/>{transfer.ownerId==='new'&&<>{field(transfer,setTransfer,'name','New owner legal name')}{field(transfer,setTransfer,'email','Owner email','email')}</>}{field(transfer,setTransfer,'date','Effective first day of month','date')}{field(transfer,setTransfer,'source','Verified transfer document / reviewer')}<p className="hint">Current owner: {data.owners.find(o=>o.id===ownerAt(data,transfer.unitId,transfer.date))?.name}. Prior owner statements and ownership IDs are retained. Mid-month prorations and opening-balance settlement require a separate reviewed adjustment.</p><button disabled={busy} onClick={async()=>{try{const n=structuredClone(data);let id=transfer.ownerId;if(id==='new'){if(!transfer.name.trim())throw Error('Enter owner name');id=crypto.randomUUID();n.owners.push({id,name:transfer.name.trim(),email:transfer.email.trim()});}transferOwnership(n,transfer.unitId,id,transfer.date,transfer.source);if(await persist(n,'Ownership dates and draft statement owners updated'))setTransfer(null);}catch(e){toast.error((e as Error).message);}}}>Save transfer</button><button className="secondary" onClick={()=>setTransfer(null)}>Cancel</button></div>}</section></>;
}
