'use client';
import {useEffect,useState} from 'react';
import {Grid,Pick} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {ApprovalRequest,ControlCollection,RecordState} from '@/lib/workflow-controls';
const collectionName:Record<ControlCollection,string>={events:'Calendar event',workOrders:'Work order',prospects:'Leasing prospect',communications:'Communication draft'};
type RecordChoice={collection:ControlCollection;id:string;unitId:string;label:string;state:RecordState};
type Snapshot={revision:number;requests:ApprovalRequest[];records:RecordChoice[];canReview:boolean};
export default function ApprovalCenter({disabled=false,onSaved}:{disabled?:boolean;onSaved?:()=>Promise<void>}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState<any>(null);
 async function refresh(){setError('');const r=await fetch('/api/approvals',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error??'Approval list unavailable');setSnapshot(j);}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(disabled||busy||!snapshot)return;setBusy(true);setError('');try{const r=await fetch('/api/approvals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,revision:snapshot.revision,operation:crypto.randomUUID()})}),j=await r.json();if(!r.ok)throw Error(j.error);setForm(null);await refresh();await onSaved?.();if(j.status==='Stale')setError('The record changed after this request. It was not modified. Submit a fresh request.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const requests=snapshot?.requests??[],records=snapshot?.records??[];const chosen=records.find(r=>r.collection+':'+r.id===form?.recordKey);
 return <section className="panel approval-center"><div className="panel-heading"><div><h3>Approval center & recoverable records</h3><p>Review requested changes before applying them. Deleted records remain in trash with their history.</p></div><button className="secondary" disabled={disabled||busy} onClick={()=>void refresh().catch(e=>setError(e.message))}>Refresh approvals</button></div>{error&&<p role="alert" className="import-errors">{error}</p>}{!snapshot?<p>Loading approval records…</p>:<><p>{requests.filter(q=>q.status==='Pending').length} pending requests · {snapshot.canReview?'Global Admin and Management can review.':'You can see your own requests.'}</p><button disabled={disabled||busy||!records.length} onClick={()=>setForm({action:'request',recordKey:records[0].collection+':'+records[0].id,collection:records[0].collection,recordId:records[0].id,state:'Deleted',reason:''})}>Request record action</button><Grid headers={['Record','Action','Requested by','Reason','Status','Reviewer','']} rows={requests.map(q=>[q.collection+' · '+q.label,q.action==='Deleted'?'Delete to trash':q.action==='Canceled'?'Cancel':'Restore',q.requesterName,q.reason,q.status,q.reviewerName??'Awaiting review',q.status==='Pending'?<div className="row-actions">{snapshot.canReview?<><button disabled={disabled||busy} onClick={()=>setForm({action:'review',requestId:q.id,decision:'Approve',comment:'',request:q})}>Review</button></>:<button disabled={disabled||busy} onClick={()=>setForm({action:'withdraw',requestId:q.id,request:q})}>Withdraw</button>}</div>:q.comment??''])}/><h4>Record states & trash</h4><Grid headers={['Record','State','']} rows={records.map(r=>[r.collection+' · '+r.label,r.state,<div className="row-actions"><button disabled={disabled||busy||r.state==='Deleted'} onClick={()=>setForm({action:'request',recordKey:r.collection+':'+r.id,collection:r.collection,recordId:r.id,state:'Deleted',reason:''})}>Request deletion</button>{snapshot.canReview&&<>{r.collection==='events'&&r.state==='Active'&&<button disabled={disabled||busy} onClick={()=>setForm({action:'state',collection:r.collection,recordId:r.id,state:'Canceled',label:r.label})}>Cancel event</button>}{r.state!=='Active'&&<button disabled={disabled||busy} onClick={()=>setForm({action:'state',collection:r.collection,recordId:r.id,state:'Active',label:r.label})}>Restore</button>}{r.state!=='Deleted'&&<button disabled={disabled||busy} onClick={()=>setForm({action:'state',collection:r.collection,recordId:r.id,state:'Deleted',label:r.label})}>Delete to trash</button>}</>}</div>])}/></>}
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent><DialogHeader><DialogTitle>{form?.action==='review'?'Review approval':form?.action==='withdraw'?'Withdraw request':form?.action==='state'?'Confirm record action':'Request record action'}</DialogTitle><DialogDescription>Actions preserve the original record and create an audit entry. A changed record requires a fresh review.</DialogDescription></DialogHeader>{form&&<form onSubmit={submit}>{form.action==='request'?<><label className="field">Record<Pick label="Approval record" value={form.recordKey} onChange={value=>{const r=records.find(r=>r.collection+':'+r.id===value)!;setForm({...form,recordKey:value,collection:r.collection,recordId:r.id});}} items={records.map(r=>({value:r.collection+':'+r.id,label:r.collection+' · '+r.label+' · '+r.state}))}/></label><label className="field">Action<Pick label="Requested action" value={form.state} onChange={state=>setForm({...form,state})} items={[{value:'Deleted',label:'Delete to trash'},...(chosen?.collection==='events'?[{value:'Canceled',label:'Cancel event'}]:[]),{value:'Active',label:'Restore'}]}/></label><label className="field">Reason<textarea required maxLength={2000} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></>:form.action==='review'?<><p>{form.request.label} · {form.request.action}</p><p>Requested by {form.request.requesterName}: {form.request.reason}</p><details><summary>Record at time of request</summary><pre style={{whiteSpace:'pre-wrap',maxHeight:200,overflow:'auto'}}>{JSON.stringify(form.request.recordSnapshot,null,2)}</pre></details><label className="field">Decision<Pick label="Approval decision" value={form.decision} onChange={decision=>setForm({...form,decision})} items={['Approve','Reject'].map(v=>({value:v,label:v}))}/></label><label className="field">Review comment<textarea required maxLength={2000} value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})}/></label></>:<p>{form.label??form.request?.label} · {form.action==='withdraw'?'Withdraw pending request':form.state==='Deleted'?'Move to recoverable trash':form.state==='Canceled'?'Cancel event':'Restore record'}</p>}{error&&<p role="alert">{error}</p>}<button disabled={disabled||busy}>{busy?'Saving…':'Confirm & save'}</button></form>}</DialogContent></Dialog></section>;
}
