'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,cents,money} from '@/lib/pool';
import {native,bookChart,statementMovements} from '@/lib/native-accounting';
import {bankWorkflow,undepositedAccount,availableDepositReceipts,postGeneralReceipt,postDepositGroup,validateBankWorkflow,RECEIPT_TYPES,type BankReview} from '@/lib/bank-workflow';
import {recordAudit,validateAccounting} from '@/lib/accounting-model';
import {parseCSV,csv,download} from '@/lib/exports';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Grid,Pick} from './report-controls';
type Props={initialBook?:string;initialBank?:string;data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;mode:'receipts'|'deposits'|'review';onPage:(page:string,context?:{bookId:string;bankKey:string})=>void;openUnit:(id:string)=>void};
export default function BankWorkflowPanel({data,period,busy,persist,mode,onPage,openUnit,initialBook,initialBank}:Props){
 const [bookId,setBook]=useState(initialBook??''),[accountKey,setAccount]=useState(initialBank??''),[form,setForm]=useState<any>(null),[verified,setVerified]=useState(false),[saving,setSaving]=useState(false),[input,setInput]=useState(''),[source,setSource]=useState(''),[status,setStatus]=useState('Pending'),[detail,setDetail]=useState<string>('');
 const n=native(data),w=bankWorkflow(data),book=n.books.find(b=>b.id===bookId)??n.books[0],accounts=book?bookChart(data,book.id)?.accounts.filter(a=>a.active)??[]:[],bankAccounts=accounts.filter(a=>['bank','credit card'].includes(a.type.toLowerCase())),clearing=accounts.filter(undepositedAccount),cash=accounts.filter(a=>a.type.toLowerCase()==='bank'||undepositedAccount(a)),blocked=busy||saving,account=bankAccounts.find(a=>a.key===accountKey)??bankAccounts[0];
 const latest=new Map<string,BankReview>();for(const r of w.reviews)latest.set(r.reviewId,r);
 const field=(key:string,label:string,type='text')=><label className="field">{label}<input type={type} value={form[key]??''} maxLength={2000} onChange={e=>{setVerified(false);setForm({...form,[key]:e.target.value});}}/></label>;
 const pick=(key:string,label:string,items:{value:string;label:string}[])=><label className="field">{label}<Pick label={label} value={form[key]||'none'} onChange={v=>{setVerified(false);setForm({...form,[key]:v==='none'?'':v,...(key==='clearingKey'?{receiptEntryIds:[]}:{}),...(key==='kind'?{counterKey:'',partyId:'',unitId:'',payer:''}:{})});}} items={[{value:'none',label:'Choose verified account / record'},...items]}/></label>;
 function start(){if(!book)return;setVerified(false);setForm({bookId:book.id,date:period+'-01',reference:'',source:'',kind:RECEIPT_TYPES[0],partyId:'',payer:'',unitId:'',amount:'',cashKey:'',counterKey:'',bankKey:'',clearingKey:clearing.find(a=>a.key===initialBank)?.key??clearing[0]?.key??'',feeKey:'',fee:'0.00',receiptEntryIds:[]});}
 async function save(){if(blocked||!verified)return;setSaving(true);try{let next:Data;const reviewer='Authenticated workspace reviewer';if(mode==='receipts'){const {amount,fee,receiptEntryIds,bankKey,clearingKey,feeKey,...r}=form;next=postGeneralReceipt(data,{...r,cents:cents(amount),reviewer});}else if(mode==='deposits'){next=postDepositGroup(data,{bookId:form.bookId,date:form.date,reference:form.reference,source:form.source,bankKey:form.bankKey,clearingKey:form.clearingKey,feeKey:form.feeKey,fee:cents(form.fee),receiptEntryIds:form.receiptEntryIds,reviewer});}else{next=structuredClone(data);if(!next.accounting)throw Error('Initialize company books');(next.accounting.bankWorkflow??={receipts:[],deposits:[],reviews:[]}).reviews.push({...form,id:crypto.randomUUID(),version:form.version+1,reviewer,created:new Date().toISOString()});validateBankWorkflow(next,data);}validateAccounting(next,data);recordAudit(next,'Bank workflow '+mode+' reviewed',form.reference);if(await persist(next,'Reviewed accounting record saved'))setForm(null);}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function importRows(){if(blocked||!book||!account)return;setSaving(true);try{if(input.length>2000000)throw Error('Bank CSV exceeds 2 MB');const rows=parseCSV(input),header=rows.shift();if(header?.map(x=>x.trim().toLowerCase()).join(',')!=='date,reference,description,amount,external_id')throw Error('Use date,reference,description,amount,external_id headers');if(!rows.length||rows.length>5000)throw Error('Import 1–5,000 source rows');const next=structuredClone(data);if(!next.accounting)throw Error('Initialize company books');const target=next.accounting.bankWorkflow??={receipts:[],deposits:[],reviews:[]};for(const r of rows){if(r.length!==5)throw Error('Every bank row requires five columns');const id=crypto.randomUUID();target.reviews.push({id,reviewId:id,version:1,bookId:book.id,accountKey:account.key,date:r[0].trim(),reference:r[1].trim(),description:r[2],cents:cents(r[3]),externalId:r[4].trim(),source:source.trim(),status:'Pending',entryIds:[],reason:'',reviewer:'Authenticated workspace reviewer',created:new Date().toISOString()});}validateBankWorkflow(next,data);recordAudit(next,'Bank source rows imported for review',source);if(await persist(next,'Bank rows saved as pending; no journal posted'))setInput('');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 const eligible=form&&mode==='deposits'?availableDepositReceipts(data,form.bookId,form.clearingKey).filter(e=>e.date<=form.date):[],gross=eligible.filter(e=>form.receiptEntryIds.includes(e.id)).reduce((s,e)=>s+e.lines.filter(l=>l.accountKey===form.clearingKey).reduce((n,l)=>n+l.debit-l.credit,0),0);
 let feeAmount=0;try{feeAmount=cents(form?.fee??'0');}catch{}
 const name=(key:string)=>accounts.find(a=>a.key===key)?.name??key;
 return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">CONNECTED ACCOUNTING</p><h3>{{receipts:'Additional receipt types',deposits:'Grouped bank deposits',review:'Bank transaction review'}[mode]}</h3></div><button className="secondary" onClick={()=>onPage('Native ledger')}>Open general ledger</button></div>
 <label className="field">Company books<Pick label="Bank workflow company" value={book?.id??'none'} onChange={v=>{setBook(v);setAccount('');}} items={n.books.length?n.books.map(b=>({value:b.id,label:b.company})):[{value:'none',label:'Initialize verified books in General ledger'}]}/></label>
 {!book&&<p className="notice">Initialize verified company books and its chart before recording or matching transactions.</p>}
 {mode!=='review'&&<button disabled={blocked||!book} onClick={start}>{mode==='receipts'?'Review a receipt':'Build a deposit from existing receipts'}</button>}
 {mode==='receipts'&&<><p>Choose a direct bank receipt or hold funds in Undeposited Funds for a grouped deposit. Tenant rent belongs in Tenant ledger posting; security deposits remain liabilities.</p><Grid headers={['Date','Type','Payer','Unit','Reference','Amount','Receiving account']} rows={w.receipts.filter(r=>r.bookId===book?.id).map(r=>[r.date,r.kind,r.payer,r.unitId?<button className="text-button" onClick={()=>openUnit(r.unitId)}>Unit {data.units.find(u=>u.id===r.unitId)?.number}</button>:'Company',r.reference,<button className="text-button" onClick={()=>setDetail(r.ledgerEntryId)}>{money(r.cents)}</button>,name(r.cashKey)])}/><button className="secondary" onClick={()=>onPage('Grouped deposits')}>Next: group undeposited receipts</button></>}
 {mode==='deposits'&&<><p>Select posted tenant or general receipts held in Undeposited Funds. Deposit once, preserve original receipt detail, and deduct any verified bank fee separately.</p><Grid headers={['Date','Deposit reference','Receipts','Net deposit','Fee','Bank','Source']} rows={w.deposits.filter(g=>g.bookId===book?.id).map(g=>[g.date,g.reference,g.receiptEntryIds.length,<button className="text-button" onClick={()=>setDetail(g.ledgerEntryId)}>{money(n.entries.find(e=>e.id===g.ledgerEntryId)?.lines.filter(l=>l.accountKey===g.bankKey).reduce((s,l)=>s+l.debit-l.credit,0)??0)}</button>,money(g.fee),name(g.bankKey),g.source])}/><button className="secondary" onClick={()=>onPage('Bank transaction review')}>Next: match the bank transaction</button></>}
 {mode==='review'&&book&&<><label className="field">Bank / credit-card account<Pick label="Bank review account" value={account?.key??'none'} onChange={setAccount} items={bankAccounts.length?bankAccounts.map(a=>({value:a.key,label:a.number+' · '+a.name})):[{value:'none',label:'No bank or credit-card accounts'}]}/></label><p>Match reviewed source rows to existing OG journals. Matching does not post income, clear the monthly statement, or change QBO. Bank deposits are positive; withdrawals negative. Card charges are positive; payments / refunds negative.</p><div className="toolbar"><a className="text-button" href="https://qbo.intuit.com/app/banking" target="_blank" rel="noopener noreferrer">Open QuickBooks bank transactions ↗</a><a className="text-button" href="https://quickbooks.intuit.com/learn-support/en-us/help-article/statement-reconciliation/reconcile-account-quickbooks-online/L3XzsllsK_US_en_US" target="_blank" rel="noopener noreferrer">Reconciliation reference ↗</a></div><details><summary>Import reviewed bank rows</summary><label className="field">Original source / export identifier<input value={source} onChange={e=>setSource(e.target.value)}/></label><label className="field">Reviewed CSV<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="date,reference,description,amount,external_id"/></label><button className="secondary" disabled={blocked||!account} onClick={importRows}>Save rows for review</button><button className="secondary" onClick={()=>download(new Blob([csv([['date','reference','description','amount','external_id']])],{type:'text/csv'}),'OG_Bank_Review_Template.csv')}>Download template</button></details><nav className="people-tabs" aria-label="Bank review status">{['Pending','Matched','Excluded'].map(s=><button key={s} className={status===s?'selected':''} onClick={()=>setStatus(s)}>{s} ({[...latest.values()].filter(r=>r.bookId===book.id&&r.accountKey===account?.key&&r.status===s).length})</button>)}</nav><Grid headers={['Date','Bank description','Reference','Amount','Status','Review']} rows={[...latest.values()].filter(r=>r.bookId===book.id&&r.accountKey===account?.key&&r.status===status).map(r=>[r.date,r.description,r.reference,money(r.cents),r.status,<button className="secondary" disabled={blocked} onClick={()=>{setVerified(false);setForm(structuredClone(r));}}>Review match / exclusion</button>])}/><button className="secondary" onClick={()=>onPage('Statement reconciliation',{bookId:book?.id??'',bankKey:account?.key??''})}>Next: reconcile original statement</button></>}
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail('');}}><DialogContent className="app-dialog native-accounting-dialog"><DialogHeader><DialogTitle>Receipt / deposit journal</DialogTitle><DialogDescription>Original source and exact balanced posting</DialogDescription></DialogHeader>{(()=>{const e=n.entries.find(e=>e.id===detail);return e?<><h4>{e.reference} · {e.date}</h4><p>{e.memo}</p><Grid headers={['Account','Unit','Debit','Credit']} rows={e.lines.map(l=>[name(l.accountKey),l.unitId?<button className="text-button" onClick={()=>openUnit(l.unitId)}>Unit {data.units.find(u=>u.id===l.unitId)?.number}</button>:'Company',money(l.debit),money(l.credit)])}/><p>{e.reviewer} · {e.created}</p></>:null;})()}</DialogContent></Dialog>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!saving)setForm(null);}}><DialogContent className="app-dialog native-accounting-dialog"><DialogHeader><DialogTitle>{{receipts:'Review receipt posting',deposits:'Review grouped deposit',review:'Review bank transaction'}[mode]}</DialogTitle><DialogDescription>{book?.company} · Source evidence and original journals stay intact.</DialogDescription></DialogHeader>{form&&<>
 {mode!=='review'&&<div className="leasing-form-grid">{field('date','Accounting date','date')}{field('reference','Unique original reference')}{field('source','Original source / statement reference')}</div>}
 {mode==='receipts'&&<>{pick('kind','Receipt type',RECEIPT_TYPES.map(value=>({value,label:value})))}{form.kind==='Owner contribution'&&pick('partyId','Owner',data.owners.map(o=>({value:o.id,label:o.name})))}{form.kind==='Security deposit'&&<label className="field">Tenant<Pick label="Deposit tenant" value={form.partyId||'none'} onChange={v=>{const t=data.operations?.tenants?.find(t=>t.id===v);setVerified(false);setForm({...form,partyId:v,unitId:t?.unitId??'',payer:t?t.firstName+' '+t.lastName:''});}} items={[{value:'none',label:'Choose tenant'},...(data.operations?.tenants??[]).map(t=>({value:t.id,label:t.firstName+' '+t.lastName+' · Unit '+data.units.find(u=>u.id===t.unitId)?.number}))]}/></label>}{field('payer','Payer name')}{field('amount','Receipt amount ($)')}{pick('cashKey','Receiving bank / Undeposited Funds',cash.map(a=>({value:a.key,label:a.number+' · '+a.name})))}{pick('counterKey','Credit account',accounts.filter(a=>form.kind==='Owner contribution'?['equity','other current liability','other current liabilities'].includes(a.type.toLowerCase()):form.kind==='Security deposit'?['other current liability','other current liabilities'].includes(a.type.toLowerCase()):form.kind==='Other income'?['income','other income'].includes(a.type.toLowerCase()):['expense','expenses','other expense','other expenses','cost of goods sold','accounts payable'].includes(a.type.toLowerCase())).map(a=>({value:a.key,label:a.number+' · '+a.name})))}</>}
 {mode==='deposits'&&<>{pick('clearingKey','Undeposited Funds',clearing.map(a=>({value:a.key,label:a.name})))}{pick('bankKey','Deposit bank',accounts.filter(a=>a.type.toLowerCase()==='bank').map(a=>({value:a.key,label:a.name})))}{field('fee','Bank fee ($)')}{pick('feeKey','Fee expense account (when fee applies)',accounts.filter(a=>['expense','expenses','other expense','other expenses'].includes(a.type.toLowerCase())).map(a=>({value:a.key,label:a.name})))}<h4>Available posted receipts</h4>{eligible.map(e=><label className="check" key={e.id}><input type="checkbox" checked={form.receiptEntryIds.includes(e.id)} onChange={ev=>{setVerified(false);setForm({...form,receiptEntryIds:ev.target.checked?[...form.receiptEntryIds,e.id]:form.receiptEntryIds.filter((id:string)=>id!==e.id)});}}/>{e.date} · {e.reference} · {e.memo}</label>)}{!eligible.length&&<p className="notice">No ungrouped receipts in this clearing account and date. Post existing tenant receipts to Undeposited Funds first.</p>}<p>Gross receipts {money(gross)} − fee {money(feeAmount)} = net bank deposit <strong>{money(gross-feeAmount)}</strong></p></>}
 {mode==='review'&&<><p>{form.date} · {form.reference} · {form.description} · {money(form.cents)}</p>{pick('status','Review status',['Pending','Matched','Excluded'].map(value=>({value,label:value})))}{field('reason','Review / exclusion reason')}{form.status==='Matched'&&<><h4>Choose existing ledger movements</h4>{statementMovements(data,form.bookId,form.accountKey).filter(x=>x.entry.date<=form.date).map(x=><label className="check" key={x.entry.id}><input type="checkbox" checked={form.entryIds.includes(x.entry.id)} onChange={e=>{setVerified(false);setForm({...form,entryIds:e.target.checked?[...form.entryIds,x.entry.id]:form.entryIds.filter((id:string)=>id!==x.entry.id)});}}/>{x.entry.date} · {x.entry.reference} · {money(x.cents)}</label>)}</>}{form.status!=='Matched'&&form.entryIds.length>0&&<button className="secondary" onClick={()=>setForm({...form,entryIds:[]})}>Remove selected matches</button>}</>}
 <label className="check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified the company, original source, amount and existing transactions.</label><button disabled={blocked||!verified} onClick={save}>{saving?'Saving…':mode==='review'?'Save reviewed status':'Post reviewed balanced journal'}</button>
 </>}</DialogContent></Dialog></section>;
}
