'use client';
import {useState} from 'react';
import type {Data} from '@/lib/pool';
import {operationalReport,operationalReports,type OperationalReportId} from '@/lib/report-center';
import {buildReport,type ReportFilter} from '@/lib/report-builder';
import {reportTablePDF} from '@/lib/report-pdf';
import {csv,download} from '@/lib/exports';
import {Grid,Pick} from './report-controls';
import {toast} from 'sonner';
export default function CustomReport({data,period,openUnit}:{data:Data;period:string;openUnit:(id:string)=>void}){
 const [base,setBase]=useState<OperationalReportId>('receipts'),[property,setProperty]=useState(''),[filters,setFilters]=useState<ReportFilter[]>([]),[group,setGroup]=useState(''),[total,setTotal]=useState(''),[working,setWorking]=useState(false);
 const source=operationalReport(data,base,period,property);let result:ReturnType<typeof buildReport>|null=null,error='';try{result=buildReport(source,filters,group,total);}catch(e){error=(e as Error).message;}
 const items=source.headers.map(h=>({value:h,label:h})),title='Custom '+operationalReports.find(r=>r[0]===base)![1];
 async function exportReport(pdf:boolean){if(!result)return;setWorking(true);try{const blob=pdf?await reportTablePDF(title,period+' | '+(property?data.properties.find(p=>p.id===property)?.name:'All properties'),result.note,result.headers,result.rows):new Blob([csv([result.headers,...result.rows])],{type:'text/csv;charset=utf-8'});download(blob,'OG_custom_report_'+period+(pdf?'.pdf':'.csv'));}catch(e){toast.error((e as Error).message);}finally{setWorking(false);}}
 return <><p>Build a view from your company’s existing records. Filters and summaries change the report only.</p><div className="input-grid"><label className="field">Source report<Pick label="Custom report source" value={base} items={operationalReports.map(([value,label])=>({value,label}))} onChange={v=>{setBase(v as OperationalReportId);setFilters([]);setGroup('');setTotal('');}}/></label><label className="field">Property<Pick label="Custom report property" value={property||'all'} items={[{value:'all',label:'All properties'},...data.properties.map(p=>({value:p.id,label:p.name}))]} onChange={v=>setProperty(v==='all'?'':v)}/></label></div><h4>Refine records</h4>{filters.map((f,i)=><div className="toolbar" key={i}><Pick label={'Filter column '+(i+1)} value={f.column} items={items} onChange={v=>setFilters(filters.map((x,j)=>j===i?{...x,column:v}:x))}/><Pick label={'Filter condition '+(i+1)} value={f.operator} items={[{value:'contains',label:'Contains'},{value:'equals',label:'Equals'},{value:'not-equals',label:'Does not equal'},{value:'greater',label:'Greater than'},{value:'less',label:'Less than'}]} onChange={v=>setFilters(filters.map((x,j)=>j===i?{...x,operator:v as ReportFilter['operator']}:x))}/><input aria-label={'Filter value '+(i+1)} value={f.value} maxLength={200} onChange={e=>setFilters(filters.map((x,j)=>j===i?{...x,value:e.target.value}:x))}/><button className="secondary" onClick={()=>setFilters(filters.filter((_,j)=>j!==i))}>Remove filter</button></div>)}<button className="secondary" disabled={filters.length>=10} onClick={()=>setFilters([...filters,{column:source.headers[0],operator:'contains',value:''}])}>Add filter</button><h4>Summarize</h4><div className="input-grid"><Pick label="Group report by" value={group||'none'} items={[{value:'none',label:'Show individual records'},...items]} onChange={v=>{setGroup(v==='none'?'':v);setTotal('');}}/><Pick label="Report total column" value={total||'none'} items={[{value:'none',label:'Count records only'},...items.filter(i=>i.value!==group&&!i.value.toLowerCase().includes('repeated'))]} onChange={v=>setTotal(v==='none'?'':v)}/></div>{error?<p role="alert">{error}</p>:result&&<><p className="notice">{result.note}</p><div className="toolbar"><span>{result.rows.length} result rows</span><button disabled={working} onClick={()=>void exportReport(true)}>Download PDF / print</button><button className="secondary" disabled={working} onClick={()=>void exportReport(false)}>Export CSV</button></div><Grid headers={result.headers} rows={result.rows.map((row,i)=>row.map((v,j)=>result!.headers[j]==='Unit'&&result!.unitIds[i]?<button className="text-button" onClick={()=>openUnit(result!.unitIds[i])}>{v}</button>:v))}/></>}</>;
}
