'use client';
import {useEffect,useState} from 'react';import {Checkbox} from '@/components/ui/checkbox';import {toast} from 'sonner';
export default function DocumentMigration({busy}:{busy:boolean}){
 const [status,setStatus]=useState<{backend:string;total:number;migrated:number;connected:boolean}|null>(null),[confirmed,setConfirmed]=useState(false),[moving,setMoving]=useState(false),[error,setError]=useState('');
 async function refresh(){try{const r=await fetch('/api/document-migration',{cache:'no-store'});if(r.ok)setStatus(await r.json());}catch{}}
 useEffect(()=>{void refresh();},[]);
 async function migrate(){setMoving(true);setError('');try{const r=await fetch('/api/document-migration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed})}),j=await r.json() as {error?:string;remaining:number;copied:number};if(!r.ok)throw Error(j.error??'Document migration failed');toast.success(j.remaining?'Copied '+j.copied+' documents. Continue to move '+j.remaining+' remaining.':'Private Supabase file storage verified. All listed documents migrated.');await refresh();}catch(e){setError((e as Error).message);await refresh();}finally{setMoving(false);}}
 return <section className="panel"><h3>Private document storage</h3><p>{status?.backend==='supabase'?'New invoices and receipts use private Supabase Storage.':'Invoices and receipts currently use OG’s original private storage.'}</p><p>{status?status.migrated+' / '+status.total+' linked documents in Supabase':'Loading document status…'}</p><label className="check"><Checkbox checked={confirmed} disabled={moving||busy} onCheckedChange={v=>setConfirmed(v===true)}/> I saved a fresh workspace backup and other sessions are not uploading during the move.</label><button disabled={busy||moving||!confirmed||!status?.connected} onClick={migrate}>{moving?'Testing and copying…':status?.backend==='supabase'?'Verify / continue document migration':'Verify & migrate private documents'}</button>{error&&<p className="warning">{error}</p>}<p className="hint">Tests an upload, download checksum and blocked public access before enabling private files. Copies up to five existing files per run, preserving document IDs and invoice links. Original files stay in OG storage for recovery. Metadata remains in OG’s private database. No public owner portal or staff access is enabled by this action.</p></section>;
}
