'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,audit} from '@/lib/pool';
import {parseGL,validateMapping,mappingAccount,GL_ROLES,type GLChart,type GLRole} from '@/lib/gl-controls';
import {download} from '@/lib/exports';
import {Grid,Pick} from './report-controls';
export default function GLMapping({data,period,busy,persist}:{data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){
 const controls=data.glControls??{charts:[],mappings:[]},chart=controls.charts.at(-1),[preview,setPreview]=useState<GLChart|null>(null),[confirmed,setConfirmed]=useState(false),[company,setCompany]=useState(data.properties[0]?.companyName??'DEVONSHIRE LEASING AGENCY INC.'),[role,setRole]=useState<GLRole>('DLA management income'),[account,setAccount]=useState(''),[reviewer,setReviewer]=useState(''),[source,setSource]=useState('');
 const accounts=chart?.accounts.filter(a=>a.active)??[];
 async function file(f?:File){try{setPreview(null);setConfirmed(false);if(!f)return;if(f.size>2000000)throw Error('Chart file exceeds 2 MB');const text=await f.text(),accounts=parseGL(text),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(b=>b.toString(16).padStart(2,'0')).join('');if(controls.charts.some(c=>c.hash===hash&&c.company===company))throw Error('Chart source already saved');setPreview({id:crypto.randomUUID(),company,fileName:f.name,hash,source:text,created:new Date().toISOString(),accounts});}catch(e){toast.error((e as Error).message);}}
 return <section className="panel"><h3>QBO Chart of Accounts & bank mapping</h3><p>Preserve exact QBO account numbers, full names, types and active state. Account number is not an API account ID. This directory does not create or rename QBO accounts.</p><label className="field">QBO company name<input value={company} onChange={e=>{setCompany(e.target.value);setPreview(null);setConfirmed(false);}}/></label><button className="secondary" onClick={()=>download(new Blob(['Account number,Account name,Account type,Detail type,Active,QBO account ID\n'],{type:'text/csv'}),'OG_QBO_Chart_Template.csv')}>Download chart import template</button><label className="field">Reviewed chart CSV<input type="file" accept=".csv" disabled={busy} onChange={e=>file(e.target.files?.[0])}/></label><p className="hint">Normalized columns: Account number, Account name, Account type, Detail type, Active (true/false). Optional QBO account ID is preserved when the source supplies it. Convert the actual QBO export to these columns; this is not a QBO posting template.</p>{preview&&<><p>{preview.accounts.length} source accounts · {preview.accounts.filter(a=>a.active).length} active · {preview.company}</p><Grid headers={['Account number','QBO full name','Type','Active']} rows={preview.accounts.map(a=>[a.number,a.name,a.type,a.active?'Yes':'No'])}/><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Company and source account records reviewed</label><button disabled={busy||!confirmed||!company.trim()} onClick={async()=>{try{const n=structuredClone(data);n.glControls??={charts:[],mappings:[]};n.glControls.charts.push(preview);audit(n,'QBO chart source saved',preview.company+' / '+preview.fileName+' / '+preview.accounts.length+' accounts');if(await persist(n,'Chart saved; no QBO changes'))setPreview(null);}catch(e){toast.error((e as Error).message);}}}>Save reviewed chart</button><button className="secondary" onClick={()=>setPreview(null)}>Cancel import preview</button></>}
 <h4>Separate owner-pool and DLA roles</h4><Grid headers={['Role','QBO account','Effective month','Reviewed by']} rows={GL_ROLES.map(r=>{const current=mappingAccount(data,r,period);return [r,current?.account?.name??'Not mapped',current?.mapping.from??'—',current?.mapping.reviewer??'—'];})}/><div className="input-grid"><Pick label="Accounting role to map" value={role} onChange={v=>{setRole(v as GLRole);setAccount('');}} items={GL_ROLES.map(r=>({value:r,label:r}))}/><Pick label="Verified QBO account" value={account} onChange={setAccount} items={accounts.map(a=>({value:a.key,label:(a.number?a.number+' · ':'')+a.name+' · '+a.type}))}/><label className="field">Mapping source / approved agreement<input value={source} onChange={e=>setSource(e.target.value)}/></label><label className="field">Mapping reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label></div><button disabled={busy||!chart||!account||!source.trim()||!reviewer.trim()} onClick={async()=>{try{const n=structuredClone(data),mapping={id:crypto.randomUUID(),chartId:chart!.id,accountKey:account,role,from:period,reviewer,source,created:new Date().toISOString()};validateMapping(n,mapping);n.glControls!.mappings.push(mapping);audit(n,'QBO account role mapped',role+' / '+account+' / '+period+' / '+reviewer);await persist(n,'Effective mapping saved; original versions retained');}catch(e){toast.error((e as Error).message);}}}>Save effective account mapping</button><p className="hint">DLA fee income requires income accounts. Owner deductions require expense accounts. Owner operating, escrow and DLA operating must use distinct bank accounts. A new DLA bank account must be opened externally before mapping it here. No transfer or payment is initiated.</p><p>{controls.charts.length} preserved chart sources · {controls.mappings.length} preserved mapping versions.</p></section>;
}
