'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,audit,money,latest} from '@/lib/pool';
import {homeownerRows,validateHoaAssociations,type HoaAssociation} from '@/lib/hoa-directory';
import {Grid} from './report-controls';
import TenantProfile from './tenant-profile';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';

type Props={data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;navigate:(view:string)=>void;openUnit:(id:string)=>void};
export default function HoaWorkspace({data,period,busy,persist,navigate,openUnit}:Props){
 const [tab,setTab]=useState('HomeOwners'),[search,setSearch]=useState(''),[property,setProperty]=useState('All'),[unit,setUnit]=useState<string|null>(null),[form,setForm]=useState<HoaAssociation|null>(null),[saving,setSaving]=useState(false);
 const blocked=busy||saving;
 const matches=(value:string)=>value.toLowerCase().includes(search.toLowerCase());
 const rows=homeownerRows(data,period).filter(r=>(property==='All'||r.unit.propertyId===property)&&matches([r.unit.number,r.owner?.name,r.property?.name].join(' ')));
 async function save(){if(!form||blocked)return;setSaving(true);try{const next=structuredClone(data);next.hoaAssociations??=[];const record={...form,name:form.name.trim(),email:form.email.trim(),phone:form.phone.trim(),contactName:form.contactName.trim()};const index=next.hoaAssociations.findIndex(a=>a.id===record.id);if(index<0)next.hoaAssociations.push(record);else next.hoaAssociations[index]=record;validateHoaAssociations(data,next);audit(next,index<0?'HOA association added':'HOA association updated',record.name+' / '+record.propertyIds.length+' linked properties');if(await persist(next,'Association saved'))setForm(null);}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 return <div className="hoa-workspace">
  <div className="people-tabs" role="tablist" aria-label="HOA workspace">{['HomeOwners','Properties','Associations'].map(label=><button key={label} role="tab" aria-selected={tab===label} className={tab===label?'selected':''} onClick={()=>{setTab(label);setSearch('');}}>{label}</button>)}</div>
  <section className="panel"><div className="panel-heading"><div><h2>{tab}</h2><p>Shared property and owner records · {period}</p></div>{tab==='Associations'&&<button disabled={blocked||!data.properties.length} onClick={()=>setForm({id:crypto.randomUUID(),name:'',propertyIds:property==='All'?[]:[property],contactName:'',email:'',phone:'',notes:''})}>Add association</button>}</div>
   <div className="toolbar"><label className="field">Property<select aria-label="HOA property" value={property} onChange={e=>setProperty(e.target.value)}><option value="All">All properties</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">Search<input aria-label="Search HOA records" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
   {tab==='HomeOwners'&&<><Grid headers={['Unit','Homeowner','Property','Association','HOA on owner statement','Next action']} rows={rows.map(r=>{const statement=latest(data,period).find(s=>s.unitId===r.unit.id);const amount=statement?.expenses.filter(e=>e.gl==='80000'&&(e.linkedUnitId??statement.unitId)===r.unit.id).reduce((sum,e)=>sum+e.cents,0);return [r.unit.number,r.owner?.name??'Owner needs verification',r.property?.name??'Property needs verification',r.associations.map(a=>a.name).join(', ')||'Not linked',r.unit.hoaChargedThrough?'Through Unit '+(data.units.find(u=>u.id===r.unit.hoaChargedThrough)?.number??'Unverified'):amount===undefined?'No statement':money(amount),<div className="toolbar"><button className="text-button" disabled={blocked} onClick={()=>setUnit(r.unit.id)}>Open homeowner</button><button className="text-button" onClick={()=>openUnit(r.unit.id)}>Owner statement</button></div>];})}/><p className="hint">Includes units outside the leasing pool. HOA amounts shown are owner-statement deductions, not association invoices or proof of payment.</p></>}
   {tab==='Properties'&&<Grid headers={['Property','Address','Units','Associations','Next action']} rows={data.properties.filter(p=>(property==='All'||p.id===property)&&matches(p.name+' '+(p.address??''))).map(p=>[p.name,[p.address,p.city,p.state,p.zip].filter(Boolean).join(', ')||'Not entered',data.units.filter(u=>u.propertyId===p.id).length,(data.hoaAssociations??[]).filter(a=>a.propertyIds.includes(p.id)).map(a=>a.name).join(', ')||'Not linked',<div className="toolbar"><button className="text-button" onClick={()=>{setProperty(p.id);setSearch('');setTab('HomeOwners');}}>Homeowners</button><button className="text-button" onClick={()=>{setProperty(p.id);setSearch('');setTab('Associations');}}>Associations</button><button className="text-button" onClick={()=>navigate('properties')}>Manage property</button></div>])}/>}
   {tab==='Associations'&&<><Grid headers={['Association','Linked properties','Contact','Email / phone','Next action']} rows={(data.hoaAssociations??[]).filter(a=>(property==='All'||a.propertyIds.includes(property))&&matches(a.name+' '+a.contactName)).map(a=>[a.name,a.propertyIds.map(id=>data.properties.find(p=>p.id===id)?.name??'Unknown property').join(', '),a.contactName||'Not entered',[a.email,a.phone].filter(Boolean).join(' / ')||'Not entered',<div className="toolbar"><button className="text-button" disabled={blocked} onClick={()=>setForm(structuredClone(a))}>Edit association</button>{a.propertyIds.map(id=><button key={id} className="text-button" onClick={()=>{setProperty(id);setSearch('');setTab('HomeOwners');}}>Homeowners · {data.properties.find(p=>p.id===id)?.name}</button>)}</div>])}/>{!(data.hoaAssociations??[]).length&&<p>No associations recorded. Add a verified association and link its properties.</p>}<p className="hint">Association contacts and property links are saved in this workspace. Board portals, association billing and external HOA synchronization are not connected.</p></>}
  </section>
  {unit&&<TenantProfile initialTab="Owner" data={data} period={period} unitId={unit} close={()=>setUnit(null)} busy={blocked} persist={persist} openOwner={()=>{setUnit(null);openUnit(unit);}}/>}
  <Dialog open={!!form} onOpenChange={open=>{if(!open&&!saving)setForm(null);}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{data.hoaAssociations?.some(a=>a.id===form?.id)?'Edit association':'Add association'}</DialogTitle><DialogDescription>Link verified association details to existing properties.</DialogDescription></DialogHeader>{form&&<><div className="input-grid">{(['name','contactName','email','phone'] as const).map(key=><label className="field" key={key}>{({name:'Association name',contactName:'Contact name',email:'Email',phone:'Phone'})[key]}<input disabled={blocked} type={key==='email'?'email':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><fieldset disabled={blocked}><legend>Linked properties</legend>{data.properties.map(p=><label className="check" key={p.id}><input type="checkbox" checked={form.propertyIds.includes(p.id)} onChange={e=>setForm({...form,propertyIds:e.target.checked?[...form.propertyIds,p.id]:form.propertyIds.filter(id=>id!==p.id)})}/>{p.name}</label>)}</fieldset><label className="field">Notes<textarea disabled={blocked} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="toolbar"><button disabled={blocked} onClick={save}>{saving?'Saving…':'Save association'}</button><button className="secondary" disabled={saving} onClick={()=>setForm(null)}>Cancel</button></div></>}</DialogContent></Dialog>
 </div>;
}
