'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,money} from '@/lib/pool';
import {type InvoiceSourceRow,checkInvoiceRows,postInvoiceBatch,linkPendingInvoices,moveImportedMaterialsToStock,applyReviewedTaskNotes} from '@/lib/invoice-import';
import {Grid} from './report-controls';
export default function InvoiceImportPanel({data,period,busy,persist}:{data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){
 const [review,setReview]=useState<{fileName:string;hash:string;rows:InvoiceSourceRow[]}|null>(null),[reviewer,setReviewer]=useState(''),[error,setError]=useState('');
 const history=(data.invoiceImports??[]).filter(b=>b.period===period),rows=review?.rows??history.flatMap(b=>b.rows),effectiveKind=(r:InvoiceSourceRow)=>!review&&data.invoiceStockCorrections?.some(c=>c.sourceId===r.sourceId)?'Stock':r.kind,sum=(kind:string)=>rows.filter(r=>effectiveKind(r)===kind).reduce((n,r)=>n+r.cents,0);
 async function read(file:File){setError('');setReview(null);try{if(file.size>2000000)throw Error('Source package exceeds 2 MB');const text=await file.text(),j=JSON.parse(text);if(j.period!==period)throw Error('Choose the accounting month matching the source package');checkInvoiceRows(j.rows,period);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),b=>b.toString(16).padStart(2,'0')).join('');setReview({fileName:j.fileName||file.name,hash,rows:j.rows});}catch(e){setError((e as Error).message);}}
 async function taskNotes(){try{const n=structuredClone(data),count=applyReviewedTaskNotes(n,period,reviewer);await persist(n,count+' owner drafts updated with reviewed English task descriptions');}catch(e){setError((e as Error).message);}}
 async function moveStock(sourceId:string){try{const n=structuredClone(data);moveImportedMaterialsToStock(n,sourceId,reviewer,'Management reviewed: full receipt is small tools and equipment inventory, not a unit owner charge.');await persist(n,'Receipt moved to inventory; owner charge removed');}catch(e){setError((e as Error).message);}}
 async function link(){try{const n=structuredClone(data),count=linkPendingInvoices(n,period,reviewer);await persist(n,count+' saved unit bills linked');}catch(e){setError((e as Error).message);}}
 async function save(){try{if(!review)return;const n=structuredClone(data),b=postInvoiceBatch(n,{...review,period,reviewer});if(await persist(n,'Invoice source saved: '+b.rows.filter(r=>r.status==='Posted'&&['Labor','Materials'].includes(r.kind)).length+' unit charges; '+b.rows.filter(r=>r.status==='Held').length+' owner links pending')){setReview(null);setReviewer('');}}catch(e){setError((e as Error).message);toast.error((e as Error).message);}}
 return <section className="panel" aria-label="Reviewed supplier invoices"><h3>Reviewed supplier invoices · {period}</h3><p>Import the reviewed invoice package prepared from the source invoices and QBO register. The charge month and original payment information are kept separately. Already recorded QBO items are excluded from new QBO bill exports; bank balances do not change.</p><label className="field">Reviewed invoice source<input aria-label="Reviewed invoice source" type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void read(file);e.target.value='';}}/></label>{error&&<p role="alert" className="warning">{error}</p>}{review&&<><label className="field">Invoice reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><p>{review.fileName} · {rows.length} items · {money(rows.reduce((n,r)=>n+r.cents,0))}. Unit records missing from OG are saved as bills with owner links pending, without creating an owner or changing pool membership.</p><button disabled={busy||!reviewer.trim()} onClick={()=>void save()}>Record reviewed invoices</button><button className="secondary" disabled={busy} onClick={()=>setReview(null)}>Cancel import preview</button></>}
 <div className="summary-line"><span>Labor</span><strong>{money(sum('Labor'))}</strong></div><div className="summary-line"><span>Unit materials</span><strong>{money(sum('Materials'))}</strong></div><div className="summary-line"><span>Stock purchases · no owner charge until issued</span><strong>{money(sum('Stock'))}</strong></div><div className="summary-line"><span>DLA operating items · no unit allocation</span><strong>{money(sum('Operating'))}</strong></div>
 <Grid headers={['Unit / destination','Vendor / reference','Charge date','Description','Amount','QBO GL / class','Payment status','Original payment information','Posting / source']} rows={rows.map(r=>[effectiveKind(r)==='Stock'?'Inventory':r.unit||r.kind,r.vendor+' / '+(r.reference||'No invoice number in source'),r.date,r.description,money(r.cents),r.gl+' '+r.accountName+' / '+(r.qboClass||'No QBO class'),r.paymentState,r.paymentMonth?'Payment month reported: '+r.paymentMonth+'; '+r.notes:r.notes,('status' in r?r.status==='Held'?'Bill saved · owner link pending':'Recorded':'Import preview')+' · '+r.source])}/>
 {!review&&history.some(b=>b.rows.some(r=>r.status==='Held'&&!data.invoiceLinks?.some(l=>l.sourceId===r.sourceId)))&&<><label className="field">Link reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><button disabled={busy||!reviewer.trim()} onClick={()=>void link()}>Link saved bills after unit setup</button></>}
 {!review&&<details><summary>Owner task notes and inventory corrections</summary><p>Preserves the source receipt and audit history. Removes the owner charge and records one receipt lot, not an invented item quantity. No QBO or bank posting.</p><label className="field">Correction reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><button disabled={busy||!reviewer.trim()} onClick={()=>void taskNotes()}>Apply reviewed English task descriptions to owner drafts</button>{history.flatMap(b=>b.rows).filter(r=>r.kind==='Materials'&&r.status==='Posted'&&!data.invoiceStockCorrections?.some(c=>c.sourceId===r.sourceId)).map(r=><p key={r.sourceId}>Unit {r.unit} · {r.vendor} · {r.reference} · {money(r.cents)} <button disabled={busy||!reviewer.trim()} onClick={()=>void moveStock(r.sourceId)}>Move receipt {r.reference} to inventory</button></p>)}</details>}
 {history.map(b=><p className="hint" key={b.id}>{b.fileName} · {b.rows.length} items · reviewed by {b.reviewer} · {b.created}</p>)}<p className="hint">Stock quantity is the book quantity from received invoices minus recorded usage. Verify the physical count before issuing. Purchase cost does not set the owner’s unit charge price.</p></section>;
}

