'use client';
import {useState,useEffect} from 'react';
import {toast} from 'sonner';
import {ArrowRight,Plus,CalendarDays,Users,Building2,FileText,CheckCircle2} from 'lucide-react';
import {type Data,money,cents,audit} from '@/lib/pool';
import {emptyOperations,type Prospect,type Lease} from '@/lib/operations-model';
import {leasingSections,leasingSnapshot,applicationForGuest,saveLeasingLease,leasingSearch,leasingActivityMetrics,validLeasingRange,type LeasingSection,type RentalApplication} from '@/lib/leasing-workflow';
import {Grid,Pick} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import RecordDocuments from './record-documents';
import DateInput from './date-input';
import {csv,download} from '@/lib/exports';
type Props={data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;onRecords:()=>void;initialSection?:LeasingSection;onSectionChange?:(section:LeasingSection)=>void};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function LeasingWorkspace({data,period,busy,persist,onRecords,initialSection='Vacancies',onSectionChange}:Props){
 const [section,setCurrentSection]=useState<LeasingSection>(initialSection),[property,setProperty]=useState(''),[query,setQuery]=useState(''),[form,setForm]=useState<any>(null),[kind,setKind]=useState(''),[saving,setSaving]=useState(false),[originalForm,setOriginalForm]=useState(''),[discardRequested,setDiscardRequested]=useState(false);
 const [metricFrom,setMetricFrom]=useState(period+'-01'),[metricTo,setMetricTo]=useState(new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),0)).toISOString().slice(0,10)),[metricGroup,setMetricGroup]=useState<'Property'|'Unit type'>('Property');
 useEffect(()=>{setMetricFrom(period+'-01');setMetricTo(new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),0)).toISOString().slice(0,10));},[period]);
 useEffect(()=>setCurrentSection(initialSection),[initialSection]);
 function setSection(next:LeasingSection){setCurrentSection(next);onSectionChange?.(next);}
 const ops=data.operations??emptyOperations(),snapshot=leasingSnapshot(data,period,today(),property),blocked=busy||saving;
 const activity=leasingActivityMetrics(data,metricFrom,metricTo,property,metricGroup),activityHeaders=['Group','Units','Applications created','Approval decisions','Signed leases','Lease starts','Expiring active leases','Completed showings'],activityRows=activity.map(r=>[r.name,r.units,r.applications,r.approved,r.signed,r.starts,r.expiring,r.showings]);
 function exportSummary(){if(!validLeasingRange(metricFrom,metricTo)){toast.error('Enter a valid activity date range');return;}download(new Blob([csv([['Leasing activity',metricFrom,metricTo],['Property',property?data.properties.find(p=>p.id===property)?.name:'All properties'],activityHeaders,...activityRows])],{type:'text/csv'}),'leasing-summary-'+period+'.csv');}
 const number=(id:string)=>data.units.find(u=>u.id===id)?.number??'Choose unit',guest=(id:string)=>ops.prospects.find(p=>p.id===id)?.name??'Guest';
 const matches=(r:unknown)=>leasingSearch(data,r,query);
 function availability(unitId:string){open('occupancy',ops.occupancy?.find(o=>o.unitId===unitId&&o.month===period)??{id:crypto.randomUUID(),unitId,month:period,status:'Unknown',marketingStatus:'Not recorded',listedDate:'',notes:''});}
 function viewLease(l:Lease){open('lease',{...l,rentText:(l.rent/100).toFixed(2)});}
 function open(type:string,value?:any){setKind(type);setDiscardRequested(false);const next=value?structuredClone(value):type==='guest'?{id:crypto.randomUUID(),name:'',email:'',phone:'',source:'',assignee:'',unitId:snapshot.units[0]?.id??'',stage:'Inquiry',tour:'',moveIn:'',followUp:'',notes:'',maxRent:0}:type==='showing'?{id:crypto.randomUUID(),prospectId:'',unitId:'',date:today(),time:'10:00',assignee:'',status:'Scheduled',notes:''}:null;setForm(next);setOriginalForm(JSON.stringify(next));}
 async function commit(n:Data,label:string){if(blocked)return false;setSaving(true);try{audit(n,label,'Leasing workspace · '+period);return await persist(n,label);}catch(e){toast.error((e as Error).message);return false;}finally{setSaving(false);}}
 async function startApplication(p:Prospect){const n=structuredClone(data);n.operations??=emptyOperations();try{const a=applicationForGuest(n.operations,p.id,crypto.randomUUID(),today());if(await commit(n,'Application draft saved')){setSection('Applications');open('application',a);}}catch(e){toast.error((e as Error).message);}}
 function prepareLease(a?:RentalApplication,original?:Lease){const existing=ops.leases.find(l=>original?l.renewalOf===original.id:a?l.applicationId===a.id:false);if(existing){setSection('Leases');viewLease(existing);return;}if(a?.status!=='Approved'&&!original){toast.error('Complete the application review first');return;}const p=ops.prospects.find(p=>p.id===a?.prospectId);const unitId=original?.unitId??a?.unitId??'';const tenant=ops.tenants?.find(t=>t.id===original?.tenantId);const start=original?new Date(Date.parse(original.end+'T12:00:00Z')+86400000).toISOString().slice(0,10):p?.moveIn||today();open('lease',{id:crypto.randomUUID(),unitId,tenant:original?.tenant??p?.name??'',tenantId:tenant?.id??'',start,end:'',rentText:((original?.rent??0)/100).toFixed(2),status:'Draft',signedDate:'',notes:'',...(a?{applicationId:a.id}:{}),...(original?{renewalOf:original.id}:{})});}
 async function save(){if(!form||blocked)return;try{const n=structuredClone(data);n.operations??=emptyOperations();const o=n.operations;if(kind==='guest'){const existing=o.prospects.find(p=>p.id===form.id);if(existing)Object.assign(existing,form);else o.prospects.push(form);}else if(kind==='showing'){const existing=o.leasingShowings?.find(s=>s.id===form.id);if(existing)Object.assign(existing,form);else(o.leasingShowings??=[]).push(form);const p=o.prospects.find(p=>p.id===form.prospectId);if(p&&form.status==='Scheduled'){p.tour=form.date;if(p.stage==='Inquiry')p.stage='Tour scheduled';}}else if(kind==='application'){const existing=o.rentalApplications?.find(a=>a.id===form.id);if(!existing)throw Error('Save a guest card before creating an application');Object.assign(existing,form);if(form.status==='Submitted')o.prospects.find(p=>p.id===form.prospectId)!.stage='Application received';}else if(kind==='lease'){const {rentText,...record}=form;const result=saveLeasingLease(o,{...record,rent:cents(rentText)});if(result.id!==form.id){toast.info('The existing draft is available in Leases');setForm(null);setSection('Leases');return;}const p=o.prospects.find(p=>p.id===o.rentalApplications?.find(a=>a.id===form.applicationId)?.prospectId);if(p)p.stage='Lease prepared';}else if(kind==='occupancy'){const existing=o.occupancy?.find(r=>r.unitId===form.unitId&&r.month===period);if(existing)Object.assign(existing,form);else(o.occupancy??=[]).push(form);}if(await commit(n,'Leasing '+kind+' saved'))setForm(null);}catch(e){toast.error((e as Error).message);}}
 const recordLocked=busy||(kind==='lease'&&!!ops.leases.find(l=>l.id===form?.id&&l.status!=='Draft'))||(kind==='showing'&&!!ops.leasingShowings?.find(s=>s.id===form?.id&&s.status!=='Scheduled'));
 const decisionLocked=recordLocked||kind==='application'&&['Approved','Denied','Withdrawn'].includes(ops.rentalApplications?.find(a=>a.id===form?.id)?.status??'');
 const field=(key:string,label:string,type='text')=><label className="field">{label}{type==='date'?<DateInput disabled={decisionLocked} label={label} value={form?.[key]??''} onChange={value=>setForm((f:any)=>({...f,[key]:value}))}/>:<input readOnly={decisionLocked} type={type} value={form?.[key]??''} onChange={e=>{const value=e.target.value;setForm((f:any)=>({...f,[key]:value}));}}/>}</label>;
 function closeForm(){if(saving)return;if(!decisionLocked&&JSON.stringify(form)!==originalForm){setDiscardRequested(true);return;}setForm(null);}
 const notes=<label className="field">Notes<textarea readOnly={decisionLocked} value={form?.notes??''} onChange={e=>setForm({...form,notes:e.target.value})}/></label>;
 const unitPicker=<label className="field">Unit<Pick disabled={recordLocked} label="Leasing unit" value={form?.unitId||'none'} onChange={unitId=>{const id=unitId==='none'?'':unitId;if(kind==='occupancy')availability(id);else setForm({...form,unitId:id});}} items={[{value:'none',label:'Choose unit'},...snapshot.units.map(u=>({value:u.id,label:'Unit '+u.number}))]}/></label>;
 const actions:Record<LeasingSection,[string,()=>void][]>= {Vacancies:[['Verify unit availability',()=>availability(snapshot.units[0]?.id??'')],['Add a guest card',()=>open('guest')]],'Guest cards':[['Add a guest card',()=>open('guest')],['Schedule a showing',()=>open('showing')]],Applications:[['View guest cards',()=>setSection('Guest cards')],['Review lease drafts',()=>setSection('Leases')]],Leases:[['Review resident & lease records',onRecords],['View applications',()=>setSection('Applications')]],Renewals:[['Review lease records',onRecords],['View all leases',()=>setSection('Leases')]],Metrics:[['View application pipeline',()=>setSection('Applications')],['Download summary',exportSummary]]};
 return <div className="leasing-workspace"><section className="leasing-hero"><div><p className="eyebrow">DEVONSHIRE LEASING · {period}</p><h2>A better journey home.</h2><p>From the first inquiry to a confident renewal. Every next step in one place.</p></div><Building2 size={44}/></section><nav className="leasing-stages" aria-label="Leasing workflow">{leasingSections.map((s,i)=><button key={s} className={section===s?'active':'secondary'} aria-current={section===s?'page':undefined} onClick={()=>setSection(s)}><span>{i+1}</span>{s}</button>)}<button className="secondary" onClick={onRecords}>Rent & residents</button></nav><div className="leasing-filters"><label className="field">Property<Pick label="Leasing property" value={property||'all'} onChange={v=>setProperty(v==='all'?'':v)} items={[{value:'all',label:'All properties'},...data.properties.map(p=>({value:p.id,label:p.name}))]}/></label>{section!=='Metrics'&&<label className="field">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Guest, unit or record"/></label>}</div><div className="leasing-columns"><main className="leasing-main"><section className="panel">{query.trim()&&section!=='Metrics'&&<div className="toolbar"><span className="hint">Filtering by “{query}”</span><button className="text-button" onClick={()=>setQuery('')}>Clear search</button></div>}<div className="panel-heading"><div><p className="eyebrow">LEASING WORKSPACE</p><h3>{section}</h3></div><span className="badge">Saved workspace records</span></div>
 {section==='Vacancies'&&<><p>Only verified vacant units appear here. {snapshot.unknown.length} unit(s) still need occupancy review.</p><Grid headers={['Unit','Property','Availability','Marketing','Next action']} rows={snapshot.vacancies.filter(matches).map(u=>{const r=ops.occupancy?.find(o=>o.unitId===u.id&&o.month===period);return [u.number,data.properties.find(p=>p.id===u.propertyId)?.name,'Verified vacant',r?.marketingStatus??'Not recorded',<button className="text-button" disabled={blocked} onClick={()=>open('guest',{id:crypto.randomUUID(),name:'',email:'',unitId:u.id,stage:'Inquiry',tour:'',notes:''})}>Add interested guest</button>];})}/><h3>Availability to verify</h3><Grid headers={['Unit','Property','Next action']} rows={snapshot.unknown.filter(matches).map(u=>[u.number,data.properties.find(p=>p.id===u.propertyId)?.name,<button className="text-button" disabled={blocked} onClick={()=>availability(u.id)}>Verify availability</button>])}/><p className="hint">Listing publication and syndication are not connected. Marketing status is a manual record.</p></>}
 {section==='Guest cards'&&<><p>Capture the inquiry, schedule a showing, then prepare an application.</p><Grid headers={['Guest','Unit','Stage','Contact','Follow-up','Next action']} rows={snapshot.prospects.filter(matches).map(p=>[p.name,number(p.unitId),p.stage,p.email||p.phone||'Not recorded',p.followUp||'Not scheduled',<div className="toolbar"><button className="text-button" disabled={saving} onClick={()=>open('guest',p)}>Open card</button><button className="text-button" disabled={blocked||!p.unitId} onClick={()=>startApplication(p)}>Application</button><button className="text-button" disabled={blocked||!p.unitId} onClick={()=>open('showing',{id:crypto.randomUUID(),prospectId:p.id,unitId:p.unitId,date:today(),time:'10:00',assignee:p.assignee??'',status:'Scheduled',notes:''})}>Showing</button></div>])}/><h3>Showings</h3><Grid headers={['Guest','Unit','Date','Time','Host','Status','']} rows={snapshot.showings.filter(matches).map(s=>[guest(s.prospectId),number(s.unitId),s.date,s.time,s.assignee,s.status,<button className="text-button" disabled={saving} onClick={()=>open('showing',s)}>{s.status==='Scheduled'?'Update showing':'View showing'}</button>])}/></>}
 {section==='Applications'&&<><p>Review each application deliberately. Decisions require a date and reason.</p><Grid headers={['Applicant','Unit','Created','Status','Next action']} rows={snapshot.applications.filter(matches).map(a=>[guest(a.prospectId),number(a.unitId),a.submitted,a.status,<div className="toolbar"><button className="text-button" disabled={saving} onClick={()=>open('application',a)}>Review</button>{a.status==='Approved'&&<button className="text-button" disabled={blocked} onClick={()=>prepareLease(a)}>Prepare lease</button>}</div>])}/><p className="hint">Screening, application fees and online applicant submission are not connected. Record the results of your review; this workspace does not make eligibility decisions.</p></>}
 {section==='Leases'&&<><p>Open a draft to review terms, link the resident and record the verified signature. Signed history stays read-only.</p><Grid headers={['Unit','Resident','Start','End','Contract rent','Status','Documents & next action']} rows={snapshot.leases.filter(matches).map(l=>[number(l.unitId),l.tenant,l.start,l.end,money(l.rent),l.status,<div><RecordDocuments type="lease" id={l.id} busy={blocked}/><button className="text-button" disabled={saving} onClick={()=>viewLease(l)}>Open lease</button></div>])}/><p className="hint">Contract rent is separate from receipts and owner distributions. E-signature is not connected. Use your approved lease forms.</p></>}
 {section==='Renewals'&&<><p>Active leases expiring in the next 90 days. Original signed terms stay intact.</p><Grid headers={['Unit','Resident','Expires','Current rent','Next action']} rows={snapshot.renewals.filter(matches).map(l=>[number(l.unitId),l.tenant,l.end,money(l.rent),<button className="text-button" disabled={blocked} onClick={()=>prepareLease(undefined,l)}>{ops.leases.some(r=>r.renewalOf===l.id)?'View existing renewal':'Prepare renewal'}</button>])}/><p className="hint">Month-to-month residents without a dated active lease remain available in Rent & residents for manual review.</p></>}
 {section==='Metrics'&&<><div className="leasing-form-grid"><label className="field">Activity from<DateInput label="Activity from" value={metricFrom} onChange={setMetricFrom}/></label><label className="field">Activity through<DateInput label="Activity through" value={metricTo} onChange={setMetricTo}/></label><label className="field">Group by<Pick label="Leasing metrics grouping" value={metricGroup} onChange={v=>setMetricGroup(v as 'Property'|'Unit type')} items={['Property','Unit type'].map(value=>({value,label:value}))}/></label></div>{!validLeasingRange(metricFrom,metricTo)?<p className="notice">Enter valid dates with the start before the end.</p>:<><h3>Activity during the selected dates</h3><Grid headers={activityHeaders} rows={activityRows}/><p className="hint">Applications use their creation date; approvals and signed leases use their recorded decision or signature date. Drafts are excluded from signed leases and lease starts.</p></>}<p>Counts follow the selected property and saved records. Application totals are cumulative; availability uses {period}.</p><div className="leasing-metric-grid">{[['Verified vacant',snapshot.vacancies.length,Building2],['Open guest cards',snapshot.prospects.filter(p=>p.stage!=='Closed').length,Users],['Applications in review',snapshot.applications.filter(a=>['Submitted','Under review'].includes(a.status)).length,FileText],['Approved applications',snapshot.applications.filter(a=>a.status==='Approved').length,CheckCircle2],['Scheduled showings',snapshot.showings.filter(s=>s.status==='Scheduled'&&s.date>=today()).length,CalendarDays],['Renewals in 90 days',snapshot.renewals.length,FileText]].map(([label,value,Icon])=>{const I=Icon as typeof Building2;return <div className="leasing-metric" key={String(label)}><I size={20}/><strong>{String(value)}</strong><span>{String(label)}</span></div>;})}</div><Grid headers={['Lead source','Guest cards']} rows={Array.from(new Set(snapshot.prospects.map(p=>p.source||'Not recorded'))).map(source=>[source,snapshot.prospects.filter(p=>(p.source||'Not recorded')===source).length])}/></>}
 {((section==='Vacancies'&&!snapshot.vacancies.length)||(section==='Guest cards'&&!snapshot.prospects.length)||(section==='Applications'&&!snapshot.applications.length)||(section==='Leases'&&!snapshot.leases.length)||(section==='Renewals'&&!snapshot.renewals.length))&&<div className="leasing-empty"><FileText/><h3>Your next step is ready.</h3><p>No {section.toLowerCase()} match this property yet. Use the tasks alongside to begin.</p></div>}
 </section></main><aside className="panel luxury-tasks leasing-tasks"><p className="eyebrow">YOUR NEXT STEP</p><h3>{section} tasks</h3>{actions[section].map(([label,fn])=><button key={label} className="secondary" disabled={blocked&&section!=='Metrics'} onClick={fn}>{label}<ArrowRight size={16}/></button>)}<div className="leasing-guide"><h4>A clear path</h4><ol><li>Verify availability</li><li>Capture the guest</li><li>Schedule a showing</li><li>Review the application</li><li>Prepare and verify the lease</li><li>Plan the renewal</li></ol></div></aside></div>
 <Dialog open={!!form} onOpenChange={v=>{if(!v)closeForm();}}><DialogContent className="app-dialog leasing-dialog"><DialogHeader><DialogTitle>{kind==='guest'?'Guest card':kind==='showing'?'Showing':kind==='application'?'Application review':kind==='lease'?(recordLocked?'Lease record':'Lease terms & activation'):'Verify availability'}</DialogTitle><DialogDescription>{decisionLocked?'Read-only saved history.':'Review the details before saving. All changes use the workspace audit history.'}</DialogDescription></DialogHeader>{form&&<><div className="leasing-form-grid">
 {kind==='guest'&&<>{field('name','Full name')}{field('email','Email','email')}{field('phone','Phone','tel')}{unitPicker}{field('source','Lead source')}{field('assignee','Assigned to')}{field('moveIn','Desired move-in','date')}{field('followUp','Next follow-up','date')}<label className="field">Stage<Pick disabled={recordLocked} label="Guest stage" value={form.stage} onChange={stage=>setForm({...form,stage})} items={['Inquiry','Tour scheduled','Application received','Lease prepared','Closed'].map(value=>({value,label:value}))}/></label></>}
 {kind==='showing'&&<><label className="field">Guest<Pick disabled={recordLocked} label="Showing guest" value={form.prospectId||'none'} onChange={v=>{const p=ops.prospects.find(p=>p.id===v);setForm({...form,prospectId:p?.id??'',unitId:p?.unitId??''});}} items={[{value:'none',label:'Choose guest'},...snapshot.prospects.filter(p=>p.unitId).map(p=>({value:p.id,label:p.name+' · Unit '+number(p.unitId)}))]}/></label>{field('date','Date','date')}{field('time','Time · America/Chicago','time')}{field('assignee','Showing host')}<label className="field">Status<Pick disabled={recordLocked} label="Showing status" value={form.status} onChange={status=>setForm({...form,status})} items={['Scheduled','Completed','Cancelled'].map(value=>({value,label:value}))}/></label></>}
 {kind==='application'&&<><p>{guest(form.prospectId)} · Unit {number(form.unitId)}</p><label className="field">Review stage<Pick label="Application stage" disabled={decisionLocked} value={form.status} onChange={status=>setForm({...form,status,decided:['Approved','Denied','Withdrawn'].includes(status)?today():'',reason:''})} items={({Draft:['Draft','Submitted','Withdrawn'],Submitted:['Submitted','Under review','Withdrawn'],'Under review':['Under review','Approved','Denied','Withdrawn'],Approved:['Approved'],Denied:['Denied'],Withdrawn:['Withdrawn']} as Record<string,string[]>)[ops.rentalApplications?.find(a=>a.id===form.id)?.status??'Draft'].map(value=>({value,label:value}))}/></label>{['Approved','Denied','Withdrawn'].includes(form.status)&&<>{field('decided','Decision date','date')}{field('reason','Decision reason')}</>}</>}
 {kind==='lease'&&<><p>Unit {number(form.unitId)} · {form.renewalOf?'Renewal':form.applicationId?'Application lease':'Lease record'}</p>{field('tenant','Resident name')}<label className="field">Link resident record<Pick disabled={recordLocked} label="Lease resident" value={form.tenantId||'none'} onChange={v=>{const t=ops.tenants?.find(t=>t.id===v);setForm({...form,tenantId:t?.id??'',tenant:t?t.firstName+' '+t.lastName:form.tenant});}} items={[{value:'none',label:'Link before activating'},...(ops.tenants??[]).filter(t=>t.unitId===form.unitId).map(t=>({value:t.id,label:t.firstName+' '+t.lastName}))]}/></label>{field('start','Term starts','date')}{field('end','Term ends','date')}{field('rentText','Monthly contract rent','text')}{ops.leases.some(l=>l.id===form.id)&&<><label className="field">Lease status<Pick disabled={recordLocked} label="Lease status" value={form.status} onChange={status=>setForm({...form,status})} items={(recordLocked?[form.status]:['Draft','Active']).map(value=>({value,label:value==='Active'&&!recordLocked?'Activate verified signed lease':value}))}/></label>{field('signedDate','Verified signature date','date')}<p className="hint">Activation requires a linked resident, a verified signature date and a matching tenancy term. Attach your signed lease in the documents column. No charges or payments are created.</p></>}{!form.tenantId&&!recordLocked&&<button className="secondary" onClick={()=>{setForm(null);onRecords();}}>Open resident records to add or verify the resident</button>}</>}
 {kind==='occupancy'&&<>{unitPicker}<label className="field">Verified occupancy<Pick label="Verified occupancy" value={form.status} onChange={status=>setForm({...form,status})} items={['Unknown','Vacant','Occupied','Make ready'].map(value=>({value,label:value}))}/></label><label className="field">Marketing status<Pick label="Marketing status" value={form.marketingStatus??'Not recorded'} onChange={marketingStatus=>setForm({...form,marketingStatus})} items={['Not recorded','Not listed','On market','Reserved'].map(value=>({value,label:value}))}/></label>{field('listedDate','Listing date','date')}</>}
 </div>{notes}{discardRequested&&<section className="notice" role="alertdialog" aria-label="Unsaved leasing changes"><h3>Keep your changes?</h3><p>This edit has not been saved.</p><div className="toolbar"><button className="secondary" onClick={()=>setDiscardRequested(false)}>Keep editing</button><button onClick={()=>{setDiscardRequested(false);setForm(null);}}>Discard changes</button></div></section>}<div className="toolbar"><button disabled={blocked||decisionLocked} onClick={save}><Plus size={16}/>{saving?'Saving…':'Save '+(kind==='lease'?(form.status==='Active'?'verified activation':'draft'):'record')}</button><button className="secondary" disabled={saving} onClick={closeForm}>{decisionLocked?'Done':'Cancel'}</button></div></>}</DialogContent></Dialog>
 </div>;
}








