'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,audit} from '@/lib/pool';
import {emptyOperations} from '@/lib/operations-model';
import {manualLeasingNext,validateManualLeasing,type ManualLeasingKind} from '@/lib/leasing-services';
import {Grid,Pick} from './report-controls';
import DateInput from './date-input';

export default function LeasingServices({data,kind,busy,persist,property}:{data:Data;kind:ManualLeasingKind;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;property:string}){
 const [recordId,setRecord]=useState(''),[status,setStatus]=useState(''),[date,setDate]=useState(''),[reference,setReference]=useState(''),[notes,setNotes]=useState(''),[confirmed,setConfirmed]=useState(false),[saving,setSaving]=useState(false);
 const ops=data.operations??emptyOperations(),unit=(id:string)=>data.units.find(u=>u.id===id),inScope=(id:string)=>!property||unit(id)?.propertyId===property;
 const records=kind==='screening'?(ops.rentalApplications??[]).filter(a=>inScope(a.unitId)&&!['Approved','Denied','Withdrawn'].includes(a.status)).map(a=>({value:a.id,label:(ops.prospects.find(p=>p.id===a.prospectId)?.name??'Guest')+' · Unit '+unit(a.unitId)?.number})):kind==='signature'?ops.leases.filter(l=>inScope(l.unitId)&&l.status==='Draft').map(l=>({value:l.id,label:l.tenant+' · Unit '+unit(l.unitId)?.number})):data.units.filter(u=>inScope(u.id)).map(u=>({value:u.id,label:'Unit '+u.number}));
 const selected=records.some(r=>r.value===recordId)?recordId:'',next=selected?manualLeasingNext(ops,kind,selected):[],chosen=next.includes(status)?status:next[0]??'';
 const titles={screening:'Screening review',signature:'Lease signature tracking',listing:'Listing publication tracking'};
 const history=(ops.manualLeasingEvents??[]).filter(e=>e.kind===kind&&(!selected||e.recordId===selected)).filter(e=>{const id=kind==='listing'?e.recordId:kind==='signature'?ops.leases.find(l=>l.id===e.recordId)?.unitId:ops.rentalApplications?.find(a=>a.id===e.recordId)?.unitId;return !!id&&inScope(id);});
 function label(id:string){return records.find(r=>r.value===id)?.label??(kind==='listing'?'Unit '+unit(id)?.number:kind==='signature'?ops.leases.find(l=>l.id===id)?.tenant:ops.prospects.find(p=>p.id===ops.rentalApplications?.find(a=>a.id===id)?.prospectId)?.name)??'Record';}
 async function save(){if(busy||saving)return;setSaving(true);try{if(!selected||!chosen)throw Error('Choose a record with an available next step');const n=structuredClone(data);n.operations??=emptyOperations();(n.operations.manualLeasingEvents??=[]).push({id:crypto.randomUUID(),kind,recordId:selected,status:chosen,date,reference:reference.trim(),notes:notes.trim(),confirmed});validateManualLeasing(n.operations,new Set(n.units.map(u=>u.id)),ops);audit(n,'Manual leasing step recorded',kind+' · '+chosen);if(await persist(n,'Manual leasing step recorded')){setStatus('');setReference('');setNotes('');setConfirmed(false);}}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 return <section className="panel"><p className="eyebrow">STAFF WORKFLOW · MANUAL</p><h3>{titles[kind]}</h3><p>{kind==='screening'?'Record documented consent, your external request and human review. Application decisions remain a separate reviewed step.':kind==='signature'?'Prepare and send the lease through your chosen service, then record completion here. Attach the completed lease in its document record before activating it.':'Prepare the listing, publish it on your chosen channels and record the reference here. OG does not send a listing feed.'}</p><p className="hint">Record completed actions only. Do not enter identity numbers, credit reports or credentials in notes.</p><div className="leasing-form-grid"><label className="field">{kind==='screening'?'Application':kind==='signature'?'Lease draft':'Unit'}<Pick label={titles[kind]+' record'} value={selected||'none'} onChange={v=>{setRecord(v==='none'?'':v);setStatus('');setConfirmed(false);}} items={[{value:'none',label:'Choose record'},...records]}/></label><label className="field">Next completed step<Pick label="Manual workflow step" value={chosen||'none'} onChange={setStatus} items={next.length?next.map(v=>({value:v,label:v})):[{value:'none',label:'No available step'}]}/></label><label className="field">Completed date<DateInput label="Manual workflow completed date" value={date} onChange={setDate}/></label><label className="field">Supporting reference<input maxLength={500} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Document name, request ID or listing reference"/></label><label className="field">Notes<textarea maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><label className="manual-leasing-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I verified this step was completed and its supporting record is available.</label><button disabled={busy||saving||!selected||!chosen||!confirmed||!date||!reference.trim()} onClick={save}>{saving?'Saving…':'Record completed step'}</button><h4>Saved action history</h4><Grid headers={['Record','Completed step','Date','Reference','Notes']} rows={history.map(e=>[label(e.recordId),e.status,e.date,e.reference,e.notes])}/></section>;
}
