'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,audit} from '@/lib/pool';
import {emptyOperations} from '@/lib/operations-model';
import {providerSignInURL,validateManualLeasing,type ManualLeasingKind} from '@/lib/leasing-services';
export default function LeasingProviderSetup({data,kind,busy,persist}:{data:Data;kind:ManualLeasingKind;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){
 const [name,setName]=useState(''),[url,setURL]=useState(''),[saving,setSaving]=useState(false);
 const providers=(data.operations?.leasingProviders??[]).filter(p=>p.kind===kind);
 async function save(){if(busy||saving)return;setSaving(true);try{const signInURL=providerSignInURL(url.trim());if(!name.trim())throw Error('Enter the provider name');const n=structuredClone(data);n.operations??=emptyOperations();const rows=n.operations.leasingProviders??=[];if(rows.some(p=>p.kind===kind&&p.signInURL===signInURL))throw Error('This provider sign-in address is already saved');rows.push({id:crypto.randomUUID(),kind,name:name.trim(),signInURL});validateManualLeasing(n.operations,new Set(n.units.map(u=>u.id)),data.operations);audit(n,'Leasing provider sign-in saved',kind+' · '+name.trim());if(await persist(n,'Provider sign-in saved')){setName('');setURL('');}}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 return <details className="leasing-provider-setup"><summary>Provider access · {providers.length?providers.length+' saved':'choose any provider'}</summary><p>Add the provider you use, then open its sign-in page in a new tab. Sign in directly with that service. This saves a sign-in shortcut; it does not authorize an automatic connection to OG.</p><div className="leasing-form-grid"><label className="field">Provider name<input maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Your screening, signature or listing service"/></label><label className="field">Sign-in page<input type="url" maxLength={1000} value={url} onChange={e=>setURL(e.target.value)} placeholder="https://provider.com/login"/></label></div><p className="hint">Use the public sign-in address. Keep passwords, API keys and private login links with the provider.</p><button disabled={busy||saving||!name.trim()||!url.trim()} onClick={save}>{saving?'Saving…':'Save provider access'}</button><div className="leasing-provider-links">{providers.map(p=><div key={p.id}><strong>{p.name}</strong><span>Manual access · no automatic connection</span><a className="report-file-link" href={p.signInURL} target="_blank" rel="noopener noreferrer">Sign in to {p.name} ↗</a><small>{new URL(p.signInURL).hostname}</small></div>)}</div></details>;
}
