'use client';
import {useState} from 'react';
import {CloudSun,ArrowUpRight} from 'lucide-react';
import {weatherCities,type PublicForecast} from '@/lib/public-weather';
export default function LocalWeather(){
 const [city,setCity]=useState(''),[forecast,setForecast]=useState<PublicForecast|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function show(){setBusy(true);setError('');setForecast(null);try{const r=await fetch('/api/public-weather?city='+encodeURIComponent(city));if(!r.ok)throw Error();setForecast(await r.json());}catch{setError('Forecast unavailable. Open the official weather source below.');}finally{setBusy(false);}}
 return <section className="welcome-weather" aria-labelledby="weather-title"><div className="welcome-section-title"><div><span className="welcome-eyebrow">PLAN YOUR DAY</span><h2 id="weather-title"><CloudSun size={28}/> Local weather</h2><p>Official forecasts for selected U.S. and Puerto Rico cities.</p></div><a href="https://www.weather.gov/" target="_blank" rel="noopener noreferrer">Weather source <ArrowUpRight size={15}/></a></div><form className="welcome-weather-form" onSubmit={e=>{e.preventDefault();void show();}}><label htmlFor="weather-city">Your area</label><select id="weather-city" value={city} disabled={busy} onChange={e=>{setCity(e.target.value);setForecast(null);setError('');}}><option value="">Choose a city</option>{weatherCities.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><button className="welcome-primary" disabled={!city||busy} type="submit">{busy?'Loading forecast…':'Show forecast'}</button></form><p className="welcome-data-note">Your selected city is sent to the National Weather Service to retrieve its forecast. OG does not request or track your device location. For other areas, use the weather source.</p><div role="status">{error&&<p>{error}</p>}{forecast&&<><h3>{forecast.city}</h3><div className="welcome-market-grid">{forecast.periods.map(p=><article className="welcome-market-card" key={p.startTime}><h3>{p.name}</h3><strong>{p.temperature}°{p.temperatureUnit}</strong><p>{p.shortForecast}</p><span>Wind: {p.windSpeed}</span></article>)}</div><p className="welcome-data-note">National Weather Service · Forecast updated {new Date(forecast.updated).toLocaleString()}. Forecast temperatures are not current observations.</p></>}</div></section>;
}
