'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Data,audit,money,cents} from '@/lib/pool';
import {emptyOperations} from '@/lib/operations-model';
import {generateRecurringWork,validateMaintenanceRecords} from '@/lib/maintenance-model';
import {Grid,Pick} from './report-controls';
type Register='Recurring Work Orders'|'Purchase Orders'|'Fixed Assets';
export default function MaintenanceRegisters({data,section,busy,persist,openWork}:{data:Data;section:Register;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;openWork:(id:string)=>void}){
 const [form,setForm]=useState<any>(null),[query,setQuery]=useState('');const ops=data.operations??emptyOperations(),key=section==='Recurring Work Orders'?'recurringWork':section==='Purchase Orders'?'purchaseOrders':'fixedAssets';
 const rows=ops[key]??[],today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const unit=(id:string)=>data.units.find(u=>u.id===id)?.number??'Property-wide';
 function create(record?:any){setForm(record?structuredClone(record):{id:crypto.randomUUID(),unitId:'',notes:'',...(key==='recurringWork'?{kind:'Repair',title:'',description:'',assignee:'',vendor:'',nextDate:today,intervalMonths:1,active:true}:key==='purchaseOrders'?{number:'PO-'+crypto.randomUUID().slice(0,8).toUpperCase(),workOrderId:'',supplier:'',description:'',date:today,expectedDate:'',amount:0,status:'Draft',approvedBy:''}:{tag:'',name:'',serial:'',acquired:'',cost:0,status:'In service',nextService:''})});}
 async function save(){try{const n=structuredClone(data);n.operations??=emptyOperations();const list:any[]=n.operations[key]??=[];const index=list.findIndex(r=>r.id===form.id);if(index<0)list.push(form);else list[index]=form;validateMaintenanceRecords(n.operations,new Set(n.units.map(u=>u.id)),ops);audit(n,section+' saved',form.title??form.number??form.tag);if(await persist(n,'Maintenance record saved'))setForm(null);}catch(e){toast.error((e as Error).message);}}
 async function generate(id:string){try{const n=structuredClone(data);const w=generateRecurringWork(n.operations!,id,today);audit(n,'Recurring work order generated',w.number+' / '+w.title+' / '+w.scheduled);if(await persist(n,'Work order created'))openWork(w.id);}catch(e){toast.error((e as Error).message);}}
 const text=(k:string,label:string,type='text')=><label className="field">{label}<input type={type} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>;
 const pick=(k:string,label:string,values:string[])=><label className="field">{label}<Pick label={label} value={form[k]} onChange={v=>setForm({...form,[k]:v})} items={values.map(v=>({value:v,label:v}))}/></label>;
 const amount=(k:string,label:string)=><label className="field">{label}<input inputMode="decimal" defaultValue={(form[k]/100).toFixed(2)} onBlur={e=>{try{setForm({...form,[k]:cents(e.target.value)});}catch(e){toast.error((e as Error).message);}}}/></label>;
 const filtered=rows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(query.toLowerCase()))||unit(r.unitId).includes(query));
 return <section className="panel"><div className="panel-heading"><h3>{section}</h3><button disabled={busy} onClick={()=>create()}>Add {key==='recurringWork'?'recurring schedule':key==='purchaseOrders'?'purchase order':'fixed asset'}</button></div><div className="search"><input aria-label={'Search '+section} placeholder="Search records or unit…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {key==='recurringWork'?<><Grid headers={['Schedule','Unit','Assignment','Next due','Interval','Status','']} rows={(filtered as any[]).map(r=>[r.title,unit(r.unitId),r.assignee||r.vendor||'Unassigned',r.nextDate,r.intervalMonths+' month(s)',r.active?'Active':'Paused',<div className="toolbar"><button className="text-button" disabled={busy} onClick={()=>create(r)}>Edit</button><button disabled={busy||!r.active||r.nextDate>today} onClick={()=>generate(r.id)}>Create next due job</button></div>])}/><p className="hint">Create one due occurrence at a time. Each job retains its schedule source and advances the next date. Pausing preserves history. Entry permission and owner approval must be recorded on each job.</p></>:key==='purchaseOrders'?<><Grid headers={['Order','Unit / work order','Supplier','Description','Order / expected date','Amount','Status / approval','']} rows={(filtered as any[]).map(r=>[r.number,unit(r.unitId)+' / '+(ops.workOrders.find(w=>w.id===r.workOrderId)?.number??'No work order'),r.supplier,r.description,r.date+' / '+(r.expectedDate||'Not entered'),money(r.amount),r.status+' / '+(r.approvedBy||'Not approved'),<button className="text-button" disabled={busy} onClick={()=>create(r)}>Edit</button>])}/><p className="hint">Purchase orders track planned purchases and documented approval. Changing status does not send an order, pay a supplier, receive inventory, or charge an owner. Receive delivered stock in Inventory → Bulk purchases with the supplier invoice reference.</p></>:<><Grid headers={['Asset / tag','Unit / location','Serial','Acquired','Recorded cost','Next service','Status','']} rows={(filtered as any[]).map(r=>[r.name+' / '+r.tag,unit(r.unitId),r.serial||'Not entered',r.acquired||'Not entered',money(r.cost),r.nextService||'Not scheduled',r.status,<button className="text-button" disabled={busy} onClick={()=>create(r)}>Edit</button>])}/><p className="hint">Track equipment and service dates. This register does not calculate depreciation or post accounting entries. Retire an asset to preserve its history.</p></>}
 {!filtered.length&&<p>No {section.toLowerCase()} match this view.</p>}
 <Dialog open={!!form} onOpenChange={v=>{if(!v)setForm(null);}}><DialogContent className="app-dialog ops-dialog"><DialogHeader><DialogTitle>{section}</DialogTitle><DialogDescription>Save an internal maintenance record.</DialogDescription></DialogHeader>{form&&<><label className="field">Unit / location<Pick label="Unit / location" value={form.unitId||'none'} onChange={v=>setForm({...form,unitId:v==='none'?'':v,workOrderId:''})} items={[{value:'none',label:'Property-wide'},...data.units.map(u=>({value:u.id,label:'Unit '+u.number}))]}/></label><div className="input-grid">{key==='recurringWork'?<>{text('title','Job title')}{pick('kind','Recurring work type',['Repair','Inspection','Unit turn','Project'])}{text('description','Work instructions')}{text('assignee','Assigned technician')}{text('vendor','Vendor')}{text('nextDate','Next due date','date')}<label className="field">Repeat every (months)<input type="number" min={1} max={12} value={form.intervalMonths} onChange={e=>setForm({...form,intervalMonths:Number(e.target.value)})}/></label><label className="field">Schedule status<Pick label="Schedule status" value={form.active?'Active':'Paused'} onChange={v=>setForm({...form,active:v==='Active'})} items={['Active','Paused'].map(v=>({value:v,label:v}))}/></label></>:key==='purchaseOrders'?<>{text('number','Order number')}{text('supplier','Supplier')}{text('description','Items / purchase description')}{text('date','Order date','date')}{text('expectedDate','Expected delivery','date')}{amount('amount','Total planned amount ($)')}{pick('status','Order status',['Draft','Submitted','Approved','Received','Cancelled'])}{text('approvedBy','Approval documented by')}<label className="field">Related work order<Pick label="Related work order" value={form.workOrderId||'none'} onChange={v=>setForm({...form,workOrderId:v==='none'?'':v})} items={[{value:'none',label:'No work order'},...ops.workOrders.filter(w=>w.unitId===form.unitId).map(w=>({value:w.id,label:w.number+' · '+w.title}))]}/></label></>:<>{text('tag','Unique asset tag')}{text('name','Asset name')}{text('serial','Serial number')}{text('acquired','Acquired date','date')}{amount('cost','Recorded acquisition cost ($)')}{text('nextService','Next service date','date')}{pick('status','Asset status',['In service','Under repair','Retired'])}</>}</div><label className="field">Notes / evidence<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button disabled={busy} onClick={save}>Save record</button></>}</DialogContent></Dialog></section>;
}

