'use client';
import type {MaintenanceSection} from '@/lib/maintenance-model';
export type MaintenanceTask={label:string;target?:MaintenanceSection;action:string};
export const maintenanceTasks:Record<MaintenanceSection,{tasks:MaintenanceTask[];reports:string[];help:string}>={
 'Work Orders':{tasks:[{label:'New Work Order',action:'work'},{label:'New Recurring Work Order',target:'Recurring Work Orders',action:'new'},{label:'New Purchase Order',target:'Purchase Orders',action:'new'}],reports:['Work Order','Labor Summary','Billable Detail'],help:'Assign the job, record entry permission, track estimates and dates, then record completion. Ready to bill posts approved labor once to a draft owner statement.'},
 'Recurring Work Orders':{tasks:[{label:'New Recurring Work Order',action:'new'},{label:'New Work Order',target:'Work Orders',action:'work'}],reports:['Recurring Work Order','Work Order'],help:'Save a schedule, then create the next due job from its row. Each occurrence advances the due date and retains its source. Pause schedules to retain history.'},
 'Inspections':{tasks:[{label:'New Inspection',action:'work'},{label:'View Inspection Calendar',action:'calendar'}],reports:['Inspection Detail','Unit Inspection'],help:'Inspection jobs use the work-order workflow. Record findings and checklist results in the job notes and attach completion evidence to the saved job.'},
 'Unit Turns':{tasks:[{label:'New Unit Turn',action:'work'},{label:'New Recurring Work Order',target:'Recurring Work Orders',action:'new'}],reports:['Unit Turn Detail'],help:'Create a Unit turn job, assign a technician, record the make-ready tasks and scheduled date, and track progress through completion. Update occupancy separately in Leasing.'},
 'Projects':{tasks:[{label:'New Project',action:'work'},{label:'New Purchase Order',target:'Purchase Orders',action:'new'}],reports:['Project Detail'],help:'Track each project as a work-order job with an assignee, estimate, follow-up date and progress notes. Link purchase orders to the project job.'},
 'Purchase Orders':{tasks:[{label:'New Purchase Order',action:'new'},{label:'Receive Bulk Purchase',target:'Inventory',action:'purchase'}],reports:['Purchase Order'],help:'Record the supplier, planned amount, expected delivery and approval evidence. Receive delivered stock separately in Inventory. Order status does not send or pay an order.'},
 'Inventory':{tasks:[{label:'Add Part',action:'part'},{label:'Receive Bulk Purchase',action:'purchase'},{label:'Issue Parts to Unit',action:'issue'},{label:'Returns & Adjustments',action:'corrections'}],reports:['Inventory','Bulk Purchases','Unit Usage'],help:'Receive stock at purchase cost, issue parts at the saved list price, and use Returns & adjustments for corrections. Issuing parts adds a materials charge to the unit’s draft statement.'},
 'Fixed Assets':{tasks:[{label:'New Fixed Asset',action:'new'},{label:'New Service Work Order',target:'Work Orders',action:'work'}],reports:['Fixed Asset'],help:'Record an asset tag, serial number, location and next service date. Retire equipment to preserve its record. Create a service work order when maintenance is due.'},
};
export default function MaintenanceTasks({section,busy,onTask,onReport}:{section:MaintenanceSection;busy:boolean;onTask:(task:MaintenanceTask)=>void;onReport:(report:string)=>void}){const config=maintenanceTasks[section];return <aside className="maintenance-task-panel" aria-label={section+' actions'}><h3>Tasks</h3><p>{section}</p><div className="action-group"><span>Tasks</span>{config.tasks.map(task=><button className="text-button" key={task.label} disabled={busy} onClick={()=>onTask(task)}>{task.label}</button>)}</div><div className="action-group"><span>Reports · CSV</span>{config.reports.map(report=><button className="text-button" key={report} onClick={()=>onReport(report)}>{report}</button>)}</div><details><summary>Help · {section} workflow</summary><p>{config.help}</p></details></aside>;}

