'use client';
import {useState} from 'react';
import {type Data,money} from '@/lib/pool';
import {clearingReview,clearingState,recordClearing} from '@/lib/monthly-clearing';
import {toast} from 'sonner';
export default function MonthlyClearing({data,period,busy,persist}:{data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){
 const [reviewer,setReviewer]=useState(''),[reason,setReason]=useState('');const r=clearingReview(data,period),state=clearingState(data,period),closed=state?.kind==='Closed';
 async function save(){try{const n=structuredClone(data);recordClearing(n,period,closed?'Reopened':'Closed',reviewer,reason);if(await persist(n,closed?'Monthly clearing reopened':'Monthly clearing closed at $0.00')){setReason('');}}catch(e){toast.error((e as Error).message);}}
 return <section className="panel monthly-clearing-panel"><div className="panel-heading"><div><h3>Monthly clearing · {period}</h3><p>Each month starts at zero; recorded receipts must be fully assigned.</p></div><span className={'badge '+(closed?'approved':'pending')}>{closed?'Closed':'Open review'}</span></div><div className="summary-line"><span>Opening clearing target</span><strong>$0.00</strong></div><div className="summary-line"><span>Calculated closing difference</span><strong>{money(r.closing)}</strong></div><div className="summary-line"><span>Unpaid prior-month rent remaining</span><strong>{money(r.unpaidRent)}</strong></div><p className="hint">Unpaid tenant rent stays on its original charge and carries forward until a receipt or credit settles it. Closing this review does not erase owner balances, bills or escrow and does not move bank funds.</p>{!closed&&r.blockers.length>0&&<details><summary>{r.blockers.length} items to resolve before closing</summary><ul>{r.blockers.map(b=><li key={b}>{b}</li>)}</ul></details>}<label className="field">Reviewer<input maxLength={200} value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><label className="field">{closed?'Reason to reopen':'Review notes'}<input maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reviewer.trim()||!reason.trim()||!closed&&r.blockers.length>0} onClick={save}>{closed?'Reopen monthly clearing':'Close monthly clearing at $0.00'}</button>{closed&&<p className="hint">Closed by {state.reviewer} · {state.created.slice(0,10)}. Reopen with a reason before changing the month’s income/allocation sources.</p>}<details><summary>Clearing review history</summary>{(data.clearingEvents??[]).filter(e=>e.period===period).map(e=><p className="hint" key={e.id}>{e.created} · {e.kind} · {e.reviewer} · {e.reason} · closing {money(e.closing)}</p>)}</details></section>;
}
