'use client';
import {useState,type ReactNode} from 'react';
import {toast} from 'sonner';
import {type Data,audit,isParticipating,verifiedVacantUnits} from '@/lib/pool';
import {propertySections,accountingSections,reportingSections,type OfficeKey} from '@/lib/office-model';
import {buildReport,reportCatalog,reportSupported,selectReportColumns} from '@/lib/report-engine';
import {csv,download} from '@/lib/exports';
import {Grid,Pick} from './report-controls';
import QboGLImport from './qbo-gl-import';
import OfficeRegister,{type RegisterAction} from './office-register';
import {officeTasks} from '@/lib/office-tasks';
import AccountingPanel from './accounting-panel';
import MonthlyClearing from './monthly-clearing';
type Props={data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;navigate:(s:string)=>void;management:boolean;view:string;section:string;onSection:(s:string)=>void;children?:ReactNode;newProperty?:()=>void};
const registers:Record<string,[OfficeKey,string,string]>={Associations:['profiles','Association and property settings','Classify existing properties and record board contacts and statement instructions.'], 'Financial Accounts':['accounts','Financial accounts','External statement snapshots only. Unknown balances stay blank; bank feeds are not connected.'], 'Journal Entries':['journals','Journal entries','Balanced internal review records. Recording an external reference does not post to QBO or change balances.'], 'Bank Transfers':['transfers','Bank transfers','Prepare and track transfers performed externally. OG does not move funds or change account balances.'], 'GL Accounts':['glAccounts','GL accounts','Directory and QBO account mapping only; balances remain in the accounting system.'], 'Online Payments':['tasks','Online payment setup requests','Payment processing is not connected. Store preparation requests; no payment or activation is submitted.'], 'Scheduled Reports':['schedules','Scheduled report preparation','Manual preparation plans linked to saved reports. No automatic run, email or delivery is connected.'], Surveys:['surveys','Maintenance survey responses','Record responses received externally. Survey invitations are not sent.'], Compliance:['compliance','Violations and architectural reviews','Internal register with rule and evidence references. No fines or notices are issued.']};
export default function OfficeWorkspace(p:Props){const {data,period,busy,persist,navigate,management,view,section,onSection}=p;const [property,setProperty]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[report,setReport]=useState('Property Directory'),[from,setFrom]=useState(period+'-01'),[to,setTo]=useState(period+'-'+new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate()),[columns,setColumns]=useState<string[]>([]),[hidden,setHidden]=useState(false),[reportName,setReportName]=useState(''),[taskAction,setTaskAction]=useState<RegisterAction|null>(null);
const sections=view==='properties'?propertySections:view==='accounting'?accountingSections.filter(s=>management||s!=='DLA Analysis'):reportingSections;
const register=registers[section];let result;try{result=selectReportColumns(buildReport(data,report,{propertyId:property,from,to}),columns);}catch(e){result={available:false,columns:[],rows:[],note:(e as Error).message};}
const items=reportCatalog.flatMap(group=>group.reports.map(name=>({group:group.category,name}))).filter(r=>(category==='All'||r.group===category)&&r.name.toLowerCase().includes(query.toLowerCase()));
function exportReport(){try{const r=selectReportColumns(buildReport(data,report,{propertyId:property,from,to}),columns);if(!r.available)throw Error(r.note);download(new Blob([csv([r.columns,...r.rows])],{type:'text/csv'}),report.replaceAll(' ','_')+'.csv');}catch(e){toast.error((e as Error).message);}}
async function saveReport(){const name=reportName.trim()||report;try{const n=structuredClone(data);n.office??={};n.office.presets??=[];n.office.presets.push({id:crypto.randomUUID(),name:name.trim(),report,propertyId:property,from,to,columns:[...columns],favorite:false,active:true,notes:''});audit(n,'Save report filters',name);await persist(n,'Report filters saved');}catch(e){toast.error((e as Error).message);}}
function loadPreset(id:string){const r=data.office?.presets?.find(r=>r.id===id);if(!r)return;setReport(r.report);setProperty(r.propertyId);setFrom(r.from);setTo(r.to);setColumns(r.columns);onSection('Reports');}
const dateField=(label:string,value:string,set:(v:string)=>void)=><label className="field">{label}<input aria-label={label} type="date" value={value} onInput={e=>set(e.currentTarget.value)} onChange={e=>set(e.target.value)}/></label>;
return <div className="maintenance-workspace"><main className="maintenance-main"><div className="toolbar"><Pick label={view+' section'} value={section} onChange={onSection} items={sections.map(s=>({value:s,label:s}))}/><Pick label="Register / report property" value={property||'all'} onChange={v=>setProperty(v==='all'?'':v)} items={[{value:'all',label:'All authorized properties'},...data.properties.map(p=>({value:p.id,label:p.name}))]}/></div>
{view==='properties'&&section==='Properties'&&<><section className="panel"><h3>Property directory</h3><label><input type="checkbox" checked={hidden} onChange={e=>setHidden(e.target.checked)}/> Include hidden properties</label><Grid headers={['Property','Classification','Unit records','Active leasing','Verified vacant']} rows={data.properties.filter(p=>(!property||property===p.id)&&(hidden||!data.office?.profiles?.find(r=>r.propertyId===p.id)?.hidden)).map(p=>[p.name,data.office?.profiles?.find(r=>r.propertyId===p.id)?.kind??'Unclassified',data.units.filter(u=>u.propertyId===p.id).length,data.units.filter(u=>u.propertyId===p.id&&isParticipating(data,u,period)).length,verifiedVacantUnits(data,period).filter(u=>u.propertyId===p.id).length])}/></section>{p.children}<OfficeRegister {...p} recordKey="groups" title="Property groups" propertyId={property}/><OfficeRegister {...p} recordKey="profiles" title="Property classification and statement settings" propertyId={property}/></>}
{section==='GL Accounts'&&<QboGLImport {...p}/>} {register&&<OfficeRegister key={section} {...p} recordKey={register[0]} title={register[1]} description={register[2]} propertyId={property} defaults={{section:view}}/>}
{section==='Associations'&&<><OfficeRegister {...p} recordKey="attendance" title="Meeting sign-in" propertyId={property}/><OfficeRegister {...p} recordKey="rules" title="Association rules" propertyId={property}/><button onClick={()=>navigate('calendar')}>Association calendar</button></>}
{view==='accounting'&&['Receivables','Payables','DLA Analysis','Pool Allocation & Contracts','QBO Exports'].includes(section)&&<AccountingPanel key={section} initialTab={section==='Receivables'?'Tenant rent':section==='Payables'?'Agency income & payables':section==='DLA Analysis'?'Executive Summary':section==='QBO Exports'?'QBO exports':'Pool allocation & contracts'} {...p}/>} 
{section==='Diagnostics'&&<><MonthlyClearing {...p}/><section className="panel"><h3>Bank and trust-account checks</h3><p>Bank reconciliation, security-deposit cash matching and trust balances require external bank and ledger evidence. They are unverified here.</p></section></>}
{view==='accounting'&&['Receivables','Payables'].includes(section)&&<OfficeRegister key={section} {...p} recordKey="tasks" title={section+' preparation tasks'} defaults={{section,task:section==='Receivables'?'Review bulk charges and credits':'Prepare bill / owner payment'}} description="Track supporting work and external completion references. This register does not create charges, bills or payments."/>}
{view==='reporting'&&section==='Reports'&&<><section className="panel"><h3>Report library</h3><div className="toolbar"><input aria-label="Search reports" placeholder="Search reports" value={query} onChange={e=>setQuery(e.target.value)}/><Pick label="Report category" value={category} onChange={setCategory} items={['All',...reportCatalog.map(g=>g.category)].map(v=>({value:v,label:v}))}/></div><Grid headers={['Report','Category','Source','']} rows={items.map(r=>[r.name,r.group,reportSupported(r.name)?'Saved OG records':'Additional source required',<button onClick={()=>{setReport(r.name);setColumns([]);}}>Open report</button>])}/></section><section className="panel"><h3>{report}</h3><div className="toolbar">{dateField('Report from',from,setFrom)}{dateField('Report through',to,setTo)}</div><p className="hint">{result.note}</p>{result.available&&<><p>{result.rows.length} records · CSV includes all matching rows.</p><details><summary>Report columns</summary>{buildReport(data,report,{propertyId:property,from,to}).columns.map(c=><label key={c} style={{display:'block'}}><input type="checkbox" checked={!columns.length||columns.includes(c)} onChange={e=>{const current=columns.length?columns:buildReport(data,report,{propertyId:property,from,to}).columns;const next=e.target.checked?[...new Set([...current,c])]:current.filter(x=>x!==c);if(next.length)setColumns(next);}}/>{c}</label>)}</details><button onClick={exportReport}>Export CSV</button><input aria-label="Saved report name" placeholder="Saved report name" value={reportName} onChange={e=>setReportName(e.target.value)}/><button disabled={busy} onClick={saveReport}>Save report filters</button><Grid printTitle={report+' · '+from+' through '+to} printNote={result.note} headers={result.columns} rows={result.rows.map(r=>r.map(v=>v===null?'UNCONFIRMED':String(v??'')))}/></>}</section><section className="panel"><h3>Saved reports</h3><Grid headers={['Name','Report','Scope','']} rows={(data.office?.presets??[]).filter(r=>r.active).map(r=>[r.name,r.report,data.properties.find(p=>p.id===r.propertyId)?.name??'All authorized properties',<button onClick={()=>loadPreset(r.id)}>Run saved report</button>])}/></section><OfficeRegister {...p} recordKey="presets" title="Manage saved reports"/></>}
{section==='Scheduled Reports'&&<section className="panel"><h3>Prepare a planned report</h3><Grid headers={['Name','Next date','Status','']} rows={(data.office?.schedules??[]).map(r=>[r.name,r.nextDate,r.status,<button onClick={()=>loadPreset(r.presetId)}>Open saved report</button>])}/></section>}
{section==='Metrics'&&<section className="panel"><h3>Saved OG metrics · {period}</h3><Grid headers={['Property','Unit records','Active leasing','Verified vacant','Lease records']} rows={data.properties.filter(p=>!property||p.id===property).map(p=>[p.name,data.units.filter(u=>u.propertyId===p.id).length,data.units.filter(u=>u.propertyId===p.id&&isParticipating(data,u,period)).length,verifiedVacantUnits(data,period).filter(u=>u.propertyId===p.id).length,(data.operations?.leases??[]).filter(l=>data.units.some(u=>u.id===l.unitId&&u.propertyId===p.id)).length])}/><p className="hint">Unverified occupancy is not counted as vacancy. Pricing benchmarks and insurance coverage require additional source records.</p></section>}
{section==='Compliance'&&<OfficeRegister {...p} recordKey="rules" title="Rules and regulations" propertyId={property}/>} 
<OfficeRegister {...p} recordKey="tasks" title="External workflow preparation" action={taskAction} defaults={{section}} description="Preparation requests only. A task title does not perform a posting, payment, bank connection, permission change, notice or recalculation."/></main><aside className="maintenance-tasks panel"><h3>Tasks</h3>{(officeTasks[section]??[]).map(task=><button key={task} disabled={busy} onClick={()=>setTaskAction({key:'tasks',defaults:{section,task,propertyId:property,notes:'Prepare and verify externally; no external action is submitted by OG.'},token:Date.now()})}>{task} · prepare</button>)}{view==='properties'&&<><button disabled={busy} onClick={p.newProperty}>New property / association</button><button onClick={()=>onSection('Associations')}>Meeting sign-in & board settings</button><button onClick={()=>navigate('reporting')}>Property and unit reports</button></>}{view==='accounting'&&<><button onClick={()=>navigate('people')}>Tenant / homeowner ledger and receipts</button><button onClick={()=>navigate('statements')}>Owner statement packages</button><button onClick={()=>onSection('Financial Accounts')}>Financial account directory</button><button onClick={()=>onSection('Journal Entries')}>New journal entry</button><button onClick={()=>onSection('Bank Transfers')}>Prepare bank transfer</button><button onClick={()=>onSection('GL Accounts')}>GL account mapping</button><button onClick={()=>onSection('Diagnostics')}>Monthly close review</button><button onClick={()=>navigate('reporting')}>Accounting reports</button></>}{view==='reporting'&&<><button onClick={()=>onSection('Reports')}>Report builder & saved reports</button><button onClick={()=>onSection('Scheduled Reports')}>New preparation schedule</button><button onClick={()=>navigate('statements')}>Owner statement packages</button><button onClick={()=>onSection('Surveys')}>Record survey response</button><button onClick={()=>onSection('Compliance')}>New violation / architectural review</button></>}<p className="hint">Internal records and preparation. External posting, payments and delivery remain in their connected systems.</p></aside></div>;
}




