'use client';
import {type Data,ownerAt,money,totals} from '@/lib/pool';
import {monthTenants} from '@/lib/tenancy';
import {Grid} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function OwnerContactProfile({data,ownerId,period,close,openUnit,busy}:{data:Data;ownerId:string;period:string;close:()=>void;openUnit:(id:string)=>void;busy:boolean}){
 const owner=data.owners.find(o=>o.id===ownerId),units=data.units.filter(u=>ownerAt(data,u.id,period+'-01')===ownerId);
 const accounts=<><h3>Residents & unit accounts</h3><Grid headers={['Unit','Property','Residents','']} rows={units.map(u=>[u.number,data.properties.find(p=>p.id===u.propertyId)?.name??'Not entered',monthTenants(data,u.id,period).map(t=>t.firstName+' '+t.lastName).join(', ')||'No verified tenant',<button className="text-button" disabled={busy} onClick={()=>openUnit(u.id)}>Open profile & tenant ledger</button>])}/><h3>Owner statement history · {period}</h3><Grid headers={['Unit','Version','Status','Income','Deductions','Paid','']} rows={data.statements.filter(s=>s.ownerId===ownerId&&s.period===period).map(s=>[data.units.find(u=>u.id===s.unitId)?.number??s.unitId,s.version,s.status,money(s.allocated),money(totals(s).deductions),money(s.paidAmount),<button className="text-button" disabled={busy} onClick={()=>openUnit(s.unitId)}>Unit account</button>])}/><h3>Posted general ledger · owned units · {period}</h3><Grid headers={['Date','Reference','Unit','Account','Memo','Debit','Credit']} rows={(data.accounting?.native?.entries??[]).filter(e=>e.date.startsWith(period)).flatMap(e=>e.lines.filter(l=>ownerAt(data,l.unitId,e.date)===ownerId).map(l=>[e.date,e.reference,data.units.find(u=>u.id===l.unitId)?.number??l.unitId,l.accountKey,l.memo||e.memo,money(l.debit),money(l.credit)]))}/><p className="hint">Only posted, unit-linked general ledger lines appear here. Tenant ledger balances and owner statement versions remain separate; statement versions must not be added together.</p></>;
 return <section className="panel" aria-label="Owner account"><button className="secondary" onClick={close}>Back to owners</button><h3>{owner?.name??'Owner unavailable'} · Owner information</h3><p>Saved owner contact and unit relationships · {period}</p>{owner&&<><dl className="input-grid">{[['Email',owner.email],['Phone',owner.phone],['Contact name',owner.contactName],['Mailing address',[owner.address,owner.city,owner.state,owner.zip].filter(Boolean).join(', ')],['Payment method',owner.paymentMethod],['Special instructions',owner.specialInstructions]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not entered'}</dd></div>)}</dl><h3>Owned units · {period}</h3><div className="toolbar">{units.map(u=><button key={u.id} className="secondary" disabled={busy} onClick={()=>openUnit(u.id)}>Unit {u.number} · {u.type===1?'1/1':u.type===2?'2/2':'Type unverified'} · {data.properties.find(p=>p.id===u.propertyId)?.name??'Property needs review'}</button>)}</div>{!units.length&&<p>No units linked to this owner for the selected month.</p>}{accounts}</>}</section>;
}