'use client';
import {useMemo,useRef,useState} from 'react';
import {type Data,latest,money,totals} from '@/lib/pool';
import {packetApproved} from '@/lib/owner-run';
import {ownerOutstanding} from '@/lib/month-close';
import {ownerReportTotals,selectedOwnerStatements} from '@/lib/owner-report';
import {download} from '@/lib/exports';
import {printReport} from '@/lib/print-report';
import {reportRequest} from '@/lib/report-request';
import ReportPreview from './report-preview';
import StatementDocument from './statement-document';

export default function OwnerReport({data,period,disabled=false}:{data:Data;period:string;disabled?:boolean}){
 const current=useMemo(()=>latest(data,period),[data,period]);
 const owners=data.owners.filter(o=>current.some(s=>s.ownerId===o.id)).sort((a,b)=>a.name.localeCompare(b.name));
 const [ownerId,setOwnerId]=useState(''),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[receipts,setReceipts]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState('');
 const report=useRef<HTMLDivElement>(null);
 const available=current.filter(s=>s.ownerId===ownerId).sort((a,b)=>(data.units.find(u=>u.id===a.unitId)?.number??'').localeCompare(data.units.find(u=>u.id===b.unitId)?.number??'',undefined,{numeric:true}));
 const activeSelected=selected.filter(id=>available.some(s=>s.unitId===id));
 const statements=activeSelected.length?selectedOwnerStatements(data,ownerId,period,activeSelected):[],summary=ownerReportTotals(data,statements);
 const name=data.owners.find(o=>o.id===ownerId)?.name??'';
 async function pdf(){setWorking(true);setError('');try{const params=new URLSearchParams({owner:ownerId,period,receipts:receipts?'1':'0'});activeSelected.forEach(id=>params.append('unit',id));const url='/api/owner-report?'+params;download(await reportRequest(url),'Devonshire_Owner_'+ownerId.replace(/[^a-zA-Z0-9_-]/g,'_')+'_'+period+'.pdf',url);}catch(e){setError(e instanceof Error?e.message:'Unable to generate the report. Please retry.');}finally{setWorking(false);}}
 const reportContent=(<div className="owner-report-preview"><div className="devonshire-wordmark">Devonshire</div><h2>Owner distribution statement</h2><p>{name} · {period} · {statements.length} selected units</p><p>{statements.some(s=>s.status==='Pending'&&!packetApproved(data,s))?'DRAFT — includes unapproved statements':'Current saved statement versions'}</p><table><thead><tr><th>Unit</th><th>Pool income</th><th>Charges</th><th>Closing balance</th></tr></thead><tbody>{statements.map(s=><tr key={s.id}><td>{data.units.find(u=>u.id===s.unitId)?.number} · v{s.version}</td><td>{money(s.allocated)}</td><td>{money(totals(s).deductions)}</td><td>{money(ownerOutstanding(data,s))}</td></tr>)}</tbody></table><dl>{Object.entries({'Pool income':summary.allocated,'Deductions':summary.deductions,'Credits':summary.credits,'Opening balances':summary.opening,'Adjustments':summary.adjustments,'Proposed net distribution':summary.available,'Cash payments recorded':summary.cash,'Internal owner offsets (net)':summary.internalOffsets,'HOA offsets applied':summary.offsetApplied,'HOA offsets received':summary.offsetReceived,'Owner contributions received':summary.contributions,'Combined closing balance':summary.closing}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{money(value)}</dd></div>)}</dl><p>Selected units only. Negative balances remain visible. No payment is initiated.</p>{statements.map(s=><article key={s.id}><StatementDocument data={data} statement={s}/></article>)}</div>);
 return <section className="panel owner-report"><h3>Print an owner’s units together</h3><p>Choose an owner, select their units, then print one statement or save one PDF for {period}.</p>
 <div className="toolbar no-print"><label className="field">Find owner<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Owner name"/></label><label className="field">Owner<select aria-label="Report owner" value={ownerId} disabled={working||disabled} onChange={e=>{const id=e.target.value;setOwnerId(id);setSelected(current.filter(s=>s.ownerId===id).map(s=>s.unitId));setError('');}}><option value="">Choose an owner</option>{owners.filter(o=>o.id===ownerId||o.name.toLowerCase().includes(search.toLowerCase())).map(o=><option key={o.id} value={o.id}>{o.name} · {current.filter(s=>s.ownerId===o.id).length} units</option>)}</select></label></div>
 {ownerId&&<><div className="toolbar no-print"><button className="secondary" disabled={working||disabled} onClick={()=>setSelected(available.map(s=>s.unitId))}>Select all units</button><button className="secondary" disabled={working||disabled} onClick={()=>setSelected([])}>Clear selection</button><span>{activeSelected.length} of {available.length} units selected</span></div><div className="owner-unit-selection no-print">{available.map(s=><label key={s.id}><input type="checkbox" disabled={working||disabled} checked={selected.includes(s.unitId)} onChange={e=>setSelected(e.target.checked?[...selected,s.unitId]:selected.filter(id=>id!==s.unitId))}/>Unit {data.units.find(u=>u.id===s.unitId)?.number} · {money(ownerOutstanding(data,s))} · {s.status==='Pending'?'Draft':s.status}</label>)}</div></>}
 {!!statements.length&&<><div ref={report}>{reportContent}</div></>}
 <div className="toolbar no-print"><label><input type="checkbox" checked={receipts} disabled={working} onChange={e=>setReceipts(e.target.checked)}/>Include labor bills and receipts in PDF</label><ReportPreview title={"Owner statement preview · "+name+" · "+period} disabled={working||!statements.length} unsaved={disabled}>{reportContent}</ReportPreview><button disabled={disabled||working||!statements.length} onClick={pdf}>{working?'Preparing PDF…':'Download combined PDF'}</button><button className="secondary" disabled={disabled||working||!statements.length} onClick={()=>{if(report.current)printReport(report.current);}}>Print selected units</button></div>{disabled&&<p className="hint">Save your changes before printing or downloading.</p>}{working&&<p role="status">Preparing your selected unit statements{receipts?' and receipts':''}…</p>}{error&&<p role="alert" className="notice">{error}</p>}
 </section>;
}
