'use client';
import {useState,useEffect} from 'react';
import {toast} from 'sonner';
import {type Data,latest,money,totals} from '@/lib/pool';
import {closeState,closeReview,recordMonthClose,recordContribution,ownerOutstanding,contributionTotal,tenantArrears,openFollowingMonth,missingOwnerSupport} from '@/lib/month-close';
import {recordClearing,clearingState,clearingReview} from '@/lib/monthly-clearing';
import {incomeRows} from '@/lib/accounting-model';
import {download,simpleReportPDF,csv,combinedOwnerPackage,supportPackage,type Doc} from '@/lib/exports';
import {dlaIncomeReview} from '@/lib/pool-finance';
import {zipSync} from 'fflate';
import {Grid,Pick} from './report-controls';
import DateInput from './date-input';
export default function OwnerClose({data,period,busy,persist,openUnit,navigate,docs}:{data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;openUnit:(id:string)=>void;navigate:(s:string)=>void;docs:Doc[]}){
 const [owner,setOwner]=useState('All'),[reason,setReason]=useState(''),[bank,setBank]=useState(''),[escrow,setEscrow]=useState(''),[form,setForm]=useState<{id:string;amount:string;date:string;reference:string}|null>(null);
 useEffect(()=>{setOwner('All');setReason('');setBank('');setEscrow('');setForm(null);},[period]);
 const supportMissing=missingOwnerSupport(data,period,docs);const dla=dlaIncomeReview(data,period);const current=latest(data,period),rows=incomeRows(data,period),review=closeReview(data,period),state=closeState(data,period),closed=state?.kind==='Closed',clearing=clearingReview(data,period),filtered=current.filter(s=>owner==='All'||s.ownerId===owner),name=(id:string)=>data.owners.find(o=>o.id===id)?.name??id,unit=(id:string)=>data.units.find(u=>u.id===id)?.number??id;
 async function action(kind:'clearing'|'close'|'next'){try{const n=structuredClone(data);if(kind==='clearing')recordClearing(n,period,'Closed','Management',reason);else if(kind==='close')recordMonthClose(n,period,closed?'Reopened':'Closed','Management',reason,bank,escrow);else openFollowingMonth(n,period);if(await persist(n,kind==='next'?'Next month opened; tenant arrears retained':kind==='clearing'?'Rent clearing reviewed at zero':closed?'Month reopened':'Month closed and sources locked'))setReason('');}catch(e){toast.error((e as Error).message);}}
 async function contribution(){try{const {cents}=await import('@/lib/pool');const n=structuredClone(data);recordContribution(n,form!.id,cents(form!.amount),form!.date,form!.reference,'Management');if(await persist(n,'Verified external owner contribution recorded'))setForm(null);}catch(e){toast.error((e as Error).message);}}
 async function bills(){try{const s=filtered,lines=s.flatMap(s=>['Owner: '+name(s.ownerId)+' | Unit '+unit(s.unitId)+' | '+period+' v'+s.version+' | '+s.status,...s.expenses.map(e=>e.label+' | '+e.recipient+' | GL '+(e.gl??'Unassigned')+' | '+money(e.cents)),...((s.credits??[]).map(c=>c.label+' | Credit '+money(c.cents))),'Total deductions: '+money(totals(s).deductions),'Outstanding owner balance: '+money(ownerOutstanding(data,s)),'']);download(await simpleReportPDF('OG | ITEMIZED OWNER CHARGES',lines),'OG_Owner_Charges_'+period+'.pdf');}catch(e){toast.error((e as Error).message);}}
 async function archive(){try{if(!closed)throw Error('Close the month before downloading the final close package.');const files:Record<string,Uint8Array>={};files['Close_Record.json']=new TextEncoder().encode(JSON.stringify(state,null,2));files['Tenant_Arrears.csv']=new TextEncoder().encode(csv([['tenant_id','unit','charge_id','charge_date','category','balance'],...tenantArrears(data,period).map(r=>[r.entry.tenantId,unit(data.operations?.tenants?.find(t=>t.id===r.entry.tenantId)?.unitId??''),r.entry.id,r.entry.date,r.entry.category,(r.remaining/100).toFixed(2)])]));for(const id of new Set(current.map(s=>s.ownerId)))files['Owners/Owner_'+id.replace(/[^a-zA-Z0-9_-]/g,'_')+'.zip']=new Uint8Array(await (await combinedOwnerPackage(data,id,period,docs)).arrayBuffer());files['DLA_Internal_Close.pdf']=new Uint8Array(await (await simpleReportPDF('OG | INTERNAL MONTHLY CLOSE',[period,'Reviewer: '+state.reviewer,'Owner operating reconciliation: '+state.bankReference,'Owner escrow reconciliation: '+state.escrowReference,'Rent allocated: '+money(review.summary.allocated),'Owner cash distributions: '+money(review.summary.ownerCash),'Owner contributions: '+money(review.summary.ownerContributions),'Tenant rent carried forward: '+money(review.summary.unpaidTenantRent),'Owner unit balances: '+money(review.summary.ownerOutstanding),'DLA income before operating expenses: '+money(state.summary.dlaIncome),'DLA minimum: '+money(dla.target)+' / Shortfall flagged: '+money(state.summary.dlaShortfall),state.reason,'Reconciliation references are management attestations; no bank funds moved by OG.'])).arrayBuffer());download(new Blob([new Uint8Array(zipSync(files))],{type:'application/zip'}),'OG_Month_Close_'+period+'.zip');}catch(e){toast.error((e as Error).message);}}
 return <><section className="panel"><div className="panel-heading"><div><h3>Owner bills & monthly close</h3><p>Review charges and support, approve statements, record completed distributions, then close the month.</p></div><span className="badge">{closed?'Closed':'Open for review'}</span></div><div className="toolbar"><Pick label="Owner review" value={owner} onChange={setOwner} items={[{value:'All',label:'All owners'},...data.owners.filter(o=>current.some(s=>s.ownerId===o.id)).map(o=>({value:o.id,label:o.name}))]}/><button className="secondary" onClick={bills}>Print itemized owner charges</button><button className="secondary" disabled={busy} onClick={()=>navigate('distributions')}>Prepare distributions</button></div><Grid headers={['Owner / unit','Statement','Itemized charges','Support / GL review','Outstanding','Actions']} rows={filtered.map(s=>{const charges=rows.filter(r=>s.expenses.some(e=>e.id===r.id)),missing=charges.filter(r=>!r.confirmed).length;return [name(s.ownerId)+' / '+unit(s.unitId),'v'+s.version+' · '+s.status,money(totals(s).deductions),s.expenses.filter(e=>docs.some(d=>d.expenseId===e.id)||e.partsIssueId||e.laborPostId).length+'/'+s.expenses.length+' supported · '+missing+' GL reviews',money(ownerOutstanding(data,s)),<div className="toolbar"><button className="text-button" onClick={()=>openUnit(s.unitId)}>Review bill & receipts</button><button className="text-button" onClick={async()=>{try{download(await supportPackage(data,s,docs),'OG_Unit_'+unit(s.unitId)+'_'+period+'.zip');}catch(e){toast.error((e as Error).message);}}}>Bill & receipts ZIP</button>{ownerOutstanding(data,s)<0&&<button disabled={busy||closed||s.status!=='Approved'} onClick={()=>setForm({id:s.id,amount:(-ownerOutstanding(data,s)/100).toFixed(2),date:period+'-01',reference:''})}>Record owner contribution</button>}</div>];})}/><p className="hint">Each unit’s positive or negative balance must be settled separately. Contributions record money already received externally. Tenant arrears remain on the tenant/unit ledger.</p></section>
 {form&&<section className="panel"><h3>Verified external owner contribution</h3><label className="field">Amount received<input inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><DateInput label="Owner contribution date" value={form.date} onChange={v=>setForm({...form,date:v})}/><label className="field">Unique bank receipt reference<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><button disabled={busy} onClick={contribution}>Record verified receipt</button><button className="secondary" onClick={()=>setForm(null)}>Cancel</button></section>}
 <section className="panel"><h3>Monthly close checklist</h3>{dla.shortfall>0&&<p className="notice">DLA private review: income before operating expenses is {money(dla.income)}; minimum shortfall {money(dla.shortfall)}. Review only; no additional owner fee is created.</p>}<p>Collected rent: {money(review.summary.rent)} · Allocated: {money(review.summary.allocated)} · Rent clearing difference: {money(clearing.closing)}</p><p>Tenant rent carried forward: {money(review.summary.unpaidTenantRent)} · Owner balances: {money(review.summary.ownerOutstanding)}</p>{!closed&&supportMissing.length>0&&<p className="warning">Attach supporting invoices for {supportMissing.length} manual repair, labor or materials charge(s) before closing.</p>}{!closed&&review.blockers.map(b=><p className="warning" key={b}>{b}</p>)}<label className="field">Close / reopen review notes<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{!closed&&<><label className="field">Owner operating reconciliation reference<input value={bank} onChange={e=>setBank(e.target.value)}/></label><label className="field">Owner escrow reconciliation reference<input value={escrow} onChange={e=>setEscrow(e.target.value)}/></label><p className="hint">Enter the externally verified bank reconciliation references. Zero rent clearing does not mean the bank balance is zero. Escrow liabilities and unpaid tenant amounts are preserved.</p></>}<div className="toolbar">{!closed&&clearingState(data,period)?.kind!=='Closed'&&<button disabled={busy||!!clearing.blockers.length||!reason.trim()} onClick={()=>action('clearing')}>Close rent clearing at $0.00</button>}<button disabled={busy||!reason.trim()||!closed&&(!!review.blockers.length||!!supportMissing.length||!bank.trim()||!escrow.trim())} onClick={()=>action('close')}>{closed?'Reopen month for correction':'Close accounting month'}</button><button className="secondary" disabled={!closed} onClick={archive}>Download final month package</button><button className="secondary" disabled={busy||!closed} onClick={()=>action('next')}>Open following month</button></div><Grid headers={['Date','Action','Reviewer','Notes']} rows={(data.closeControls?.events??[]).filter(e=>e.period===period).map(e=>[e.created,e.kind,e.reviewer,e.reason])}/><Grid headers={['Unit','Date','Receipt reference','Contribution']} rows={(data.closeControls?.contributions??[]).filter(c=>c.period===period).map(c=>[unit(data.statements.find(s=>s.id===c.statementId)?.unitId??''),c.date,c.reference,money(c.cents)])}/></section></>;
}
