'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,cents,money} from '@/lib/pool';
import {emptyAccounting,recordAudit,validateAccounting} from '@/lib/accounting-model';
import {native,bookChart} from '@/lib/native-accounting';
import {payables,payableState,payableTotal,payableAging,postPayableDocument,prepareRecurringPayable,recurringPayablesDue,type PayableDocument,type RecurringPayable} from '@/lib/payables-ledger';
import {Grid,Pick} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {csv,download,simpleReportPDF} from '@/lib/exports';
import './accounting-connections.css';
type Props={data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;openUnit:(id:string)=>void;onPage:(page:string,context:{bookId:string;bankKey:string})=>void;mode:'bills'|'payments'|'recurring';initialBook?:string};
const emptyLine=()=>({accountKey:'',unitId:'',amount:'',description:'',serviceFrom:'',serviceTo:''});
export default function PayablesLedger({data,period,busy,persist,openUnit,onPage,mode,initialBook}:Props){
 const [selected,setSelected]=useState(initialBook??''),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[form,setForm]=useState<any>(null),[kind,setKind]=useState(''),[verified,setVerified]=useState(false),[saving,setSaving]=useState(false),[detail,setDetail]=useState<PayableDocument|null>(null);
 const p=payables(data),n=native(data),book=n.books.find(b=>b.id===selected)??n.books[0],chart=book?bookChart(data,book.id):undefined,end=new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),0)).toISOString().slice(0,10),blocked=busy||saving;
 const rules=new Map<string,RecurringPayable>();for(const r of p.rules)rules.set(r.ruleId,r);
 const accounts=chart?.accounts.filter(a=>a.active)??[],apAccounts=accounts.filter(a=>a.type.toLowerCase()==='accounts payable'),lineAccounts=accounts.filter(a=>!['bank','accounts payable','accounts receivable'].includes(a.type.toLowerCase())),name=(key:string)=>{const a=chart?.accounts.find(a=>a.key===key);return [a?.number,a?.name??key].filter(Boolean).join(' · ');};
 const docs=p.documents.filter(r=>r.bookId===book?.id&&r.date<=end&&(r.payee+' '+r.reference+' '+r.lines.map(l=>l.description).join(' ')).toLowerCase().includes(query.toLowerCase())).filter(r=>status==='All'||payableState(data,r,end).status===status),due=recurringPayablesDue(data,period).filter(r=>r.document.bookId===book?.id);
 function start(k:string,doc?:PayableDocument){setKind(k);setVerified(false);const date=doc&&doc.date>period+'-01'?doc.date:period+'-01';setForm(k==='decision'?{documentId:doc!.id,date,action:'Approved',reason:'',reviewer:''}:k==='post'?{documentId:doc!.id,date,reviewer:''}:k==='apply'?{billId:doc!.id,date,amount:(payableState(data,doc!,end).remaining/100).toFixed(2),paymentEntryId:'',creditId:'',reviewer:''}:k==='recurring'?{documentId:doc!.id,name:doc!.payee+' · '+doc!.reference,start:new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),1)).toISOString().slice(0,7),end:'',day:1,dueDays:30,reviewer:''}:{bookId:book?.id??'',kind:k==='credit'?'Credit':'Bill',payee:'',date:period+'-01',due:period+'-28',reference:'',source:'',payableKey:apAccounts[0]?.key??'',reviewer:'',lines:[emptyLine()]});}
 async function save(){if(!verified||blocked||!book)return;setSaving(true);try{let next=structuredClone(data);next.accounting??=emptyAccounting();next.accounting.payablesLedger??={documents:[],decisions:[],applications:[],rules:[]};const out=next.accounting.payablesLedger,actor={id:crypto.randomUUID(),reviewer:form.reviewer.trim(),created:new Date().toISOString()};
  if(kind==='bill'||kind==='credit')out.documents.push({...actor,bookId:book.id,kind:form.kind,payee:form.payee.trim(),date:form.date,due:form.due,reference:form.reference.trim(),source:form.source.trim(),payableKey:form.payableKey,recurringId:'',lines:form.lines.map((l:any)=>({accountKey:l.accountKey,unitId:l.unitId,cents:cents(l.amount),description:l.description.trim(),serviceFrom:l.serviceFrom,serviceTo:l.serviceTo}))});
  if(kind==='decision')out.decisions.push({...actor,documentId:form.documentId,date:form.date,action:form.action,reason:form.reason.trim()});
  if(kind==='post')next=postPayableDocument(data,form.documentId,form.date,actor.reviewer,verified);
  if(kind==='apply')out.applications.push({...actor,billId:form.billId,date:form.date,cents:cents(form.amount),paymentEntryId:form.paymentEntryId,creditId:form.creditId});
  if(kind==='recurring'){const doc=p.documents.find(r=>r.id===form.documentId)!;out.rules.push({...actor,ruleId:actor.id,version:1,active:true,name:form.name.trim(),start:form.start,end:form.end,day:Number(form.day),dueDays:Number(form.dueDays),document:{bookId:doc.bookId,kind:doc.kind,payee:doc.payee,source:doc.source,payableKey:doc.payableKey,lines:doc.lines.map(l=>({...l,serviceFrom:'',serviceTo:''}))}});}
  validateAccounting(next,data);recordAudit(next,'Payable '+kind+' reviewed',form.reference||form.documentId||form.billId);if(await persist(next,'Payable review saved; no payment issued'))setForm(null);
 }catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function ruleAction(rule:RecurringPayable,prepare:boolean){if(blocked)return;setSaving(true);try{const next=prepare?prepareRecurringPayable(data,rule.id,period,'Authenticated workspace reviewer'):structuredClone(data);if(!prepare)next.accounting!.payablesLedger!.rules.push({...rule,id:crypto.randomUUID(),version:rule.version+1,active:!rule.active,reviewer:'Authenticated workspace reviewer',created:new Date().toISOString()});validateAccounting(next,data);recordAudit(next,prepare?'Recurring payable prepared for approval':'Recurring payable availability changed',rule.name+' · '+period);await persist(next,prepare?'Monthly bill prepared; approval and posting still required':'Recurring rule history saved');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 const columns=['Date','Due','Payee','Document','Reference','Amount','Applied','Remaining','Status'];const printable=docs.map(r=>{const s=payableState(data,r,end);return [r.date,r.due,r.payee,r.kind,r.reference,money(s.total),money(s.applied),money(s.remaining),s.status];});
 const aging=book?payableAging(data,book.id,end):[],agingPrint=aging.map(r=>[r.payee,money(r.current),money(r.days30),money(r.days60),money(r.days90),money(r.older),money(r.total)]);
 const detailState=detail?payableState(data,detail,end):undefined;
 const field=(key:string,label:string,type='text')=><label className="field">{label}<input aria-label={'Payable '+key} type={type} value={form[key]} onChange={e=>{setVerified(false);setForm({...form,[key]:e.target.value});}}/></label>;
 return <section className="panel"><div className="panel-heading"><h3>{mode==='bills'?'Bills, credits & approval':mode==='payments'?'Recorded bill settlement':'Recurring bills & credits'}</h3></div><label className="field">Company ledger<Pick label="Payables company" value={book?.id??'none'} onChange={v=>{setSelected(v);setForm(null);setDetail(null);}} items={n.books.length?n.books.map(b=>({value:b.id,label:b.company})):[{value:'none',label:'Initialize company ledger first'}]}/></label><p>Enter the source once, approve it, post the liability, then apply an existing ledger payment or supplier credit. OG does not issue checks or charge ACH/cards here.</p>{!book||!apAccounts.length?<div className="notice">A company ledger and an active Accounts Payable GL are required.<button className="secondary" onClick={()=>onPage('Chart & mapping',{bookId:book?.id??'',bankKey:''})}>Review chart & mapping</button></div>:<>
 {mode!=='recurring'&&<><div className="toolbar">{mode==='bills'&&<><button disabled={blocked} onClick={()=>start('bill')}>Enter bill</button><button className="secondary" disabled={blocked} onClick={()=>start('credit')}>Enter supplier credit</button></>}<button className="secondary" onClick={()=>onPage('Payment posting review',{bookId:book.id,bankKey:''})}>Review recorded bank payments</button><button className="secondary" onClick={()=>download(new Blob([csv([columns,...printable])],{type:'text/csv'}),'OG_Payable_Detail_'+period+'.csv')}>Export bill detail</button><button className="secondary" onClick={async()=>download(await simpleReportPDF('OPERVIX GROUP | PAYABLE DETAIL',[book.company+' · Through '+end,...printable.map(r=>r.join(' | '))]),'OG_Payable_Detail_'+period+'.pdf')}>Print bill detail</button></div><div className="leasing-form-grid"><label className="field">Search<input aria-label="Search payable documents" placeholder="Payee, reference or work description" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field">Status<Pick label="Payable status" value={status} onChange={setStatus} items={['All','Pending approval','On hold','Approved','Open','Partially settled','Settled','Voided','Posting reversed — review'].map(v=>({value:v,label:v}))}/></label></div><Grid headers={[...columns,'Next step']} rows={docs.map(r=>{const s=payableState(data,r,end);const cells=[...printable[docs.indexOf(r)]] as any[];for(const index of [4,5,6,7])cells[index]=<button className='text-button' onClick={()=>setDetail(r)}>{cells[index]}</button>;return [...cells,<div className="toolbar"><button className="secondary" onClick={()=>setDetail(r)}>Open {r.kind.toLowerCase()}</button>{!s.posting&&s.status!=='Voided'&&<button className="secondary" disabled={blocked} onClick={()=>start('decision',r)}>Review approval</button>}{s.status==='Approved'&&<button disabled={blocked} onClick={()=>start('post',r)}>Review ledger posting</button>}{r.kind==='Bill'&&['Open','Partially settled'].includes(s.status)&&<button disabled={blocked} onClick={()=>start('apply',r)}>Apply payment / credit</button>}</div>];})}/></>}
 {mode==='payments'&&<section className='panel'><div className='panel-heading'><h3>Aged payables summary</h3><button className='secondary' onClick={async()=>download(await simpleReportPDF('OPERVIX GROUP | AGED PAYABLES',[book!.company+' · Through '+end,'Payee | Current | 1–30 days | 31–60 | 61–90 | 90+ | Total',...agingPrint.map(r=>r.join(' | '))]),'OG_Aged_Payables_'+period+'.pdf')}>Print aged payables</button></div><Grid headers={['Payee','Current','1–30 days','31–60 days','61–90 days','90+ days','Total']} rows={aging.map((r,i)=>[...agingPrint[i].slice(0,6),<button className='text-button' onClick={()=>setQuery(r.payee)}>{money(r.total)}</button>])}/></section>}
 {mode==='recurring'&&<><p>Open a bill or credit and choose “Create recurring template.” Each month prepares a new document for approval; no bills or payments post automatically.</p><Grid headers={['Template','Payee','Months','Day','Status','Next step']} rows={[...rules.values()].filter(r=>r.document.bookId===book.id).map(r=>[r.name,r.document.payee,r.start+' → '+(r.end||'ongoing'),r.day,r.active?'Active':'Paused',<div className="toolbar"><button className="secondary" disabled={blocked} onClick={()=>ruleAction(r,false)}>{r.active?'Pause':'Resume'}</button>{due.some(x=>x.id===r.id)&&<button disabled={blocked} onClick={()=>ruleAction(r,true)}>Prepare {period} bill for approval</button>}</div>])}/><button className="secondary" onClick={()=>onPage('Bills & credits',{bookId:book.id,bankKey:''})}>Open bills & credits</button></>}
 </>}
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="app-dialog native-accounting-dialog"><DialogHeader><DialogTitle>{detail?.kind} · {detail?.reference}</DialogTitle><DialogDescription>Source, itemized work and immutable approval history</DialogDescription></DialogHeader>{detail&&<><p>{detail.payee} · {detail.date} · Due {detail.due} · {detailState!.status}</p><p>{detail.source}</p><Grid headers={['Account','Unit','Work / description','Service dates','Amount']} rows={detail.lines.map(l=>[name(l.accountKey),l.unitId?<button className="text-button" onClick={()=>openUnit(l.unitId)}>{data.units.find(u=>u.id===l.unitId)?.number}</button>:'Company',l.description,[l.serviceFrom,l.serviceTo].filter(Boolean).join(' → '),money(l.cents)])}/><p>Total {money(payableTotal(detail))} · Applied {money(detailState!.applied)} · Remaining {money(detailState!.remaining)}</p><Grid headers={['Review date','Decision','Reason','Reviewer']} rows={p.decisions.filter(x=>x.documentId===detail.id).map(e=>[e.date,e.action,e.reason,e.reviewer])}/><Grid headers={['Settlement date','Original payment / credit','Amount']} rows={p.applications.filter(a=>a.billId===detail.id||a.creditId===detail.id).map(a=>[a.date,n.entries.find(e=>e.id===a.paymentEntryId)?.reference??p.documents.find(x=>x.id===a.creditId)?.reference,money(a.cents)])}/><div className="toolbar"><button className="secondary" onClick={()=>{start('recurring',detail);setDetail(null);}}>Create recurring template</button><button className="secondary" onClick={()=>{onPage('Native ledger',{bookId:detail.bookId,bankKey:''});setDetail(null);}}>Open ledger</button></div></>}</DialogContent></Dialog>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!saving)setForm(null);}}><DialogContent className="app-dialog native-accounting-dialog"><DialogHeader><DialogTitle>{{bill:'Enter itemized bill',credit:'Enter supplier credit',decision:'Review payable approval',post:'Review payable ledger posting',apply:'Apply recorded payment or credit',recurring:'Create recurring payable template'}[kind]}</DialogTitle><DialogDescription>{book?.company} · Verify existing source records before saving. No funds move.</DialogDescription></DialogHeader>{form&&<>
 {(kind==='bill'||kind==='credit')&&<><div className="leasing-form-grid">{field('payee','Exact supplier / payee')}{field('date','Document date','date')}{field('due','Due date','date')}{field('reference','Original unique supplier reference')}{field('source','Original invoice / supporting document reference')}<label className="field">Accounts Payable GL<Pick label="Payable liability account" value={form.payableKey} onChange={v=>{setVerified(false);setForm({...form,payableKey:v});}} items={apAccounts.map(a=>({value:a.key,label:name(a.key)}))}/></label></div>{form.lines.map((l:any,i:number)=>{const update=(key:string,value:string)=>{setVerified(false);setForm({...form,lines:form.lines.map((x:any,j:number)=>j===i?{...x,[key]:value}:x)});};return <fieldset className="panel" key={i}><legend>Line {i+1}</legend><div className="leasing-form-grid"><label className="field">GL account<Pick label={'Payable line '+(i+1)+' account'} value={l.accountKey||'none'} onChange={v=>update('accountKey',v)} items={[{value:'none',label:'Choose reviewed GL'},...lineAccounts.map(a=>({value:a.key,label:name(a.key)}))]}/></label><label className="field">Unit<Pick label={'Payable line '+(i+1)+' unit'} value={l.unitId||'company'} onChange={v=>update('unitId',v==='company'?'':v)} items={[{value:'company',label:'Company'},...data.units.map(u=>({value:u.id,label:'Unit '+u.number}))]}/></label>{['amount','description','serviceFrom','serviceTo'].map(k=><label className="field" key={k}>{{amount:'Amount ($)',description:'Itemized work / description',serviceFrom:'Service from',serviceTo:'Service through'}[k]}<input aria-label={'Payable line '+(i+1)+' '+k} type={k.startsWith('service')?'date':'text'} value={l[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div><button className="secondary" disabled={form.lines.length===1} onClick={()=>{setVerified(false);setForm({...form,lines:form.lines.filter((_:any,j:number)=>j!==i)});}}>Remove line</button></fieldset>;})}<button className="secondary" disabled={form.lines.length>=99} onClick={()=>{setVerified(false);setForm({...form,lines:[...form.lines,emptyLine()]});}}>Add itemized line</button></>}
 {kind==='decision'&&<><label className="field">Decision<Pick label="Payable approval decision" value={form.action} onChange={v=>{setVerified(false);setForm({...form,action:v});}} items={['Approved','On hold','Voided'].map(v=>({value:v,label:v}))}/></label>{field('reason','Review reason')}{field('date','Review date','date')}</>}
 {kind==='post'&&<><p>{p.documents.find(r=>r.id===form.documentId)?.reference} · {money(payableTotal(p.documents.find(r=>r.id===form.documentId)!))}</p><p>Posts the itemized bill or credit against the selected Accounts Payable account. It does not pay the bill.</p>{field('date','Posting date','date')}</>}
 {kind==='apply'&&<>{field('date','Settlement review date','date')}{field('amount','Amount to apply ($)')}<label className="field">Existing posted bank payment<Pick label="Payable posted payment" value={form.paymentEntryId||'none'} onChange={v=>{setVerified(false);setForm({...form,paymentEntryId:v==='none'?'':v,creditId:'',date:v==='none'?form.date:[form.date,n.entries.find(e=>e.id===v)?.date??''].sort().at(-1)});}} items={[{value:'none',label:'Select payment or supplier credit'},...n.entries.filter(e=>e.bookId===book!.id&&e.date<=end&&!e.reverses&&!n.entries.some(x=>x.reverses===e.id)&&e.lines.some(l=>l.accountKey===p.documents.find(r=>r.id===form.billId)?.payableKey&&l.debit>0)&&e.lines.some(l=>accounts.find(a=>a.key===l.accountKey)?.type.toLowerCase()==='bank'&&l.credit>0)).map(e=>({value:e.id,label:e.date+' · '+e.reference+' · '+money(e.lines.filter(l=>l.accountKey===p.documents.find(r=>r.id===form.billId)?.payableKey).reduce((s,l)=>s+l.debit-l.credit,0))}))]}/></label><label className="field">Posted supplier credit<Pick label="Payable supplier credit" value={form.creditId||'none'} onChange={v=>{setVerified(false);setForm({...form,creditId:v==='none'?'':v,paymentEntryId:'',date:v==='none'?form.date:[form.date,n.entries.find(e=>e.sourceSystem==='OG payable'&&e.externalId===v)?.date??''].sort().at(-1)});}} items={[{value:'none',label:'Choose a posted credit'},...p.documents.filter(r=>r.bookId===book!.id&&r.kind==='Credit'&&r.payee===p.documents.find(x=>x.id===form.billId)?.payee&&['Open','Partially settled'].includes(payableState(data,r,end).status)).map(r=>({value:r.id,label:r.reference+' · '+money(payableState(data,r,end).remaining)}))]}/></label><p>Confirm the original payment is for this supplier and has not already settled another bill. Only the bill allocation is saved; the bank payment is not posted again.</p></>}
 {kind==='recurring'&&<p>Starts next month by default. Prior invoice service dates are cleared; verify each new monthly bill against its current supporting document before approving.</p>}{kind==='recurring'&&<div className="leasing-form-grid">{field('name','Template name')}{field('start','First month','month')}{field('end','Last month (optional)','month')}{field('day','Monthly bill day (1–31)','number')}{field('dueDays','Days until due (0–365)','number')}</div>}
 {field('reviewer','Reviewed by')}<label className="check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified the original source, company, supplier, itemized amounts and existing payments.</label><button disabled={blocked||!verified} onClick={save}>{saving?'Saving…':kind==='post'?'Post reviewed liability':kind==='apply'?'Apply existing payment / credit':'Save reviewed record'}</button></>}</DialogContent></Dialog>
 </section>;
}
