"use client";
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,type PoolAssumption,poolAssumptionCalculation,savePoolAssumption,nextPoolMonth,money,cents} from '@/lib/pool';
export default function PoolAssumptionReview({data,period,poolId,busy,persist}:{data:Data;period:string;poolId:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){
 const [editing,setEditing]=useState(false),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[reviewer,setReviewer]=useState('');
 let calc:ReturnType<typeof poolAssumptionCalculation>|null=null;try{calc=poolAssumptionCalculation(data,poolId,period);}catch{}
 const history=(data.poolAssumptions??[]).filter(r=>r.poolId===poolId&&r.sourceMonth===period),draft=[...history].reverse().find(r=>r.status==='Draft'),approved=[...history].reverse().find(r=>r.status==='Approved'),stale=!!draft&&draft.sourceKey!==calc?.sourceKey;
 async function save(status:'Draft'|'Approved',record?:PoolAssumption){try{const n=structuredClone(data);savePoolAssumption(n,poolId,period,record?.proposed??(editing?cents(amount):calc!.calculated),record?.reason??reason,reviewer,status,record?.id);if(await persist(n,status==='Approved'?'Pool assumption approved for next month':'Assumption draft saved')){setEditing(false);setReason('');}}catch(e){toast.error((e as Error).message);}}
 return <section className="panel" aria-label="Next month pool assumption"><h3>Next month pool assumption · {nextPoolMonth(period)}</h3><p>Source: tenant receipts applied to {period} rent charges ÷ participating pool units. Vacant participants are included; escrow and electricity allocation are separate.</p>{calc&&<><div className="summary-line"><span>Tenant rent collected</span><strong>{money(calc.collected)}</strong></div><div className="summary-line"><span>Participating units</span><strong>{calc.unitIds.length}</strong></div><div className="summary-line"><span>Calculated equal share per unit</span><strong>{money(calc.calculated)}</strong></div><p className="hint">Rounded to cents. This is a next-month forecast assumption, not current owner income, bank cash or authorization to distribute funds. It updates owner drafts only after approval.</p><label className="field">Reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label>{editing&&<><label className="field">Proposed pool rent per unit<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Edit reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label></>}<div className="toolbar"><button disabled={busy} onClick={()=>save('Draft')}>{editing?'Save edited draft':'Calculate & save draft'}</button><button className="secondary" disabled={busy} onClick={()=>{setAmount(((draft?.proposed??calc!.calculated)/100).toFixed(2));setReason(draft?.reason??'');setEditing(true);}}>Edit assumption</button></div>{draft&&<><p>Saved draft: {money(draft.proposed)} per unit · {draft.reviewer}. {stale?'Source changed—calculate a fresh draft before approving.':'Source matches current saved rent records.'}</p><button disabled={busy||editing||stale||history.some(r=>r.draftId===draft.id)} onClick={()=>save('Approved',draft)}>Approve assumption</button></>}{approved&&<p>Approved: {money(approved.proposed)} per unit for {approved.targetMonth} · {approved.reviewer}. {approved.sourceKey!==calc.sourceKey?'Collected rent has changed since approval; review a fresh draft.':''}</p>}<details><summary>Assumption review history · {history.length}</summary>{history.map(r=><p key={r.id}>{r.status} · {r.created} · calculated {money(r.calculated)} / proposed {money(r.proposed)} · {r.reviewer} · {r.reason||'Calculated amount accepted'}</p>)}</details></>}</section>;
}
