'use client';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {type Data,money} from '@/lib/pool';
import {poolProjection} from '@/lib/pool-projection';
export default function PoolProjection({data,period,poolId}:{data:Data;period:string;poolId:string}){
 const p=poolProjection(data,period,poolId);if(!p)return null;
 const red=(value:number,threshold=0)=>value<threshold?'#b91c1c':undefined;
 const shortage=(office:number)=>Math.max(0,p.target-office);
 return <section className="panel" aria-label="Monthly rent allocation review"><h2>Monthly rent allocation review · {period}</h2><p>One rent source across Dashboard, Leasing and Accounting. Owner amounts below come from the latest saved statements, including entered repairs. Drafts are not approved payments.</p>
 <div className="metrics"><div className="metric"><span>Tenant rent expected</span><strong>{money(p.rent.expected)}</strong><small>Dated tenant agreements and verified vacancy</small></div><div className="metric"><span>Rent received for this month</span><strong>{money(p.rent.applied)}</strong><small>Receipts applied to rent charges · escrow excluded</small></div><div className="metric"><span>Rent still to collect</span><strong>{money(p.rent.remaining)}</strong><small>Same unpaid-unit queue as Leasing</small></div><div className="metric"><span>Projected DLA share</span><strong style={{color:red(p.projectedOffice,p.target)}}>{money(p.projectedOffice)}</strong><small>If expected rent is collected and net owner allocations are settled · before office expenses</small></div></div>
 <Table><TableHeader><TableRow><TableHead>Monthly allocation breakdown</TableHead><TableHead>Amount</TableHead><TableHead>Source</TableHead></TableRow></TableHeader><TableBody>
 <TableRow><TableCell>Owner net rent allocation</TableCell><TableCell>{money(p.ownerNet)}</TableCell><TableCell>Latest statements: allocations less all charges, plus credits</TableCell></TableRow>
 <TableRow><TableCell>HOA · all recorded unit charges</TableCell><TableCell>{money(p.statementFees.hoa)}</TableCell><TableCell>Statement GL 80000, including private 1315 through 1607</TableCell></TableRow>
 <TableRow><TableCell>Pool electricity · pass-through</TableCell><TableCell>{money(p.statementFees.electricity)}</TableCell><TableCell>Recorded shared-electricity statement lines</TableCell></TableRow>
 <TableRow><TableCell>Repairs, labor, materials and other charges · net of credits</TableCell><TableCell>{money(p.otherCosts)}</TableCell><TableCell>Remaining statement charges; inventory only when issued</TableCell></TableRow>
 <TableRow><TableCell>Projected DLA share · remaining monthly allocation</TableCell><TableCell style={{color:red(p.projectedOffice,p.target),fontWeight:700}}>{money(p.projectedOffice)}</TableCell><TableCell>Expected tenant rent less the four rows above</TableCell></TableRow>
 <TableRow><TableCell>Total allocated from expected rent</TableCell><TableCell>{money(p.ownerNet+p.statementFees.hoa+p.statementFees.electricity+p.otherCosts+p.projectedOffice)}</TableCell><TableCell>Must equal {money(p.rent.expected)} expected rent</TableCell></TableRow>
 </TableBody></Table>
 <p className="notice">This is a planning calculation, not bank cash or earned-income confirmation. Owner net allocation includes units with negative draft balances; it is not the total checks to print. Opening balances, adjustments, completed distributions and owner contributions must be reviewed in the distribution register.</p>
 <Table><TableHeader><TableRow><TableHead>DLA target review</TableHead><TableHead>Current month</TableHead><TableHead>Next month · {p.nextPeriod}</TableHead></TableRow></TableHeader><TableBody>
 <TableRow><TableCell>Scheduled tenant rent</TableCell><TableCell>{money(p.rent.expected)}</TableCell><TableCell>{money(p.next.expected)}</TableCell></TableRow>
 <TableRow><TableCell>DLA share with current owner allocations retained</TableCell><TableCell style={{color:red(p.projectedOffice,p.target)}}>{money(p.projectedOffice)}</TableCell><TableCell style={{color:red(p.nextOffice,p.target)}}>{money(p.nextOffice)}</TableCell></TableRow>
 <TableRow><TableCell>Shortfall against $10,000 minimum</TableCell><TableCell style={{color:shortage(p.projectedOffice)>0?'#b91c1c':undefined,fontWeight:700}}>{money(shortage(p.projectedOffice))}</TableCell><TableCell style={{color:shortage(p.nextOffice)>0?'#b91c1c':undefined,fontWeight:700}}>{money(shortage(p.nextOffice))}</TableCell></TableRow>
 </TableBody></Table><p className="hint">Next-month comparison retains current owner allocations and charges for comparison only. It is not next month’s final budget.</p>
 <details><summary>Fee agreements and funding difference · explain the calculation</summary><p>Proposed management {money(p.statementFees.management)} + maintenance {money(p.statementFees.maintenance)} = {money(p.statementFees.fees)}. These are charges in owner statements, not verified collected DLA income.</p><p style={{color:p.statementAllocated>p.rent.expected?'#b91c1c':undefined}}>Draft owner allocations exceed expected rent by {money(Math.max(0,p.statementAllocated-p.rent.expected))}. Keeping those allocations reduces the funded DLA share to {money(p.projectedOffice)}.</p><Table><TableHeader><TableRow><TableHead>Type</TableHead><TableHead>Participants</TableHead><TableHead>Assumed allocation / unit</TableHead><TableHead>MGT / unit</TableHead><TableHead>MAINT / unit</TableHead></TableRow></TableHeader><TableBody>{p.groups.map(g=><TableRow key={g.type}><TableCell>{g.type===1?'1/1':'2/2'}</TableCell><TableCell>{g.count}</TableCell><TableCell>{money(g.allocation)}</TableCell><TableCell>{money(g.management)}</TableCell><TableCell>{money(g.maintenance)}</TableCell></TableRow>)}</TableBody></Table><p className="hint">Rates come from Monthly settings v{data.settings.filter(s=>s.period===period&&s.poolId===poolId).sort((a,b)=>b.version-a.version)[0]?.version}. Actual charge totals above come from saved statements and can differ after unit-level edits.</p></details>
 <details><summary>Source records and items needing review</summary><p>{p.statements.length} latest unit statements; {p.statements.filter(s=>s.status==='Pending').length} drafts. {p.groups.reduce((n,g)=>n+g.count,0)} pool participants; excluded units remain separate HOA-only records.</p>{p.missingRent.map(u=><p key={u.number}>Unit {u.number} · {u.participating?'Pool participant':'Outside pool'} · {u.review}</p>)}<Table><TableHeader><TableRow><TableHead>Unit</TableHead><TableHead>Charge</TableHead><TableHead>GL</TableHead><TableHead>Amount</TableHead></TableRow></TableHeader><TableBody>{p.statements.flatMap(s=>s.expenses.map(e=><TableRow key={s.id+e.id}><TableCell>{data.units.find(u=>u.id===s.unitId)?.number}</TableCell><TableCell>{e.label}</TableCell><TableCell>{e.gl||'Review classification'}</TableCell><TableCell>{money(e.cents)}</TableCell></TableRow>))}</TableBody></Table></details>
 </section>;
}
