'use client';
import {useEffect,useState} from 'react';
import {zipSync,strToU8} from 'fflate';
import {download} from '@/lib/exports';
import {QBO_KINDS,type QboKind} from '@/lib/qbo-exchange';
const labels:Record<QboKind,string>={accounts:'Chart of accounts',customers:'Customer contacts',vendors:'Vendor contacts',payments:'Tenant payments', 'profit-loss':'Profit and Loss by Class'};
type Status={configured:boolean;connected:boolean;canConnect:boolean;status:string;company?:string;environment?:string};
export default function QboConnectionPanel({period}:{period:string}){const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[basis,setBasis]=useState<'Cash'|'Accrual'>('Accrual');async function refresh(){setError('');try{const r=await fetch('/api/qbo/status',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setStatus(j);}catch(e){setError((e as Error).message);}}useEffect(()=>{void refresh();},[]);async function connection(action:string){if(action==='disconnect'&&!confirm('Remove OG’s stored QuickBooks access? This changes no financial records. You can also revoke OG in Intuit Connected Apps.'))return;setBusy(true);setError('');try{const r=await fetch('/api/qbo/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}),j=await r.json();if(!r.ok)throw Error(j.error);if(j.url){window.location.assign(j.url);return;}await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pull(kind:QboKind){setBusy(true);setError('');try{const r=await fetch('/api/qbo/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,month:period,basis})}),j=await r.json();if(!r.ok)throw Error(j.error);const source=JSON.stringify(j.source,null,2),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(source)))).map(b=>b.toString(16).padStart(2,'0')).join('');const zip=zipSync({'review.csv':strToU8(j.csv),'qbo-source.json':strToU8(source),'source-sha256.txt':strToU8(hash+'  qbo-source.json\n'),'README.txt':strToU8('Downloaded for review only. No OG ledger or QBO transaction changed. Chart CSV: import and review in GL mapping. Payment CSV: Tenant rent > QBO payment import; review tenant/unit/charge matches. Contacts: manually compare exact names and QBO IDs before updating People. Profit and Loss by Class is an accounting comparison, not proof of collected rent. Source JSON retains original records.\n')});download(new Blob([zip.slice().buffer],{type:'application/zip'}),j.fileName+'.zip');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><div className="panel-heading"><h3>QuickBooks connection & downloads</h3><button disabled={busy} onClick={refresh}>Refresh connection</button></div><p>{status?status.status:'Checking connection…'}{status?.company?' · '+status.company:''}{status?.environment?' · '+status.environment:''}</p>{error&&<p role="alert">{error}</p>}{status?.canConnect&&<div className="toolbar"><button disabled={busy||!status.configured} onClick={()=>connection('connect')}>{status.connected?'Reconnect QuickBooks':'Connect QuickBooks'}</button>{status.connected&&<button disabled={busy} onClick={()=>connection('disconnect')}>Disconnect</button>}</div>}<label className="field">Profit and Loss basis<select value={basis} onChange={e=>setBasis(e.target.value as 'Cash'|'Accrual')}><option>Accrual</option><option>Cash</option></select></label><p>Review month: {period}</p><div className="toolbar">{QBO_KINDS.map(kind=><button key={kind} disabled={busy||!status?.connected} onClick={()=>pull(kind)}>{labels[kind]}</button>)}</div><p className="hint">Downloads include original QBO records, review CSV, and a source checksum. Review them before importing into OG. This connection sends no bills, invoices, payments, or journal entries to QBO. CSV exchange remains available while registration is pending. Contact downloads do not automatically create tenants or owners.</p></section>;
}
