'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,money} from '@/lib/pool';
import {undepositedAccount} from '@/lib/bank-workflow';
import {native,bookChart} from '@/lib/native-accounting';
import {postTenantSource,tenantLedgerLink,tenantPostingCandidates} from '@/lib/receivables-ledger';
import {recordAudit,validateAccounting} from '@/lib/accounting-model';
import {appliedThroughMonth} from '@/lib/accounting-workspace';
import {Grid,Pick} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Props={data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;openUnit:(id:string)=>void;openTenant:(unitId:string,tenantId:string,entryId?:string)=>void;onPage:(page:string,context:{bookId:string;bankKey:string})=>void;initialBook?:string};
export default function ReceivablesLedger({data,period,busy,persist,openUnit,openTenant,onPage,initialBook}:Props){
 const [selected,setSelected]=useState(initialBook??''),[kind,setKind]=useState('All'),[query,setQuery]=useState(''),[form,setForm]=useState<any>(null),[verified,setVerified]=useState(false),[saving,setSaving]=useState(false);const n=native(data),book=n.books.find(b=>b.id===selected)??n.books[0],chart=book?bookChart(data,book.id):undefined,accounts=chart?.accounts.filter(a=>a.active)??[],ar=accounts.filter(a=>a.type.toLowerCase()==='accounts receivable'),entries=(data.operations?.tenantEntries??[]).filter(e=>e.date.slice(0,7)<=period&&(kind==='All'||e.kind===kind)).filter(e=>{const t=data.operations?.tenants?.find(t=>t.id===e.tenantId),u=data.units.find(u=>u.id===t?.unitId);return [e.reference,e.description,t?.firstName,t?.lastName,u?.number].join(' ').toLowerCase().includes(query.toLowerCase());}),blocked=busy||saving;
 async function save(){if(!form||!book||blocked||!verified)return;setSaving(true);try{const next=postTenantSource(data,{...form,bookId:book.id,verified});validateAccounting(next,data);recordAudit(next,'Tenant source linked to native ledger',form.entryId);if(await persist(next,'Existing tenant source posted once; no payment collected'))setForm(null);}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 return <section className="panel"><h3>Tenant receipt, charge & credit posting</h3><p>Use the original tenant source already recorded in OG. Review its accounts before posting it once to the company ledger. Applying receipts to charges remains in the tenant profile; this posting does not create another tenant transaction or collect money.</p><label className="field">Company ledger<Pick label="Receivables posting company" value={book?.id??'none'} onChange={v=>{setSelected(v);setForm(null);}} items={n.books.length?n.books.map(b=>({value:b.id,label:b.company})):[{value:'none',label:'Initialize company ledger first'}]}/></label><div className="leasing-form-grid"><label className="field">Entry type<Pick label="Receivable entry type" value={kind} onChange={setKind} items={['All','Charge','Receipt','Credit'].map(v=>({value:v,label:v}))}/></label><label className="field">Search<input aria-label="Search receivable sources" value={query} placeholder="Tenant, unit, reference or description" onChange={e=>setQuery(e.target.value)}/></label></div><Grid headers={['Date','Tenant','Unit','Kind','Source reference','Amount','Applied','Unapplied','Ledger / next step']} rows={entries.map(e=>{const t=data.operations!.tenants!.find(t=>t.id===e.tenantId)!,u=data.units.find(u=>u.id===t.unitId),link=tenantLedgerLink(data,e.id),ledger=link?n.entries.find(x=>x.id===link.ledgerEntryId):undefined,reversed=ledger&&n.entries.some(x=>x.reverses===ledger.id&&x.date.slice(0,7)<=period),applied=appliedThroughMonth(data,e.id,period);return [e.date,t.firstName+' '+t.lastName,<button className="text-button" onClick={()=>openUnit(t.unitId)}>{u?.number}</button>,e.kind,e.reference,<button className="text-button" onClick={()=>openTenant(t.unitId,t.id,e.id)}>{money(e.cents)}</button>,money(applied),money(e.cents-applied),<div className="toolbar">{link?<><span>{reversed?'Reversed — review':ledger&&ledger.date.slice(0,7)>period?'Posted after selected month':'Posted'}</span><button className="secondary" onClick={()=>onPage('Native ledger',{bookId:link.bookId,bankKey:link.receivableKey})}>Open receivable ledger</button>{e.kind==='Receipt'&&<button className="secondary" onClick={()=>onPage(undepositedAccount(accounts.find(a=>a.key===link.counterKey)??{name:'',type:''})?'Grouped deposits':'Statement reconciliation',{bookId:link.bookId,bankKey:link.counterKey})}>Reconcile receipt</button>}</>:<button disabled={blocked||!book||!ar.length} onClick={()=>{setVerified(false);setForm({entryId:e.id,receivableKey:ar[0]?.key??'',counterKey:'',reviewer:'',existingLedgerEntryId:''});}}>Review posting</button>}<button className="secondary" onClick={()=>openTenant(t.unitId,t.id,e.id)}>Open source / apply credits</button></div>];})}/><button className="secondary" onClick={()=>onPage('Receipts & charges',{bookId:book?.id??'',bankKey:''})}>Open tenant receipt matching</button>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!saving)setForm(null);}}><DialogContent className="app-dialog native-accounting-dialog"><DialogHeader><DialogTitle>Review tenant source posting</DialogTitle><DialogDescription>{book?.company} · Preserves the original tenant amount, date, unit and source.</DialogDescription></DialogHeader>{form&&(()=>{const e=data.operations!.tenantEntries!.find(x=>x.id===form.entryId)!;return <><p>{e.kind} · {e.reference} · {e.date} · {money(e.cents)}</p><p>{e.description}</p><label className="field">Accounts Receivable GL<Pick label="Tenant receivable GL" value={form.receivableKey} onChange={v=>{setVerified(false);setForm({...form,receivableKey:v,existingLedgerEntryId:''});}} items={ar.map(a=>({value:a.key,label:a.number+' · '+a.name}))}/></label><label className="field">{e.kind==='Receipt'?'Bank / Undeposited Funds GL':'Charge / credit income GL'}<Pick label="Tenant source counter GL" value={form.counterKey||'none'} onChange={v=>{setVerified(false);setForm({...form,counterKey:v,existingLedgerEntryId:''});}} items={[{value:'none',label:'Choose the verified company account'},...accounts.filter(a=>e.kind==='Receipt'?(a.type.toLowerCase()==='bank'||undepositedAccount(a)):['income','other income'].includes(a.type.toLowerCase())).map(a=>({value:a.key,label:a.number+' · '+a.name}))]}/></label><label className="field">Existing matching ledger entry (optional)<Pick label="Existing tenant ledger posting" value={form.existingLedgerEntryId||'new'} onChange={v=>{setVerified(false);setForm({...form,existingLedgerEntryId:v==='new'?'':v});}} items={[{value:'new',label:'Post a new entry only if not already recorded'},...tenantPostingCandidates(data,e.id,book!.id,form.receivableKey,form.counterKey).map(x=>({value:x.id,label:x.date+' · '+x.reference+' · link without another posting'}))]}/></label><label className="field">Reviewer<input aria-label="Tenant source reviewer" value={form.reviewer} onChange={ev=>{setVerified(false);setForm({...form,reviewer:ev.target.value});}}/></label><label className="check"><input type="checkbox" checked={verified} onChange={ev=>setVerified(ev.target.checked)}/>I verified the source and company accounts and confirmed this entry has not already been posted or recorded as another bank deposit.</label><button disabled={blocked||!verified} onClick={save}>Post existing tenant source</button></>;})()}</DialogContent></Dialog></section>;
}
