'use client';
import {useState} from 'react';
import {type Data,money} from '@/lib/pool';
import {reconciliationSourceReview} from '@/lib/accounting-connections';
import {Grid} from './report-controls';
export default function ReconciliationSources({data,period,openUnit,onPage}:{data:Data;period:string;openUnit:(id:string)=>void;onPage?:(page:string)=>void}){
 const [search,setSearch]=useState(''),review=reconciliationSourceReview(data,period),rows=review.rows.filter(r=>[r.reference,r.description,r.kind,data.units.find(u=>u.id===r.unitId)?.number].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <section className="panel"><p className="eyebrow">YOUR RECORDED ACTIVITY · {period}</p><h3>Starting balances & recorded transactions</h3><p>Your existing OG records remain visible here before native books are initialized. Source records and ledger journals are separate views; do not add their amounts together.</p><div className="input-grid"><div className="notice"><strong>Owner statement opening balances</strong><p>{review.ownerOpening===null?'Verification incomplete':money(review.ownerOpening)} · {review.verifiedOwners} of {review.ownerStatements} verified statements</p><p className="hint">Owner balances do not establish a bank account’s opening balance.</p></div><div className="notice"><strong>Recorded bank starting points</strong>{review.openings.length||review.bookOpenings.length?<>{review.bookOpenings.map(r=><p key={r.id}>{r.company} · {r.account} · {r.date} · {money(r.cents)} · {r.source}</p>)}{review.openings.map(r=><p key={r.id}>{r.account} · {r.date} · {money(r.cents)} · {r.reference}</p>)}</>:<p>No verified bank starting point recorded. Verify the exact bank account before applying $0.00.</p>}</div></div><label className="field">Search recorded activity<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Reference, name, type or unit"/></label><Grid headers={['Actual date','Type','Reference','Details','Amount','Unit','Ledger status','Review']} rows={rows.map(r=>[r.date,r.kind,r.reference,r.description,money(r.cents),r.unitId?<button className="text-button" onClick={()=>openUnit(r.unitId)}>Unit {data.units.find(u=>u.id===r.unitId)?.number??r.unitId}</button>:'Company',r.status,onPage?<button className="secondary" onClick={()=>onPage(r.page)}>Open source</button>:r.page])}/><p className="hint">{review.rows.length} recorded source records · {review.nativeRows.length} native journals dated in {period}. Charges, credits, escrow and external checks are identified separately; this list is not a bank balance or proof of clearing. Approved September 30 receipts allocated to October retain their actual date.</p>{!!review.nativeRows.length&&<details><summary>Native journals recorded this month</summary><Grid headers={['Date','Reference','Company book','Memo','Source']} rows={review.nativeRows.map(e=>[e.date,e.reference,data.accounting?.native?.books.find(b=>b.id===e.bookId)?.company??e.bookId,e.memo,e.sourceSystem||'OG journal'])}/></details>}<div className="toolbar">{onPage&&<><button className="secondary" onClick={()=>onPage('Tenant ledger posting')}>Review tenant receipt links</button><button className="secondary" onClick={()=>onPage('Payment posting review')}>Review recorded check links</button></>}</div></section>;
}
