'use client';
import {type Data,money,ownerAt} from '@/lib/pool';
import {expectedUnitRent,monthTenants} from '@/lib/tenancy';
import {officeRent} from '@/lib/accounting-model';
import {Grid} from './report-controls';
import RentProgress from './rent-progress';
export default function RentRoll({data,period,openTenant,navigate}:{data:Data;period:string;openTenant?:(unitId:string,tenantId:string)=>void;navigate:(view:string)=>void}){const rows=data.units.map(u=>{const r=expectedUnitRent(data,u,period),cash=officeRent(data,u.id,period),ts=monthTenants(data,u.id,period);return {unit:u,r,cash,tenant:ts.map(t=>t.firstName+' '+t.lastName).join(' / '),owner:data.owners.find(o=>o.id===ownerAt(data,u.id,period+'-01'))?.name??'Unverified'};}),known=rows.filter(r=>r.r.cents!==null),total=known.reduce((n,r)=>n+r.r.cents!,0);
 return <section className="panel check-summary"><div className="panel-heading"><div><h3>Shared rent roll · {period}</h3><p>Same tenant and lease sources across Properties, People, Leasing and Accounting.</p></div><div className="toolbar"><RentProgress data={data} period={period} compact/><button className="secondary" onClick={()=>navigate('accounting')}>Rent charges & receipts</button><a className="upload-button" href={'/api/exports?kind=rent-roll&month='+encodeURIComponent(period)}>Export shared rent roll</a></div></div><p><strong>{money(total)}</strong> verified full-month expected rent · {rows.length-known.length} units need review.</p><Grid headers={['Unit / owner','Tenant','Expected rent','Source / review','Recorded rent','']} rows={rows.map(x=>[x.unit.number+' · '+x.owner,x.tenant||'No effective tenant',x.r.cents===null?'Unverified':money(x.r.cents),x.r.review||x.r.source,x.cash.cents===null?'Not recorded':money(x.cash.cents)+' · '+x.cash.source,openTenant?<button className="text-button" onClick={()=>openTenant(x.unit.id,x.r.tenantId)}>Open unit contact</button>:<button className="text-button" onClick={()=>navigate('people')}>People directory</button>])}/><p className="hint">Expected rent is a forecast, not an invoice, collected payment or pool allocation. A vacant unit can still participate in the pool. Partial-month and conflicting records need an agreed charge; OG does not invent proration or silently substitute an assumed pool allocation. Manual recorded rent remains labeled separately from matched tenant receipts.</p></section>;
}

