'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data,money,cents,validate} from '@/lib/pool';
import {rentReview,addLateFee,validateRentDepositMatches} from '@/lib/rent-reconciliation';
import {emptyAccounting,recordAudit} from '@/lib/accounting-model';
import {cashAccounts,type CashAccount} from '@/lib/cash-planning';
import {download,csv} from '@/lib/exports';
import {Grid} from './report-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';

type Props={data:Data;period:string;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>;openTenant:(unitId:string,tenantId:string,entryId?:string)=>void;onBank:()=>void};
export default function RentReconciliation({data,period,busy,persist,openTenant,onBank}:Props){
 const [search,setSearch]=useState(''),[status,setStatus]=useState('All'),[property,setProperty]=useState('All'),[account,setAccount]=useState<CashAccount>('DLA operating'),[saving,setSaving]=useState(false);
 const [fee,setFee]=useState<{tenantId:string;date:string;amount:string;basis:string;reviewer:string}|null>(null),[match,setMatch]=useState<{depositId:string;receiptIds:string[];source:string;reviewer:string}|null>(null);
 const blocked=busy||saving,all=rentReview(data,period),tenants=data.operations?.tenants??[],entries=data.operations?.tenantEntries??[],matches=data.accounting?.rentDepositMatches??[],used=new Set(matches.flatMap(r=>r.receiptIds));
 const name=(id:string)=>{const t=tenants.find(t=>t.id===id);return t?[t.firstName,t.lastName].join(' '):'Tenant needs review';};
 const rows=all.filter(r=>(property==='All'||r.unit.propertyId===property)&&(status==='All'||r.status===status)&&[r.unit.number,name(r.original.tenantId)].join(' ').toLowerCase().includes(search.toLowerCase()));
 const sum=(key:'received'|'credits'|'posted'|'fees'|'feeDue')=>all.reduce((n,r)=>n+r[key],0),known=all.reduce((n,r)=>n+(r.original.cents??0),0),pending=all.reduce((n,r)=>n+(r.pending??0),0),unknown=all.filter(r=>r.pending===null).length;
 const receipts=entries.filter(e=>e.kind==='Receipt'&&e.date.startsWith(period)),deposits=(data.accounting?.cashPlanning?.manualEntries??[]).filter(e=>e.kind==='Deposit'&&e.account===account&&e.date.startsWith(period));
 async function save(kind:'fee'|'match'){if(blocked)return;setSaving(true);try{const next=structuredClone(data);if(kind==='fee'&&fee){const entry=addLateFee(next,fee.tenantId,period,fee.date,cents(fee.amount),fee.basis,fee.reviewer);recordAudit(next,'Reviewed tenant late fee recorded',entry.reference+' / '+entry.cents+' cents');}else if(kind==='match'&&match){next.accounting??=emptyAccounting();(next.accounting.rentDepositMatches??=[]).push({...match,id:crypto.randomUUID(),created:new Date().toISOString()});validateRentDepositMatches(data,next);recordAudit(next,'Rent receipt deposit matched',match.depositId+' / '+match.source+' / '+match.reviewer);}else return;validate(data,next);if(await persist(next,kind==='fee'?'Late fee saved to tenant ledger':'Deposit match saved')){setFee(null);setMatch(null);}}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 return <><section className="panel" aria-label="Monthly rent reconciliation"><div className="panel-heading"><div><p className="eyebrow">MONTHLY RENT · {period}</p><h3>Rent received & pending payment</h3><p>Review agreed rent, applied payments and bank deposit evidence in one place.</p></div><button className="secondary" onClick={()=>download(new Blob([csv([['Month','Unit','Tenant','Original monthly rent','Posted rent','Rent received','Rent credits','Rent pending','Late fees','Late fees pending','Posted variance','Status','Rent source'],...rows.map(r=>[period,r.unit.number,name(r.original.tenantId),r.original.cents===null?'Needs review':(r.original.cents/100).toFixed(2),(r.posted/100).toFixed(2),(r.received/100).toFixed(2),(r.credits/100).toFixed(2),r.pending===null?'Needs review':(r.pending/100).toFixed(2),(r.fees/100).toFixed(2),(r.feeDue/100).toFixed(2),r.variance===null?'Needs review':(r.variance/100).toFixed(2),r.status,r.original.source])])],{type:'text/csv'}),'OG_Rent_Reconciliation_'+period+'.csv')}>Export filtered list</button></div>
 <div className="ops-metrics">{[['Original monthly rent',money(known)],['Rent received / applied',money(sum('received'))],['Rent pending',money(pending)],['Rent credits',money(sum('credits'))],['Late fees pending',money(sum('feeDue'))],['Units needing verification',String(unknown)]].map(([label,value])=><div className="ops-metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 {unknown>0&&<p className="notice">{unknown} units have unverified monthly rent. Original and pending totals include verified amounts only.</p>}
 <div className="toolbar"><label className="field">Property<select value={property} onChange={e=>setProperty(e.target.value)}><option value="All">All properties</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">Payment status<select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Unpaid','Partial','Settled','Needs review'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Unit or tenant"/></label></div>
 <Grid headers={['Unit / tenant','Original rent','Posted rent / variance','Received','Credits','Rent pending','Late fees / pending','Status','Next action']} rows={rows.map(r=>[r.unit.number+' · '+name(r.original.tenantId),r.original.cents===null?'Needs review':money(r.original.cents),money(r.posted)+' / '+(r.variance===null?'Needs review':money(r.variance)),money(r.received),money(r.credits),r.pending===null?'Needs review':money(r.pending),money(r.fees)+' / '+money(r.feeDue),r.status,<div className="toolbar"><button className="text-button" disabled={!r.original.tenantId} onClick={()=>openTenant(r.unit.id,r.original.tenantId)}>Tenant ledger / payment</button><button className="text-button" disabled={blocked||!r.pending||!r.original.tenantId||entries.some(e=>e.reference==='LATE-FEE:'+r.original.tenantId+':'+period)} onClick={()=>setFee({tenantId:r.original.tenantId,date:period+'-01',amount:'',basis:'',reviewer:''})}>Add late fee</button><details><summary>Rent basis</summary>{r.original.source} {r.original.review}</details></div>])}/>
 <p className="hint">Received means cash receipts applied to this month's rent, including prepaid receipts. Credits reduce rent pending separately. Late fees stay separate from rent. Posted variance compares saved rent charges to the original verified monthly amount; fees do not change that amount.</p></section>
 <section className="panel"><div className="panel-heading"><div><h3>Cash receipts & bank deposits · {period}</h3><p>Receipt dates and deposit dates are separate from the rent month above.</p></div><button className="secondary" onClick={onBank}>Bank balances / record deposit</button></div><div className="ops-metrics"><div className="ops-metric"><span>Cash receipts dated this month</span><strong>{money(receipts.reduce((n,e)=>n+e.cents,0))}</strong><small>Includes rent, other charges and unapplied cash; excludes escrow</small></div><div className="ops-metric"><span>{account} deposits recorded this month</span><strong>{money(deposits.reduce((n,e)=>n+e.cents,0))}</strong><small>All recorded deposits; verify receipt matches below</small></div></div>
 <Grid headers={['Receipt date','Tenant / unit','Reference','Cash received','Bank deposit match','Review']} rows={receipts.map(e=>{const t=tenants.find(t=>t.id===e.tenantId),m=matches.find(m=>m.receiptIds.includes(e.id)),dep=data.accounting?.cashPlanning?.manualEntries?.find(d=>d.id===m?.depositId);return [e.date,name(e.tenantId)+' / '+(data.units.find(u=>u.id===t?.unitId)?.number??'Needs review'),e.reference,money(e.cents),dep?dep.date+' · '+dep.reference:'Unmatched',<button className="text-button" disabled={!t} onClick={()=>t&&openTenant(t.unitId,t.id,e.id)}>Open receipt</button>];})}/>
 <label className="field">Bank account<select value={account} onChange={e=>setAccount(e.target.value as CashAccount)}>{cashAccounts.map(a=><option key={a}>{a}</option>)}</select></label>
 <Grid headers={['Deposit date','Account','Reference','Deposit amount','Receipt amount / difference','Status','Next action']} rows={deposits.map(d=>{const m=matches.find(m=>m.depositId===d.id),total=m?.receiptIds.reduce((n,id)=>n+(entries.find(e=>e.id===id)?.cents??0),0);return [d.date,d.account,d.reference,money(d.cents),total===undefined?'Not matched':money(total)+' / '+money(d.cents-total),m?(total===d.cents&&!m.receiptIds.some(id=>(entries.find(e=>e.id===id)?.date??'')>d.date)?'Matched · manual evidence':'Needs review · receipt corrected'):'Unmatched',m?<details><summary>Evidence</summary>{m.source} · {m.reviewer}</details>:<button className="text-button" disabled={blocked||d.account!=='DLA operating'} onClick={()=>setMatch({depositId:d.id,receiptIds:[],source:'',reviewer:''})}>Match receipts</button>];})}/>
 <p className="hint">A match requires full receipt amounts to equal one recorded DLA operating deposit. Earlier-month receipts can be selected. Each receipt is matched once. Split deposits, bank fees and mixed deposits need separate review in Statement reconciliation. Equal monthly totals alone do not prove reconciliation. Bank sync is not connected.</p></section>
 <Dialog open={!!fee||!!match} onOpenChange={open=>{if(!open&&!saving){setFee(null);setMatch(null);}}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{fee?'Review late fee':'Match bank deposit'}</DialogTitle><DialogDescription>{fee?'Confirm the lease basis and reviewed amount before posting a separate tenant charge.':'Select receipts and verify their total against the recorded bank deposit.'}</DialogDescription></DialogHeader>
 {fee&&<><p>{name(fee.tenantId)} · {period}</p><div className="input-grid"><label className="field">Fee date<input type="date" value={fee.date} onChange={e=>setFee({...fee,date:e.target.value})}/></label><label className="field">Late fee ($)<input inputMode="decimal" value={fee.amount} onChange={e=>setFee({...fee,amount:e.target.value})}/></label><label className="field">Lease clause / grace period and reason<textarea value={fee.basis} onChange={e=>setFee({...fee,basis:e.target.value})}/></label><label className="field">Reviewed by<input value={fee.reviewer} onChange={e=>setFee({...fee,reviewer:e.target.value})}/></label></div><p className="hint">One reviewed late fee per tenant per month. Corrections use the existing tenant ledger history. This records a charge; it sends no notice and collects no money.</p><button disabled={blocked} onClick={()=>save('fee')}>{saving?'Saving…':'Save reviewed late fee'}</button></>}
 {match&&<><p>Deposit: {money(deposits.find(d=>d.id===match.depositId)?.cents??0)} · Selected: {money(match.receiptIds.reduce((n,id)=>n+(entries.find(e=>e.id===id)?.cents??0),0))}</p><div style={{maxHeight:280,overflowY:'auto'}}>{entries.filter(e=>e.kind==='Receipt'&&!used.has(e.id)&&e.date<=(deposits.find(d=>d.id===match.depositId)?.date??'')).map(e=><label className="check" key={e.id}><input type="checkbox" checked={match.receiptIds.includes(e.id)} onChange={ev=>setMatch({...match,receiptIds:ev.target.checked?[...match.receiptIds,e.id]:match.receiptIds.filter(id=>id!==e.id)})}/>{e.date} · {name(e.tenantId)} · {e.reference} · {money(e.cents)}</label>)}</div><label className="field">Bank statement / deposit evidence reference<input value={match.source} onChange={e=>setMatch({...match,source:e.target.value})}/></label><label className="field">Reviewed by<input value={match.reviewer} onChange={e=>setMatch({...match,reviewer:e.target.value})}/></label><button disabled={blocked} onClick={()=>save('match')}>{saving?'Saving…':'Save verified match'}</button></>}
 <button className="secondary" disabled={saving} onClick={()=>{setFee(null);setMatch(null);}}>Cancel</button></DialogContent></Dialog></>;
}
