'use client';
import {createContext,useContext,useEffect,useState,isValidElement,type ReactNode} from 'react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Pagination,PaginationContent,PaginationItem,PaginationPrevious,PaginationNext} from '@/components/ui/pagination';
import PrintPreview from './print-preview';
function printText(node:ReactNode):string{if(node===null||node===undefined||typeof node==='boolean')return '';if(typeof node==='string'||typeof node==='number')return String(node);if(Array.isArray(node))return node.map(printText).filter(Boolean).join(' ');if(isValidElement<{children?:ReactNode}>(node)){if(node.type==='button')return '';return printText(node.props.children);}return '';}
const PageSizeContext=createContext(15);
export function PageSizeProvider({userId,children}:{userId:string;children:React.ReactNode}){const [value,setValue]=useState(15);useEffect(()=>{try{const n=Number(localStorage.getItem('og.rows.'+userId));if([15,50,100].includes(n))setValue(n);}catch{}const update=(e:Event)=>{const n=(e as CustomEvent).detail;if([15,50,100].includes(n))setValue(n);};window.addEventListener('og-row-preference',update);return ()=>window.removeEventListener('og-row-preference',update);},[userId]);return <PageSizeContext.Provider value={value}>{children}</PageSizeContext.Provider>;}
export function usePageSize(){const preference=useContext(PageSizeContext),[size,setSize]=useState(preference);useEffect(()=>setSize(preference),[preference]);return [size,setSize] as const;}
function ListPager({count,page,size,setPage,setSize}:{count:number;page:number;size:number;setPage:(n:number)=>void;setSize:(n:number)=>void}){const pages=Math.max(1,Math.ceil(count/size));return <div className="pager"><div className="directory-page-controls"><label className="page-size-label">Rows per page<Pick label="Rows per page" value={String(size)} onChange={v=>{setSize(Number(v));setPage(1);}} items={[15,50,100].map(n=>({value:String(n),label:String(n)}))}/></label><span>{count} results · page {page} of {pages}</span></div><Pagination><PaginationContent><PaginationItem><PaginationPrevious href="#" aria-disabled={page===1} onClick={e=>{e.preventDefault();setPage(Math.max(1,page-1));}}/></PaginationItem><PaginationItem><PaginationNext href="#" aria-disabled={page===pages} onClick={e=>{e.preventDefault();setPage(Math.min(pages,page+1));}}/></PaginationItem></PaginationContent></Pagination></div>;}
export function PagedList({children}:{children:React.ReactNode[]}){const [size,setSize]=usePageSize(),[page,setPage]=useState(1);const current=Math.min(page,Math.max(1,Math.ceil(children.length/size)));return <>{children.slice((current-1)*size,current*size)}<ListPager count={children.length} page={current} size={size} setPage={setPage} setSize={setSize}/></>;}
export function Grid({headers,rows,printTitle,printNote}:{headers:string[];rows:React.ReactNode[][];printTitle?:string;printNote?:string}){const [size,setSize]=usePageSize(),[page,setPage]=useState(1);useEffect(()=>setPage(1),[rows.length]);const current=Math.min(page,Math.max(1,Math.ceil(rows.length/size)));return <><PrintPreview title={printTitle??headers.filter(Boolean).join(" / ")} lines={[...(printNote?[printNote,'']:[]),...rows.flatMap((row,i)=>["Record "+(i+1),...headers.map((h,j)=>h?h+": "+printText(row[j]):"").filter(Boolean),""])]}/><div className="table-wrap"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((current-1)*size,current*size).map((row,i)=><TableRow key={i}>{row.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table></div><ListPager count={rows.length} page={current} size={size} setPage={setPage} setSize={setSize}/></>;}
export function Pick({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
