'use client';
import {useEffect,useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
export default function StorageConnection({busy}:{busy:boolean}){
 const [status,setStatus]=useState<{active:boolean;ready:boolean;verifiedRevision:number|null}|null>(null),[secret,setSecret]=useState(''),[confirmed,setConfirmed]=useState(false),[connecting,setConnecting]=useState(false);
 useEffect(()=>{fetch('/api/storage-connection',{cache:'no-store'}).then(async r=>{if(r.ok)setStatus(await r.json());}).catch(()=>{});},[]);
 async function connect(){setConnecting(true);try{const r=await fetch('/api/storage-connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:secret.trim(),confirmed})});const result=await r.json() as {error?:string;active?:boolean};if(!r.ok)throw Error(result.error??'Connection failed');setSecret('');toast.success('Supabase records connected. Reloading workspace.');window.location.reload();}catch(e){toast.error((e as Error).message);}finally{setSecret('');setConnecting(false);}}
 return <section className="panel"><h3>Supabase connection</h3><p>{status?.active?'Records use Supabase PostgreSQL. Check Private document storage below for file migration status.':'Records currently use OG’s original database. Connect only after transferring and verifying the latest backup.'}</p><p className="hint">Project conganplywqzmuktmyxd · Opervix Group. The key is encrypted on the server and never returned to the browser. This screen is for the signed-in private workspace owner. It does not grant staff access.</p><label className="field">Replacement Supabase secret key<input type="password" autoComplete="new-password" spellCheck={false} value={secret} onChange={e=>setSecret(e.target.value)} placeholder="sb_secret_…" disabled={busy||connecting||!status?.ready}/></label><label className="check"><Checkbox checked={confirmed} disabled={busy||connecting} onCheckedChange={v=>setConfirmed(v===true)}/> All OG edits are saved, the latest backup is transferred, and no other session is editing during connection.</label><button disabled={busy||connecting||!status?.ready||!confirmed||!secret.trim()} onClick={connect}>{connecting?'Verifying records…':status?.active?'Verify replacement key':'Verify & connect Supabase records'}</button>{!status?.ready&&<p className="hint">Secure connection setup is loading or unavailable. Do not submit keys in chat.</p>}<p className="hint">Connecting checks your workspace ID, revision and complete record contents. Mismatched data blocks the switch. No payments or emails are sent. Private file migration is a separate action below. Separate app sign-in and shared staff permissions remain pending.</p></section>;
}
