'use client';
import {useState} from 'react';
import {type Data,money} from '@/lib/pool';
import {parseTenantImport,importTenants,type TenantImportFile} from '@/lib/tenant-import';
import {csv} from '@/lib/exports';
import {Checkbox} from '@/components/ui/checkbox';
import {Grid} from './report-controls';
export default function TenantImport({data,busy,persist}:{data:Data;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){const [file,setFile]=useState<TenantImportFile|null>(null),[name,setName]=useState(''),[hash,setHash]=useState(''),[selected,setSelected]=useState<number[]>([]),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 async function read(f:File){setError('');setFile(null);setSelected([]);setConfirmed(false);try{if(!f.name.toLowerCase().endsWith('.csv')||f.size>5000000)throw Error('Choose a CSV up to 5 MB');const text=await f.text(),parsed=parseTenantImport(data,text),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));setName(f.name);setHash([...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join(''));setFile(parsed);}catch(e){setError((e as Error).message);}}
 async function save(){if(!file||busy||saving||!confirmed)return;setSaving(true);setError('');try{const fresh=parseTenantImport(data,csv([file.headers,...file.rows.map(r=>r.raw)]));const next=importTenants(data,fresh,name,hash,selected);if(await persist(next,'Reviewed tenant contacts saved; no financial entries created')){setFile(null);setSelected([]);setConfirmed(false);}}catch(e){setError((e as Error).message);}finally{setSaving(false);}}

 return <section className="panel tenant-import"><div className="panel-heading"><div><h3>Tenant directory import & export</h3><p>Review contacts and agreed rent before saving them to the shared unit record.</p></div><div className="toolbar"><a className="upload-button" href="/api/exports?kind=tenant-template">Download tenant template</a><a className="upload-button" href="/api/exports?kind=tenant-directory">Export tenant directory</a></div></div><p className="hint">Use the OG template to prepare QBO customer-contact information. QBO Customer Contact List provides Customer full name, Phone numbers, Email, Full name, Bill address and Ship address; it does not verify tenancy dates or monthly rent. Dates use YYYY-MM-DD; monthly_rent uses dollars without currency symbols. Enter property_id if a unit number occurs in more than one property. To update an existing contact, use tenant_id from the directory export. Blank rent remains unverified for new contacts. Blank contact fields preserve existing information. Optional address, co-tenant, pets and notes columns carry supporting information. Opening balances, invoices and payments are not imported here.</p><label className="field">Reviewed tenant CSV<input type="file" accept=".csv,text/csv" disabled={busy||saving} onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);e.target.value='';}}/></label>{error&&<p role="alert" className="warning">{error}</p>}{file&&<><Grid headers={['Select','Row','Unit / tenant','Email','Expected monthly rent','Review']} rows={file.rows.map(r=>[<Checkbox aria-label={'Select tenant row '+r.row} checked={selected.includes(r.row)} disabled={busy||saving||!!r.error} onCheckedChange={v=>{setSelected(s=>v===true?[...new Set([...s,r.row])]:s.filter(x=>x!==r.row));setConfirmed(false);}}/>,r.row,r.tenant?data.units.find(u=>u.id===r.tenant!.unitId)?.number+' · '+r.tenant.firstName+' '+r.tenant.lastName:'Not matched',r.tenant?.email??'—',r.tenant&&r.tenant.rentConfirmed!==false?money(r.tenant.rent):'Unverified',r.error||((data.operations?.tenants??[]).some(t=>t.id===r.tenant?.id)?'Update existing contact':'Create reviewed tenancy')])}/><label className="check"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/> Selected names, unit identities, tenancy dates and rent agree with the source</label><button disabled={busy||saving||!confirmed||!selected.length} onClick={save}>{saving?'Saving…':'Save reviewed tenant rows'}</button><button className="secondary" disabled={saving} onClick={()=>{setFile(null);setSelected([]);setConfirmed(false);}}>Cancel import</button></>}<p className="hint">{data.tenantImports?.length??0} saved import batches retain the original rows and before/after contact evidence. Contact import does not mark a unit occupied or change pool participation.</p></section>;
}
