'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {type Data} from '@/lib/pool';
import {type VendorContact,emptyOperations} from '@/lib/operations-model';
import {recordAudit} from '@/lib/accounting-model';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Grid} from './report-controls';
export default function VendorContacts({data,busy,persist}:{data:Data;busy:boolean;persist:(d:Data,message?:string)=>Promise<boolean>}){
 const [selected,setSelected]=useState<string|null>(null);const contact=(data.operations?.vendorContacts??[]).find(v=>v.id===selected);
 const [rows,setRows]=useState<VendorContact[]|null>(null),[search,setSearch]=useState('');
 async function save(){if(!rows||busy)return;try{const n=structuredClone(data);n.operations??=emptyOperations();const existing=n.operations.vendorContacts??=[];const keys=new Set(existing.map(v=>v.name.trim().toLowerCase()));const added=rows.filter(v=>!keys.has(v.name.trim().toLowerCase()));for(const v of added){keys.add(v.name.trim().toLowerCase());existing.push(v);}recordAudit(n,'QBO vendor contacts imported',added.length+' verified contacts; no bills or payments imported');if(await persist(n,added.length+' vendor contacts imported'))setRows(null);}catch(e){toast.error((e as Error).message);}}
 return <section className="panel" aria-label="Shared vendor contact directory"><h3>QBO vendor contacts</h3><p className="hint">Shared vendor directory for manual payments. Contacts are independent of unit service assignments. No bills, bank details or tax identifiers are imported.</p><label className="upload-button">Import prepared vendor contacts<input type="file" accept="application/json,.json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>2000000)throw Error('Vendor file exceeds 2 MB');const parsed=JSON.parse(await file.text());if(!Array.isArray(parsed)||parsed.length>10000||parsed.some(v=>!v.id||!v.name?.trim()||!v.source?.trim()||[v.company,v.phone,v.email].some(x=>typeof x!=='string'))||new Set(parsed.map(v=>v.id)).size!==parsed.length)throw Error('Invalid vendor contact file');setRows(parsed.map(v=>({id:v.id,name:v.name,company:v.company,phone:v.phone,email:v.email,source:v.source})));}catch(err){toast.error((err as Error).message);}}}/></label>{rows&&<><p>Review {rows.length} source contacts. Existing names will be skipped.</p><Grid headers={['Name','Company','Phone','Email']} rows={rows.map(v=>[v.name,v.company,v.phone,v.email])}/><button disabled={busy} onClick={save}>Save vendor contacts</button><button className="secondary" onClick={()=>setRows(null)}>Cancel import</button></>}<label className="field">Find vendor<input value={search} onChange={e=>setSearch(e.target.value)}/></label><Grid headers={['Vendor','Company','Phone','Email','Source']} rows={(data.operations?.vendorContacts??[]).filter(v=>(v.name+' '+v.company).toLowerCase().includes(search.toLowerCase())).map(v=>[<button className="text-button" onClick={()=>setSelected(v.id)} aria-label={'Open vendor contact '+v.name}>{v.name}</button>,v.company||'Not provided',v.phone||'Not provided',v.email||'Not provided',v.source])}/><Dialog open={!!contact} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{contact?.name} · Vendor information</DialogTitle><DialogDescription>Saved shared vendor contact</DialogDescription></DialogHeader>{contact&&<dl className="input-grid">{[['Company',contact.company],['Phone',contact.phone],['Email',contact.email],['Source',contact.source]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not provided'}</dd></div>)}</dl>}</DialogContent></Dialog></section>;
}
