'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ChartNoAxesColumnIncreasing,House,KeyRound,Users, Wrench,Percent,Newspaper,Search} from 'lucide-react';
import {marketSeries,type MarketObservation} from '@/lib/public-market';
import './welcome.css';
export default function Welcome(){
 const [market,setMarket]=useState<{retrievedAt:string;observations:MarketObservation[]}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[query,setQuery]=useState(''),[intent,setIntent]=useState('rent');
 async function refresh(){setLoading(true);setError(false);try{const r=await fetch('/api/public-market',{cache:'no-store'});if(!r.ok)throw Error();setMarket(await r.json());}catch{setError(true);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 const services=[{name:'Leasing',description:'Find your next home with personal support.',icon:KeyRound},{name:'Property management',description:'Thoughtful care for properties and investments.',icon:House},{name:'Owners & residents',description:'Your records, statements and services in one place.',icon:Users},{name:'Maintenance',description:'Connected requests, repairs and property care.',icon:Wrench}];
 return <div className="og-welcome"><a className="welcome-skip" href="#welcome-main">Skip to content</a><header className="welcome-header"><a href="/" className="welcome-brand" aria-label="Opervix home">OPERVIX<span>GROUP</span></a><nav aria-label="Public navigation"><a href="#discover">Discover properties</a><a href="#services">Our services</a><a href="#market">Market & housing</a><a href="#contact">Contact</a></nav><a href="/login" className="welcome-primary"><Users size={16}/> Sign in</a></header>
 <main id="welcome-main"><section className="welcome-hero" id="discover"><div className="welcome-hero-inner"><span className="welcome-eyebrow">A CONNECTED REAL ESTATE EXPERIENCE</span><h1>Exceptional homes.<br/>Connected living.</h1><p>Discover properties and a smarter real estate experience.</p><form className="welcome-search" onSubmit={e=>{e.preventDefault();document.getElementById('property-enquiry')?.scrollIntoView({behavior:'smooth'});}}><Search size={22}/><input aria-label="City, neighborhood or property" placeholder="City, neighborhood or property" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Buy or rent" value={intent} onChange={e=>setIntent(e.target.value)}><option value="rent">For rent</option><option value="buy">For sale</option></select><button type="submit">Explore</button></form><a href="#services" className="welcome-hero-link">Explore our services <ArrowUpRight size={17}/></a></div><p className="welcome-hero-caption">Extraordinary places.<br/>A more connected tomorrow.</p></section>
 <div className="welcome-content"><section className="welcome-discover" id="property-enquiry"><div><span className="welcome-eyebrow">YOUR NEXT ADDRESS</span><h2>Find a place to call home.</h2><p>{query?`Interested in ${intent==='buy'?'buying':'renting'} in ${query}?`:'Discover leasing opportunities and personal property guidance.'} Contact our team for verified availability and details.</p></div><a className="welcome-primary" href={`mailto:mmartinez@devonshirecondos.com?subject=${encodeURIComponent('Property enquiry: '+(intent==='buy'?'Buy':'Rent')+(query?' in '+query:''))}`}>Enquire about properties <ArrowUpRight size={18}/></a></section>
 <section id="market" aria-labelledby="market-title"><div className="welcome-section-title"><div><span className="welcome-eyebrow">KNOW YOUR MARKET</span><h2 id="market-title">Market & housing</h2><p>Source-linked insights for a more informed tomorrow.</p></div><button className="welcome-secondary" disabled={loading} onClick={()=>void refresh()}>{loading?'Updating…':'Refresh data'}</button></div><div className="welcome-market-grid">{marketSeries.map((s,i)=>{const o=market?.observations.find(v=>v.id===s.id),Icon=[ChartNoAxesColumnIncreasing,Percent,House][i];return <article className="welcome-market-card" key={s.id}><Icon size={29}/><h3>{s.title}</h3><p>{s.label}</p><strong>{o?.value!=null?(s.unit==='percent'?o.value.toFixed(2)+'%':o.value.toLocaleString('en-US',{maximumFractionDigits:2})):(loading?'Loading…':'Unavailable')}</strong><span className="welcome-frequency">{s.frequency}</span>{o?.change!=null&&<span>Previous observation: {o.change>=0?'+':''}{o.change.toFixed(2)} {s.unit==='percent'?'percentage points':'points'}</span>}<p className="welcome-source">{s.source}<br/>{o?.date?`Observation: ${o.date}`:'Source temporarily unavailable'}{o?.status==='stale'?' · Older observation':''}</p><a href={`https://fred.stlouisfed.org/series/${s.id}`} target="_blank" rel="noopener noreferrer">View source & history <ArrowUpRight size={15}/></a></article>;})}<article className="welcome-market-card"><Newspaper size={29}/><h3>Real estate news</h3><p>Housing research and industry updates from original sources.</p><a href="https://www.nar.realtor/press-releases" target="_blank" rel="noopener noreferrer">NAR housing news <ArrowUpRight size={15}/></a><a href="https://www.freddiemac.com/research" target="_blank" rel="noopener noreferrer">Freddie Mac research <ArrowUpRight size={15}/></a><a href="https://trerc.tamu.edu/" target="_blank" rel="noopener noreferrer">Texas housing research <ArrowUpRight size={15}/></a><p className="welcome-source">Open the publisher for current stories and publication dates.</p></article></div><p className="welcome-data-note" role="status">{error?'Refresh failed. Open the source links for current data. ':''}{market?`Retrieved ${new Date(market.retrievedAt).toLocaleString('en-US')}. `:''}Stock figures are daily closing observations, not live quotes. Mortgage figures are national averages; the housing index is not a listing price.</p></section>
 <section id="services"><div className="welcome-section-title"><div><span className="welcome-eyebrow">PERSONAL SERVICE. CONNECTED TOOLS.</span><h2>Our services</h2></div></div><div className="welcome-service-grid">{services.map(s=><a href="/login" className="welcome-service" key={s.name}><s.icon size={30}/><div><h3>{s.name}</h3><p>{s.description}</p></div><ArrowUpRight size={18}/></a>)}</div></section></div></main><footer id="contact" className="welcome-footer"><div><span className="welcome-brand">OPERVIX GROUP</span><p>Real people. Real properties. A brighter tomorrow.</p></div><a href="mailto:mmartinez@devonshirecondos.com">Contact Devonshire Leasing</a><a href="/login">Secure workspace <ArrowUpRight size={15}/></a><small>© {new Date().getFullYear()} Opervix Group · Architectural imagery is illustrative.</small></footer></div>;
}
