'use client';
import {useEffect,useRef,useState} from 'react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Bot,Search,Send,BookOpen,ArrowRight,CheckCircle2} from 'lucide-react';
import {workflowGuides,searchWorkflowGuides,type WorkflowGuide} from '@/lib/workflow-guide';
import LiveSupport from './live-support';
import {quickQuestions} from '@/lib/assistant-guide';
type Message={id:number;role:'assistant'|'user';text:string;guideIds?:string[];sources?:string[];checkedAt?:string;mode?:string};
type Props={tab:string;period:string;scoped?:boolean;navigate:(id:string,page?:string)=>void|boolean};
export default function WorkflowHelp({tab,period,navigate,scoped=false}:Props){
 const [open,setOpen]=useState(false),[mode,setMode]=useState<'Chat'|'Knowledge base'|'Walkthrough'>('Chat'),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[suggestions,setSuggestions]=useState<string[]>([]),[thinking,setThinking]=useState(false),[unitNumber,setUnitNumber]=useState(''),[step,setStep]=useState(0),[done,setDone]=useState<number[]>([]);
 const end=useRef<HTMLDivElement>(null),guide=workflowGuides.find(g=>g.id===(selected||tab))??workflowGuides[0],results=searchWorkflowGuides(query);
 useEffect(()=>{if(open&&mode==='Chat')end.current?.scrollIntoView({block:'nearest'});},[messages.length,open,mode]);
 useEffect(()=>{setUnitNumber('');setSelected('');setStep(0);setDone([]);},[tab,period]);
 function start(){if(!messages.length)setMessages([{id:0,role:'assistant',text:'Welcome. I can help you find the right page, follow a process or check your authorized saved records. Choose Chat, Knowledge base or Walkthrough.'}]);setSuggestions(quickQuestions[tab]??['Walk me through this page','What needs review this month?']);setOpen(true);}
 function openGuide(g:WorkflowGuide){if(navigate(g.target??g.id,scoped?undefined:g.page)!==false)setOpen(false);}
 function walk(id:string){setSelected(id);setStep(0);setDone([]);setMode('Walkthrough');}
 async function ask(text:string){const value=text.trim().slice(0,1000);if(!value||thinking)return;setThinking(true);setQuestion('');setMessages(m=>[...m,{id:Date.now(),role:'user',text:value}]);try{const response=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:value,context:selected||tab,period,...(unitNumber?{unitNumber}:{})})}),answer=await response.json();if(!response.ok)throw Error(answer.error);setMessages(m=>[...m,{id:Date.now()+1,role:'assistant',text:answer.text,guideIds:answer.guideIds,sources:answer.sources,checkedAt:answer.checkedAt,mode:answer.mode}]);setSuggestions(answer.questions??[]);setUnitNumber(answer.unitNumber??'');}catch(e){setMessages(m=>[...m,{id:Date.now()+1,role:'assistant',text:'I could not check saved records: '+(e as Error).message+'. You can still browse the knowledge base. No changes were made.'}]);setQuestion(value);}finally{setThinking(false);}}
 function reset(){setMessages([]);setUnitNumber('');setSuggestions(quickQuestions[tab]??[]);setQuestion('');setSelected('');setMode('Chat');}
 return <><button className="help-launcher" onClick={start} aria-label="Open AI Assistant"><Bot size={19}/> AI Assistant</button><Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="workflow-help"><SheetHeader><SheetTitle><Bot size={20}/> OG Assistant</SheetTitle><SheetDescription>Your workflow companion · {period}</SheetDescription></SheetHeader><nav className="people-tabs" aria-label="Assistant modes">{(['Chat','Knowledge base','Walkthrough'] as const).map(m=><button key={m} className={mode===m?'selected':''} aria-current={mode===m?'page':undefined} onClick={()=>setMode(m)}>{m}</button>)}</nav><div className="help-scroll">
 {mode==='Chat'&&<><p className="hint">Company-scoped saved records + verified OG procedures</p><div className="assistant-conversation" role="log" aria-label="Assistant conversation" aria-live="polite">{messages.map(m=><div key={m.id} className={'assistant-message '+m.role}><strong>{m.role==='user'?'You':'OG Assistant'}</strong><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p>{m.sources&&<p className="hint">{m.mode} · {m.sources.join('; ')}{m.checkedAt?' · Checked '+new Date(m.checkedAt).toLocaleString('en-US',{timeZone:'America/Chicago'}):''}</p>}{m.guideIds?.map(id=>{const g=workflowGuides.find(g=>g.id===id);return g?<div className="assistant-actions" key={id}><button className="secondary" onClick={()=>openGuide(g)}>Open {scoped?'my workspace':g.page??g.title}<ArrowRight size={14}/></button><button className="text-button" onClick={()=>walk(id)}>Guide me step by step</button></div>:null;})}</div>)}<div ref={end}/>{thinking&&<p role="status">Checking your saved records…</p>}</div><div className="assistant-suggestions">{suggestions.map(q=><button className="secondary" key={q} disabled={thinking} onClick={()=>{void ask(q);}}>{q}</button>)}</div><form className="assistant-question" onSubmit={e=>{e.preventDefault();void ask(question);}}><label htmlFor="assistant-question">Ask about a page, unit or next step</label><div><input id="assistant-question" maxLength={1000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="How do I add a credit card?"/><button type="submit" disabled={thinking||!question.trim()} aria-label="Ask assistant"><Send size={18}/></button></div></form><button className="text-button" onClick={reset} disabled={thinking}>Start new conversation</button></>}
 {mode==='Knowledge base'&&<><p className="eyebrow">CONNECTED WORKFLOWS · {workflowGuides.length} GUIDES</p><h2>Find your next step</h2><label className="field">Search pages & features<div className="help-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Banks, leases, reports, insurance…"/></div></label>{results.length?results.map(g=><section className="panel" key={g.id}><p className="eyebrow">{g.availability??'Workflow guide'}</p><h3>{g.title}</h3><p className="hint">{g.location}</p><p>{g.purpose}</p><div className="toolbar"><button className="secondary" onClick={()=>walk(g.id)}><BookOpen size={15}/> Guide me</button><button className="text-button" onClick={()=>openGuide(g)}>Open page <ArrowRight size={15}/></button></div></section>):<p>No verified guide matches. Try the page name or another feature.</p>}</>}
 {mode==='Walkthrough'&&<section className="panel"><p className="eyebrow">{guide.location}</p><h2>{guide.title}</h2><p>{guide.purpose}</p><p className="hint">{guide.availability??'Workflow guide'} · Step {step+1} of {guide.steps.length}</p><progress aria-label="Personal walkthrough progress" max={guide.steps.length} value={done.length} style={{width:'100%'}}/><h3>Your next action</h3><p>{guide.steps[step]}</p><label className="field"><span><input type="checkbox" checked={done.includes(step)} onChange={e=>setDone(v=>e.target.checked?[...v.filter(i=>i!==step),step]:v.filter(i=>i!==step))}/> I reviewed this step</span></label><div className="toolbar"><button className="secondary" disabled={step===0} onClick={()=>setStep(step-1)}>Previous</button><button disabled={step===guide.steps.length-1} onClick={()=>setStep(step+1)}>Next step <ArrowRight size={15}/></button><button className="secondary" onClick={()=>openGuide(guide)}>Open {scoped?'my workspace':guide.page??guide.title}</button></div>{done.length===guide.steps.length&&<p><CheckCircle2 size={16}/> Your personal checklist is reviewed.</p>}<p className="hint">This checklist does not save, approve, post, pay or certify completion in OG.</p><div className="help-note">{guide.note}</div><h3>Related guides</h3>{guide.links.map(id=>{const g=workflowGuides.find(g=>g.id===id);return g?<button key={id} className="secondary" onClick={()=>walk(id)}>{g.title}</button>:null;})}<button className="text-button" onClick={()=>{setMode('Chat');setSuggestions(['Walk me through '+guide.title,'What needs review this month?']);}}>Ask about this workflow</button></section>}
 <details><summary>Contact support</summary><LiveSupport context={tab}/></details><p className="help-footer">Guidance and record answers respect your role and property access. Procedures describe implemented controls; connection requirements and planned modules are labeled. Conversations and checklists stay in this browser session. This assistant uses built-in guidance, not an external generative AI service. Live QBO/bank balances are not queried. Opening a page never changes records.</p></div></SheetContent></Sheet></>;
}
