import type {StaffRole} from './staff-users';
import type {Data} from './pool';
export type Member={auth_id:string;workspace_id:string;name:string;email:string;phone:string;role:StaffRole;property_ids:string[];status:'Active'|'Disabled';must_change_password:boolean;created:string;updated:string};
export const managers=(role:StaffRole)=>role==='Global Admin'||role==='Management';
export const reviewers=(role:StaffRole)=>role==='External CPA'||role==='Accountant';
export function canManage(actor:Member,target:Pick<Member,'auth_id'|'role'>,nextRole:StaffRole){return managers(actor.role)&&(actor.role==='Global Admin'||target.role!=='Global Admin'&&nextRole!=='Global Admin')&&actor.auth_id!==target.auth_id;}
export function scopedUnits(member:Member,data:Data){return data.units.filter(u=>member.property_ids.includes(u.propertyId));}
export function scopedPortal(member:Member,data:Data){const units=scopedUnits(member,data),ids=new Set(units.map(u=>u.id)),tenants=(data.operations?.tenants??[]).filter(t=>ids.has(t.unitId));if(member.role==='Maintenance')return {properties:data.properties.filter(p=>member.property_ids.includes(p.id)).map(p=>({id:p.id,name:p.name})),units:units.map(u=>({id:u.id,number:u.number,propertyId:u.propertyId})),workOrders:(data.operations?.workOrders??[]).filter(w=>ids.has(w.unitId)),tenants:tenants.map(t=>({id:t.id,unitId:t.unitId,firstName:t.firstName,lastName:t.lastName,start:t.start,end:t.end,pets:t.pets,unitKeyNumber:t.unitKeyNumber,mailKeyNumber:t.mailKeyNumber,specialInstructions:t.specialInstructions})),parts:(data.procurement?.parts??[]).map(p=>({id:p.id,sku:p.sku,name:p.name,measure:p.measure,listPrice:p.listPrice,active:p.active}))};const tenantIds=new Set(tenants.map(t=>t.id));return {properties:data.properties.filter(p=>member.property_ids.includes(p.id)).map(p=>({id:p.id,name:p.name})),units:units.map(u=>({id:u.id,number:u.number,propertyId:u.propertyId})),tenants,entries:(data.operations?.tenantEntries??[]).filter(e=>tenantIds.has(e.tenantId)),statements:data.statements.filter(s=>ids.has(s.unitId)),applications:(data.accounting?.applications??[]).filter(a=>{const r=data.operations?.tenantEntries?.find(e=>e.id===a.receiptId);return !!r&&tenantIds.has(r.tenantId);})};}
export function documentAllowed(member:Member,data:Data,statementId:string){if(managers(member.role)||reviewers(member.role))return true;const ids=new Set(scopedUnits(member,data).map(u=>u.id));if(member.role==='Accounting Clerk'&&data.statements.some(s=>s.id===statementId&&ids.has(s.unitId)))return true;if(statementId.startsWith('work:'))return !!data.operations?.workOrders.some(w=>w.id===statementId.slice(5)&&ids.has(w.unitId));return false;}
