import type {Data} from './pool';
import {canonicalRecord} from './workflow-controls';
import {native,bookChart,statementMovements,validateNativeAccounting,type LedgerLine} from './native-accounting';
type Actor={id:string;reviewer:string;created:string};
export const RECEIPT_TYPES=['Owner contribution','Other income','Vendor refund','Security deposit'] as const;
export type GeneralReceipt=Actor&{bookId:string;date:string;reference:string;source:string;kind:typeof RECEIPT_TYPES[number];partyId:string;payer:string;unitId:string;cents:number;cashKey:string;counterKey:string;ledgerEntryId:string};
export type DepositGroup=Actor&{bookId:string;date:string;reference:string;source:string;bankKey:string;clearingKey:string;feeKey:string;fee:number;receiptEntryIds:string[];ledgerEntryId:string};
export type BankReview=Actor&{reviewId:string;version:number;bookId:string;accountKey:string;date:string;reference:string;externalId:string;source:string;description:string;cents:number;status:'Pending'|'Matched'|'Excluded';entryIds:string[];reason:string};
export type BankWorkflow={receipts:GeneralReceipt[];deposits:DepositGroup[];reviews:BankReview[]};
export const bankWorkflow=(d:Data):BankWorkflow=>d.accounting?.bankWorkflow??{receipts:[],deposits:[],reviews:[]};
export const undepositedAccount=(a:{type:string;name:string;detail?:string})=>['other current asset','other current assets'].includes(a.type.toLowerCase())&&/undeposited/i.test(a.name+' '+(a.detail??''));
const exact=(n:number)=>Number.isSafeInteger(n)&&n>=0&&n<=100000000000;
const text=(v:unknown,max=2000):v is string=>typeof v==='string'&&!!v.trim()&&v.length<=max;
const date=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const movement=(e:{lines:LedgerLine[]},key:string)=>e.lines.filter(l=>l.accountKey===key).reduce((s,l)=>s+l.debit-l.credit,0);
const line=(key:string,debit:number,credit:number,unitId=''):LedgerLine=>({accountKey:key,debit,credit,unitId,memo:''});
export function availableDepositReceipts(d:Data,bookId:string,clearingKey:string){
 const used=new Set(bankWorkflow(d).deposits.filter(g=>g.bookId===bookId).flatMap(g=>g.receiptEntryIds));
 const permitted=new Set([...bankWorkflow(d).receipts.filter(r=>r.bookId===bookId&&r.cashKey===clearingKey).map(r=>r.ledgerEntryId),...(d.accounting?.tenantLedgerLinks??[]).filter(l=>l.bookId===bookId&&l.source.kind==='Receipt'&&l.counterKey===clearingKey).map(l=>l.ledgerEntryId)]);
 return native(d).entries.filter(e=>e.bookId===bookId&&permitted.has(e.id)&&!used.has(e.id)&&movement(e,clearingKey)>0&&!native(d).entries.some(r=>r.reverses===e.id));
}
function receiptLines(r:GeneralReceipt){return [line(r.cashKey,r.cents,0,r.unitId),line(r.counterKey,0,r.cents,r.unitId)];}
function groupLines(d:Data,g:DepositGroup){const gross=g.receiptEntryIds.reduce((s,id)=>s+movement(native(d).entries.find(e=>e.id===id)!,g.clearingKey),0);return [line(g.bankKey,gross-g.fee,0),...(g.fee?[line(g.feeKey,g.fee,0)]:[]),line(g.clearingKey,0,gross)];}
export function postGeneralReceipt(d:Data,input:Omit<GeneralReceipt,'id'|'created'|'ledgerEntryId'>){
 const next=structuredClone(d);if(!next.accounting?.native)throw Error('Initialize verified company books first');const id=crypto.randomUUID(),actor={id,reviewer:input.reviewer,created:new Date().toISOString()},receipt={...input,...actor,ledgerEntryId:crypto.randomUUID()};
 (next.accounting.bankWorkflow??={receipts:[],deposits:[],reviews:[]}).receipts.push(receipt);next.accounting.native.entries.push({...actor,id:receipt.ledgerEntryId,bookId:input.bookId,date:input.date,reference:input.reference,memo:input.kind+' · '+input.payer+' · '+input.source,lines:receiptLines(receipt),reverses:'',recurringId:'',sourceSystem:'OG general receipt',externalId:id});validateBankWorkflow(next,d);validateNativeAccounting(next,d);return next;
}
export function postDepositGroup(d:Data,input:Omit<DepositGroup,'id'|'created'|'ledgerEntryId'>){
 const next=structuredClone(d);if(!next.accounting?.native)throw Error('Initialize verified company books first');const actor={id:crypto.randomUUID(),reviewer:input.reviewer,created:new Date().toISOString()},group={...input,...actor,ledgerEntryId:crypto.randomUUID()};
 const available=new Set(availableDepositReceipts(d,input.bookId,input.clearingKey).map(e=>e.id));if(!input.receiptEntryIds.length||input.receiptEntryIds.some(id=>!available.has(id)))throw Error('Select ungrouped, unreversed receipts in the same company clearing account');
 (next.accounting.bankWorkflow??={receipts:[],deposits:[],reviews:[]}).deposits.push(group);next.accounting.native.entries.push({...actor,id:group.ledgerEntryId,bookId:input.bookId,date:input.date,reference:input.reference,memo:'Grouped deposit · '+input.source,lines:groupLines(next,group),reverses:'',recurringId:'',sourceSystem:'OG grouped deposit',externalId:group.id});validateBankWorkflow(next,d);validateNativeAccounting(next,d);return next;
}
export function validateBankWorkflow(d:Data,old?:Data){
 const w=bankWorkflow(d),p=old?bankWorkflow(old):{receipts:[],deposits:[],reviews:[]};for(const key of ['receipts','deposits','reviews'] as const){const rows=w[key];if(!Array.isArray(rows)||rows.length>20000||new Set(rows.map(r=>r.id)).size!==rows.length||canonicalRecord(rows.slice(0,p[key].length))!==canonicalRecord(p[key]))throw Error('Bank workflow history is immutable');for(const r of rows)if(!text(r.id,100)||!text(r.reviewer,200)||!Number.isFinite(Date.parse(r.created))||!native(d).books.some(b=>b.id===r.bookId)||!date(r.date)||!text(r.reference,200)||!text(r.source))throw Error('Verify bank workflow company, date, source and reviewer');}
 const receiptRefs=new Set<string>();for(const r of w.receipts){const accounts=bookChart(d,r.bookId)?.accounts??[],cash=accounts.find(a=>a.key===r.cashKey),counter=accounts.find(a=>a.key===r.counterKey),entry=native(d).entries.find(e=>e.id===r.ledgerEntryId),ref=r.bookId+'|'+r.reference.trim().toLowerCase();if(receiptRefs.has(ref))throw Error('Receipt reference already recorded');receiptRefs.add(ref);
  if(!RECEIPT_TYPES.includes(r.kind)||!exact(r.cents)||!r.cents||!text(r.payer,200)||typeof r.partyId!=='string'||typeof r.unitId!=='string'||r.unitId&&!d.units.some(u=>u.id===r.unitId)||!cash?.active||!(cash.type.toLowerCase()==='bank'||undepositedAccount(cash))||!counter?.active||r.cashKey===r.counterKey)throw Error('Verify receipt type, payer, unit and compatible company accounts');
  const type=counter.type.toLowerCase();if(r.kind==='Owner contribution'&&(!d.owners.some(o=>o.id===r.partyId)||!['equity','other current liability','other current liabilities'].includes(type))||r.kind==='Security deposit'&&(!d.operations?.tenants?.some(t=>t.id===r.partyId&&t.unitId===r.unitId)||!['other current liability','other current liabilities'].includes(type))||r.kind==='Other income'&&!['income','other income'].includes(type)||r.kind==='Vendor refund'&&!['expenses','expense','other expense','other expenses','cost of goods sold','accounts payable'].includes(type))throw Error('Owner contributions need equity / liability; deposits need tenant liability; income and refunds need appropriate income / expense / payable accounts');
  if(!entry||entry.bookId!==r.bookId||entry.date!==r.date||entry.reference!==r.reference||entry.sourceSystem!=='OG general receipt'||entry.externalId!==r.id||canonicalRecord(entry.lines)!==canonicalRecord(receiptLines(r))||entry.reverses||entry.recurringId)throw Error('Receipt must preserve its exact balanced journal and source');
  if(!p.receipts.some(x=>x.id===r.id)&&((d.closeControls?.contributions??[]).some(e=>e.reference.trim().toLowerCase()===r.reference.trim().toLowerCase())||(d.operations?.tenantEntries??[]).some(e=>e.kind==='Receipt'&&e.reference.trim().toLowerCase()===r.reference.trim().toLowerCase())||(d.accounting?.deposits??[]).some(e=>e.reference.trim().toLowerCase()===r.reference.trim().toLowerCase())||(d.accounting?.cashPlanning?.manualEntries??[]).some(e=>e.reference.trim().toLowerCase()===r.reference.trim().toLowerCase())))throw Error('Original receipt reference already exists; link it rather than reposting');
 }
 const used=new Set<string>();for(const g of w.deposits){const accounts=bookChart(d,g.bookId)?.accounts??[],bank=accounts.find(a=>a.key===g.bankKey),clearing=accounts.find(a=>a.key===g.clearingKey),fee=accounts.find(a=>a.key===g.feeKey),entry=native(d).entries.find(e=>e.id===g.ledgerEntryId);if(!bank?.active||bank.type.toLowerCase()!=='bank'||!clearing?.active||!undepositedAccount(clearing)||!exact(g.fee)||g.fee&&(!fee?.active||!['expense','expenses','other expense','other expenses'].includes(fee.type.toLowerCase()))||!Array.isArray(g.receiptEntryIds)||!g.receiptEntryIds.length||g.receiptEntryIds.length>98)throw Error('Verify bank, undeposited funds, selected receipts and fee expense account');
  for(const id of g.receiptEntryIds){const receipt=native(d).entries.find(e=>e.id===id&&e.bookId===g.bookId&&e.date<=g.date),linked=w.receipts.some(r=>r.ledgerEntryId===id&&r.cashKey===g.clearingKey)||(d.accounting?.tenantLedgerLinks??[]).some(l=>l.ledgerEntryId===id&&l.source.kind==='Receipt'&&l.counterKey===g.clearingKey);if(!receipt||!linked||used.has(id)||movement(receipt,g.clearingKey)<=0)throw Error('Deposit receipt is missing, duplicated, already grouped or outside its company / date');if(!p.deposits.some(x=>x.id===g.id)&&native(d).entries.some(e=>e.reverses===id))throw Error('Cannot deposit a reversed receipt');used.add(id);}
  if(!native(d).entries.some(e=>e.reverses===g.ledgerEntryId)&&g.receiptEntryIds.some(id=>native(d).entries.some(e=>e.reverses===id)))throw Error('Reverse the grouped deposit before reversing its receipt');
  const lines=groupLines(d,g);if(lines[0].debit<=0||!entry||entry.bookId!==g.bookId||entry.date!==g.date||entry.reference!==g.reference||entry.sourceSystem!=='OG grouped deposit'||entry.externalId!==g.id||entry.reverses||entry.recurringId||canonicalRecord(entry.lines)!==canonicalRecord(lines))throw Error('Deposit must transfer exact receipt totals less fees, without recording income twice');
 }
 const latest=new Map<string,BankReview>(),identities=new Set<string>();for(const r of w.reviews){const prior=latest.get(r.reviewId),account=bookChart(d,r.bookId)?.accounts.find(a=>a.key===r.accountKey),identity=[r.bookId,r.accountKey,r.externalId.trim().toLowerCase()].join('|');if(!text(r.reviewId,100)||!text(r.externalId,200)||!account?.active||!['bank','credit card'].includes(account.type.toLowerCase())||!Number.isSafeInteger(r.cents)||!r.cents||Math.abs(r.cents)>100000000000||typeof r.description!=='string'||r.description.length>500||typeof r.reason!=='string'||r.reason.length>2000||!['Pending','Matched','Excluded'].includes(r.status)||!Array.isArray(r.entryIds)||r.entryIds.length>100||new Set(r.entryIds).size!==r.entryIds.length||r.version!==(prior?.version??0)+1)throw Error('Invalid bank review');
  if(prior){if(prior.status==='Matched'&&native(d).reconciliations.some(c=>c.bookId===prior.bookId&&c.accountKey===prior.accountKey&&c.rows.some(row=>row.entryIds.some(id=>prior.entryIds.includes(id))))&&(r.status!==prior.status||canonicalRecord(r.entryIds)!==canonicalRecord(prior.entryIds)))throw Error('Completed reconciliation protects its bank match');if(canonicalRecord({...r,id:prior.id,created:prior.created,reviewer:prior.reviewer,version:prior.version,status:prior.status,entryIds:prior.entryIds,reason:prior.reason})!==canonicalRecord(prior))throw Error('Bank source identity and amounts are immutable');}else{if(identities.has(identity))throw Error('Bank source already imported');identities.add(identity);}
  if(r.status==='Matched'){const candidates=statementMovements(d,r.bookId,r.accountKey).filter(x=>r.entryIds.includes(x.entry.id));if(!r.entryIds.length||candidates.length!==r.entryIds.length||candidates.some(x=>x.entry.date>r.date||native(d).entries.some(e=>e.reverses===x.entry.id&&e.date<=r.date))||candidates.reduce((s,x)=>s+x.cents,0)!==r.cents)throw Error('Bank match must equal existing ledger movements in the same account and date');}else if(r.entryIds.length||r.status==='Excluded'&&!text(r.reason))throw Error('Excluded rows need a reason; pending / excluded rows cannot match ledger entries');
  latest.set(r.reviewId,r);
 }
 const matched=new Set<string>();for(const r of latest.values())if(r.status==='Matched')for(const id of r.entryIds){const key=r.accountKey+'|'+id;if(matched.has(key))throw Error('Ledger movement already matched to another bank row');matched.add(key);}
 for(const e of native(d).entries){if(e.sourceSystem==='OG general receipt'&&!w.receipts.some(r=>r.ledgerEntryId===e.id)||e.sourceSystem==='OG grouped deposit'&&!w.deposits.some(g=>g.ledgerEntryId===e.id))throw Error('Receipt / deposit journal requires its immutable source record');}
}
