import {ownerOutstanding} from './month-close';
import {type Data,latest,totals} from './pool';
export type CheckGroup={ownerId:string;owner:string;lines:{statementId:string;version:number;unit:string;cents:number}[];cents:number;gross:number;hoaCharge:number;hoaOffset:number;ownerBill:number;blocked:string};
export function prepareChecks(data:Data,period:string,selectedIds:string[],includeDrafts=false){
 const selected=new Set(selectedIds),current=latest(data,period),hoaUnit=data.units.find(u=>u.id==='unit-108'),hoa=current.find(s=>s.unitId===hoaUnit?.id),groups=new Map<string,CheckGroup>();
 const eligible=(s:typeof current[number])=>(s.status==='Approved'||includeDrafts&&s.status==='Pending')&&s.paidAmount===0&&!data.statements.some(x=>x.unitId===s.unitId&&x.period===period&&x.status==='Paid');
 for(const s of current){if(!selected.has(s.id)||!eligible(s))continue;const amount=totals(s).closing;if(amount<=0&&s.unitId!==hoaUnit?.id)continue;let g=groups.get(s.ownerId);if(!g){g={ownerId:s.ownerId,owner:(s as any).ownerSnapshot?.name??data.owners.find(o=>o.id===s.ownerId)?.name??'Unknown owner',lines:[],cents:0,gross:0,hoaCharge:0,hoaOffset:0,ownerBill:0,blocked:''};groups.set(s.ownerId,g);}if(s.unitId!==hoaUnit?.id){g.lines.push({statementId:s.id,version:s.version,unit:data.units.find(u=>u.id===s.unitId)?.number??s.unitId,cents:amount});g.gross+=amount;}}
 for(const g of groups.values()){g.cents=g.gross;if(!hoaUnit)continue;if(g.ownerId!==hoa?.ownerId)continue;if(!hoa||hoa.ownerId!==g.ownerId||!eligible(hoa)){g.blocked='Unit 108 statement must be current, approved and unpaid (or included in draft preview) before this owner’s total can be prepared.';g.cents=0;continue;}const charge=hoa.expenses.filter(e=>e.gl==='80000'&&(!e.linkedUnitId||e.linkedUnitId===hoaUnit.id)).reduce((n,e)=>n+e.cents,0);g.hoaCharge=Math.min(charge,Math.max(0,-ownerOutstanding(data,hoa)));g.hoaOffset=Math.min(g.gross,g.hoaCharge);g.ownerBill=g.hoaCharge-g.hoaOffset;g.cents=g.gross-g.hoaOffset;g.lines.push({statementId:hoa.id,version:hoa.version,unit:hoaUnit.number+' HOA',cents:-g.hoaCharge});}
 return [...groups.values()].sort((a,b)=>a.owner.localeCompare(b.owner));
}
