import {verifiedFeeBasis} from './pool-finance';
import type {Data} from './pool';
import {canonicalRecord} from './workflow-controls';
export type GLAccount={key:string;number:string;name:string;type:string;detail:string;active:boolean;qboId:string};
export type GLChart={id:string;company:string;fileName:string;hash:string;source:string;created:string;accounts:GLAccount[]};
export const GL_ROLES=['Owner pool operating','Owner escrow','DLA operating','DLA management income','DLA maintenance income','Owner management expense','Owner maintenance expense','Pool electricity expense'] as const;
export type GLRole=typeof GL_ROLES[number];
export function compatibleGLAccount(role:GLRole,account:GLAccount){const type=account.type.toLowerCase();if(!account.active)return false;if(role.includes('income'))return ['income','other income'].includes(type);if(role.includes('expense'))return ['expense','expenses','other expense','other expenses'].includes(type);return type==='bank';}
export type GLMapping={id:string;chartId:string;accountKey:string;role:GLRole;from:string;reviewer:string;source:string;created:string};
export type GLControls={charts:GLChart[];mappings:GLMapping[]};
function rows(text:string){const result:string[][]=[];let row:string[]=[],v='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(v);v='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(v);if(row.some(v=>v.trim()))result.push(row);row=[];v='';}else v+=c;}if(q)throw Error('Unclosed chart CSV quote');row.push(v);if(row.some(v=>v.trim()))result.push(row);return result;}
export function parseGL(text:string){if(text.length>2000000)throw Error('Chart file is too large');const data=rows(text.replace(/^\uFEFF/,'')),headers=(data.shift()??[]).map(v=>v.trim());const required=['Account number','Account name','Account type','Detail type','Active'];if(new Set(headers).size!==headers.length||required.some(h=>!headers.includes(h)))throw Error('Use the reviewed OG chart CSV columns: '+required.join(', '));if(!data.length||data.length>5000)throw Error('Chart requires 1–5000 accounts');const keys=new Set<string>();return data.map(row=>{const get=(key:string)=>(row[headers.indexOf(key)]??'').trim(),number=get('Account number'),name=get('Account name'),type=get('Account type'),detail=get('Detail type'),active=get('Active').toLowerCase();if(!name||!type||!['true','false'].includes(active)||row.length!==headers.length)throw Error('Invalid chart row or active state');const key=number?'number:'+number:'name:'+name;if(keys.has(key))throw Error('Duplicate chart number/name');keys.add(key);return {key,number,name,type,detail,active:active==='true',qboId:get('QBO account ID')};});}
export function mappingAccount(d:Data,role:GLRole,period:string){const m=[...(d.glControls?.mappings??[])].reverse().filter(m=>m.role===role&&m.from<=period).sort((a,b)=>b.from.localeCompare(a.from))[0];return m?{mapping:m,account:d.glControls?.charts.find(c=>c.id===m.chartId)?.accounts.find(a=>a.key===m.accountKey)}:undefined;}
export function validateMapping(d:Data,m:GLMapping){const chart=d.glControls?.charts.find(c=>c.id===m.chartId),account=chart?.accounts.find(a=>a.key===m.accountKey);if(!GL_ROLES.includes(m.role)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(m.from)||!m.reviewer.trim()||!m.source.trim()||!account?.active)throw Error('Map an active source account with effective month, source and reviewer');const latest=d.glControls?.charts.filter(c=>c.company===chart?.company).at(-1);if(latest?.id!==chart?.id)throw Error('Select the latest reviewed company chart');const type=account.type.toLowerCase();if(m.role.includes('income')&&!['income','other income'].includes(type))throw Error('DLA income must map to an income account, not an owner expense');if(m.role.includes('expense')&&!['expenses','expense','other expense','other expenses'].includes(type))throw Error('Owner deductions require expense accounts');if(['Owner pool operating','Owner escrow','DLA operating'].includes(m.role)&&type!=='bank')throw Error('Bank role requires a Bank account');}
export function validateGL(old:Data,next:Data){const previous=old.glControls??{charts:[],mappings:[]},controls=next.glControls??{charts:[],mappings:[]};for(const kind of ['charts','mappings'] as const){if(controls[kind].length>10000||new Set(controls[kind].map(r=>r.id)).size!==controls[kind].length)throw Error('Invalid GL history');for(const r of previous[kind])if(!controls[kind].some(n=>n.id===r.id&&canonicalRecord(n)===canonicalRecord(r)))throw Error('GL source and mapping history must be preserved');}for(const c of controls.charts.filter(c=>!previous.charts.some(p=>p.id===c.id))){if(!c.company.trim()||!c.fileName.trim()||! /^[a-f0-9]{64}$/.test(c.hash)||canonicalRecord(parseGL(c.source))!==canonicalRecord(c.accounts))throw Error('Chart source does not match saved accounts');if(previous.charts.some(p=>p.hash===c.hash&&p.company===c.company))throw Error('Chart file already imported');}for(const m of controls.mappings.filter(m=>!previous.mappings.some(p=>p.id===m.id)))validateMapping(next,m);for(const month of new Set(controls.mappings.map(m=>m.from))){const banks=['Owner pool operating','Owner escrow','DLA operating'].map(role=>mappingAccount(next,role as GLRole,month)?.account).filter(Boolean);if(new Set(banks.map(a=>a!.qboId||a!.key)).size!==banks.length)throw Error('Owner operating, escrow and DLA operating must use distinct bank accounts');}
 for(const b of (next.accounting?.exports??[]).filter(b=>!old.accounting?.exports.some(o=>o.id===b.id)))for(const id of b.sourceIds){const c=[...(next.accounting?.classifications??[])].reverse().find(c=>c.sourceId===id);if(!c)throw Error('Export requires a confirmed account classification');verifiedGL(next,c.gl,c.accountName);}
 const chart=controls.charts.at(-1);for(const c of (next.accounting?.classifications??[]).filter(c=>!old.accounting?.classifications.some(p=>p.id===c.id))){if(!chart)throw Error('Review the QBO chart before confirming new classifications');const a=chart.accounts.find(a=>a.active&&(a.number||a.qboId||a.key)===c.gl&&a.name===c.accountName);if(!a)throw Error('Select an active account with exact number and full name from the saved QBO chart');if(c.treatment==='Agency income'&&!['income','other income'].includes(a.type.toLowerCase()))throw Error('Agency income requires an income GL account');if(c.treatment==='Agency income'&&c.sourceKind==='Owner charge'){const st=next.statements.find(s=>s.expenses.some(e=>e.id===c.sourceId)),line=st?.expenses.find(e=>e.id===c.sourceId);if(st&&['80300','80400'].includes(line?.gl??'')&&!verifiedFeeBasis(next,st.period,c.sourceId))throw Error('Confirm the effective fee agreement and calculated amount before recording DLA fee income');}}
}

export function verifiedGL(d:Data,number:string,name:string){const chart=d.glControls?.charts.at(-1);if(!chart)throw Error('Import and review the QBO chart before preparing new exports');const a=chart.accounts.find(a=>a.active&&(a.number||a.qboId||a.key)===number&&a.name===name);if(!a)throw Error('Export account must match an active account in the latest reviewed QBO chart');return a;}
