import type {Data} from './pool';
import {canonicalRecord} from './workflow-controls';
import {emptyProcurement} from './procurement-model';
export type InvoiceSourceRow={sourceId:string;unit:string;qboClass:string;kind:'Labor'|'Materials'|'Stock'|'Operating';vendor:string;reference:string;date:string;description:string;cents:number;gl:string;accountName:string;paymentState:'Paid'|'Unpaid'|'Unknown';paymentMonth:string;notes:string;source:string;quantity?:number;stockName?:string;sku?:string};
export type InvoiceBatch={id:string;period:string;fileName:string;hash:string;reviewer:string;created:string;rows:(InvoiceSourceRow&{recordId:string;statementId:string;status:'Posted'|'Held'})[]};
export type InvoiceLink={id:string;sourceId:string;recordId:string;statementId:string;reviewer:string;created:string};
export type InvoiceStockCorrection={id:string;sourceId:string;statementId:string;expenseId:string;purchaseId:string;partId:string;cents:number;reason:string;reviewer:string;created:string};
export function applyReviewedTaskNotes(d:Data,period:string,reviewer:string){
 if(!reviewer.trim())throw Error('Reviewer required');let count=0;
 for(const s of d.statements.filter(s=>s.period===period&&s.status==='Pending'&&!d.statements.some(x=>x.period===period&&x.unitId===s.unitId&&x.version>s.version))){
 const rows=d.invoiceImports?.flatMap(b=>b.rows).filter(r=>r.statementId===s.id&&['Labor','Materials'].includes(r.kind)&&s.expenses.some(e=>e.id===r.recordId))??[];
 const tasks=rows.map(r=>r.kind+': '+r.description+'. Reference '+r.reference+'.');
 if(!rows.length)tasks.push('No imported labor or materials charges recorded for this statement.');
 const marker='Work performed and supporting receipts:';
 const existing=(s.ownerNotes??'').split(marker)[0].trim();
 s.ownerNotes=[existing,marker,...tasks].filter(Boolean).join('\n');count++;
 }
 d.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),action:'Reviewed task descriptions added to owner statements',detail:period+' / '+count+' drafts / '+reviewer.trim()+' / reviewed English source descriptions only'});return count;
}
export function moveImportedMaterialsToStock(d:Data,sourceId:string,reviewer:string,reason:string){
 const row=d.invoiceImports?.flatMap(b=>b.rows).find(r=>r.sourceId===sourceId),s=d.statements.find(s=>s.id===row?.statementId);
 if(!row||row.kind!=='Materials'||row.status!=='Posted'||!s||s.status!=='Pending'||d.statements.some(x=>x.unitId===s.unitId&&x.period===s.period&&x.version>s.version))throw Error('Choose an imported materials charge on the latest draft statement');
 if(!reviewer.trim()||!reason.trim())throw Error('Reviewer and correction reason required');
 if(d.invoiceStockCorrections?.some(c=>c.sourceId===sourceId))throw Error('Receipt already moved to inventory');
 const expense=s.expenses.find(e=>e.id===row.recordId);if(!expense||expense.cents!==row.cents)throw Error('Source amount changed');
 const p=d.procurement??=emptyProcurement(),partId=crypto.randomUUID(),purchaseId=crypto.randomUUID(),created=new Date().toISOString();
 p.parts.push({id:partId,sku:'RECEIPT-'+row.reference,name:'Small tools and equipment · '+row.reference,measure:'receipt lot',listPrice:0,priceConfirmed:false,reorderAt:0,active:true});
 p.purchases.push({id:purchaseId,partId,date:row.date,quantity:1,totalCost:row.cents,supplier:row.vendor,reference:row.reference,notes:'Reclassified receipt lot; not an item count. No owner charge. Original source: '+row.source+'. '+reason.trim(),created});
 s.expenses=s.expenses.filter(e=>e.id!==expense.id);
 (d.invoiceStockCorrections??=[]).push({id:crypto.randomUUID(),sourceId,statementId:s.id,expenseId:expense.id,purchaseId,partId,cents:row.cents,reason:reason.trim(),reviewer:reviewer.trim(),created});
 d.audit.unshift({id:crypto.randomUUID(),at:created,action:'Imported unit charge moved to inventory',detail:row.unit+' / '+row.reference+' / '+row.cents+' cents / '+reviewer.trim()+' / '+reason.trim()});
}
const periodOK=(v:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(v);
export function checkInvoiceRows(rows:InvoiceSourceRow[],period:string){
 if(!periodOK(period)||!Array.isArray(rows)||!rows.length||rows.length>1000)throw Error('Choose a valid month and 1–1000 invoice rows');
 const keys=new Set<string>();for(const r of rows){if(!r.sourceId?.trim()||keys.has(r.sourceId)||!r.vendor?.trim()||!r.description?.trim()||!r.source?.trim()||!r.accountName?.trim()||!/^\d+$/.test(r.gl)||!['Labor','Materials','Stock','Operating'].includes(r.kind)||!['Paid','Unpaid','Unknown'].includes(r.paymentState)||!Number.isSafeInteger(r.cents)||r.cents<=0||r.cents>100000000000||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||new Date(r.date+'T12:00:00Z').toISOString().slice(0,10)!==r.date||r.date.slice(0,7)!==period||r.paymentMonth&&!periodOK(r.paymentMonth))throw Error('Invalid invoice source row '+r.sourceId);keys.add(r.sourceId);if(['Labor','Materials'].includes(r.kind)&&!r.unit.trim())throw Error('Unit required for labor/materials');if(r.kind==='Stock'&&(r.unit||!r.stockName?.trim()||!r.sku?.trim()||!Number.isSafeInteger(r.quantity)||r.quantity!<=0||!r.reference.trim()))throw Error('Stock needs its own name, SKU, whole quantity and invoice reference');if(r.kind==='Operating'&&r.unit)throw Error('Operating costs must not be charged to a unit');}
}
export function postInvoiceBatch(d:Data,input:{period:string;fileName:string;hash:string;reviewer:string;rows:InvoiceSourceRow[]}){
 checkInvoiceRows(input.rows,input.period);if(!input.fileName.trim()||!input.reviewer.trim()||!input.hash.trim())throw Error('Source file, checksum and reviewer required');
 const history=d.invoiceImports??[];if(history.some(b=>b.hash===input.hash))throw Error('This source file is already recorded');
 const existing=history.flatMap(b=>b.rows);for(const r of input.rows)if(existing.some(e=>e.sourceId===r.sourceId||r.reference&&e.vendor.toLowerCase()===r.vendor.toLowerCase()&&e.reference===r.reference&&e.unit===r.unit&&e.cents===r.cents))throw Error('Invoice already recorded: '+r.reference);
 const latest=(unitId:string)=>d.statements.filter(s=>s.unitId===unitId&&s.period===input.period).sort((a,b)=>b.version-a.version)[0];
 for(const r of input.rows.filter(r=>['Labor','Materials'].includes(r.kind))){const units=d.units.filter(u=>u.number===r.unit);if(units.length>1)throw Error('Ambiguous property for unit '+r.unit);if(units.length){const s=latest(units[0].id);if(!s||s.status!=='Pending')throw Error('Latest draft statement required for unit '+r.unit);if(s.expenses.some(e=>e.cents===r.cents&&e.recipient.toLowerCase()===r.vendor.toLowerCase()&&r.reference&&e.label.includes(r.reference)))throw Error('Possible existing unit charge: '+r.unit+' / '+r.reference);}}
 const created=new Date().toISOString(),batch:InvoiceBatch={id:crypto.randomUUID(),period:input.period,fileName:input.fileName,hash:input.hash,reviewer:input.reviewer,created,rows:[]};
 for(const r of input.rows){let recordId='',statementId='',status:'Posted'|'Held'='Posted';if(['Labor','Materials'].includes(r.kind)){const u=d.units.find(u=>u.number===r.unit),s=u?latest(u.id):undefined;if(!s)status='Held';else{recordId=crypto.randomUUID();statementId=s.id;s.expenses.push({id:recordId,label:r.kind+' · '+r.description+(r.reference?' · '+r.reference:''),cents:r.cents,recipient:r.vendor,classification:r.kind==='Labor'?'Unit repair labor':'Unit repair materials',gl:r.gl});}}
  else if(r.kind==='Stock'){const p=d.procurement??=emptyProcurement();if(p.purchases.some(p=>p.supplier===r.vendor&&p.reference===r.reference))throw Error('Stock invoice already received');let part=p.parts.find(p=>p.sku===r.sku);if(!part){part={id:crypto.randomUUID(),sku:r.sku!,name:r.stockName!,measure:'each',listPrice:0,priceConfirmed:false,reorderAt:0,active:true};p.parts.push(part);}recordId=crypto.randomUUID();p.purchases.push({id:recordId,partId:part.id,date:r.date,quantity:r.quantity!,totalCost:r.cents,supplier:r.vendor,reference:r.reference,notes:'Already recorded in QBO. GL '+r.gl+' '+r.accountName+'. '+r.notes+' Physical count and owner charge price require review.',created});}
  else recordId=crypto.randomUUID();batch.rows.push({...r,recordId,statementId,status});
 }
 (d.invoiceImports??=[]).push(batch);d.audit.unshift({id:crypto.randomUUID(),at:created,action:'Reviewed invoice source imported',detail:input.fileName+' / '+input.rows.length+' rows / '+input.reviewer+' / owner month '+input.period+' / no bank payment or QBO posting'});return batch;
}
export function validateInvoiceImports(old:Data,next:Data){
 const corrections=next.invoiceStockCorrections??[],oldCorrections=old.invoiceStockCorrections??[];
 if(canonicalRecord(corrections.slice(0,oldCorrections.length))!==canonicalRecord(oldCorrections)||new Set(corrections.map(c=>c.sourceId)).size!==corrections.length)throw Error('Inventory reclassification history is immutable');
 for(const c of corrections){const r=next.invoiceImports?.flatMap(b=>b.rows).find(r=>r.sourceId===c.sourceId),s=next.statements.find(s=>s.id===c.statementId),p=next.procurement?.purchases.find(p=>p.id===c.purchaseId),part=next.procurement?.parts.find(p=>p.id===c.partId);if(!r||r.kind!=='Materials'||r.status!=='Posted'||r.statementId!==c.statementId||r.recordId!==c.expenseId||r.cents!==c.cents||!c.reason.trim()||!c.reviewer.trim()||!Number.isFinite(Date.parse(c.created))||!s||s.expenses.some(e=>e.id===c.expenseId)||!p||!part||p.partId!==part.id||p.totalCost!==r.cents||p.quantity!==1||p.reference!==r.reference||p.supplier!==r.vendor||p.date!==r.date)throw Error('Inventory reclassification must match its original receipt');if(!oldCorrections.some(x=>x.id===c.id)&&(old.statements.find(x=>x.id===s.id)?.status!=='Pending'||s.status!=='Pending'||!old.statements.find(x=>x.id===s.id)?.expenses.some(e=>e.id===c.expenseId&&e.cents===c.cents)))throw Error('Inventory correction requires the original draft charge');}
 const prior=old.invoiceImports??[],rows=next.invoiceImports??[];if(rows.length>10000||new Set(rows.map(b=>b.id)).size!==rows.length||canonicalRecord(rows.slice(0,prior.length))!==canonicalRecord(prior))throw Error('Invoice source history is immutable');const sourceIds=new Set<string>(),hashes=new Set<string>();
 for(const b of rows){checkInvoiceRows(b.rows,b.period);if(!b.id||!b.reviewer.trim()||!b.fileName.trim()||!b.hash.trim()||hashes.has(b.hash)||!Number.isFinite(Date.parse(b.created)))throw Error('Invalid invoice batch');hashes.add(b.hash);for(const r of b.rows){if(sourceIds.has(r.sourceId)||!['Posted','Held'].includes(r.status))throw Error('Duplicate invoice source');sourceIds.add(r.sourceId);if(r.status==='Held'){if(r.recordId||r.statementId||!['Labor','Materials'].includes(r.kind))throw Error('Invalid held charge');continue;}if(!r.recordId)throw Error('Invoice link missing');if(['Labor','Materials'].includes(r.kind)){if(corrections.some(c=>c.sourceId===r.sourceId))continue;const s=next.statements.find(s=>s.id===r.statementId),e=s?.expenses.find(e=>e.id===r.recordId);if(!s||s.period!==b.period||next.units.find(u=>u.id===s.unitId)?.number!==r.unit||e?.cents!==r.cents||e.gl!==r.gl||e.recipient!==r.vendor)throw Error('Imported unit charge must match its QBO source');if(!prior.some(p=>p.id===b.id)&&old.statements.find(p=>p.id===s.id)?.status!=='Pending')throw Error('Import requires a draft statement');}else if(r.kind==='Stock'){const p=next.procurement?.purchases.find(p=>p.id===r.recordId);if(!p||p.totalCost!==r.cents||p.quantity!==r.quantity||p.reference!==r.reference||p.supplier!==r.vendor||p.date!==r.date)throw Error('Imported stock must match source invoice');}}}
 const priorLinks=old.invoiceLinks??[],links=next.invoiceLinks??[],recordIds=[...rows.flatMap(b=>b.rows.filter(r=>r.recordId).map(r=>r.recordId)),...links.map(l=>l.recordId)];if(new Set(recordIds).size!==recordIds.length)throw Error('Duplicate invoice posting link');if(canonicalRecord(links.slice(0,priorLinks.length))!==canonicalRecord(priorLinks)||new Set(links.map(l=>l.id)).size!==links.length||new Set(links.map(l=>l.sourceId)).size!==links.length)throw Error('Invoice link history is immutable');
 for(const l of links){const b=rows.find(b=>b.rows.some(r=>r.sourceId===l.sourceId)),r=b?.rows.find(r=>r.sourceId===l.sourceId),s=next.statements.find(s=>s.id===l.statementId),e=s?.expenses.find(e=>e.id===l.recordId);if(!l.reviewer.trim()||!Number.isFinite(Date.parse(l.created))||r?.status!=='Held'||!s||s.period!==b?.period||next.units.find(u=>u.id===s.unitId)?.number!==r.unit||e?.cents!==r.cents||e.gl!==r.gl||e.recipient!==r.vendor)throw Error('Linked invoice must match its original unit and QBO source');if(!priorLinks.some(p=>p.id===l.id)&&(s.status!=='Pending'||old.statements.find(s=>s.id===l.statementId)?.status!=='Pending'))throw Error('Invoice linking requires a draft statement');}
}
export function linkPendingInvoices(d:Data,period:string,reviewer:string){if(!reviewer.trim())throw Error('Reviewer required');let count=0;for(const b of d.invoiceImports?.filter(b=>b.period===period)??[])for(const r of b.rows.filter(r=>r.status==='Held'&&!d.invoiceLinks?.some(l=>l.sourceId===r.sourceId))){const units=d.units.filter(u=>u.number===r.unit);if(units.length!==1)continue;const s=d.statements.filter(s=>s.unitId===units[0].id&&s.period===period).sort((a,b)=>b.version-a.version)[0];if(!s||s.status!=='Pending')continue;const recordId=crypto.randomUUID();s.expenses.push({id:recordId,label:r.kind+' · '+r.description+(r.reference?' · '+r.reference:''),cents:r.cents,recipient:r.vendor,classification:r.kind==='Labor'?'Unit repair labor':'Unit repair materials',gl:r.gl});(d.invoiceLinks??=[]).push({id:crypto.randomUUID(),sourceId:r.sourceId,recordId,statementId:s.id,reviewer,created:new Date().toISOString()});count++;}if(!count)throw Error('Add the missing unit and its draft statement before linking the saved bills');d.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),action:'Pending invoice bills linked',detail:period+' / '+count+' / '+reviewer});return count;}
export function importedInvoiceRow(d:Data,id:string){const linked=d.invoiceLinks?.find(l=>l.recordId===id);return d.invoiceImports?.flatMap(b=>b.rows).find(r=>r.recordId===id||linked?.sourceId===r.sourceId);}

