import type {Data} from './pool';
import type {Operations,Lease} from './operations-model';
import {canonicalRecord} from './workflow-controls';

export const leasingSections=['Vacancies','Guest cards','Applications','Leases','Renewals','Metrics'] as const;
export type LeasingSection=typeof leasingSections[number];
export type RentalApplication={id:string;prospectId:string;unitId:string;submitted:string;status:'Draft'|'Submitted'|'Under review'|'Approved'|'Denied'|'Withdrawn';reason:string;decided:string;notes:string};
export type LeasingShowing={id:string;prospectId:string;unitId:string;date:string;time:string;assignee:string;status:'Scheduled'|'Completed'|'Cancelled';notes:string};
const date=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const terminal=['Approved','Denied','Withdrawn'];
const transitions:Record<string,string[]>={Draft:['Draft','Submitted','Withdrawn'],Submitted:['Submitted','Under review','Withdrawn'],'Under review':['Under review','Approved','Denied','Withdrawn'],Approved:['Approved'],Denied:['Denied'],Withdrawn:['Withdrawn']};
export function validateLeasingWorkflow(ops:Operations,units:Set<string>,old?:Operations){
 for(const key of ['rentalApplications','leasingShowings'] as const){const rows=ops[key]??[];if(!Array.isArray(rows)||rows.length>10000||new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Invalid leasing records');for(const r of old?.[key]??[])if(!rows.some(x=>x.id===r.id))throw Error('Preserve leasing history');for(const r of rows)if(!r.id||!units.has(r.unitId)||!ops.prospects.some(p=>p.id===r.prospectId&&p.unitId===r.unitId))throw Error('Choose the guest card and its unit');}
 const live=new Set<string>();for(const a of ops.rentalApplications??[]){if(!transitions[a.status]||!date(a.submitted)||typeof a.notes!=='string'||typeof a.reason!=='string'||a.notes.length>10000||a.reason.length>2000)throw Error('Invalid application');if(terminal.includes(a.status)&&(!a.reason.trim()||!date(a.decided)))throw Error('Record the decision date and reason');if(!terminal.includes(a.status)&&a.decided)throw Error('Only reviewed decisions have a decision date');const previous=old?.rentalApplications?.find(x=>x.id===a.id);if(old&&!previous&&a.status!=='Draft')throw Error('New applications start as drafts');if(previous){if(previous.unitId!==a.unitId||previous.prospectId!==a.prospectId||previous.submitted!==a.submitted||!transitions[previous.status].includes(a.status))throw Error('Invalid application transition');if(terminal.includes(previous.status)&&canonicalRecord(previous)!==canonicalRecord(a))throw Error('Preserve reviewed application decisions');}if(!['Denied','Withdrawn'].includes(a.status)){const key=a.prospectId+':'+a.unitId;if(live.has(key))throw Error('An application already exists for this guest and unit');live.add(key);}}
 for(const s of ops.leasingShowings??[]){if(!date(s.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.time)||!s.assignee.trim()||!['Scheduled','Completed','Cancelled'].includes(s.status)||typeof s.notes!=='string')throw Error('Enter showing date, time and host');const previous=old?.leasingShowings?.find(x=>x.id===s.id);if(previous&&(previous.unitId!==s.unitId||previous.prospectId!==s.prospectId||previous.status!=='Scheduled'&&canonicalRecord(previous)!==canonicalRecord(s)))throw Error('Preserve completed showing history');if(s.status==='Scheduled'&&(ops.leasingShowings??[]).some(x=>x.id!==s.id&&x.status==='Scheduled'&&x.date===s.date&&x.time===s.time&&(x.unitId===s.unitId||x.assignee.trim().toLowerCase()===s.assignee.trim().toLowerCase())))throw Error('This unit or host already has a showing at that time');}
 for(const l of ops.leases){const previous=old?.leases.find(x=>x.id===l.id);if(previous&&(previous.applicationId!==l.applicationId||previous.renewalOf!==l.renewalOf))throw Error('Preserve lease workflow links');if(l.applicationId){const a=ops.rentalApplications?.find(a=>a.id===l.applicationId);if(!a||a.status!=='Approved'||a.unitId!==l.unitId)throw Error('Lease requires a reviewed approved application');if(ops.leases.some(x=>x.id!==l.id&&x.applicationId===l.applicationId))throw Error('Application already has a lease');}if(l.renewalOf){const original=ops.leases.find(x=>x.id===l.renewalOf);if(!original||original.id===l.id||original.unitId!==l.unitId||original.tenantId!==l.tenantId||original.status==='Draft'||l.start<=original.end)throw Error('Renewal must follow the existing lease for this resident');if(ops.leases.some(x=>x.id!==l.id&&x.renewalOf===l.renewalOf))throw Error('A renewal already exists for this lease');}}
 for(const p of ops.prospects){for(const key of ['phone','source','assignee','moveIn','followUp'] as const)if(p[key]!==undefined&&(typeof p[key]!=='string'||p[key]!.length>2000))throw Error('Invalid guest card');if(p.moveIn&&!date(p.moveIn)||p.followUp&&!date(p.followUp))throw Error('Invalid guest date');if(p.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))throw Error('Invalid guest email');if(p.maxRent!==undefined&&(!Number.isSafeInteger(p.maxRent)||p.maxRent<0))throw Error('Invalid desired rent');}
}
export function applicationForGuest(ops:Operations,prospectId:string,id:string,submitted:string){const p=ops.prospects.find(p=>p.id===prospectId);if(!p?.unitId)throw Error('Choose a unit on the guest card first');const existing=ops.rentalApplications?.find(a=>a.prospectId===p.id&&!['Denied','Withdrawn'].includes(a.status));if(existing)return existing;const a:RentalApplication={id,prospectId:p.id,unitId:p.unitId,submitted,status:'Draft',reason:'',decided:'',notes:''};(ops.rentalApplications??=[]).push(a);return a;}
export function draftLease(ops:Operations,input:Lease){const existing=ops.leases.find(l=>input.applicationId&&l.applicationId===input.applicationId||input.renewalOf&&l.renewalOf===input.renewalOf);if(existing)return existing;if(input.status!=='Draft')throw Error('Prepare a draft before signing');ops.leases.push(input);return input;}
export function leasingSnapshot(data:Data,month:string,asOf:string,propertyId=''){
 const ops=data.operations,units=data.units.filter(u=>!propertyId||u.propertyId===propertyId),ids=new Set(units.map(u=>u.id));
 const prospects=(ops?.prospects??[]).filter(p=>ids.has(p.unitId));const applications=(ops?.rentalApplications??[]).filter(a=>ids.has(a.unitId));const leases=(ops?.leases??[]).filter(l=>ids.has(l.unitId));
 const horizon=new Date(Date.parse(asOf+'T12:00:00Z')+90*86400000).toISOString().slice(0,10);
 return {units,prospects,applications,leases,showings:(ops?.leasingShowings??[]).filter(s=>ids.has(s.unitId)),vacancies:units.filter(u=>ops?.occupancy?.some(o=>o.unitId===u.id&&o.month===month&&o.status==='Vacant')),unknown:units.filter(u=>!ops?.occupancy?.some(o=>o.unitId===u.id&&o.month===month&&o.status!=='Unknown')),renewals:leases.filter(l=>l.status==='Active'&&l.end>=asOf&&l.end<=horizon)};
}



