import type {Operations,WorkOrder} from './operations-model';
export const maintenanceSections=['Work Orders','Recurring Work Orders','Inspections','Unit Turns','Projects','Purchase Orders','Inventory','Fixed Assets'] as const;
export type MaintenanceSection=typeof maintenanceSections[number];
export type RecurringWork={kind?:WorkOrder['kind'];id:string;title:string;unitId:string;description:string;assignee:string;vendor:string;nextDate:string;intervalMonths:number;active:boolean;notes:string};
export type PurchaseOrder={id:string;number:string;unitId:string;workOrderId:string;supplier:string;description:string;date:string;expectedDate:string;amount:number;status:'Draft'|'Submitted'|'Approved'|'Received'|'Cancelled';approvedBy:string;notes:string};
export type FixedAsset={id:string;tag:string;name:string;unitId:string;serial:string;acquired:string;cost:number;status:'In service'|'Under repair'|'Retired';nextService:string;notes:string};
export function validMaintenanceDate(s:string){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}
export function nextRecurringDate(date:string,months:number){if(!validMaintenanceDate(date)||!Number.isInteger(months)||months<1||months>12)throw Error('Choose a valid date and interval of 1–12 months');const [y,m,d]=date.split('-').map(Number),target=new Date(Date.UTC(y,m-1+months,1)),last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();target.setUTCDate(Math.min(d,last));return target.toISOString().slice(0,10);}
export function generateRecurringWork(ops:Operations,id:string,through:string,now=new Date().toISOString()){
 const schedule=ops.recurringWork?.find(r=>r.id===id);if(!schedule?.active||!validMaintenanceDate(through)||schedule.nextDate>through)throw Error('This schedule is not due');
 const due=schedule.nextDate,key=id+':'+due;if(ops.workOrders.some(w=>w.recurringKey===key))throw Error('This occurrence already has a work order');
 let sequence=ops.workOrders.length+1;while(ops.workOrders.some(w=>w.number==='WO-'+String(sequence).padStart(4,'0')))sequence++;
 const w:WorkOrder={id:crypto.randomUUID(),number:'WO-'+String(sequence).padStart(4,'0'),unitId:schedule.unitId,title:schedule.title,description:schedule.description,status:'New',priority:'Normal',kind:schedule.kind??'Repair',assignee:schedule.assignee,vendor:schedule.vendor,scheduled:due,followUp:'',estimate:0,hours100:0,rate:0,materials:0,ownerApproved:false,permissionToEnter:'No',entryInstructions:'',notes:schedule.notes,created:now,updated:now,recurringKey:key};
 ops.workOrders.unshift(w);schedule.nextDate=nextRecurringDate(due,schedule.intervalMonths);return w;
}
export function validateMaintenanceRecords(ops:Operations,units:Set<string>,old?:Operations){
 for(const key of ['recurringWork','purchaseOrders','fixedAssets'] as const){const rows=ops[key]??[];if(!Array.isArray(rows)||rows.length>10000||new Set(rows.map(r=>r.id)).size!==rows.length||rows.some(r=>!r.id))throw Error('Invalid maintenance register');for(const r of old?.[key]??[])if(!rows.some(n=>n.id===r.id))throw Error('Maintenance history must be preserved');for(const r of rows)if(r.unitId&&!units.has(r.unitId))throw Error('Unknown maintenance unit');}
 for(const r of ops.recurringWork??[]){if(!r.title.trim()||typeof r.active!=='boolean'||r.kind!==undefined&&!['Repair','Inspection','Unit turn','Project'].includes(r.kind))throw Error('Recurring work requires a title and active status');nextRecurringDate(r.nextDate,r.intervalMonths);}
 const numbers=new Set<string>();for(const r of ops.purchaseOrders??[]){if(!r.number.trim()||numbers.has(r.number)||!r.supplier.trim()||!r.description.trim()||!validMaintenanceDate(r.date)||r.expectedDate&&!validMaintenanceDate(r.expectedDate)||!Number.isSafeInteger(r.amount)||r.amount<0||r.amount>100000000000||!['Draft','Submitted','Approved','Received','Cancelled'].includes(r.status))throw Error('Invalid purchase order');numbers.add(r.number);if(['Approved','Received'].includes(r.status)&&!r.approvedBy.trim())throw Error('Record purchase-order approval');if(r.workOrderId&&!ops.workOrders.some(w=>w.id===r.workOrderId&&w.unitId===r.unitId))throw Error('Purchase-order work order must match the unit');}
 const tags=new Set<string>();for(const r of ops.fixedAssets??[]){if(!r.tag.trim()||tags.has(r.tag)||!r.name.trim()||r.acquired&&!validMaintenanceDate(r.acquired)||r.nextService&&!validMaintenanceDate(r.nextService)||!Number.isSafeInteger(r.cost)||r.cost<0||r.cost>100000000000||!['In service','Under repair','Retired'].includes(r.status))throw Error('Invalid fixed asset');tags.add(r.tag);}
 for(const w of old?.workOrders??[])if(w.recurringKey!==ops.workOrders.find(n=>n.id===w.id)?.recurringKey)throw Error('Recurring work source must be preserved');
 const keys=new Set<string>();for(const w of ops.workOrders){if(w.recurringKey){if(keys.has(w.recurringKey))throw Error('Duplicate recurring work occurrence');keys.add(w.recurringKey);const prior=old?.workOrders.find(r=>r.id===w.id);if(prior&&prior.recurringKey!==w.recurringKey)throw Error('Recurring work source must be preserved');}}
}

