import {dlaIncomeReview} from './pool-finance';
import {verifiedGL} from './gl-controls';
import {type Data,type Statement,latest,totals,audit,draftFor} from './pool';
import {clearingReview,clearingState} from './monthly-clearing';
import {canonicalRecord} from './workflow-controls';
import {incomeRows} from './accounting-model';
export type OwnerContribution={id:string;statementId:string;period:string;cents:number;date:string;reference:string;reviewer:string;created:string};
export type MonthCloseEvent={id:string;period:string;kind:'Closed'|'Reopened';reviewer:string;reason:string;bankReference:string;escrowReference:string;fingerprint:string;summary:{rent:number;allocated:number;ownerCash:number;ownerContributions:number;ownerOutstanding:number;unpaidTenantRent:number;dlaIncome:number;dlaShortfall:number};created:string};
export type CloseControls={contributions:OwnerContribution[];events:MonthCloseEvent[]};
export const closeState=(d:Data,period:string)=>[...(d.closeControls?.events??[])].reverse().find(e=>e.period===period);
export const contributionTotal=(d:Data,s:Statement)=>(d.closeControls?.contributions??[]).filter(c=>c.statementId===s.id).reduce((n,c)=>n+c.cents,0);
export const ownerOutstanding=(d:Data,s:Statement)=>totals(s).closing+contributionTotal(d,s);
const month=(p:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(p);
const date=(p:string)=>/^\d{4}-\d{2}-\d{2}$/.test(p)&&Number.isFinite(Date.parse(p+'T12:00:00Z'))&&new Date(p+'T12:00:00Z').toISOString().slice(0,10)===p;
// Freeze source records for this month, not future operational work or contact edits.
export function closeFingerprint(d:Data,period:string){const entries=(d.operations?.tenantEntries??[]).filter(e=>e.date.slice(0,7)<=period),ids=new Set(entries.map(e=>e.id));return canonicalRecord({period,...((d.operations?.rentAmendments??[]).some(r=>r.from<=period)?{rentAmendments:d.operations!.rentAmendments!.filter(r=>r.from<=period)}:{}),invoiceSources:(d.invoiceImports??[]).filter(b=>b.period===period),invoiceLinks:(d.invoiceLinks??[]).filter(l=>d.invoiceImports?.some(b=>b.period===period&&b.rows.some(r=>r.sourceId===l.sourceId))),chargeReview:incomeRows(d,period),purchases:d.procurement?.purchases.filter(p=>p.date.startsWith(period))??[],issues:d.procurement?.issues.filter(p=>p.date.startsWith(period))??[],corrections:d.procurement?.corrections?.filter(p=>p.date.startsWith(period))??[],contracts:d.accounting?.contracts.filter(c=>c.from<=period)??[],statements:latest(d,period),settings:d.settings.filter(s=>s.period===period),memberships:d.memberships?.filter(m=>m.month<=period)??[],allocations:d.accounting?.allocations.filter(r=>r.period===period)??[],reviews:d.finance?.reviews.filter(r=>r.inputs.period===period)??[],classifications:d.accounting?.classifications.filter(c=>c.date.startsWith(period))??[],settlements:d.accounting?.settlements.filter(r=>r.period===period)??[],deposits:d.accounting?.deposits.filter(r=>r.date.startsWith(period))??[],contributions:d.closeControls?.contributions.filter(c=>c.period===period)??[],entries,applications:d.accounting?.applications.filter(a=>ids.has(a.receiptId))??[],clearing:clearingState(d,period)??null});}
export function tenantArrears(d:Data,period:string){const entries=d.operations?.tenantEntries??[],apps=d.accounting?.applications??[];return entries.filter(e=>e.kind==='Charge'&&e.date.slice(0,7)<=period).map(e=>({entry:e,remaining:Math.max(0,e.cents-apps.filter(a=>a.chargeId===e.id&&entries.some(r=>r.id===a.receiptId&&r.date.slice(0,7)<=period)).reduce((n,a)=>n+a.cents,0))})).filter(r=>r.remaining>0);}
export function closeReview(d:Data,period:string){const current=latest(d,period),r=clearingReview(d,period),rows=incomeRows(d,period),blockers=[...r.blockers];if(d.invoiceImports?.some(b=>b.period===period&&b.rows.some(r=>r.status==='Held'&&!d.invoiceLinks?.some(l=>l.sourceId===r.sourceId))))blockers.push('Complete the missing unit/owner links for saved supplier bills before closing.');if(clearingState(d,period)?.kind!=='Closed')blockers.push('Close the zero-difference rent clearing review first.');if(current.some(s=>s.status==='Paid'&&!s.paidDate.startsWith(period)))blockers.push('Review owner payments completed outside this accounting month before closing.');if(current.some(s=>ownerOutstanding(d,s)!==0))blockers.push('Record completed owner distributions or verified owner contributions until each owner unit balance is zero.');if(dlaIncomeReview(d,period).unconfirmed)blockers.push('Verify DLA recurring fee agreements and income classification.');if(rows.some(r=>r.confirmed&&(()=>{try{verifiedGL(d,r.gl,r.kind==='Escrow'?(d.glControls?.charts.at(-1)?.accounts.find(a=>a.number===r.gl)?.name??''):r.accountName);return r.kind!=='Escrow'&&!r.invoiceRef.trim();}catch{return true;}})()))blockers.push('Verify each charge against an active QBO account and source reference.');if(rows.some(r=>!r.confirmed))blockers.push('Review the recipient and QBO GL treatment of all owner charges, credits and purchases.');return {blockers:[...new Set(blockers)],summary:{dlaIncome:dlaIncomeReview(d,period).income,dlaShortfall:dlaIncomeReview(d,period).shortfall,rent:r.recordedRent,allocated:current.reduce((n,s)=>n+s.allocated,0),ownerCash:current.reduce((n,s)=>n+(s.cashPaid??s.paidAmount),0),ownerContributions:current.reduce((n,s)=>n+contributionTotal(d,s),0),ownerOutstanding:current.reduce((n,s)=>n+ownerOutstanding(d,s),0),unpaidTenantRent:tenantArrears(d,period).filter(r=>r.entry.category==='Rent').reduce((n,r)=>n+r.remaining,0)}};}
export function recordContribution(d:Data,statementId:string,cents:number,paidDate:string,reference:string,reviewer:string){const s=latest(d,d.statements.find(s=>s.id===statementId)?.period??'').find(s=>s.id===statementId);if(!s||s.status!=='Approved')throw Error('Choose the latest approved owner statement.');if(closeState(d,s.period)?.kind==='Closed')throw Error('Reopen the month before recording contributions.');if(!Number.isSafeInteger(cents)||cents<=0||cents>-ownerOutstanding(d,s))throw Error('Contribution must not exceed the outstanding owner obligation.');if(!date(paidDate)||!paidDate.startsWith(s.period)||!reference.trim()||!reviewer.trim())throw Error('Enter a valid completion date in this month, unique reference and reviewer.');if((d.closeControls?.contributions??[]).some(c=>c.reference.toLowerCase()===reference.trim().toLowerCase())||d.statements.some(s=>s.paymentRef.toLowerCase()===reference.trim().toLowerCase())||d.accounting?.settlements.some(s=>s.reference.toLowerCase()===reference.trim().toLowerCase()))throw Error('Payment reference already recorded.');const c={id:crypto.randomUUID(),statementId,period:s.period,cents,date:paidDate,reference:reference.trim(),reviewer:reviewer.trim(),created:new Date().toISOString()};(d.closeControls??={contributions:[],events:[]}).contributions.push(c);audit(d,'External owner contribution recorded',statementId+' / '+c.reference+' / '+cents+' cents');return c;}
export function recordMonthClose(d:Data,period:string,kind:'Closed'|'Reopened',reviewer:string,reason:string,bankReference='',escrowReference=''){const prior=closeState(d,period),r=closeReview(d,period);if(!month(period)||!d.periods.some(p=>p.month===period)||!reviewer.trim()||!reason.trim())throw Error('Enter an open month, reviewer and review notes.');if(kind==='Closed'&&prior?.kind==='Closed'||kind==='Reopened'&&prior?.kind!=='Closed')throw Error('Invalid monthly close transition.');if(kind==='Closed'&&(r.blockers.length||!bankReference.trim()||!escrowReference.trim()))throw Error([...r.blockers,'Enter verified owner-operating and escrow reconciliation references (including documented zero activity).'].join(' '));const e:MonthCloseEvent={id:crypto.randomUUID(),period,kind,reviewer:reviewer.trim(),reason:reason.trim(),bankReference:bankReference.trim(),escrowReference:escrowReference.trim(),fingerprint:closeFingerprint(d,period),summary:r.summary,created:new Date().toISOString()};(d.closeControls??={contributions:[],events:[]}).events.push(e);audit(d,'Accounting month '+kind.toLowerCase(),period+' / '+reviewer+' / '+reason);return e;}
export function validateClose(old:Data,next:Data){const c=next.closeControls;if(!c){if(old.closeControls)throw Error('Preserve monthly close history.');return;}for(const key of ['events','contributions'] as const){if(!Array.isArray(c[key])||c[key].length>20000||new Set(c[key].map(e=>e.id)).size!==c[key].length)throw Error('Invalid close history.');const prior=old.closeControls?.[key]??[];if(canonicalRecord(c[key].slice(0,prior.length))!==canonicalRecord(prior))throw Error('Close history is immutable.');}
 for(const p of c.contributions){const s=next.statements.find(s=>s.id===p.statementId);if(!s||s.status!=='Approved'||s.period!==p.period||!date(p.date)||!p.date.startsWith(p.period)||!Number.isSafeInteger(p.cents)||p.cents<=0||p.reference!==p.reference.trim()||p.reference.length>200||!p.reference.trim()||p.reviewer.length>200||!p.reviewer.trim()||!Number.isFinite(Date.parse(p.created)))throw Error('Invalid owner contribution.');if(contributionTotal(next,s)>Math.max(0,-totals(s).closing)||latest(next,p.period).find(x=>x.unitId===s.unitId)?.id!==s.id)throw Error('Contribution exceeds the latest owner obligation.');if(!old.closeControls?.contributions.some(x=>x.id===p.id)&&old.statements.find(x=>x.id===s.id)?.status!=='Approved')throw Error('Approve owner statement before recording contribution.');if(c.contributions.filter(x=>x.reference.toLowerCase()===p.reference.toLowerCase()).length!==1||next.statements.some(s=>s.paymentRef.toLowerCase()===p.reference.toLowerCase())||next.accounting?.settlements.some(s=>s.reference.toLowerCase()===p.reference.toLowerCase()))throw Error('Duplicate owner contribution reference.');}
 const states=new Map<string,MonthCloseEvent>();for(const e of c.events){if(!e.id||!month(e.period)||!next.periods.some(p=>p.month===e.period)||!['Closed','Reopened'].includes(e.kind)||e.reviewer.length>200||e.reason.length>2000||e.bankReference.length>500||e.escrowReference.length>500||!e.reviewer.trim()||!e.reason.trim()||!Number.isFinite(Date.parse(e.created)))throw Error('Invalid close event.');const prior=states.get(e.period);if(e.kind==='Closed'&&prior?.kind==='Closed'||e.kind==='Reopened'&&prior?.kind!=='Closed')throw Error('Invalid close history transition.');if(!old.closeControls?.events.some(x=>x.id===e.id)){const r=closeReview(next,e.period);if(e.fingerprint!==closeFingerprint(next,e.period)||canonicalRecord(e.summary)!==canonicalRecord(r.summary)||e.kind==='Closed'&&(r.blockers.length||!e.bankReference.trim()||!e.escrowReference.trim()))throw Error('Monthly close sources are incomplete or changed.');if(e.kind==='Reopened'&&closeFingerprint(old,e.period)!==closeFingerprint(next,e.period))throw Error('Save the reopen before editing financial records.');}states.set(e.period,e);}
 for(const [period,e] of states)if(e.kind==='Closed'&&e.fingerprint!==closeFingerprint(next,period))throw Error('Reopen the accounting month before changing closed financial sources.');
}
export function openFollowingMonth(d:Data,period:string){if(closeState(d,period)?.kind!=='Closed')throw Error('Close this accounting month first.');const [y,m]=period.split('-').map(Number),next=new Date(Date.UTC(y,m,1)).toISOString().slice(0,7);if(d.periods.some(p=>p.month===next))throw Error('The next month is already open.');d.periods.push({id:crypto.randomUUID(),month:next});for(const pool of d.pools){const previous=d.settings.filter(s=>s.poolId===pool.id&&s.period<=period).sort((a,b)=>b.period.localeCompare(a.period)||b.version-a.version)[0];if(!previous)continue;const setting={...structuredClone(previous),id:crypto.randomUUID(),period:next,version:1,electricTotal:null,electricConfirmed:false,notes:'New month: verify collected rent, agreements and CPS sources.'};d.settings.push(setting);for(const u of d.units.filter(u=>u.poolId===pool.id&&(!u.addedMonth||u.addedMonth<=next))){const s=draftFor(d,u,setting);s.opening=0;s.openingConfirmed=true;if(!s.allocationSource?.startsWith('Approved next-month assumption')){s.allocated=0;s.allocationSource='New month; collected rent review required';}d.statements.push(s);}}audit(d,'Following month opened',next+' / owner opening zero; unpaid tenant entries retained');return next;}

export function missingOwnerSupport(d:Data,period:string,docs:{statementId:string;expenseId:string}[]){return latest(d,period).flatMap(s=>s.expenses.filter(e=>/repair|labor|material/i.test(e.label)&&!e.laborPostId&&!e.partsIssueId&&!docs.some(doc=>doc.expenseId===e.id&&d.statements.some(v=>v.id===doc.statementId&&v.unitId===s.unitId&&v.ownerId===s.ownerId))).map(e=>({statementId:s.id,expenseId:e.id,unitId:s.unitId,label:e.label})));}
