import type {Data} from './pool';
import {canonicalRecord} from './workflow-controls';

export type LedgerLine={accountKey:string;debit:number;credit:number;unitId:string;memo:string};
type Actor={id:string;reviewer:string;created:string};
export type LedgerBook=Actor&{company:string;chartId:string;openingDate:string;source:string;opening:LedgerLine[]};
export type LedgerEntry=Actor&{bookId:string;date:string;reference:string;memo:string;lines:LedgerLine[];reverses:string;recurringId:string;sourceSystem:string;externalId:string};
export type RecurringRule=Actor&{ruleId:string;version:number;bookId:string;name:string;start:string;end:string;day:number;active:boolean;lines:LedgerLine[]};
export type StatementRow={id:string;date:string;reference:string;description:string;cents:number;entryIds:string[]};
export type BankReconciliation=Actor&{bookId:string;accountKey:string;start:string;end:string;beginning:number;ending:number;source:string;rows:StatementRow[]};
export type PaymentConnection=Actor&{name:string;url:string;methods:('ACH'|'Card')[];active:boolean};
export type NativeAccounting={books:LedgerBook[];entries:LedgerEntry[];rules:RecurringRule[];reconciliations:BankReconciliation[];paymentConnections:PaymentConnection[]};
export const emptyNativeAccounting=():NativeAccounting=>({books:[],entries:[],rules:[],reconciliations:[],paymentConnections:[]});
export const native=(d:Data)=>d.accounting?.native??emptyNativeAccounting();
const validText=(v:unknown,max=500)=>typeof v==='string'&&!!v.trim()&&v.length<=max;
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const validMonth=(v:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(v);
const amount=(v:number,signed=false)=>Number.isSafeInteger(v)&&(signed||v>=0)&&Math.abs(v)<=100000000000;
export const lineTotals=(lines:LedgerLine[])=>lines.reduce((n,l)=>({debit:n.debit+l.debit,credit:n.credit+l.credit}),{debit:0,credit:0});
export const bookChart=(d:Data,bookId:string)=>d.glControls?.charts.find(c=>c.id===native(d).books.find(b=>b.id===bookId)?.chartId);
export function ledgerBalance(d:Data,bookId:string,accountKey:string,date:string){const b=native(d).books.find(b=>b.id===bookId);if(!b||date<b.openingDate)return 0;return [...b.opening,...native(d).entries.filter(e=>e.bookId===bookId&&e.date<=date).flatMap(e=>e.lines)].filter(l=>l.accountKey===accountKey).reduce((n,l)=>n+l.debit-l.credit,0);}
export function ledgerMovements(d:Data,bookId:string,accountKey:string){return native(d).entries.filter(e=>e.bookId===bookId).map(e=>({entry:e,cents:e.lines.filter(l=>l.accountKey===accountKey).reduce((n,l)=>n+l.debit-l.credit,0)})).filter(e=>e.cents!==0);}
export function trialBalance(d:Data,bookId:string,date:string){return (bookChart(d,bookId)?.accounts??[]).map(a=>{const balance=ledgerBalance(d,bookId,a.key,date);return {account:a,balance,debit:Math.max(0,balance),credit:Math.max(0,-balance)};});}
export function recurringDue(d:Data,bookId:string,period:string){const rules=new Map<string,RecurringRule>();for(const r of native(d).rules)rules.set(r.ruleId,r);return [...rules.values()].filter(r=>r.bookId===bookId&&r.active&&r.start<=period&&(!r.end||r.end>=period)&&!native(d).entries.some(e=>e.recurringId===r.id&&e.date.startsWith(period)||e.bookId===bookId&&e.date.startsWith(period)&&native(d).rules.some(p=>p.id===e.recurringId&&p.ruleId===r.ruleId)));}
export function recurringDate(r:RecurringRule,period:string){const [y,m]=period.split('-').map(Number),day=Math.min(r.day,new Date(Date.UTC(y,m,0)).getUTCDate());return period+'-'+String(day).padStart(2,'0');}
export function reconciliationReview(d:Data,r:BankReconciliation){const n=native(d),prior=n.reconciliations.filter(p=>p.bookId===r.bookId&&p.accountKey===r.accountKey&&p.end<r.start).at(-1),used=new Set(n.reconciliations.filter(p=>p.bookId===r.bookId&&p.accountKey===r.accountKey&&p.id!==r.id&&p.end<r.start).flatMap(p=>p.rows.flatMap(row=>row.entryIds))),selected=new Set(r.rows.flatMap(row=>row.entryIds));
 const outstanding=ledgerMovements(d,r.bookId,r.accountKey).filter(x=>x.entry.date<=r.end&&!used.has(x.entry.id)&&!selected.has(x.entry.id));const ledger=ledgerBalance(d,r.bookId,r.accountKey,r.end),adjusted=r.ending+outstanding.reduce((s,e)=>s+e.cents,0);return {prior,outstanding,ledger,adjusted,difference:adjusted-ledger,statementDifference:r.ending-r.beginning-r.rows.reduce((s,row)=>s+row.cents,0)};
}
function checkLines(d:Data,book:LedgerBook,lines:LedgerLine[]){const chart=d.glControls?.charts.find(c=>c.id===book.chartId);if(!Array.isArray(lines)||lines.length<2||lines.length>100)throw Error('Enter 2–100 balanced journal lines');for(const l of lines)if(!chart?.accounts.some(a=>a.key===l.accountKey&&a.active)||!amount(l.debit)||!amount(l.credit)||!(l.debit>0&&l.credit===0||l.credit>0&&l.debit===0)||typeof l.memo!=='string'||l.memo.length>500||typeof l.unitId!=='string'||l.unitId&&!d.units.some(u=>u.id===l.unitId))throw Error('Use active company accounts, known units and one debit or credit per line');const t=lineTotals(lines);if(!Number.isSafeInteger(t.debit)||t.debit!==t.credit||!t.debit)throw Error('Journal debits and credits must balance');}
export function validateNativeAccounting(d:Data,old?:Data){const n=native(d),p=old?native(old):emptyNativeAccounting();
 for(const key of ['books','entries','rules','reconciliations','paymentConnections'] as const){const rows=n[key];if(!Array.isArray(rows)||rows.length>20000||new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Invalid native accounting history');if(canonicalRecord(rows.slice(0,p[key].length))!==canonicalRecord(p[key]))throw Error('Native accounting history is immutable');for(const r of rows)if(!validText(r.id,100)||!validText(r.reviewer,200)||!Number.isFinite(Date.parse(r.created)))throw Error('Accounting records require an authenticated reviewer and timestamp');}
 const companyIds=new Set<string>();for(const b of n.books){const c=d.glControls?.charts.find(c=>c.id===b.chartId),company=b.company.trim().toLowerCase();if(!validText(b.company,200)||!c||c.company.trim().toLowerCase()!==company||companyIds.has(company)||!validDate(b.openingDate)||!validText(b.source,2000)||!Array.isArray(b.opening))throw Error('Verify a unique company book, reviewed chart, opening date and source');companyIds.add(company);if(old&&!p.books.some(x=>x.id===b.id)&&d.glControls?.charts.filter(c=>c.company.trim().toLowerCase()===company).at(-1)?.id!==b.chartId)throw Error('Initialize from the latest reviewed company chart');if(b.opening.length)checkLines(d,b,b.opening);}
 const refs=new Set<string>(),sources=new Set<string>(),runs=new Set<string>(),reversed=new Set<string>();
 for(const e of n.entries){const b=n.books.find(b=>b.id===e.bookId);if(!b||!validDate(e.date)||e.date<=b.openingDate||!validText(e.reference,200)||!validText(e.memo,2000)||typeof e.sourceSystem!=='string'||typeof e.externalId!=='string'||e.sourceSystem.length>100||e.externalId.length>200||!!e.sourceSystem!==!!e.externalId||typeof e.reverses!=='string'||typeof e.recurringId!=='string')throw Error('Verify book, posting date, reference, memo and source identity');checkLines(d,b,e.lines);const ref=e.bookId+'|'+e.reference.trim().toLowerCase();if(refs.has(ref))throw Error('Duplicate ledger reference');refs.add(ref);
  if(e.sourceSystem||e.externalId){if(!validText(e.sourceSystem,100)||!validText(e.externalId,200))throw Error('External system and transaction ID must both be provided');const key=[b.company,e.sourceSystem,e.externalId].map(x=>x.trim().toLowerCase()).join('|');if(sources.has(key)||(d.accounting?.journalRecords??[]).some(j=>[j.company,j.system,j.externalId].map(x=>x.trim().toLowerCase()).join('|')===key)||(d.accounting?.transferRecords??[]).some(j=>[j.company,j.system,j.externalId].map(x=>x.trim().toLowerCase()).join('|')===key))throw Error('External transaction is already recorded; do not post it twice');sources.add(key);}
  if(e.reverses){const prior=n.entries.slice(0,n.entries.indexOf(e)).find(x=>x.id===e.reverses);if(!prior||prior.bookId!==e.bookId||prior.date>e.date||prior.reverses||e.recurringId||reversed.has(prior.id)||canonicalRecord(e.lines)!==canonicalRecord(prior.lines.map(l=>({...l,debit:l.credit,credit:l.debit}))))throw Error('Reversal must offset one original entry exactly once');reversed.add(prior.id);}
  if(e.recurringId){const r=n.rules.find(r=>r.id===e.recurringId),key=r?.ruleId+'|'+e.date.slice(0,7);if(!r||r.bookId!==b.id||!r.active||r.start>e.date.slice(0,7)||r.end&&r.end<e.date.slice(0,7)||e.date!==recurringDate(r,e.date.slice(0,7))||canonicalRecord(r.lines)!==canonicalRecord(e.lines)||runs.has(key))throw Error('Recurring entry must match its reviewed template once per month');runs.add(key);}
  if(!p.entries.some(x=>x.id===e.id)){if(!d.periods.some(x=>x.month===e.date.slice(0,7)))throw Error('Choose an existing accounting month');if([...(old?.closeControls?.events??[])].reverse().find(x=>x.period===e.date.slice(0,7))?.kind==='Closed')throw Error('Reopen the month before posting');if(p.reconciliations.some(r=>r.bookId===b.id&&e.date<=r.end&&e.lines.some(l=>l.accountKey===r.accountKey)))throw Error('A reconciled bank period is locked; post a later correction');if(old&&e.recurringId&&n.rules.filter(r=>r.ruleId===n.rules.find(x=>x.id===e.recurringId)?.ruleId).at(-1)?.id!==e.recurringId)throw Error('Use the current recurring template');}
 }
 const versions=new Map<string,RecurringRule>();for(const r of n.rules){const b=n.books.find(b=>b.id===r.bookId),prior=versions.get(r.ruleId);if(!b||!validText(r.ruleId,100)||!validText(r.name,200)||!validMonth(r.start)||r.end&&(!validMonth(r.end)||r.end<r.start)||!Number.isInteger(r.day)||r.day<1||r.day>31||typeof r.active!=='boolean'||r.version!==(prior?.version??0)+1||prior&&prior.bookId!==r.bookId)throw Error('Invalid recurring template or revision');checkLines(d,b,r.lines);versions.set(r.ruleId,r);}
 for(const b of n.books){const balances=new Map<string,number>();for(const line of [...b.opening,...n.entries.filter(e=>e.bookId===b.id).flatMap(e=>e.lines)]){const value=(balances.get(line.accountKey)??0)+line.debit-line.credit;if(!Number.isSafeInteger(value))throw Error('Ledger balance exceeds exact-cent limits');balances.set(line.accountKey,value);}}
 for(const r of n.reconciliations){const b=n.books.find(b=>b.id===r.bookId),account=bookChart(d,r.bookId)?.accounts.find(a=>a.key===r.accountKey);if(!b||!account?.active||account.type.toLowerCase()!=='bank'||!validDate(r.start)||!validDate(r.end)||r.start>r.end||r.start<=b.openingDate||!amount(r.beginning,true)||!amount(r.ending,true)||!validText(r.source,2000)||!Array.isArray(r.rows)||r.rows.length>5000||n.reconciliations.some(x=>x.id!==r.id&&x.bookId===r.bookId&&x.accountKey===r.accountKey&&x.start<=r.end&&x.end>=r.start))throw Error('Verify a nonoverlapping Bank statement period and source');const review=reconciliationReview(d,r),prev=review.prior,expectedStart=prev?new Date(Date.parse(prev.end+'T12:00:00Z')+86400000).toISOString().slice(0,10):new Date(Date.parse(b.openingDate+'T12:00:00Z')+86400000).toISOString().slice(0,10);if(r.start!==expectedStart||r.beginning!==(prev?.ending??b.opening.filter(l=>l.accountKey===r.accountKey).reduce((s,l)=>s+l.debit-l.credit,0)))throw Error('Statement must carry forward the verified prior closing balance and next date');const ids=new Set<string>(),rowIds=new Set<string>(),rowRefs=new Set<string>(),cleared=new Set(n.reconciliations.filter(x=>x.id!==r.id&&x.bookId===b.id&&x.accountKey===r.accountKey&&x.end<r.start).flatMap(x=>x.rows.flatMap(row=>row.entryIds)));
  for(const row of r.rows){if(!validText(row.id,100)||rowIds.has(row.id)||!validDate(row.date)||row.date<r.start||row.date>r.end||!validText(row.reference,200)||rowRefs.has(row.reference.trim().toLowerCase())||typeof row.description!=='string'||row.description.length>500||!amount(row.cents,true)||!row.cents||!Array.isArray(row.entryIds)||!row.entryIds.length||row.entryIds.length>100)throw Error('Statement rows need unique references, dates, nonzero amounts and matched ledger entries');rowIds.add(row.id);rowRefs.add(row.reference.trim().toLowerCase());let matched=0;for(const id of row.entryIds){const e=n.entries.find(e=>e.id===id&&e.bookId===b.id&&e.date<=r.end);if(!e||ids.has(id)||cleared.has(id))throw Error('Ledger entry is missing, already cleared or matched twice');ids.add(id);const movement=e.lines.filter(l=>l.accountKey===r.accountKey).reduce((s,l)=>s+l.debit-l.credit,0);if(!movement)throw Error('Matched entry must contain a nonzero movement for this bank');matched+=movement;}if(matched!==row.cents)throw Error('Statement amount must equal matched ledger movement');}
  if(review.statementDifference!==0||review.difference!==0)throw Error('Statement and adjusted bank differences must both be zero');
 }
 for(const c of n.paymentConnections){let url:URL;try{url=new URL(c.url);}catch{throw Error('Enter the provider HTTPS dashboard URL');}if(!validText(c.name,200)||url.protocol!=='https:'||url.username||url.password||url.search||url.hash||url.hostname==='localhost'||/^\d+(\.\d+){3}$/.test(url.hostname)||!Array.isArray(c.methods)||!c.methods.length||new Set(c.methods).size!==c.methods.length||c.methods.some(m=>!['ACH','Card'].includes(m))||typeof c.active!=='boolean')throw Error('Verify provider name, clean HTTPS dashboard URL and payment methods; no credentials');}
}

