import type {Data} from './pool';
import {validDate} from './people-calendar';
export const propertySections=['Properties','Associations'] as const;
export const accountingSections=['Receivables','Payables','Financial Accounts','Journal Entries','Bank Transfers','GL Accounts','Diagnostics','Online Payments','DLA Analysis','Pool Allocation & Contracts','QBO Exports'] as const;
export const reportingSections=['Reports','Scheduled Reports','Metrics','Surveys','Compliance'] as const;
export type PropertySection=typeof propertySections[number];
export type AccountingSection=typeof accountingSections[number];
export type ReportingSection=typeof reportingSections[number];
export type PropertyGroup={id:string;name:string;propertyIds:string[];notes:string;active:boolean};
export type PropertyProfile={id:string;propertyId:string;kind:'Rental'|'Association'|'Unclassified';hidden:boolean;boardContact:string;statementInstructions:string;boardReportInstructions:string;notes:string};
export type FinancialAccount={id:string;name:string;institution:string;type:'Bank'|'Credit card';last4:string;propertyId:string;active:boolean;balance:number|null;balanceDate:string;reference:string;notes:string};
export type GLAccount={id:string;code:string;name:string;type:'Asset'|'Liability'|'Equity'|'Income'|'Expense';active:boolean;qboName:string;notes:string};
export type Journal={id:string;propertyId:string;date:string;description:string;status:'Draft'|'Recorded externally';reference:string;lines:{glId:string;debit:number;credit:number}[];notes:string};
export type Transfer={id:string;fromId:string;toId:string;date:string;cents:number;status:'Draft'|'Completed externally';reference:string;notes:string};
export type ReportPreset={id:string;name:string;report:string;propertyId:string;from:string;to:string;columns:string[];favorite:boolean;active:boolean;notes:string};
export type ReportSchedule={id:string;name:string;presetId:string;cadence:'Monthly'|'Weekly';nextDate:string;recipient:string;status:'Planned'|'Paused';notes:string};
export type SurveyResponse={id:string;propertyId:string;workOrderId:string;date:string;respondent:string;rating:number;comments:string;reference:string};
export type ComplianceRecord={id:string;propertyId:string;unitId:string;kind:'Violation'|'Architectural review';date:string;title:string;ruleId:string;status:'Draft'|'Open'|'In review'|'Resolved'|'Decision recorded externally';reference:string;notes:string};
export type AssociationRule={id:string;propertyId:string;title:string;text:string;active:boolean;reference:string};
export type MeetingAttendance={id:string;propertyId:string;date:string;name:string;unitId:string;notes:string};
export type OfficeTask={id:string;section:string;propertyId:string;task:string;date:string;status:'Draft'|'Prepared'|'Completed externally'|'Cancelled';reference:string;notes:string};
export type OfficeRecords={groups?:PropertyGroup[];profiles?:PropertyProfile[];accounts?:FinancialAccount[];glAccounts?:GLAccount[];journals?:Journal[];transfers?:Transfer[];presets?:ReportPreset[];schedules?:ReportSchedule[];surveys?:SurveyResponse[];compliance?:ComplianceRecord[];rules?:AssociationRule[];attendance?:MeetingAttendance[];tasks?:OfficeTask[]};
export type OfficeKey=keyof OfficeRecords;
const keys:OfficeKey[]=['groups','profiles','accounts','glAccounts','journals','transfers','presets','schedules','surveys','compliance','rules','attendance','tasks'];
export function validateOffice(old:Data,next:Data){const o=next.office??{},previous=old.office??{};const property=(id:string)=>{if(!next.properties.some(p=>p.id===id))throw Error('Choose a known property');};const unit=(id:string,pid:string)=>{if(id&&!next.units.some(u=>u.id===id&&u.propertyId===pid))throw Error('Unit belongs to another property');};const date=(v:string)=>{if(!validDate(v))throw Error('Enter a valid date');};const amount=(v:number)=>{if(!Number.isSafeInteger(v)||Math.abs(v)>100000000000)throw Error('Invalid amount');};
 for(const key of keys){const rows=o[key]??[];if(!Array.isArray(rows)||rows.length>10000||rows.some(r=>!r.id)||new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Invalid '+key);for(const r of previous[key]??[]){const n=rows.find(x=>x.id===r.id);if(!n)throw Error('Office history must be preserved');if((key==='journals'&&(r as Journal).status==='Recorded externally'||key==='transfers'&&(r as Transfer).status==='Completed externally')&&JSON.stringify(n)!==JSON.stringify(r))throw Error('Completed financial records are immutable; record a correction separately');}for(const row of rows)for(const value of Object.values(row))if(typeof value==='string'&&value.length>10000)throw Error('Record text is too long');}
 for(const g of o.groups??[]){if(!g.name.trim()||!Array.isArray(g.propertyIds)||!g.propertyIds.length||new Set(g.propertyIds).size!==g.propertyIds.length)throw Error('Group needs a name and unique properties');g.propertyIds.forEach(property);}
 const profiles=new Set<string>();for(const p of o.profiles??[]){property(p.propertyId);if(profiles.has(p.propertyId)||!['Rental','Association','Unclassified'].includes(p.kind)||typeof p.hidden!=='boolean')throw Error('Invalid or duplicate property profile');profiles.add(p.propertyId);}
 for(const a of o.accounts??[]){property(a.propertyId);if(!a.name.trim()||!['Bank','Credit card'].includes(a.type)||a.last4&&!/^\d{4}$/.test(a.last4))throw Error('Enter account name and only the last four digits');if(a.balance!==null){amount(a.balance);date(a.balanceDate);if(!a.reference.trim())throw Error('External balance requires a statement reference');}}
 const codes=new Set<string>();for(const g of o.glAccounts??[]){if(!g.code.trim()||!g.name.trim()||codes.has(g.code)||!['Asset','Liability','Equity','Income','Expense'].includes(g.type))throw Error('Duplicate or invalid GL account');codes.add(g.code);}
 for(const j of o.journals??[]){property(j.propertyId);date(j.date);if(!j.description.trim()||!['Draft','Recorded externally'].includes(j.status)||!Array.isArray(j.lines)||j.lines.length<2||j.lines.length>200)throw Error('Journal needs a description and at least two lines');let debit=0,credit=0;for(const l of j.lines){amount(l.debit);amount(l.credit);if(!o.glAccounts?.some(g=>g.id===l.glId)||l.debit<0||l.credit<0||l.debit&&l.credit)throw Error('Choose a GL account and either a debit or credit');debit+=l.debit;credit+=l.credit;}if(!debit||debit!==credit||!Number.isSafeInteger(debit))throw Error('Journal debits and credits must balance exactly');if(j.status==='Recorded externally'&&!j.reference.trim())throw Error('External journal requires a reference');}
 const transferRefs=new Set<string>();for(const t of o.transfers??[]){date(t.date);amount(t.cents);if(t.cents<=0||t.fromId===t.toId||!o.accounts?.some(a=>a.id===t.fromId)||!o.accounts?.some(a=>a.id===t.toId)||!['Draft','Completed externally'].includes(t.status))throw Error('Choose separate accounts and a positive transfer amount');if(t.status==='Completed externally'){const ref=t.reference.trim().toLowerCase();if(!ref||transferRefs.has(ref))throw Error('Duplicate or missing transfer reference');transferRefs.add(ref);}}
 for(const p of o.presets??[]){if(p.propertyId)property(p.propertyId);date(p.from);date(p.to);if(!p.name.trim()||!p.report.trim()||p.to<p.from||!Array.isArray(p.columns)||new Set(p.columns).size!==p.columns.length||p.columns.some(c=>typeof c!=='string'))throw Error('Invalid saved report');}
 for(const s of o.schedules??[]){date(s.nextDate);if(!s.name.trim()||!o.presets?.some(p=>p.id===s.presetId)||!['Monthly','Weekly'].includes(s.cadence)||!['Planned','Paused'].includes(s.status))throw Error('Choose saved report and valid schedule');}
 for(const s of o.surveys??[]){property(s.propertyId);date(s.date);const w=next.operations?.workOrders.find(w=>w.id===s.workOrderId);if(s.workOrderId&&(!w||!next.units.some(u=>u.id===w.unitId&&u.propertyId===s.propertyId))||!Number.isInteger(s.rating)||s.rating<1||s.rating>5||!s.reference.trim())throw Error('Survey needs rating 1–5, source reference and matching work order');}
 for(const c of o.compliance??[]){property(c.propertyId);unit(c.unitId,c.propertyId);date(c.date);if(!c.title.trim()||!['Violation','Architectural review'].includes(c.kind)||!['Draft','Open','In review','Resolved','Decision recorded externally'].includes(c.status)||c.ruleId&&!o.rules?.some(r=>r.id===c.ruleId&&r.propertyId===c.propertyId)||['Resolved','Decision recorded externally'].includes(c.status)&&!c.reference.trim())throw Error('Invalid compliance record or missing completion evidence');}
 for(const r of o.rules??[]){property(r.propertyId);if(!r.title.trim()||!r.text.trim())throw Error('Rule needs title and text');}
 for(const m of o.attendance??[]){property(m.propertyId);unit(m.unitId,m.propertyId);date(m.date);if(!m.name.trim())throw Error('Enter attendee name');}
 for(const t of o.tasks??[]){if(t.propertyId)property(t.propertyId);date(t.date);if(!t.task.trim()||!['Draft','Prepared','Completed externally','Cancelled'].includes(t.status)||t.status==='Completed externally'&&!t.reference.trim())throw Error('Task needs a name and external completion reference');}
}
