import {validateLeasingWorkflow,type RentalApplication,type LeasingShowing} from './leasing-workflow';
import {canonicalRecord} from './workflow-controls';
import {validateManualLeasing,type LeasingProvider,type ManualLeasingEvent} from './leasing-services';
export const workStatuses=['New','Assigned','Estimate requested','Estimated','Scheduled','Waiting','Work done, unbilled','Ready to bill','Completed'] as const;
export type WorkStatus=typeof workStatuses[number];
export type WorkOrder={permissionToEnter?:'Yes'|'No';entryInstructions?:string;id:string;number:string;unitId:string;title:string;description:string;status:WorkStatus;priority:'Normal'|'Urgent'|'Emergency';kind:'Repair'|'Inspection'|'Unit turn'|'Project';assignee:string;vendor:string;scheduled:string;followUp:string;estimate:number;hours100:number;rate:number;materials:number;ownerApproved:boolean;notes:string;created:string;updated:string};
export type CalendarEvent={id:string;title:string;date:string;end:string;unitId:string;kind:'Administrative'|'Announcements'|'Maintenance'|'Meeting'|'Showing';notes:string};
export type Communication={audience?:'Tenants'|'Owners'|'Other';id:string;recipient:string;unitId:string;subject:string;body:string;status:'Draft';created:string};
export type Prospect={phone?:string;source?:string;assignee?:string;moveIn?:string;followUp?:string;maxRent?:number;id:string;name:string;email:string;unitId:string;stage:'Inquiry'|'Tour scheduled'|'Application received'|'Lease prepared'|'Closed';tour:string;notes:string};
export type Lease={applicationId?:string;renewalOf?:string;id:string;unitId:string;tenant:string;tenantId?:string;signedDate?:string;start:string;end:string;rent:number;status:'Draft'|'Active'|'Ended';notes:string};
export type BankRecord={id:string;date:string;reference:string;description:string;cents:number;classification:'Pool'|'Agency'|'Unclassified';reviewed:boolean};
export type Occupancy={marketingStatus?:'Not recorded'|'Not listed'|'On market'|'Reserved';listedDate?:string;id:string;unitId:string;month:string;status:'Unknown'|'Vacant'|'Occupied'|'Make ready';notes:string};
export type Tenant={rentConfirmed?:boolean;secondFirstName?:string;secondLastName?:string;secondCell?:string;secondEmail?:string;specialInstructions?:string;id:string;unitId:string;firstName:string;lastName:string;email:string;cell:string;start:string;end:string;signedDate:string;rent:number;opening:number|null;openingDate:string;notes:string;address?:string;emergencyName?:string;emergencyCell?:string;pets?:string;vehicles?:string;vehiclePlate?:string;vehicleMake?:string;vehicleYear?:string;secondVehiclePlate?:string;secondVehicleMake?:string;secondVehicleYear?:string;unitKeyNumber?:string;mailKeyNumber?:string;insurance?:string};
export type TenantEntry={paymentMethod?:'Not provided'|'Check'|'Money Order'|"Cashier's Check";qboImportId?:string;qboSourceKey?:string;id:string;tenantId:string;category?:'Rent'|'Other';date:string;kind:"Charge"|"Receipt"|"Credit";description:string;cents:number;reference:string;recurringId?:string};
export type UnitVendor={id:string;unitId:string;name:string;email:string;cell:string;service:string;amount:number;start:string;end:string;notes:string};
export type TenantRecurring={category?:'Rent'|'Other';id:string;tenantId:string;description:string;cents:number;start:string;end:string};
export type VendorContact={id:string;name:string;company:string;phone:string;email:string;source:string};
export type TenantEntryRevision={id:string;entryId:string;before:TenantEntry;after:TenantEntry;reason:string;created:string};
export type RentAmendment={id:string;tenantId:string;unitId:string;from:string;before:number|null;cents:number;reason:string;created:string};
export type Operations={leasingProviders?:LeasingProvider[];manualLeasingEvents?:ManualLeasingEvent[];rentalApplications?:RentalApplication[];leasingShowings?:LeasingShowing[];rentAmendments?:RentAmendment[];tenantEntryRevisions?:TenantEntryRevision[];vendorContacts?:VendorContact[];tenants?:Tenant[];tenantEntries?:TenantEntry[];tenantRecurring?:TenantRecurring[];unitVendors?:UnitVendor[];occupancy?:Occupancy[];workOrders:WorkOrder[];events:CalendarEvent[];communications:Communication[];prospects:Prospect[];leases:Lease[];bankRecords:BankRecord[]};
export const emptyOperations=():Operations=>({workOrders:[],events:[],communications:[],prospects:[],leases:[],bankRecords:[]});
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T12:00:00'))&&new Date(v+'T12:00:00').toISOString().slice(0,10)===v;
export function validateOperations(ops:Operations,unitIds:Set<string>,old?:Operations){
 validateTenantRecords(ops,unitIds,old);
 validateLeasingWorkflow(ops,unitIds,old);
 validateManualLeasing(ops,unitIds,old);
 const amount=(n:number)=>{if(!Number.isSafeInteger(n)||Math.abs(n)>100000000000)throw Error('Invalid operational amount');};
 const unit=(id:string)=>{if(id&&!unitIds.has(id))throw Error('Unknown operational unit');};
 for(const key of ['workOrders','events','communications','prospects','leases','bankRecords'] as const){const rows=ops[key];if(!Array.isArray(rows)||rows.length>10000||new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Invalid '+key);for(const row of rows){if(!row.id)throw Error('Missing operational ID');}for(const row of old?.[key]??[]){if(!rows.some(x=>x.id===row.id))throw Error('Operational history must be preserved');}}
 const occupancyKeys=new Set<string>();for(const r of ops.occupancy??[]){if(r.marketingStatus!==undefined&&!['Not recorded','Not listed','On market','Reserved'].includes(r.marketingStatus))throw Error('Invalid marketing status');if(r.listedDate&&!validDate(r.listedDate))throw Error('Invalid listing date');unit(r.unitId);const key=r.unitId+':'+r.month;if(!r.id||!r.unitId||!/^\d{4}-(0[1-9]|1[0-2])$/.test(r.month)||!['Unknown','Vacant','Occupied','Make ready'].includes(r.status)||occupancyKeys.has(key))throw Error('Invalid or duplicate occupancy record');occupancyKeys.add(key);}
 const numbers=new Set<string>();for(const w of ops.workOrders){if(w.permissionToEnter!==undefined&&!['Yes','No'].includes(w.permissionToEnter))throw Error('Permission to enter must be Yes or No');if(w.entryInstructions!==undefined&&(typeof w.entryInstructions!=='string'||w.entryInstructions.length>2000))throw Error('Invalid work-order entry instructions');unit(w.unitId);if(!Number.isSafeInteger(w.hours100*w.rate))throw Error('Labor calculation exceeds supported precision');if(!w.title.trim()||!w.number.trim()||numbers.has(w.number)||!workStatuses.includes(w.status)||!['Normal','Urgent','Emergency'].includes(w.priority)||!['Repair','Inspection','Unit turn','Project'].includes(w.kind))throw Error('Invalid work order');numbers.add(w.number);[w.estimate,w.hours100,w.rate,w.materials].forEach(n=>{amount(n);if(n<0)throw Error('Negative work-order amount');});if(w.scheduled&&!validDate(w.scheduled)||w.followUp&&!validDate(w.followUp))throw Error('Invalid work-order date');if(w.status==='Assigned'&&!w.assignee.trim()&&!w.vendor.trim())throw Error('Assign a technician or vendor');if(w.status==='Scheduled'&&!w.scheduled)throw Error('Scheduled work requires a date');}
 for(const e of ops.events){unit(e.unitId);if(!['Administrative','Announcements','Maintenance'].includes(e.kind)&&!old?.events.some(x=>x.id===e.id&&x.kind===e.kind))throw Error('Calendar uses Administrative, Announcements and Maintenance only');if(!e.title.trim()||!validDate(e.date)||e.end&&(!validDate(e.end)||e.end<e.date)||!['Administrative','Announcements','Maintenance','Meeting','Showing'].includes(e.kind))throw Error('Invalid calendar event');}
 for(const m of ops.communications){unit(m.unitId);if(m.audience!==undefined&&!['Tenants','Owners','Other'].includes(m.audience))throw Error('Invalid communication audience');if(m.status!=='Draft'||!m.subject.trim()||!m.recipient.trim())throw Error('Only communication drafts are supported');}
 for(const p of ops.prospects){unit(p.unitId);if(!p.name.trim()||!['Inquiry','Tour scheduled','Application received','Lease prepared','Closed'].includes(p.stage)||p.tour&&!validDate(p.tour))throw Error('Invalid leasing prospect');}
 for(const l of ops.leases){if(l.tenantId&&!ops.tenants?.some(t=>t.id===l.tenantId&&t.unitId===l.unitId))throw Error('Lease tenant must belong to its unit');if(l.signedDate&&!validDate(l.signedDate))throw Error('Invalid lease signature date');unit(l.unitId);amount(l.rent);if(!l.unitId||!l.tenant.trim()||l.rent<0||!validDate(l.start)||!validDate(l.end)||l.end<l.start||!['Draft','Active','Ended'].includes(l.status))throw Error('Invalid lease');}
 for(const l of ops.leases.filter(l=>l.status==='Active'))if(ops.leases.some(x=>x.id!==l.id&&x.unitId===l.unitId&&x.status==='Active'&&x.start<=l.end&&x.end>=l.start))throw Error('Active leases overlap for this unit');
 const refs=new Set<string>();for(const r of ops.bankRecords){amount(r.cents);const ref=r.reference.trim().toLowerCase();if(!validDate(r.date)||!ref||refs.has(ref)||!['Pool','Agency','Unclassified'].includes(r.classification))throw Error('Duplicate or invalid bank reference');refs.add(ref);}
}
export function laborCost(w:WorkOrder){return Number((BigInt(w.hours100)*BigInt(w.rate)+BigInt(50))/BigInt(100));}
export function calendarActivities(ops:Operations){return [...ops.events.filter(e=>['Administrative','Announcements','Maintenance'].includes(e.kind)).map(e=>({id:e.id,date:e.date,end:e.end||e.date,title:e.title,unitId:e.unitId,kind:e.kind,source:'Event'})),...ops.workOrders.filter(w=>w.scheduled).map(w=>({id:w.id,date:w.scheduled,end:w.scheduled,title:w.number+' · '+w.title,unitId:w.unitId,kind:'Maintenance',source:'Work order'}))].sort((a,b)=>a.date.localeCompare(b.date));}

export function tenantBalance(ops:Operations,t:Tenant,through:string){return t.opening===null||through<t.openingDate?null:t.opening+(ops.tenantEntries??[]).filter(e=>e.tenantId===t.id&&e.date>=t.openingDate&&e.date<=through).reduce((n,e)=>n+(e.kind==='Charge'?e.cents:-e.cents),0);}
function validateTenantRecords(ops:Operations,units:Set<string>,old?:Operations){
 const contacts=ops.vendorContacts??[];if(!Array.isArray(contacts)||contacts.length>10000||new Set(contacts.map(v=>v.id)).size!==contacts.length||contacts.some(v=>!v.id||!v.name?.trim()||!v.source?.trim()||[v.company,v.phone,v.email].some(x=>typeof x!=='string')))throw Error('Invalid vendor directory');for(const v of old?.vendorContacts??[])if(!contacts.some(x=>x.id===v.id))throw Error('Preserve vendor directory history');
 for(const key of ['tenants','tenantEntries','tenantRecurring','unitVendors'] as const){const rows=ops[key]??[];if(!Array.isArray(rows)||rows.length>10000||new Set(rows.map(r=>r.id)).size!==rows.length||rows.some(r=>!r.id))throw Error('Invalid '+key);for(const r of old?.[key]??[]){const next=rows.find(x=>x.id===r.id);if(!next)throw Error('Tenant history must be preserved');if(key==='tenantEntries'&&canonicalRecord(next)!==canonicalRecord(r)){const revisions=(ops.tenantEntryRevisions??[]).filter(e=>e.entryId===r.id&&!old?.tenantEntryRevisions?.some(p=>p.id===e.id));if(revisions.length!==1||canonicalRecord(revisions[0].before)!==canonicalRecord(r)||canonicalRecord(revisions[0].after)!==canonicalRecord(next))throw Error('Posted tenant entries require a saved correction history');}}}
 const amount=(v:number)=>{if(!Number.isSafeInteger(v)||Math.abs(v)>100000000000)throw Error('Invalid tenant amount');};
 const date=(v:string)=>{if(!validDate(v))throw Error('Invalid tenant date');};
 const tenant=(id:string)=>{if(!(ops.tenants??[]).some(t=>t.id===id))throw Error('Unknown tenant');};
 for(const t of ops.tenants??[]){for(const key of ['secondFirstName','secondLastName','secondCell','secondEmail','specialInstructions'] as const)if(t[key]!==undefined&&(typeof t[key]!=='string'||t[key]!.length>2000))throw Error('Invalid second tenant or instructions');if(t.secondEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(t.secondEmail))throw Error('Invalid second tenant email');if((t.secondFirstName||t.secondLastName||t.secondEmail||t.secondCell)&&(!t.secondFirstName?.trim()||!t.secondLastName?.trim()))throw Error('Enter the second tenant first and last name');for(const key of ['pets','vehicles','vehiclePlate','vehicleMake','vehicleYear','secondVehiclePlate','secondVehicleMake','secondVehicleYear','unitKeyNumber','mailKeyNumber'] as const)if(t[key]!==undefined&&(typeof t[key]!=='string'||t[key]!.length>2000))throw Error('Invalid tenant property details');for(const year of [t.vehicleYear,t.secondVehicleYear])if(year&&!/^(19|20|21)\d{2}$/.test(year))throw Error('Vehicle year must be four digits');if(!units.has(t.unitId)||!t.firstName.trim()||!t.lastName.trim())throw Error('Tenant requires unit, first and last name');date(t.start);date(t.openingDate);if(t.end){date(t.end);if(t.end<t.start)throw Error('Tenant end precedes start');}if(t.signedDate)date(t.signedDate);amount(t.rent);if(t.rent<0)throw Error('Rent cannot be negative');if(t.opening!==null)amount(t.opening);if(t.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(t.email))throw Error('Invalid tenant email');const previous=old?.tenants?.find(x=>x.id===t.id);if(previous&&(old?.tenantEntries??[]).some(e=>e.tenantId===t.id)&&(previous.opening!==t.opening||previous.openingDate!==t.openingDate||previous.unitId!==t.unitId))throw Error('Opening balance and unit are locked after ledger posting');}
 const revisions=ops.tenantEntryRevisions??[];if(revisions.length>10000||new Set(revisions.map(r=>r.id)).size!==revisions.length)throw Error('Invalid tenant correction history');
 for(const r of old?.tenantEntryRevisions??[])if(!revisions.some(n=>canonicalRecord(n)===canonicalRecord(r)))throw Error('Tenant correction history must be preserved');
 for(const r of revisions){if(!r.id||r.entryId!==r.before.id||r.entryId!==r.after.id||!r.reason?.trim()||r.reason.length>2000||!Number.isFinite(Date.parse(r.created)))throw Error('Enter a correction reason');for(const key of ['id','tenantId','kind','category','recurringId','qboImportId','qboSourceKey'] as const)if(r.before[key]!==r.after[key])throw Error('Transaction identity and classification cannot be changed');const current=(ops.tenantEntries??[]).find(e=>e.id===r.entryId);if(!current)throw Error('Corrected transaction missing');if(!old?.tenantEntryRevisions?.some(e=>e.id===r.id)){const prior=old?.tenantEntries?.find(e=>e.id===r.entryId);if(!prior||canonicalRecord(prior)!==canonicalRecord(r.before)||canonicalRecord(current)!==canonicalRecord(r.after))throw Error('Correction must match the saved transaction');}}
 const refs=new Set<string>(),posts=new Set<string>();for(const e of ops.tenantEntries??[]){tenant(e.tenantId);date(e.date);amount(e.cents);if(e.cents<=0)throw Error('Enter a tenant ledger amount greater than zero');if(!e.description?.trim())throw Error('Enter a description or memo for the tenant ledger entry');if(!['Charge','Receipt','Credit'].includes(e.kind))throw Error('Choose a valid tenant transaction type');const t=ops.tenants!.find(t=>t.id===e.tenantId)!;if(e.date<t.openingDate)throw Error('Entry precedes opening balance date');if(e.kind==='Receipt'){const ref=e.reference.trim().toLowerCase();if(!ref||refs.has(ref))throw Error('Duplicate or missing tenant receipt reference');refs.add(ref);}if(e.recurringId){const key=e.recurringId+':'+e.date.slice(0,7);if(posts.has(key)||!(ops.tenantRecurring??[]).some(r=>r.id===e.recurringId&&r.tenantId===e.tenantId)||e.kind!=='Charge')throw Error('Duplicate or invalid recurring posting');posts.add(key);}}
 for(const r of ops.tenantRecurring??[]){tenant(r.tenantId);date(r.start);if(r.end){date(r.end);if(r.end<r.start)throw Error('Invalid recurring term');}amount(r.cents);if(r.cents<=0||!r.description.trim())throw Error('Invalid recurring charge');}
 for(const v of ops.unitVendors??[]){if(!units.has(v.unitId)||!v.name.trim()||!v.service.trim())throw Error('Vendor requires unit, name and service');amount(v.amount);if(v.amount<0)throw Error('Invalid vendor recurring amount');date(v.start);if(v.end){date(v.end);if(v.end<v.start)throw Error('Invalid vendor term');}}
}

export function workOrderPets(ops:Operations,unitId:string,date:string){return (ops.tenants??[]).filter(t=>t.unitId===unitId&&t.start<=date&&(!t.end||t.end>=date)).map(t=>({tenantId:t.id,name:t.firstName+' '+t.lastName,pets:t.pets?.trim()||'Not recorded'}));}


