import type {Data} from './pool';
import {canonicalRecord} from './workflow-controls';
import {native,bookChart,validateNativeAccounting,type LedgerEntry} from './native-accounting';
type Actor={id:string;reviewer:string;created:string};
export type PayableLine={accountKey:string;unitId:string;cents:number;description:string;serviceFrom:string;serviceTo:string};
export type PayableDocument=Actor&{bookId:string;kind:'Bill'|'Credit';payee:string;date:string;due:string;reference:string;source:string;payableKey:string;lines:PayableLine[];recurringId:string};
export type PayableDecision=Actor&{documentId:string;date:string;action:'Approved'|'On hold'|'Voided';reason:string};
export type PayableApplication=Actor&{billId:string;date:string;cents:number;paymentEntryId:string;creditId:string};
export type RecurringPayable=Actor&{ruleId:string;version:number;active:boolean;name:string;start:string;end:string;day:number;dueDays:number;document:Omit<PayableDocument,keyof Actor|'date'|'due'|'reference'|'recurringId'>};
export type PayablesLedger={documents:PayableDocument[];decisions:PayableDecision[];applications:PayableApplication[];rules:RecurringPayable[]};
export const payables=(d:Data):PayablesLedger=>d.accounting?.payablesLedger??{documents:[],decisions:[],applications:[],rules:[]};
const text=(v:unknown,max=2000):v is string=>typeof v==='string'&&!!v.trim()&&v.length<=max;
const date=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const month=(v:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(v);
const normalize=(v:string)=>v.trim().toLowerCase();
const amount=(v:number)=>Number.isSafeInteger(v)&&v>0&&v<=100000000000;
export const payableTotal=(r:PayableDocument)=>r.lines.reduce((n,l)=>n+l.cents,0);
export const payablePosting=(d:Data,id:string)=>native(d).entries.find(e=>e.sourceSystem==='OG payable'&&e.externalId===id);
export function payableAging(d:Data,bookId:string,through:string){
 const groups=new Map<string,{payee:string;current:number;days30:number;days60:number;days90:number;older:number;total:number;documentIds:string[]}>();
 for(const doc of payables(d).documents.filter(r=>r.bookId===bookId&&r.kind==='Bill'&&r.date<=through)){
  const state=payableState(d,doc,through);if(!['Open','Partially settled'].includes(state.status))continue;
  const row=groups.get(normalize(doc.payee))??{payee:doc.payee,current:0,days30:0,days60:0,days90:0,older:0,total:0,documentIds:[]},days=Math.floor((Date.parse(through+'T12:00:00Z')-Date.parse(doc.due+'T12:00:00Z'))/86400000),bucket=days<=0?'current':days<=30?'days30':days<=60?'days60':days<=90?'days90':'older';row[bucket]+=state.remaining;row.total+=state.remaining;row.documentIds.push(doc.id);groups.set(normalize(doc.payee),row);
 }return [...groups.values()].sort((a,b)=>a.payee.localeCompare(b.payee));
}
function reversed(d:Data,id:string,through:string){return native(d).entries.some(e=>e.reverses===id&&e.date<=through);}
export function payableState(d:Data,r:PayableDocument,through='9999-12-31'){
 const p=payables(d),entry=payablePosting(d,r.id),posting=entry&&entry.date<=through?entry:undefined,decision=p.decisions.filter(e=>e.documentId===r.id&&e.date<=through).at(-1);
 const applied=p.applications.filter(a=>a.date<=through&&(a.billId===r.id||a.creditId===r.id)).filter(a=>{const source=a.paymentEntryId?native(d).entries.find(e=>e.id===a.paymentEntryId):payablePosting(d,a.creditId);return source&&!reversed(d,source.id,through);}).reduce((n,a)=>n+a.cents,0),total=payableTotal(r);
 const status=posting&&reversed(d,posting.id,through)?'Posting reversed — review':posting?(applied>=total?'Settled':applied?'Partially settled':'Open'):decision?.action??'Pending approval';
 return {status,total,applied,remaining:Math.max(0,total-applied),posting,decision};
}
function currentRules(d:Data){const rules=new Map<string,RecurringPayable>();for(const r of payables(d).rules)rules.set(r.ruleId,r);return [...rules.values()];}
export function recurringPayablesDue(d:Data,period:string){return currentRules(d).filter(r=>r.active&&r.start<=period&&(!r.end||r.end>=period)&&!payables(d).documents.some(x=>x.recurringId&&payables(d).rules.find(p=>p.id===x.recurringId)?.ruleId===r.ruleId&&x.date.startsWith(period)));}
export function prepareRecurringPayable(d:Data,id:string,period:string,reviewer:string){const rule=recurringPayablesDue(d,period).find(r=>r.id===id);if(!rule||!text(reviewer))throw Error('Choose a current due recurring bill and reviewer');const day=Math.min(rule.day,new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),0)).getUTCDate()),postingDate=period+'-'+String(day).padStart(2,'0'),due=new Date(Date.parse(postingDate+'T12:00:00Z')+rule.dueDays*86400000).toISOString().slice(0,10);const next=structuredClone(d);next.accounting!.payablesLedger??=payables(next);next.accounting!.payablesLedger.documents.push({...structuredClone(rule.document),id:crypto.randomUUID(),reviewer,created:new Date().toISOString(),date:postingDate,due,reference:'RECUR-BILL-'+rule.ruleId+'-'+period,recurringId:rule.id});validatePayablesLedger(next,d);return next;}
export function postPayableDocument(d:Data,id:string,postingDate:string,reviewer:string,verified:boolean){const doc=payables(d).documents.find(r=>r.id===id);if(!doc||!verified||!text(reviewer)||payableState(d,doc).status!=='Approved'||payablePosting(d,id))throw Error('Approve and verify the original unposted bill or credit before posting');if(postingDate<doc.date)throw Error('Posting date cannot precede the source document');const next=structuredClone(d),total=payableTotal(doc),credit=doc.kind==='Credit';next.accounting!.native!.entries.push({id:crypto.randomUUID(),reviewer,created:new Date().toISOString(),bookId:doc.bookId,date:postingDate,reference:'AP-'+doc.reference,memo:doc.kind+' · '+doc.payee+' · '+doc.source,reverses:'',recurringId:'',sourceSystem:'OG payable',externalId:doc.id,lines:[...doc.lines.map(l=>({accountKey:l.accountKey,unitId:l.unitId,memo:l.description,debit:credit?0:l.cents,credit:credit?l.cents:0})),{accountKey:doc.payableKey,unitId:'',memo:doc.payee,debit:credit?total:0,credit:credit?0:total}]});validateNativeAccounting(next,d);validatePayablesLedger(next,d);return next;}
export function validatePayablesLedger(d:Data,old?:Data){const p=payables(d),prior=old?payables(old):{documents:[],decisions:[],applications:[],rules:[]};
 for(const key of ['documents','decisions','applications','rules'] as const){const records=p[key];if(!Array.isArray(records)||records.length>20000||new Set(records.map(r=>r.id)).size!==records.length||canonicalRecord(records.slice(0,prior[key].length))!==canonicalRecord(prior[key]))throw Error('Payable documents and review history are immutable');for(const r of records)if(!text(r.id,100)||!text(r.reviewer,200)||!Number.isFinite(Date.parse(r.created)))throw Error('Payables require a reviewer and timestamp');}
 function openDate(value:string){if(!date(value)||!d.periods.some(r=>r.month===value.slice(0,7)))throw Error('Choose an existing accounting month');if([...(old?.closeControls?.events??[])].reverse().find(e=>e.period===value.slice(0,7))?.kind==='Closed')throw Error('Reopen the month before changing payables');}
 function lines(doc:Pick<PayableDocument,'bookId'|'payableKey'|'lines'>){const chart=bookChart(d,doc.bookId),ap=chart?.accounts.find(a=>a.key===doc.payableKey);if(!ap?.active||ap.type.toLowerCase()!=='accounts payable'||!Array.isArray(doc.lines)||!doc.lines.length||doc.lines.length>99)throw Error('Select the company Accounts Payable GL and itemized lines');for(const l of doc.lines){const account=chart?.accounts.find(a=>a.key===l.accountKey);if(!account?.active||['bank','accounts payable','accounts receivable'].includes(account.type.toLowerCase())||!amount(l.cents)||!text(l.description,500)||typeof l.unitId!=='string'||l.unitId&&!d.units.some(u=>u.id===l.unitId)||l.serviceFrom&&!date(l.serviceFrom)||l.serviceTo&&(!date(l.serviceTo)||l.serviceFrom&&l.serviceTo<l.serviceFrom))throw Error('Verify itemized accounts, amounts, units and service dates');}if(!amount(doc.lines.reduce((n,l)=>n+l.cents,0)))throw Error('Payable total exceeds exact-cent limits');}
 const refs=new Set<string>();for(const r of p.documents){if(!native(d).books.some(b=>b.id===r.bookId)||!['Bill','Credit'].includes(r.kind)||!text(r.payee,200)||!date(r.date)||!date(r.due)||r.due<r.date||!text(r.reference,180)||!text(r.source)||typeof r.recurringId!=='string')throw Error('Verify payable company, payee, dates, original reference and source');lines(r);const ref=r.bookId+'|'+normalize(r.payee)+'|'+normalize(r.reference);if(refs.has(ref))throw Error('Duplicate supplier document reference');refs.add(ref);if(!prior.documents.some(x=>x.id===r.id)){openDate(r.date);if((d.invoiceImports??[]).some(b=>b.rows.some(i=>normalize(i.reference)===normalize(r.reference)&&normalize(i.vendor)===normalize(r.payee))))throw Error('Supplier invoice already imported; review its existing source instead of entering another bill');}if(r.recurringId){const rule=p.rules.find(x=>x.id===r.recurringId);if(!rule||r.bookId!==rule.document.bookId||canonicalRecord(r.lines)!==canonicalRecord(rule.document.lines)||r.payee!==rule.document.payee||r.payableKey!==rule.document.payableKey||r.kind!==rule.document.kind||r.date.slice(0,7)<rule.start||rule.end&&r.date.slice(0,7)>rule.end)throw Error('Recurring bill must preserve its reviewed template');if(p.documents.some(x=>x.id!==r.id&&x.date.slice(0,7)===r.date.slice(0,7)&&p.rules.find(t=>t.id===x.recurringId)?.ruleId===rule.ruleId))throw Error('Recurring bill already prepared for this month');}}
 for(const e of native(d).entries.filter(e=>e.sourceSystem==='OG payable')){const r=p.documents.find(x=>x.id===e.externalId),credit=r?.kind==='Credit';if(!r||e.bookId!==r.bookId||e.date<r.date||e.reverses||e.recurringId||e.reference!=='AP-'+r.reference||canonicalRecord(e.lines)!==canonicalRecord([...r.lines.map(l=>({accountKey:l.accountKey,unitId:l.unitId,memo:l.description,debit:credit?0:l.cents,credit:credit?l.cents:0})),{accountKey:r.payableKey,unitId:'',memo:r.payee,debit:credit?payableTotal(r):0,credit:credit?0:payableTotal(r)}]))throw Error('Payable posting must preserve the original itemized document');if(!native(old??d).entries.some(x=>x.id===e.id)&&p.decisions.filter(a=>a.documentId===r.id&&a.date<=e.date).at(-1)?.action!=='Approved')throw Error('Payable must be approved before ledger posting');}
 for(const e of p.decisions){const doc=p.documents.find(x=>x.id===e.documentId);if(!doc||!date(e.date)||e.date<doc.date||!['Approved','On hold','Voided'].includes(e.action)||!text(e.reason))throw Error('Verify payable decision, reason and date');if(!prior.decisions.some(x=>x.id===e.id)){openDate(e.date);const posting=payablePosting(d,doc.id);if(old&&payablePosting(old,doc.id)||posting&&(e.action!=='Approved'||e.date>posting.date))throw Error('Posted payable decisions are locked; use a reviewed credit or ledger correction');const prev=p.decisions.slice(0,p.decisions.indexOf(e)).filter(x=>x.documentId===doc.id).at(-1);if(prev?.action==='Voided'||prev&&e.date<prev.date)throw Error('Voided payable or decision chronology is locked');}}
 const available=new Map<string,number>(),creditApplied=new Map<string,number>();for(const a of p.applications){const bill=p.documents.find(r=>r.id===a.billId),credit=p.documents.find(r=>r.id===a.creditId),entry=a.paymentEntryId?native(d).entries.find(e=>e.id===a.paymentEntryId):credit?payablePosting(d,credit.id):undefined,billEntry=bill?payablePosting(d,bill.id):undefined;if(!bill||bill.kind!=='Bill'||!billEntry||!entry||!amount(a.cents)||!date(a.date)||a.date<billEntry.date||a.date<entry.date||!!a.paymentEntryId===!!a.creditId||entry.bookId!==bill.bookId)throw Error('Apply a posted payment or credit to a posted bill in the same company');if(credit&&(credit.kind!=='Credit'||credit.payee!==bill.payee||credit.payableKey!==bill.payableKey))throw Error('Supplier credit must belong to the same payee and payable account');if(a.paymentEntryId&&(!entry.lines.some(l=>bookChart(d,bill.bookId)?.accounts.find(x=>x.key===l.accountKey)?.type.toLowerCase()==='bank'&&l.credit>0)||entry.reverses))throw Error('Choose a posted bank payment, not a reversal or journal adjustment');
  const historical=prior.applications.some(x=>x.id===a.id);if(!historical){openDate(a.date);if(reversed(d,billEntry.id,a.date)||reversed(d,entry.id,a.date))throw Error('Reversed postings cannot settle a bill');}
  if(a.paymentEntryId){const key=entry.id+'|'+bill.payableKey,total=entry.lines.filter(l=>l.accountKey===bill.payableKey).reduce((n,l)=>n+l.debit-l.credit,0),used=(available.get(key)??0)+a.cents;if(used>total)throw Error('Payment applications exceed the posted payable debit');available.set(key,used);const payees=p.applications.slice(0,p.applications.indexOf(a)).filter(x=>x.paymentEntryId===entry.id).map(x=>p.documents.find(r=>r.id===x.billId)?.payee);if(payees.some(name=>name!==bill.payee))throw Error('A supplier payment cannot be applied to a different payee');}else{const used=(creditApplied.get(credit!.id)??0)+a.cents;if(used>payableTotal(credit!))throw Error('Supplier credit is already fully applied');creditApplied.set(credit!.id,used);}
  // A reversed payment releases its bill allocation while preserving the original application history.
  const used=p.applications.filter(x=>x.billId===bill.id&&x.date<=a.date).filter(x=>{const source=x.paymentEntryId?native(d).entries.find(e=>e.id===x.paymentEntryId):payablePosting(d,x.creditId);return source&&!reversed(d,source.id,a.date);}).reduce((n,x)=>n+x.cents,0);if(used>payableTotal(bill))throw Error('Bill applications exceed the original bill amount at the settlement date');
 }
 const versions=new Map<string,RecurringPayable>();for(const r of p.rules){const prev=versions.get(r.ruleId);if(!text(r.ruleId,100)||!text(r.name,200)||!month(r.start)||r.end&&(!month(r.end)||r.end<r.start)||!Number.isInteger(r.day)||r.day<1||r.day>31||!Number.isInteger(r.dueDays)||r.dueDays<0||r.dueDays>365||typeof r.active!=='boolean'||r.version!==(prev?.version??0)+1||prev&&canonicalRecord({...r.document})!==canonicalRecord({...prev.document}))throw Error('Verify recurring payable template and immutable revisions');if(!['Bill','Credit'].includes(r.document.kind)||!text(r.document.payee,200)||!text(r.document.source))throw Error('Recurring payable requires the original payee and source');lines(r.document);versions.set(r.ruleId,r);}
}
import {cents} from './pool';
import {parseCSV} from './exports';
export const payableBatchHeaders=['kind','payee','date','due','reference','source','payable_account','line_account','unit','amount','description','service_from','service_to'];
export function parsePayableBatch(d:Data,bookId:string,textValue:string,reviewer:string):PayableDocument[]{
 if(textValue.length>2000000||!text(reviewer,200))throw Error('Enter a reviewer and use a payable CSV no larger than 2 MB');
 const rows=parseCSV(textValue.replace(/^\uFEFF/,'')),header=(rows.shift()??[]).map(v=>v.trim());if(header.join('|')!==payableBatchHeaders.join('|')||!rows.length||rows.length>5000)throw Error('Use the payable template columns and 1–5000 itemized rows');
 const chart=bookChart(d,bookId);if(!chart)throw Error('Select an initialized company ledger');
 const groups=new Map<string,PayableDocument>();const resolve=(value:string)=>{const a=chart.accounts.filter(a=>a.active&&(a.key===value||a.number&&a.number===value));if(a.length!==1)throw Error('Unknown or ambiguous active account: '+value);return a[0].key;};
 for(const raw of rows){if(raw.length!==header.length)throw Error('Each payable row must contain all thirteen template columns');const [kind,payee,dateValue,due,reference,source,ap,account,unit,amountValue,description,serviceFrom,serviceTo]=raw.map(v=>v.trim());if(!['Bill','Credit'].includes(kind))throw Error('Document kind must be Bill or Credit');const units=unit?d.units.filter(u=>u.id===unit||u.number===unit):[];if(unit&&units.length!==1)throw Error('Unknown or ambiguous unit; use its ID: '+unit);const payableKey=resolve(ap),key=normalize(payee)+'|'+normalize(reference),prior=groups.get(key);if(prior&&(prior.kind!==kind||prior.date!==dateValue||prior.due!==due||prior.source!==source||prior.payableKey!==payableKey))throw Error('Itemized rows for one supplier reference must preserve the same document details');const doc=prior??{id:crypto.randomUUID(),bookId,kind:kind as 'Bill'|'Credit',payee,date:dateValue,due,reference,source,payableKey,lines:[],recurringId:'',reviewer:reviewer.trim(),created:new Date().toISOString()};doc.lines.push({accountKey:resolve(account),unitId:units[0]?.id??'',cents:cents(amountValue),description,serviceFrom,serviceTo});groups.set(key,doc);}
 const next=structuredClone(d);next.accounting!.payablesLedger??=payables(next);next.accounting!.payablesLedger.documents.push(...groups.values());validatePayablesLedger(next,d);return [...groups.values()];
}
export function importPayableBatch(d:Data,bookId:string,textValue:string,reviewer:string,verified:boolean){if(!verified)throw Error('Verify every original bill and credit before importing');const docs=parsePayableBatch(d,bookId,textValue,reviewer),next=structuredClone(d);next.accounting!.payablesLedger??=payables(next);next.accounting!.payablesLedger.documents.push(...docs);validatePayablesLedger(next,d);return next;}
export function approvePayableBatch(d:Data,ids:string[],dateValue:string,reason:string,reviewer:string,verified:boolean){if(!verified||!text(reviewer,200)||!text(reason)||!ids.length||new Set(ids).size!==ids.length)throw Error('Choose original documents and verify the approval reason and reviewer');const next=structuredClone(d);next.accounting!.payablesLedger??=payables(next);for(const id of ids){const doc=payables(d).documents.find(r=>r.id===id);if(!doc||!['Pending approval','On hold'].includes(payableState(d,doc).status))throw Error('Choose only unposted documents awaiting approval');next.accounting!.payablesLedger.decisions.push({id:crypto.randomUUID(),documentId:id,date:dateValue,action:'Approved',reason,reviewer,created:new Date().toISOString()});}validatePayablesLedger(next,d);return next;}
