import type {Data} from './pool';
import type {Operations,CalendarEvent} from './operations-model';
export const peopleSections=['Tenants','Homeowners','Owners','Vendors'] as const;
export type PeopleSection=typeof peopleSections[number];
export const calendarSections=['Association Calendar','Property Calendar'] as const;
export type CalendarSection=typeof calendarSections[number];
export type Homeowner={id:string;unitId:string;ownerId:string;name:string;email:string;phone:string;start:string;end:string;opening:number|null;openingDate:string;notes:string};
export type HomeownerEntry={id:string;homeownerId:string;date:string;kind:'Charge'|'Receipt'|'Credit';cents:number;description:string;reference:string};
export type VendorContact={id:string;name:string;email:string;phone:string;address:string;trade:string;status:'Active'|'Inactive';notes:string};
export type PeopleRequest={id:string;directory:PeopleSection;contactId:string;task:string;status:'Draft'|'Prepared'|'Completed externally'|'Cancelled';date:string;reference:string;notes:string};
export const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
export function validatePeopleCalendar(ops:Operations,units:Set<string>,old?:Operations){
 const amount=(v:number)=>{if(!Number.isSafeInteger(v)||Math.abs(v)>100000000000)throw Error('Invalid homeowner amount');};
 for(const key of ['homeowners','homeownerEntries','vendorContacts','peopleRequests'] as const){const rows=ops[key]??[];if(!Array.isArray(rows)||rows.length>10000||new Set(rows.map(r=>r.id)).size!==rows.length||rows.some(r=>!r.id))throw Error('Invalid '+key);for(const r of old?.[key]??[]){const next=rows.find(x=>x.id===r.id);if(!next)throw Error('People history must be preserved');if(key==='homeownerEntries'&&JSON.stringify(next)!==JSON.stringify(r))throw Error('Posted homeowner entries are immutable');}}
 for(const h of ops.homeowners??[]){if(!units.has(h.unitId)||!h.name.trim()||!validDate(h.start)||!validDate(h.openingDate)||h.end&&(!validDate(h.end)||h.end<h.start))throw Error('Invalid homeowner record');if(h.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(h.email))throw Error('Invalid homeowner email');if(h.opening!==null)amount(h.opening);const previous=old?.homeowners?.find(x=>x.id===h.id);if(previous&&old?.homeownerEntries?.some(e=>e.homeownerId===h.id)&&(h.unitId!==previous.unitId||h.opening!==previous.opening||h.openingDate!==previous.openingDate))throw Error('Homeowner opening and unit are locked after posting');}
 const refs=new Set<string>();for(const e of ops.homeownerEntries??[]){const h=ops.homeowners?.find(h=>h.id===e.homeownerId);amount(e.cents);if(!h||!validDate(e.date)||e.date<h.openingDate||e.cents<=0||!['Charge','Receipt','Credit'].includes(e.kind)||!e.description.trim())throw Error('Invalid homeowner ledger entry');if(e.kind==='Receipt'){const key=e.reference.trim().toLowerCase();if(!key||refs.has(key))throw Error('Duplicate or missing homeowner receipt reference');refs.add(key);}}
 for(const v of ops.vendorContacts??[]){if(!v.name.trim()||!v.trade.trim()||!['Active','Inactive'].includes(v.status)||v.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email))throw Error('Invalid vendor contact');}
 for(const r of ops.peopleRequests??[]){const contacts=r.directory==='Tenants'?ops.tenants:r.directory==='Homeowners'?ops.homeowners:r.directory==='Vendors'?[...(ops.vendorContacts??[]),...(ops.unitVendors??[])]:null;if(!peopleSections.includes(r.directory)||!r.contactId||contacts&&!contacts.some(c=>c.id===r.contactId)||!r.task.trim()||!validDate(r.date)||!['Draft','Prepared','Completed externally','Cancelled'].includes(r.status)||r.status==='Completed externally'&&!r.reference.trim())throw Error('Invalid contact request or external reference');}
 for(const e of ops.events){if(!e.title.trim()||!validDate(e.date)||e.end&&(!validDate(e.end)||e.end<e.date))throw Error('Invalid calendar dates or title');for(const key of ['location','assignee','attachmentReference','notes'] as const)if(e[key]!==undefined&&(typeof e[key]!=='string'||e[key]!.length>5000))throw Error('Invalid event details');if(e.allDay!==undefined&&typeof e.allDay!=='boolean')throw Error('Invalid all-day setting');if(e.calendar!==undefined&&!calendarSections.includes(e.calendar)||e.status!==undefined&&!['Scheduled','Completed','Cancelled'].includes(e.status)||e.audience!==undefined&&!['Staff','Homeowners','Tenants','Everyone'].includes(e.audience)||e.recurrence!==undefined&&!['None','Weekly','Monthly'].includes(e.recurrence))throw Error('Invalid calendar settings');if(e.recurrence&&e.recurrence!=='None'&&(!validDate(e.repeatUntil??'')||e.repeatUntil!<e.date||e.repeatUntil!>addDays(e.date,730)))throw Error('Recurring event needs an end within two years of '+e.date+'; received '+(e.repeatUntil||'blank'));if(e.allDay===false&&(!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.startTime??'')||!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.endTime??'')||(!e.end||e.end===e.date)&&e.endTime!<=e.startTime!))throw Error('Invalid event times');if(e.unitId&&e.propertyId!==undefined&&!e.propertyId)throw Error('Choose event property');}
}
export function validatePeopleRelationships(data:Data){for(const h of data.operations?.homeowners??[])if(h.ownerId&&!data.owners.some(o=>o.id===h.ownerId))throw Error('Unknown homeowner owner');for(const r of data.operations?.peopleRequests??[])if(r.directory==='Owners'&&!data.owners.some(o=>o.id===r.contactId))throw Error('Unknown request owner');for(const e of data.operations?.events??[]){if(e.propertyId&&!data.properties.some(p=>p.id===e.propertyId))throw Error('Unknown calendar property');if(e.unitId&&e.propertyId&&data.units.find(u=>u.id===e.unitId)?.propertyId!==e.propertyId)throw Error('Event unit belongs to another property');}}
export function homeownerBalance(ops:Operations,h:Homeowner,through:string){return h.opening===null||through<h.openingDate?null:h.opening+(ops.homeownerEntries??[]).filter(e=>e.homeownerId===h.id&&e.date>=h.openingDate&&e.date<=through).reduce((sum,e)=>sum+(e.kind==='Charge'?e.cents:-e.cents),0);}
export function addDays(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export type CalendarActivity={id:string;recordId:string;date:string;end:string;title:string;unitId:string;propertyId:string;kind:string;assignee:string;time:string;source:'Event'|'Work order'|'Prospect'|'Lease'|'Tenant'|'Showing slot';calendar:CalendarSection;status:string};
export function eventOccurrences(e:CalendarEvent,from:string,through:string){const dates:string[]=[];if(e.status==='Cancelled')return [];const until=e.recurrence&&e.recurrence!=='None'?e.repeatUntil??e.date:e.date;const duration=Math.round((Date.parse((e.end||e.date)+'T12:00:00Z')-Date.parse(e.date+'T12:00:00Z'))/86400000);for(let i=0;i<105;i++){let date=e.date;if(i){if(!e.recurrence||e.recurrence==='None')break;if(e.recurrence==='Weekly')date=addDays(e.date,i*7);else{const d=new Date(e.date+'T12:00:00Z'),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+i);const monthEnd=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,monthEnd));date=d.toISOString().slice(0,10);}}if(date>until||date>through)break;if(addDays(date,duration)>=from)dates.push(date);}return dates.map(date=>({date,end:addDays(date,duration)}));}
export function calendarActivities(data:Data,from:string,to:string):CalendarActivity[]{const ops=data.operations;if(!ops||!validDate(from)||!validDate(to)||from>to)return [];const property=(unitId:string)=>data.units.find(u=>u.id===unitId)?.propertyId??'';const rows:CalendarActivity[]=[];const push=(r:CalendarActivity)=>{if(r.date<=to&&r.end>=from)rows.push(r);};for(const e of ops.events)for(const d of eventOccurrences(e,from,to))push({id:e.id+':'+d.date,recordId:e.id,...d,title:e.title,unitId:e.unitId,propertyId:e.propertyId??property(e.unitId),kind:e.kind,assignee:e.assignee??'',time:e.allDay===false?(e.startTime??''):'All day',source:'Event',calendar:e.calendar??'Property Calendar',status:e.status??'Scheduled'});
 const activity=(id:string,date:string,title:string,unitId:string,kind:string,source:CalendarActivity['source'],assignee='',time='All day',status='Scheduled')=>push({id:source+':'+id+':'+kind,recordId:id,date,end:date,title,unitId,propertyId:property(unitId),kind,source,assignee,time,calendar:'Property Calendar',status});
 for(const w of ops.workOrders)if(w.scheduled)activity(w.id,w.scheduled,w.number+' · '+w.title,w.unitId,'Work Orders','Work order',w.assignee,'All day',w.status==='Completed'?'Completed':'Scheduled');
 for(const p of ops.prospects)if(p.tour)activity(p.id,p.tour,'Showing · '+p.name,p.unitId,'Showings','Prospect',p.agent);
 for(const s of ops.showingSlots??[])if(s.status!=='Cancelled')activity(s.id,s.date,'Showing availability · '+s.agent,s.unitId,'Showings','Showing slot',s.agent,s.time);
 for(const l of ops.leases)if(l.status==='Active')activity(l.id,l.end,'Lease ends · '+l.tenant,l.unitId,'Lease Ends','Lease');
 for(const t of ops.tenants??[]){activity(t.id,t.start,'Move in · '+t.firstName+' '+t.lastName,t.unitId,'Move Ins','Tenant');if(t.end)activity(t.id,t.end,'Move out · '+t.firstName+' '+t.lastName,t.unitId,'Move Outs','Tenant');}
 return rows.sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));}

