import {validateClose,type CloseControls} from './month-close';
import {canonicalRecord} from './workflow-controls';
import {validateGL,type GLControls} from './gl-controls';
import {validateFinance,calculatePool,verifiedFeeBasis,type FinanceControls} from './pool-finance';
import {validateTenantImports,type TenantImportBatch} from './tenant-import';
import {validateTenancyChanges} from './tenancy';
import {validateQboImports,type QboImportBatch} from './qbo-import';
import {validateClearing,type ClearingEvent} from './monthly-clearing';
import {validateStaffUsers,type StaffUser} from './staff-users';
import {type Accounting,validateAccounting} from './accounting-model';
import {type Procurement,validateProcurement} from './procurement-model';
import {type Operations,validateOperations} from './operations-model';
export type Expense={electricScope?:'Pool'|'Unit';laborPostId?:string;partsIssueId?:string;id:string;label:string;cents:number;recipient:string;classification:string;sharedId?:string;linkedUnitId?:string;gl?:string};
export type Statement={credits?:{id:string;label:string;cents:number;correctionId:string}[];allocationRunId?:string;id:string;unitId:string;ownerId:string;period:string;version:number;rent:number|null;allocated:number;opening:number;adjustments:number;expenses:Expense[];status:'Pending'|'Approved'|'Paid';cashPaid?:number;offsetPaid?:number;offsetReceived?:number;settlementId?:string;notes:string;ownerNotes?:string;paymentRef:string;paidDate:string;paidAmount:number;created:string;openingConfirmed?:boolean;allocationSource?:string;settingsVersion?:number};
export type Membership={id:string;unitId:string;month:string;active:boolean;reason:string;created:string};
export type Unit={id:string;number:string;propertyId:string;poolId:string;ownerId:string;type:1|2;participating:boolean;hoaChargedThrough?:string;addedMonth?:string};
export type Owner={id:string;name:string;email:string;address?:string;city?:string;state?:string;zip?:string;contactName?:string;phone?:string;taxIdType?:'Tax ID'|'EIN';taxIdLast4?:string;taxReference?:string;paymentMethod?:'Bank deposit'|'ACH'|'Mail'|'Office pickup';specialInstructions?:string};
export type Settings={id:string;period:string;poolId:string;version:number;rent1:number;rent2:number;management1:number;management2:number;maintenance1:number;maintenance2:number;hoa1:number;hoa2:number;electricTotal:number|null;electricConfirmed:boolean;notes:string};
export type Data={workMail?:import('./work-mail-model').WorkMail;closeControls?:CloseControls;finance?:FinanceControls;glControls?:GLControls;tenantImports?:TenantImportBatch[];workflow?:import('./workflow-controls').WorkflowControls;qboImports?:QboImportBatch[];clearingEvents?:ClearingEvent[];staffUsers?:StaffUser[];accounting?:Accounting;procurement?:Procurement;operations?:Operations;memberships?:Membership[];settings:Settings[];properties:{id:string;name:string;detailsVersion?:number;companyName?:string;address?:string;city?:string;state?:string;zip?:string;contactName?:string;phone?:string;email?:string}[];pools:{id:string;propertyId:string;name:string}[];units:Unit[];owners:Owner[];ownerships:{id:string;unitId:string;ownerId:string;from:string;to:string|null}[];periods:{id:string;month:string}[];rules:{id:string;version:number;method:string;verified:boolean}[];statements:Statement[];sharedExpenses:{id:string;period:string;poolId:string;label:string;total:number;allocations:{unitId:string;cents:number}[]}[];audit:{id:string;at:string;action:string;detail:string}[]};
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
export function cents(s:string):number{if(!/^-?\d+(\.\d{1,2})?$/.test(s.trim()))throw Error('Use dollars with no more than two decimal places.');const value=s.trim(),neg=value.startsWith('-');const [a,b='']=value.replace('-','').split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n)||Math.abs(n)>100000000000)throw Error('Amount is too large.');return neg?-n:n;}
export function poolElectricLine(e:Expense){return e.gl==='81000'&&!e.sharedId&&(e.electricScope==='Pool'||e.electricScope===undefined&&/^Pool electric/i.test(e.label));}
export function totals(s:Statement){const deductions=s.expenses.reduce((a,e)=>a+e.cents,0);const available=s.opening+s.allocated+s.adjustments+(s.credits??[]).reduce((n,e)=>n+e.cents,0)-deductions;return {deductions,available,closing:available-s.paidAmount+(s.offsetReceived??0)};}
export function latest(data:Data,period:string){const map=new Map<string,Statement>();for(const s of data.statements.filter(s=>s.period===period)){if(!map.has(s.unitId)||map.get(s.unitId)!.version<s.version)map.set(s.unitId,s);}return [...map.values()];}
export function audit(d:Data,action:string,detail:string){d.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),action,detail});}
export function validate(old:Data,next:Data){
 validateClose(old,next);
 validateTenantImports(old,next);
 validateQboImports(old,next);
 validateClearing(old,next);
 validateStaffUsers(old.staffUsers,next.staffUsers,next.properties.map(p=>p.id));
 validateProcurement(next,old);
 validateAccounting(next,old);
 if(next.operations)validateOperations(next.operations,new Set(next.units.map(u=>u.id)),old.operations);else if(old.operations)throw Error('Operations must be preserved');
 validateTenancyChanges(old,next);
 validateFinance(old,next);
 validateGL(old,next);
 const num=(n:unknown)=>{if(!Number.isSafeInteger(n)||Math.abs(Number(n))>100000000000)throw Error('Invalid financial amount');};
 if(!next||!Array.isArray(next.units)||next.units.length>5000||!Array.isArray(next.statements)||next.statements.length>20000)throw Error('Invalid dataset');
 for(const key of ['properties','pools','units','owners','ownerships','periods','rules','statements','sharedExpenses','audit','settings'] as const){if(!Array.isArray(next[key]))throw Error('Missing records: '+key);const ids=next[key].map((x:any)=>x.id);if(new Set(ids).size!==ids.length)throw Error('Duplicate record ID');}
 for(const p of next.properties){if(!p.name.trim()||p.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))throw Error('Enter a property name and valid contact email');for(const key of ['companyName','address','city','state','zip','contactName','phone','email'] as const)if(p[key]!==undefined&&(typeof p[key]!=='string'||p[key]!.length>500))throw Error('Invalid property contact information');}
 for(const o of next.owners){for(const key of ['address','city','state','zip','contactName','phone','taxReference','specialInstructions'] as const)if(o[key]!==undefined&&(typeof o[key]!=='string'||o[key]!.length>2000))throw Error('Invalid owner details');if(o.taxIdLast4&&!/^\d{4}$/.test(o.taxIdLast4))throw Error('Store only the last four Tax ID/EIN digits in the prototype');if(o.taxIdType&&!['Tax ID','EIN'].includes(o.taxIdType)||o.paymentMethod&&!['Bank deposit','ACH','Mail','Office pickup'].includes(o.paymentMethod))throw Error('Invalid owner tax type or payment preference');}
 const unitIds=new Set(next.units.map(u=>u.id)),ownerIds=new Set(next.owners.map(o=>o.id));
 const numbers=next.units.map(u=>u.propertyId+':'+u.number.trim().toLowerCase());if(new Set(numbers).size!==numbers.length)throw Error('Duplicate unit number');
 for(const u of next.units){if(!u.number.trim()||!ownerIds.has(u.ownerId)||!next.pools.some(p=>p.id===u.poolId&&p.propertyId===u.propertyId))throw Error('Invalid unit relationship');}
 for(const u of old.units){const n=next.units.find(x=>x.id===u.id);if(!n)throw Error('Retire units without removing history');if(n.participating!==u.participating||n.addedMonth!==u.addedMonth)throw Error('Use effective membership changes');}
 for(const m of next.memberships??[])if(m.active&&!(old.memberships??[]).some(o=>o.id===m.id)){const unit=next.units.find(u=>u.id===m.unitId),owner=next.owners.find(o=>o.id===unit?.ownerId);if(!owner?.address?.trim()||!owner.phone?.trim()||!owner.paymentMethod)throw Error('Complete owner address, phone and payment preference before activation');}
 const membershipKeys=new Set<string>();for(const e of next.memberships??[]){const key=e.unitId+':'+e.month;if(!unitIds.has(e.unitId)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(e.month)||typeof e.active!=='boolean'||!e.reason.trim()||membershipKeys.has(key))throw Error('Invalid or duplicate membership change');membershipKeys.add(key);}if(new Set((next.memberships??[]).map(e=>e.id)).size!==(next.memberships??[]).length)throw Error('Duplicate membership ID');for(const e of old.memberships??[]){if(!(next.memberships??[]).some(n=>JSON.stringify(n)===JSON.stringify(e)))throw Error('Membership history must be preserved');}
 for(const r of next.ownerships){if(!unitIds.has(r.unitId)||!ownerIds.has(r.ownerId)||!/^\d{4}-\d{2}-\d{2}$/.test(r.from)||r.to&&(r.to<r.from||!/^\d{4}-\d{2}-\d{2}$/.test(r.to)))throw Error('Invalid ownership dates');if(next.ownerships.some(x=>x.id!==r.id&&x.unitId===r.unitId&&x.from<=(r.to??'9999-12-31')&&r.from<=(x.to??'9999-12-31')))throw Error('Ownership dates overlap');}
 for(const r of old.ownerships){const n=next.ownerships.find(x=>x.id===r.id);if(!n||n.ownerId!==r.ownerId||n.unitId!==r.unitId||n.from!==r.from||r.to!==null&&r.to!==n.to)throw Error('Ownership history is locked');if(r.to===null&&n.to!==null&&!next.ownerships.some(x=>x.unitId===r.unitId&&x.from===new Date(Date.parse(n.to+'T12:00:00Z')+86400000).toISOString().slice(0,10)))throw Error('Close ownership only with a linked transfer');}
 const versions=new Set<string>(),refs=new Map<string,string>();
 for(const s of next.statements){if(!unitIds.has(s.unitId)||!ownerIds.has(s.ownerId)||!/^\d{4}-\d{2}$/.test(s.period)||!Number.isInteger(s.version)||s.version<1)throw Error('Invalid statement');const v=s.unitId+':'+s.period+':'+s.version;if(versions.has(v))throw Error('Duplicate statement version');versions.add(v);[s.allocated,s.opening,s.adjustments,s.paidAmount].forEach(num);if(s.rent!==null)num(s.rent);if((s.rent!==null&&s.rent<0)||s.allocated<0||s.paidAmount<0)throw Error('Income and payments cannot be negative');if(!Array.isArray(s.expenses)||s.expenses.length>500)throw Error('Invalid expenses');for(const c of s.credits??[]){num(c.cents);if(c.cents<=0||!c.label.trim())throw Error('Invalid owner credit');}const ei=new Set<string>();for(const e of s.expenses){num(e.cents);if(e.cents<0||!e.label.trim()||ei.has(e.id))throw Error('Invalid expense');ei.add(e.id);}
 if(s.status!=='Pending'&&old.statements.find(o=>o.id===s.id)?.status!=='Approved'&&old.statements.find(o=>o.id===s.id)?.status!=='Paid'&&next.finance?.reviews.some(r=>r.inputs.period===s.period&&r.inputs.poolId===next.units.find(u=>u.id===s.unitId)?.poolId)&&allocationNeedsReview(next,next.units.find(u=>u.id===s.unitId)!.poolId,s.period))throw Error('Review and apply current collected rent before approving distributions; forecasts do not establish funds');
 if(s.status!=='Pending'&&old.statements.find(o=>o.id===s.id)?.status!=='Approved'&&old.statements.find(o=>o.id===s.id)?.status!=='Paid'&&next.finance?.reviews.some(r=>r.inputs.period===s.period&&r.inputs.poolId===next.units.find(u=>u.id===s.unitId)?.poolId)&&isParticipating(next,next.units.find(u=>u.id===s.unitId)!,s.period)&&(!effectiveContract(next,s.unitId,s.period)||['80300','80400'].some(gl=>s.expenses.filter(e=>e.gl===gl&&!e.sharedId).length!==1||!verifiedFeeBasis(next,s.period,s.expenses.find(e=>e.gl===gl&&!e.sharedId)?.id??''))))throw Error('Confirm the effective unit fee agreement and calculated fee amounts before owner approval');
 if(s.status!=='Pending'&&!s.openingConfirmed)throw Error('Confirm the opening balance before approval');
 if(!['Pending','Approved','Paid'].includes(s.status))throw Error('Invalid status');
 if(!s.settlementId&&(s.cashPaid!==undefined||s.offsetPaid!==undefined))throw Error('Cash and offset fields require a combined settlement');if(s.status==='Paid'){if(!s.paymentRef.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(s.paidDate)||s.paidAmount!==totals(s).available||s.paidAmount<=0)throw Error('Paid requires positive exact amount, date, and reference');const ref=s.paymentRef.trim().toLowerCase();if(refs.has(ref)&&(!s.settlementId||refs.get(ref)!==s.settlementId))throw Error('Duplicate payment reference');refs.set(ref,s.settlementId??s.id);}
 }
 for(const s of old.statements){const n=next.statements.find(n=>n.id===s.id);if(!n)throw Error('Original statements must be preserved');if(s.status==='Pending'&&n.status==='Paid')throw Error('Approve the statement before recording a payment');if(s.status==='Paid'&&JSON.stringify(n)!==JSON.stringify(s))throw Error('Paid statements are locked');if(s.status==='Approved'){const {status:a,paymentRef:b,paidDate:c,paidAmount:d,cashPaid:i,offsetPaid:j,offsetReceived:k,settlementId:l,...locked}=s;const {status:e,paymentRef:f,paidDate:g,paidAmount:h,cashPaid:cashNext,offsetPaid:offsetNext,offsetReceived:receivedNext,settlementId:settlementNext,...candidate}=n;if(JSON.stringify(locked)!==JSON.stringify(candidate)||!['Approved','Paid'].includes(n.status))throw Error('Approved statement is locked; create a new version');}}
 for(const s of old.statements.filter(s=>s.offsetReceived)){if(next.statements.some(x=>x.unitId===s.unitId&&x.period===s.period&&x.version>s.version))throw Error('Settled HOA statement cannot be superseded');}
 for(const s of next.statements.filter(s=>s.status==='Paid')){if(next.statements.some(x=>x.unitId===s.unitId&&x.period===s.period&&x.version>s.version))throw Error('Only the latest statement version can be paid');if(next.statements.filter(x=>x.unitId===s.unitId&&x.period===s.period&&x.status==='Paid').length>1)throw Error('A distribution is already paid for this unit and month');}
 for(const x of next.settings){[x.rent1,x.rent2,x.management1,x.management2,x.maintenance1,x.maintenance2,x.hoa1,x.hoa2].forEach(n=>{num(n);if(n<0)throw Error('Settings amounts cannot be negative');});if(x.electricTotal!==null){num(x.electricTotal);if(x.electricTotal<0)throw Error('Electricity total cannot be negative');}if(x.electricConfirmed&&x.electricTotal===null)throw Error('Confirmed electricity requires a total');}
 for(const entry of old.audit){if(!next.audit.some(x=>JSON.stringify(x)===JSON.stringify(entry)))throw Error('Audit history cannot be removed');}
 for(const x of next.sharedExpenses){num(x.total);if(x.total<0||!next.pools.some(p=>p.id===x.poolId))throw Error('Invalid shared expense');let sum=0;const seen=new Set();for(const a of x.allocations){num(a.cents);if(a.cents<0||seen.has(a.unitId)||!next.units.some(u=>u.id===a.unitId&&u.poolId===x.poolId))throw Error('Invalid shared allocation');seen.add(a.unitId);sum+=a.cents;}if(sum!==x.total)throw Error('Shared allocations must equal the bill exactly');}
}

export function electricShares(total:number,units:Unit[]){if(!Number.isSafeInteger(total)||total<0)throw Error('Invalid electricity total');const ids=units.filter(u=>u.participating).map(u=>u.id).sort();if(!ids.length)throw Error('No participating units');const base=Math.floor(total/ids.length),remainder=total%ids.length;return new Map(ids.map((id,i)=>[id,base+(i<remainder?1:0)]));}
export function draftFor(d:Data,u:Unit,setting:Settings):Statement{const t=u.type;const charges:Expense[]=[];const add=(label:string,n:number,gl:string,classification:string,linkedUnitId?:string)=>charges.push({id:crypto.randomUUID(),label,cents:n,gl,recipient:'Confirm recipient',classification,linkedUnitId});
 if(!u.hoaChargedThrough)add('HOA · Unit '+u.number,t===1?setting.hoa1:setting.hoa2,'80000','Owner HOA expense',u.id);
 const participating=isParticipating(d,u,setting.period);if(participating){add('Management fee',t===1?setting.management1:setting.management2,'80400','Agency fee — CPA review');add('Monthly maintenance fee',t===1?setting.maintenance1:setting.maintenance2,'80300','Agency fee — CPA review');if(setting.electricTotal!==null)add('Pool electricity',periodElectricShares(d,setting).get(u.id)??0,'81000','Electricity pass-through');}
 for(const other of d.units.filter(x=>x.hoaChargedThrough===u.id))add('HOA · Private Unit '+other.number,other.type===1?setting.hoa1:setting.hoa2,'80000','Owner HOA expense',other.id);
 const prev=d.statements.filter(s=>s.unitId===u.id&&s.period===setting.period);const result:Statement={id:crypto.randomUUID(),unitId:u.id,ownerId:ownerAt(d,u.id,setting.period+'-01'),period:setting.period,version:Math.max(0,...prev.map(s=>s.version))+1,rent:null,allocated:participating?(t===1?setting.rent1:setting.rent2):0,opening:0,openingConfirmed:false,adjustments:0,expenses:charges,status:'Pending',notes:'Opening balance must be confirmed. Actual rent not imported. '+(setting.electricTotal===null?'Electricity bill total pending. ':''),paymentRef:'',paidDate:'',paidAmount:0,created:new Date().toISOString(),allocationSource:'Monthly pool rent by unit type; settings version '+setting.version,settingsVersion:setting.version};applyContracts(d,result);return result;}

export function isParticipating(d:Data,u:Unit,month:string){if(u.addedMonth&&u.addedMonth>month)return false;const changes=(d.memberships??[]).filter(e=>e.unitId===u.id&&e.month<=month).sort((a,b)=>b.month.localeCompare(a.month));return changes[0]?.active??u.participating;}
export function periodElectricShares(d:Data,setting:Settings){if(setting.electricTotal===null)return new Map<string,number>();const market=[...(d.finance?.reviews??[])].reverse().find(r=>r.inputs.poolId===setting.poolId&&r.inputs.period===setting.period)?.inputs.marketIds??[];const units=d.units.filter(u=>u.poolId===setting.poolId&&isParticipating(d,u,setting.period)&&!market.includes(u.id));if(!units.length&&setting.electricTotal===0)return new Map<string,number>();return electricShares(setting.electricTotal,units.map(u=>({...u,participating:true})));}
export function refreshPoolDrafts(d:Data,setting:Settings){
 const statements=latest(d,setting.period).filter(s=>d.units.find(u=>u.id===s.unitId)?.poolId===setting.poolId);const locked=statements.filter(s=>s.status!=='Pending');const active=d.units.filter(u=>u.poolId===setting.poolId&&isParticipating(d,u,setting.period));let shares=new Map<string,number>();
 if(setting.electricTotal!==null){const lockedCharge=locked.reduce((n,s)=>n+s.expenses.filter(e=>poolElectricLine(e)).reduce((n,e)=>n+e.cents,0),0);const remainder=setting.electricTotal-lockedCharge;if(remainder<0)throw Error('Bill total is less than approved electricity charges. Create revised statement versions before reallocating.');const market=[...(d.finance?.reviews??[])].reverse().find(r=>r.inputs.poolId===setting.poolId&&r.inputs.period===setting.period)?.inputs.marketIds??[];const pendingUnits=active.filter(u=>!market.includes(u.id)&&!locked.some(s=>s.unitId===u.id));if(pendingUnits.length)shares=electricShares(remainder,pendingUnits.map(u=>({...u,participating:true})));else if(remainder)throw Error('No editable participating statements can receive the electricity remainder.');}
 for(const old of statements.filter(s=>s.status==='Pending')){const u=d.units.find(u=>u.id===old.unitId)!;const generated=draftFor(d,u,{...setting,electricTotal:null});applyContracts(d,generated);if(setting.electricTotal!==null&&shares.has(u.id))generated.expenses.push({id:crypto.randomUUID(),label:'Pool electricity',cents:shares.get(u.id)??0,recipient:'Confirm recipient',classification:'Electricity pass-through',gl:'81000'});
 const standard=(e:Expense)=>(['80000','80400','80300'].includes(e.gl??'')&&!e.sharedId)||poolElectricLine(e);
 generated.expenses=generated.expenses.map(e=>{const prior=old.expenses.find(p=>p.label===e.label||(poolElectricLine(e)&&poolElectricLine(p)));return prior?{...e,id:prior.id,recipient:prior.recipient,classification:prior.classification}:e;});
 // Retain zero-value recurring lines so existing supporting-document links stay recoverable.
 old.expenses=[...generated.expenses,...old.expenses.filter(e=>!standard(e)),...old.expenses.filter(e=>standard(e)&&!generated.expenses.some(n=>n.label===e.label||n.id===e.id)).map(e=>({...e,cents:0}))];
 if(!old.allocationRunId&&!old.allocationSource?.startsWith('Manual override'))old.allocated=generated.allocated;applyContracts(d,old);old.settingsVersion=setting.version;if(!old.allocationRunId)old.allocationSource=(old.allocationSource?.startsWith('Manual override')?'Manual override; ':'')+'Monthly settings v'+setting.version+'; '+active.length+' active units; approved electricity shares retained';
 }
 return {drafts:statements.filter(s=>s.status==='Pending').length,locked:locked.length,participants:active.length};
}

export function ownerAt(d:Data,unitId:string,date:string){return d.ownerships.filter(r=>r.unitId===unitId&&r.from<=date&&(!r.to||r.to>=date)).sort((a,b)=>b.from.localeCompare(a.from))[0]?.ownerId??d.units.find(u=>u.id===unitId)?.ownerId??'';}
export function effectiveContract(d:Data,unitId:string,period:string){return d.accounting?.contracts.filter(c=>c.unitId===unitId&&c.from<=period).sort((a,b)=>b.from.localeCompare(a.from))[0];}
export function allocationNeedsReview(d:Data,poolId:string,period:string){const run=d.accounting?.allocations.filter(r=>r.poolId===poolId&&r.period===period).sort((a,b)=>b.version-a.version)[0];if(!run)return true;if(run.financeReviewId){const r=d.finance?.reviews.find(r=>r.id===run.financeReviewId);if(!r||r.inputs.basis!=='Collected rent')return true;try{const {blockers,...current}=calculatePool(d,r.inputs);const {blockers:prior,...saved}=r.calculation;if(canonicalRecord(current)!==canonicalRecord(saved))return true;}catch{return true;}}const ids=d.units.filter(u=>u.poolId===poolId&&isParticipating(d,u,period)).map(u=>u.id).sort();return JSON.stringify(ids)!==JSON.stringify([...run.activeIds].sort())||latest(d,period).some(s=>ids.includes(s.unitId)&&(s.allocationRunId!==run.id||s.allocationSource?.startsWith('Manual override')));}
export function applyContracts(d:Data,s:Statement){const c=effectiveContract(d,s.unitId,s.period);for(const e of s.expenses){if(e.gl==='80400'&&c)e.cents=c.managementKind==='Percent'?Math.floor((s.allocated*c.management+5000)/10000):c.management;if(e.gl==='80300'&&c)e.cents=c.maintenance;if(e.gl==='80000'){const hoa=effectiveContract(d,e.linkedUnitId??s.unitId,s.period);if(hoa){e.cents=hoa.hoa;if(!s.notes.includes('Contract source: '+hoa.source))s.notes+=' Contract source: '+hoa.source;}}}if(c&&!s.notes.includes('Contract source: '+c.source))s.notes+=' Contract source: '+c.source;}

export function applyDevonshirePropertyDetails(d:Data){const p=d.properties.find(p=>p.id==='property-devonshire');if(p&&!p.detailsVersion){Object.assign(p,{companyName:p.companyName||'Devonshire Leasing Agency, Inc.',address:p.address||'11843 Braesview, Main Office',city:p.city||'San Antonio',state:p.state||'TX',zip:p.zip||'78213',phone:p.phone||'210-493-3161',detailsVersion:1});}return d;}
