import {verifiedGL} from './gl-controls';
import {audit,isParticipating,latest,applyContracts,effectiveContract,poolElectricLine,type Data} from './pool';
import {emptyAccounting,officeRent,incomeRows} from './accounting-model';
import {expectedUnitRent,monthBounds} from './tenancy';
import {canonicalRecord} from './workflow-controls';

export type PoolInputs={poolId:string;period:string;basis:'Collected rent'|'Reviewed forecast';forecast:number|null;method:'Equal shares'|'Reviewed type weights';weight1:number;weight2:number;marketIds:string[];bills:{unitId:string;cents:number;reference:string}[];electricConfirmed:boolean;source:string;reviewer:string};
export type PoolReview={id:string;created:string;version:number;inputs:PoolInputs;calculation:ReturnType<typeof calculatePool>};
export type FinanceControls={reviews:PoolReview[]};
const amount=(n:number)=>{if(!Number.isSafeInteger(n)||n<0||n>100000000000)throw Error('Use a nonnegative amount in exact cents');};
export function weightedShares(total:number,rows:{unitId:string;weight:number}[]){amount(total);if(!rows.length||new Set(rows.map(r=>r.unitId)).size!==rows.length||rows.some(r=>!Number.isSafeInteger(r.weight)||r.weight<1||r.weight>1000000))throw Error('Enter positive integer weights for a unique roster');const ordered=[...rows].sort((a,b)=>a.unitId.localeCompare(b.unitId)),den=ordered.reduce((n,r)=>n+BigInt(r.weight),BigInt(0));const values=ordered.map(r=>{const n=BigInt(total)*BigInt(r.weight);return {unitId:r.unitId,cents:Number(n/den),remainder:n%den};});let left=total-values.reduce((n,r)=>n+r.cents,0);const ranking=[...values].sort((a,b)=>a.remainder===b.remainder?a.unitId.localeCompare(b.unitId):a.remainder>b.remainder?-1:1);for(let i=0;i<left;i++)ranking[i].cents++;return values.map(({unitId,cents})=>({unitId,cents}));}
export function calculatePool(d:Data,input:PoolInputs){
 monthBounds(input.period);if(!d.periods.some(p=>p.month===input.period)||!d.pools.some(p=>p.id===input.poolId))throw Error('Select an open month and pool');if(!['Collected rent','Reviewed forecast'].includes(input.basis)||!['Equal shares','Reviewed type weights'].includes(input.method))throw Error('Invalid calculation basis or method');if(!input.source.trim()||!input.reviewer.trim())throw Error('Enter the calculation source and reviewer');
 const active=d.units.filter(u=>u.poolId===input.poolId&&isParticipating(d,u,input.period)).sort((a,b)=>a.id.localeCompare(b.id));if(!active.length)throw Error('No participating units');const ids=new Set(active.map(u=>u.id));if(new Set(input.marketIds).size!==input.marketIds.length||input.marketIds.some(id=>!ids.has(id)))throw Error('Market exclusions must be distinct participating units');
 const receipts=(d.operations?.tenantEntries??[]).filter(e=>e.kind==='Receipt'&&e.date.startsWith(input.period));const applications=d.accounting?.applications??[];
 const sources=active.map(u=>{const expected=expectedUnitRent(d,u,input.period),recorded=officeRent(d,u.id,input.period);const vac=d.operations?.occupancy?.find(o=>o.unitId===u.id&&o.month===input.period)?.status==='Vacant';return {unitId:u.id,number:u.number,type:u.type,expected:expected.cents,expectedSource:expected.source,collected:recorded.source==='Matched rent receipts'?recorded.cents??0:0,recordedSource:recorded.source,vacant:vac,weight:input.method==='Equal shares'?1:u.type===1?input.weight1:input.weight2};});
 const unmatched=receipts.filter(r=>d.operations?.tenants?.some(t=>t.id===r.tenantId&&ids.has(t.unitId))).reduce((n,r)=>n+Math.max(0,r.cents-applications.filter(a=>a.receiptId===r.id).reduce((s,a)=>s+a.cents,0)),0);
 const collected=sources.reduce((n,r)=>n+r.collected,0);if(input.basis==='Reviewed forecast')amount(input.forecast!);const total=input.basis==='Collected rent'?collected:input.forecast!;
 const blockers:string[]=[];if(sources.some(r=>r.vacant&&r.expected===null))blockers.push('Resolve vacancy/tenant conflicts before applying.');if(unmatched)blockers.push('Apply or review unmatched tenant cash before allocating collected rent.');if(input.basis==='Collected rent'&&sources.some(r=>r.recordedSource!=='Matched rent receipts'&&!r.vacant))blockers.push('Verify missing rent through tenant charges and receipt applications; manual office rent is excluded.');
 const electricIds=active.filter(u=>!input.marketIds.includes(u.id)).map(u=>u.id),refs=new Set<string>();for(const b of input.bills){amount(b.cents);if(!electricIds.includes(b.unitId)||!sources.find(r=>r.unitId===b.unitId)?.vacant||!b.reference.trim()||refs.has(b.reference.trim().toLowerCase()))throw Error('CPS bills require eligible verified-vacant units and unique source references');refs.add(b.reference.trim().toLowerCase());}const electricTotal=input.bills.reduce((n,b)=>n+b.cents,0);amount(electricTotal);if(!input.electricConfirmed)blockers.push('Confirm CPS bills or a reviewed zero-electric month.');if(electricTotal&&!electricIds.length)throw Error('No eligible units for pooled electricity');
 const shares=weightedShares(total,sources.map(r=>({unitId:r.unitId,weight:r.weight}))),electric= electricIds.length?weightedShares(electricTotal,electricIds.map(unitId=>({unitId,weight:1}))):[];
 const statements=latest(d,input.period).filter(s=>d.units.find(u=>u.id===s.unitId)?.poolId===input.poolId);if(statements.some(s=>s.status!=='Pending')||active.some(u=>!statements.some(s=>s.unitId===u.id)))blockers.push('Create editable draft statements for the complete pool before applying.');
 return {sources,collected,expected:sources.reduce((n,r)=>n+(r.expected??0),0),expectedUnknown:sources.filter(r=>r.expected===null).length,total,shares,electricTotal,electric,electricIds,unmatched,blockers:[...new Set(blockers)]};
}
export function applyPoolReview(d:Data,inputs:PoolInputs){const calculation=calculatePool(d,inputs);if(calculation.blockers.length)throw Error(calculation.blockers.join(' '));const finance=d.finance??={reviews:[]};const review:PoolReview={id:crypto.randomUUID(),created:new Date().toISOString(),version:1+Math.max(0,...finance.reviews.filter(r=>r.inputs.poolId===inputs.poolId&&r.inputs.period===inputs.period).map(r=>r.version)),inputs:structuredClone(inputs),calculation};const a=d.accounting??=emptyAccounting();const run={id:crypto.randomUUID(),poolId:inputs.poolId,period:inputs.period,version:1+Math.max(0,...a.allocations.filter(r=>r.poolId===inputs.poolId&&r.period===inputs.period).map(r=>r.version)),expected:[],totalSource:inputs.basis+' / '+inputs.source,total:calculation.total,activeIds:calculation.sources.map(r=>r.unitId),shares:calculation.shares,reviewer:inputs.reviewer,created:review.created,financeReviewId:review.id,weights:calculation.sources.map(r=>({unitId:r.unitId,weight:r.weight}))};a.allocations.push(run);
 for(const s of latest(d,inputs.period).filter(s=>d.units.find(u=>u.id===s.unitId)?.poolId===inputs.poolId)){s.allocated=run.shares.find(r=>r.unitId===s.unitId)?.cents??0;s.allocationRunId=run.id;s.allocationSource=inputs.basis+' / '+inputs.method+' / reviewed calculation '+review.version;applyContracts(d,s);const priorCPS=s.expenses.filter(e=>poolElectricLine(e));s.expenses=s.expenses.filter(e=>!poolElectricLine(e));if(calculation.electricIds.includes(s.unitId))s.expenses.push({id:priorCPS[0]?.id??crypto.randomUUID(),label:'Pool electricity · reviewed CPS sources',cents:calculation.electric.find(r=>r.unitId===s.unitId)?.cents??0,recipient:'CPS',classification:'Electricity pass-through',gl:'81000',electricScope:'Pool'});for(const prior of priorCPS.filter(e=>!s.expenses.some(n=>n.id===e.id)))s.expenses.push({...prior,cents:0});}
 finance.reviews.push(review);const setting=d.settings.filter(s=>s.poolId===inputs.poolId&&s.period===inputs.period).sort((a,b)=>b.version-a.version)[0];if(!setting)throw Error('Monthly settings required');const updated={...setting,id:crypto.randomUUID(),version:setting.version+1,electricTotal:calculation.electricTotal,electricConfirmed:true,notes:setting.notes+' CPS sources reviewed in '+review.id};d.settings.push(updated);for(const statement of latest(d,inputs.period).filter(s=>d.units.find(u=>u.id===s.unitId)?.poolId===inputs.poolId))statement.settingsVersion=updated.version;d.rules.push({id:crypto.randomUUID(),version:review.version,method:inputs.basis+' / '+inputs.method+' / '+review.id,verified:true});audit(d,'Monthly pool calculation applied',inputs.period+' / '+inputs.source+' / '+inputs.reviewer+' / '+calculation.total+' cents; no payments or QBO postings');return review;
}
export function validateFinance(old:Data,next:Data){const before=old.finance?.reviews??[],after=next.finance?.reviews??[];if(after.length>10000||new Set(after.map(r=>r.id)).size!==after.length)throw Error('Invalid pool review history');for(const r of before)if(!after.some(n=>n.id===r.id&&canonicalRecord(n)===canonicalRecord(r)))throw Error('Pool calculation history is immutable');const added=after.filter(r=>!before.some(o=>o.id===r.id));if(new Set(added.map(r=>r.inputs.poolId+':'+r.inputs.period)).size!==added.length)throw Error('Save one calculation per pool and month at a time');for(const r of added){const c=calculatePool(old,r.inputs);if(c.blockers.length||canonicalRecord(c)!==canonicalRecord(r.calculation))throw Error('Pool calculation source changed; review again');if(r.version!==1+Math.max(0,...before.filter(o=>o.inputs.poolId===r.inputs.poolId&&o.inputs.period===r.inputs.period).map(o=>o.version)))throw Error('Invalid pool calculation version');const runs=next.accounting?.allocations.filter(a=>a.financeReviewId===r.id)??[];if(runs.length!==1)throw Error('Reviewed calculation requires exactly one allocation run');const run=runs[0];if(!run||run.poolId!==r.inputs.poolId||run.period!==r.inputs.period||canonicalRecord(run.shares)!==canonicalRecord(c.shares)||run.total!==c.total||run.totalSource!==r.inputs.basis+' / '+r.inputs.source||canonicalRecord(run.weights)!==canonicalRecord(c.sources.map(s=>({unitId:s.unitId,weight:s.weight}))))throw Error('Pool allocation must match reviewed inputs');for(const s of latest(next,r.inputs.period).filter(s=>next.units.find(u=>u.id===s.unitId)?.poolId===r.inputs.poolId)){const electricity=s.expenses.filter(e=>poolElectricLine(e));if((c.electricIds.includes(s.unitId)&&!electricity.length)||electricity.reduce((n,e)=>n+e.cents,0)!==(c.electric.find(e=>e.unitId===s.unitId)?.cents??0))throw Error('Saved CPS charges must match reviewed bill allocation');}}
 for(const run of next.accounting?.allocations??[])if(run.financeReviewId&&!after.some(r=>r.id===run.financeReviewId&&r.inputs.poolId===run.poolId&&r.inputs.period===run.period))throw Error('Allocation requires its preserved pool review');
 for(const r of after.filter(r=>!after.some(x=>x.inputs.poolId===r.inputs.poolId&&x.inputs.period===r.inputs.period&&x.version>r.version))){const setting=next.settings.filter(s=>s.poolId===r.inputs.poolId&&s.period===r.inputs.period).sort((a,b)=>b.version-a.version)[0];if(setting?.electricTotal!==r.calculation.electricTotal||!setting?.electricConfirmed)throw Error('Monthly CPS settings must match the reviewed bill sources; save a new calculation to change CPS');const run=next.accounting?.allocations.find(a=>a.financeReviewId===r.id);for(const st of latest(next,r.inputs.period).filter(st=>next.units.find(u=>u.id===st.unitId)?.poolId===r.inputs.poolId)){if(st.allocationRunId!==run?.id)throw Error('Reviewed pool statements require the current calculation run');const total=st.expenses.filter(e=>poolElectricLine(e)).reduce((n,e)=>n+e.cents,0);if(total!==(r.calculation.electric.find(e=>e.unitId===st.unitId)?.cents??0))throw Error('Saved CPS charges must match reviewed bill allocation; save a new calculation to change CPS');}}
}
export function verifiedFeeBasis(d:Data,period:string,sourceId:string){const statement=latest(d,period).find(s=>s.expenses.some(e=>e.id===sourceId)),line=statement?.expenses.find(e=>e.id===sourceId);if(!statement||!line||!['80300','80400'].includes(line.gl??''))return false;const contract=effectiveContract(d,statement.unitId,period);if(!contract?.source.trim()||!contract.reviewer.trim())return false;const expected=line.gl==='80300'?contract.maintenance:contract.managementKind==='Percent'?Math.floor((statement.allocated*contract.management+5000)/10000):contract.management;return line.cents===expected;}
export function dlaIncomeReview(d:Data,period:string){const rows=incomeRows(d,period),feeRows=rows.filter(r=>r.kind==='Owner charge'&&['80300','80400'].includes(d.statements.flatMap(s=>s.expenses).find(e=>e.id===r.id)?.gl??''));const fees=feeRows.filter(r=>{if(!r.confirmed||r.treatment!=='Agency income'||!verifiedFeeBasis(d,period,r.id))return false;try{return ['income','other income'].includes(verifiedGL(d,r.gl,r.accountName).type.toLowerCase());}catch{return false;}});const income=fees.reduce((n,r)=>n+r.cents,0);return {income,target:1000000,shortfall:Math.max(0,1000000-income),fees,unconfirmed:feeRows.filter(r=>!fees.some(f=>f.id===r.id)).length};}
