import {canonicalRecord,recordState} from './workflow-controls';
import type {Data,Statement} from './pool';
export type Part={id:string;sku:string;name:string;measure:string;listPrice:number;reorderAt:number;active:boolean};
export type PartPurchase={origin?:'Purchase'|'Return'|'Adjustment';id:string;partId:string;date:string;quantity:number;totalCost:number;supplier:string;reference:string;notes:string;created:string};
export type PartIssue={id:string;partId:string;unitId:string;period:string;date:string;quantity:number;listPrice:number;totalCharge:number;reference:string;partName:string;sku:string;measure:string;recipient:string;classification:string;workOrderId:string;statementId:string;expenseId:string;costAllocations:{purchaseId:string;quantity:number;cost:number}[];created:string};
export type StockCorrection={id:string;partId:string;date:string;kind:'Return'|'Reversal'|'Physical adjustment'|'Supplier return';delta:number;cost:number;reference:string;reason:string;reviewer:string;issueId:string;statementId:string;creditId:string;purchaseId:string;costAllocations:{purchaseId:string;quantity:number;cost:number}[];created:string};
export type Procurement={corrections?:StockCorrection[];parts:Part[];purchases:PartPurchase[];issues:PartIssue[]};
export const emptyProcurement=():Procurement=>({parts:[],purchases:[],issues:[]});
export function partStock(p:Procurement,id:string){return p.purchases.filter(r=>r.partId===id).reduce((n,r)=>n+r.quantity,0)-p.issues.filter(r=>r.partId===id).reduce((n,r)=>n+r.quantity,0)+(p.corrections??[]).filter(r=>r.partId===id&&r.delta<0).reduce((n,r)=>n+r.delta,0);}
const validDate=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
export function allocatePartCost(p:Procurement,partId:string,quantity:number,date:string){
 let left=quantity;const rows:{purchaseId:string;quantity:number;cost:number}[]=[];
 for(const purchase of p.purchases.filter(r=>r.partId===partId&&r.date<=date).sort((a,b)=>a.date.localeCompare(b.date)||a.created.localeCompare(b.created)||a.id.localeCompare(b.id))){const used=[...p.issues.flatMap(i=>i.costAllocations),...(p.corrections??[]).flatMap(i=>i.costAllocations)].filter(a=>a.purchaseId===purchase.id).reduce((n,a)=>n+a.quantity,0);const take=Math.min(left,purchase.quantity-used);if(take<=0)continue;const base=Math.floor(purchase.totalCost/purchase.quantity),remainder=purchase.totalCost%purchase.quantity;const cost=take*base+Math.max(0,Math.min(used+take,remainder)-used);rows.push({purchaseId:purchase.id,quantity:take,cost});left-=take;if(!left)break;}
 if(left)throw Error('Not enough stock received by the usage date');return rows;
}
export function stockValue(p:Procurement){return p.purchases.reduce((n,r)=>n+r.totalCost,0)-p.issues.reduce((n,r)=>n+r.costAllocations.reduce((a,c)=>a+c.cost,0),0)-(p.corrections??[]).filter(r=>r.delta<0).reduce((n,r)=>n+r.cost,0);}
export function postPartIssue(d:Data,input:{partId:string;unitId:string;period:string;date:string;quantity:number;reference:string;recipient:string;classification:string;workOrderId:string}):PartIssue{
 const p=d.procurement??=emptyProcurement(),part=p.parts.find(r=>r.id===input.partId);if(!part?.active)throw Error('Choose an active part');if(!Number.isSafeInteger(input.quantity)||input.quantity<=0)throw Error('Use a positive whole quantity');if(p.issues.some(r=>r.reference.trim().toLowerCase()===input.reference.trim().toLowerCase()))throw Error('Duplicate usage reference');if(!input.reference.trim()||!input.recipient.trim()||!input.classification.trim())throw Error('Enter usage reference, recipient, and classification');if(!validDate(input.date)||input.date.slice(0,7)!==input.period)throw Error('Usage date must belong to the accounting month');const s=d.statements.filter(s=>s.unitId===input.unitId&&s.period===input.period).sort((a,b)=>b.version-a.version)[0];if(!s||s.status!=='Pending')throw Error('Create or open a draft owner statement for this unit and month first');if(input.workOrderId&&!d.operations?.workOrders.some(w=>w.id===input.workOrderId&&w.unitId===input.unitId&&recordState(d,'workOrders',w.id)==='Active'))throw Error('Select an active work order for the same unit');const costAllocations=allocatePartCost(p,part.id,input.quantity,input.date),id=crypto.randomUUID(),expenseId=crypto.randomUUID();const totalCharge=input.quantity*part.listPrice;if(!Number.isSafeInteger(totalCharge)||totalCharge>100000000000)throw Error('Charge exceeds supported amount');const issue:PartIssue={...input,id,reference:input.reference.trim(),listPrice:part.listPrice,totalCharge,partName:part.name,sku:part.sku,measure:part.measure,statementId:s.id,expenseId,costAllocations,created:new Date(Math.max(Date.now(),...p.issues.map(x=>Date.parse(x.created)+1),...(p.corrections??[]).map(x=>Date.parse(x.created)+1)).valueOf()).toISOString()};s.expenses.push({id:expenseId,label:'Materials · '+part.name+' · '+input.quantity+' '+part.measure+' × '+(part.listPrice/100).toFixed(2)+' · '+issue.reference,cents:totalCharge,recipient:input.recipient,classification:input.classification,gl:'81200',partsIssueId:id});p.issues.push(issue);d.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),action:'Inventory issued & owner charged',detail:issue.reference+' / unit '+input.unitId+' / '+input.period+' / '+input.quantity+' '+part.sku+' / list total '+totalCharge+' cents'});return issue;
}
export function validateProcurement(d:Data,old?:Data){
 const p=d.procurement;if(!p){if(d.statements.some(s=>s.expenses.some(e=>e.partsIssueId)))throw Error('Missing inventory receipt records');if(old?.procurement)throw Error('Procurement history must be preserved');return;}
 const integer=(n:number,positive=false)=>{if(!Number.isSafeInteger(n)||n<0||n>100000000000||positive&&n===0)throw Error('Invalid inventory quantity or amount');};
 for(const key of ['parts','purchases','issues'] as const){const rows=p[key];if(!Array.isArray(rows)||rows.length>10000||new Set(rows.map(r=>r.id)).size!==rows.length||rows.some(r=>!r.id))throw Error('Invalid procurement records');for(const r of old?.procurement?.[key]??[]){const next=rows.find(x=>x.id===r.id);if(!next||key!=='parts'&&canonicalRecord(next)!==canonicalRecord(r))throw Error('Procurement history is immutable');}}
 const skus=new Set<string>();for(const r of p.parts){integer(r.listPrice);integer(r.reorderAt);const sku=r.sku.trim().toLowerCase();if(!sku||skus.has(sku)||!r.name.trim()||!r.measure.trim()||typeof r.active!=='boolean')throw Error('Duplicate SKU or invalid part');skus.add(sku);}
 const refs=new Set<string>();for(const r of p.purchases){integer(r.quantity,true);integer(r.totalCost);const ref=r.supplier.trim().toLowerCase()+':'+r.reference.trim().toLowerCase()+':'+r.partId;if(!p.parts.some(x=>x.id===r.partId)||!validDate(r.date)||!r.reference.trim()||!r.supplier.trim()||refs.has(ref))throw Error('Duplicate purchase reference or invalid purchase');refs.add(ref);}
 const issuedRefs=new Set<string>(),lots=new Map<string,{quantity:number;cost:number}>();for(const r of [...p.issues,...(p.corrections??[]).filter(r=>r.delta<0).map(r=>({...r,quantity:-r.delta,listPrice:0,totalCharge:0,unitId:d.units[0].id,period:r.date.slice(0,7),recipient:r.reviewer,classification:r.reason,workOrderId:'',_correction:true}))].sort((a,b)=>a.created.localeCompare(b.created))){integer(r.quantity,true);integer(r.listPrice);integer(r.totalCharge);const ref=r.reference.trim().toLowerCase();if(!ref||issuedRefs.has(ref)||!p.parts.some(x=>x.id===r.partId)||!d.units.some(u=>u.id===r.unitId)||!validDate(r.date)||r.date.slice(0,7)!==r.period||!r.recipient.trim()||!r.classification.trim()||r.totalCharge!==r.quantity*r.listPrice||!Number.isSafeInteger(r.totalCharge)||r.workOrderId&&!d.operations?.workOrders.some(w=>w.id===r.workOrderId&&w.unitId===r.unitId))throw Error('Duplicate usage reference or invalid issue');issuedRefs.add(ref);let quantity=0;const seen=new Set<string>();for(const a of r.costAllocations){integer(a.quantity,true);integer(a.cost);const purchase=p.purchases.find(x=>x.id===a.purchaseId);if(!purchase||purchase.partId!==r.partId||purchase.date>r.date||seen.has(a.purchaseId))throw Error('Invalid stock cost allocation');seen.add(a.purchaseId);quantity+=a.quantity;const used=lots.get(purchase.id)??{quantity:0,cost:0};const base=Math.floor(purchase.totalCost/purchase.quantity),remainder=purchase.totalCost%purchase.quantity;const expected=a.quantity*base+Math.max(0,Math.min(used.quantity+a.quantity,remainder)-used.quantity);if(a.cost!==expected||used.quantity+a.quantity>purchase.quantity)throw Error('Stock exceeded or purchase-cost remainder incorrect');lots.set(purchase.id,{quantity:used.quantity+a.quantity,cost:used.cost+a.cost});}if(quantity!==r.quantity)throw Error('Issue quantity does not match stock allocations');if('_correction' in r)continue;const s=d.statements.find(s=>s.id===r.statementId),e=s?.expenses.find(e=>e.id===r.expenseId);if(!s||s.unitId!==r.unitId||s.period!==r.period||e?.partsIssueId!==r.id||e.cents!==r.totalCharge||e.recipient!==r.recipient)throw Error('Inventory issue must have its matching owner expense');const prior=old?.procurement?.issues.some(i=>i.id===r.id);if(!prior&&r.workOrderId&&recordState(d,'workOrders',r.workOrderId)!=='Active')throw Error('Restore work order before issuing parts');if(!prior&&(old?.statements.find(x=>x.id===s.id)?.status!=='Pending'||s.status!=='Pending'||d.statements.some(x=>x.unitId===s.unitId&&x.period===s.period&&x.version>s.version)))throw Error('Inventory charges require the latest existing draft statement');}
 for(const s of d.statements)for(const e of s.expenses.filter(e=>e.partsIssueId)){const r=p.issues.find(r=>r.id===e.partsIssueId);if(!r||s.unitId!==r.unitId||s.period!==r.period||e.cents!==r.totalCharge||e.id!==r.expenseId||e.recipient!==r.recipient)throw Error('Invalid inventory-linked statement expense');}
 validateCorrections(d,old);
 for(const part of p.parts)if(partStock(p,part.id)<0)throw Error('Inventory cannot be negative');
}
export function ownerPartsReceiptRecord(d:Data,r:PartIssue){return {reference:r.reference,date:r.date,period:r.period,unit:d.units.find(u=>u.id===r.unitId)?.number??r.unitId,owner:(d.statements.find(s=>s.id===r.statementId) as any)?.ownerSnapshot?.name??d.owners.find(o=>o.id===d.statements.find(s=>s.id===r.statementId)?.ownerId)?.name??'',sku:r.sku,part:r.partName,quantity:r.quantity,measure:r.measure,unitPrice:r.listPrice,total:r.totalCharge,recipient:r.recipient};}

export function postStockCorrection(d:Data,input:{partId:string;date:string;kind:StockCorrection['kind'];quantity:number;cost:number;reference:string;reason:string;reviewer:string;issueId:string;period:string}){
 const p=d.procurement??=emptyProcurement();p.corrections??=[];if(!p.parts.some(x=>x.id===input.partId)||!validDate(input.date)||input.date.slice(0,7)!==input.period||!Number.isSafeInteger(input.quantity)||input.quantity<=0||!input.reason.trim()||!input.reviewer.trim()||!input.reference.trim()||p.corrections.some(r=>r.reference.toLowerCase()===input.reference.toLowerCase()))throw Error('Enter positive quantity, unique reference, reason, date, and reviewer');const id=crypto.randomUUID(),created=new Date(Math.max(Date.now(),...p.issues.map(x=>Date.parse(x.created)+1),...p.corrections.map(x=>Date.parse(x.created)+1))).toISOString();let delta=-input.quantity,cost=0,statementId='',creditId='',purchaseId='',costAllocations:StockCorrection['costAllocations']=[];
 if(input.kind==='Return'||input.kind==='Reversal'){const issue=p.issues.find(r=>r.id===input.issueId&&r.partId===input.partId);if(!issue||issue.date>input.date)throw Error('Choose original unit usage before the return date');const returned=p.corrections.filter(r=>r.issueId===issue.id).reduce((n,r)=>n+r.delta,0),qty=input.kind==='Reversal'?issue.quantity-returned:input.quantity;if(qty<=0||returned+qty>issue.quantity)throw Error('Return exceeds original usage');delta=qty;const total=issue.costAllocations.reduce((n,a)=>n+a.cost,0),base=Math.floor(total/issue.quantity),rem=total%issue.quantity;cost=qty*base+Math.max(0,Math.min(returned+qty,rem)-returned);const s=d.statements.filter(s=>s.unitId===issue.unitId&&s.period===input.period).sort((a,b)=>b.version-a.version)[0];if(!s||s.status!=='Pending'||s.ownerId!==d.statements.find(v=>v.id===issue.statementId)?.ownerId)throw Error('Return credit needs a latest draft owner statement for this month');statementId=s.id;creditId=crypto.randomUUID();s.credits??=[];s.credits.push({id:creditId,label:'Materials '+input.kind.toLowerCase()+' · '+issue.partName+' · '+qty+' · '+input.reference,cents:qty*issue.listPrice,correctionId:id});
 }else if(input.kind==='Physical adjustment'&&input.cost>=0){delta=input.quantity;cost=input.cost;}else{costAllocations=allocatePartCost(p,input.partId,input.quantity,input.date);cost=costAllocations.reduce((n,a)=>n+a.cost,0);}
 if(delta>0){purchaseId=crypto.randomUUID();p.purchases.push({id:purchaseId,origin:input.kind==='Return'||input.kind==='Reversal'?'Return':'Adjustment',partId:input.partId,date:input.date,quantity:delta,totalCost:cost,supplier:'Internal stock correction',reference:input.reference,notes:input.reason,created});}
 const r:StockCorrection={id,partId:input.partId,date:input.date,kind:input.kind,delta,cost,reference:input.reference,reason:input.reason,reviewer:input.reviewer,issueId:input.kind==='Return'||input.kind==='Reversal'?input.issueId:'',statementId,creditId,purchaseId,costAllocations,created};p.corrections.push(r);d.audit.unshift({id:crypto.randomUUID(),at:created,action:'Inventory correction posted',detail:input.reference+' / '+input.kind+' / '+delta+' / '+input.reviewer});return r;
}
function validateCorrections(d:Data,old?:Data){const p=d.procurement!,rows=p.corrections??[];if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate stock correction');for(const r of old?.procurement?.corrections??[])if(!rows.some(n=>canonicalRecord(n)===canonicalRecord(r)))throw Error('Stock corrections are immutable');const refs=new Set<string>();for(const r of rows){if(!['Return','Reversal','Physical adjustment','Supplier return'].includes(r.kind)||!Number.isSafeInteger(r.delta)||!r.delta||!Number.isSafeInteger(r.cost)||r.cost<0||!validDate(r.date)||!r.reference.trim()||refs.has(r.reference.toLowerCase())||!r.reason.trim()||!r.reviewer.trim()||!p.parts.some(x=>x.id===r.partId))throw Error('Invalid stock correction');refs.add(r.reference.toLowerCase());if(r.delta>0){const lot=p.purchases.find(x=>x.id===r.purchaseId);if(!lot||lot.quantity!==r.delta||lot.totalCost!==r.cost||lot.partId!==r.partId||lot.origin==='Purchase'||!lot.origin)throw Error('Stock gain requires matching internal lot');}else if(r.costAllocations.reduce((n,a)=>n+a.quantity,0)!==-r.delta||r.costAllocations.reduce((n,a)=>n+a.cost,0)!==r.cost)throw Error('Stock loss cost does not reconcile');if((r.kind==='Return'||r.kind==='Reversal')&&!r.issueId||r.kind==='Supplier return'&&r.delta>0)throw Error('Invalid correction kind');if(r.issueId){const issue=p.issues.find(i=>i.id===r.issueId),s=d.statements.find(s=>s.id===r.statementId),credit=s?.credits?.find(c=>c.id===r.creditId);if(!issue||r.delta<=0||s?.unitId!==issue.unitId||credit?.cents!==r.delta*issue.listPrice||credit.correctionId!==r.id||rows.filter(x=>x.issueId===issue.id).reduce((n,x)=>n+x.delta,0)>issue.quantity)throw Error('Invalid return or owner credit');const prior=rows.filter(x=>x.issueId===issue.id&&rows.indexOf(x)<rows.indexOf(r)).reduce((n,x)=>n+x.delta,0),total=issue.costAllocations.reduce((n,a)=>n+a.cost,0),base=Math.floor(total/issue.quantity),rem=total%issue.quantity;if(r.cost!==r.delta*base+Math.max(0,Math.min(prior+r.delta,rem)-prior)||r.date<issue.date)throw Error('Return purchase cost does not reconcile');if(!old?.procurement?.corrections?.some(x=>x.id===r.id)&&old?.statements.find(x=>x.id===s.id)?.status!=='Pending')throw Error('Return requires a draft statement');}}
 for(const s of d.statements)for(const c of s.credits??[]){const r=rows.find(r=>r.id===c.correctionId);if(!r||r.creditId!==c.id||r.delta<=0||c.cents!==r.delta*(p.issues.find(i=>i.id===r.issueId)?.listPrice??-1)||s.period!==d.statements.find(x=>x.id===r.statementId)?.period||r.statementId!==s.id&&d.statements.find(x=>x.id===r.statementId)?.unitId!==s.unitId)throw Error('Owner credit must match stock correction');}
 for(const lot of p.purchases.filter(p=>p.origin&&p.origin!=='Purchase'))if(!rows.some(r=>r.purchaseId===lot.id))throw Error('Internal lots require correction record');
}
