import {createCipheriv,createDecipheriv,createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
export type QboConfig={clientId:string;secret:string;realm:string;company:string;environment:'sandbox'|'production';origin:string;key:Buffer};
export function qboConfig(env:NodeJS.ProcessEnv):QboConfig|null{if(env.OG_QBO_ENABLED!=='true')return null;const clientId=env.OG_QBO_CLIENT_ID??'',secret=env.OG_QBO_CLIENT_SECRET??'',realm=env.OG_QBO_EXPECTED_REALM_ID??'',company=env.OG_QBO_EXPECTED_COMPANY_NAME??'',environment=env.OG_QBO_ENVIRONMENT,encoded=env.OG_QBO_ENCRYPTION_KEY??'';let url:URL;try{url=new URL(env.OG_APP_URL??'');}catch{throw Error('QBO requires the published OG origin');}const key=Buffer.from(encoded,'base64');if(!clientId||!secret||!/^\d{1,30}$/.test(realm)||!company.trim()||!['sandbox','production'].includes(environment??'')||key.length!==32||key.toString('base64')!==encoded||url.protocol!=='https:'||url.username||url.password||url.pathname!=='/'||url.search||url.hash)throw Error('QBO registration settings are incomplete or invalid');return {clientId,secret,realm,company,environment:environment as QboConfig['environment'],origin:url.origin,key};}
export const normalizedCompany=(v:string)=>v.trim().replace(/\s+/g,' ').toLocaleLowerCase('en-US');
export function verifyCompany(c:QboConfig,payload:any){const info=payload?.CompanyInfo;if(info?.Id!==c.realm||typeof info.CompanyName!=='string'||normalizedCompany(info.CompanyName)!==normalizedCompany(c.company))throw Error('The connected QBO company does not match the approved company');return info.CompanyName as string;}
export type QboTokens={access:string;refresh:string;expires:number;refreshExpires:number|null};
export function tokenData(payload:any,now=Date.now()):QboTokens{if(typeof payload?.access_token!=='string'||!payload.access_token||typeof payload?.refresh_token!=='string'||!payload.refresh_token||!Number.isSafeInteger(payload.expires_in)||payload.expires_in<1||payload.expires_in>86400||payload.token_type?.toLowerCase()!=='bearer')throw Error('QBO authentication returned invalid credentials');const days=payload.x_refresh_token_expires_in;if(days!==undefined&&(!Number.isSafeInteger(days)||days<=0))throw Error('QBO refresh expiry is invalid');return {access:payload.access_token,refresh:payload.refresh_token,expires:now+payload.expires_in*1000,refreshExpires:days===undefined?null:now+days*1000};}
const aad=(c:QboConfig,workspace:string)=>JSON.stringify([workspace,c.realm,c.environment,c.clientId]);
export function seal(c:QboConfig,workspace:string,tokens:QboTokens){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',c.key,iv);cipher.setAAD(Buffer.from(aad(c,workspace)));const bytes=Buffer.concat([cipher.update(JSON.stringify(tokens),'utf8'),cipher.final()]);return ['v1',iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),bytes.toString('base64url')].join('.');}
export function unseal(c:QboConfig,workspace:string,value:string):QboTokens{const [v,iv,tag,data,...extra]=value.split('.');if(v!=='v1'||extra.length)throw Error('Invalid connection credentials');const decipher=createDecipheriv('aes-256-gcm',c.key,Buffer.from(iv,'base64url'));decipher.setAAD(Buffer.from(aad(c,workspace)));decipher.setAuthTag(Buffer.from(tag,'base64url'));const t=JSON.parse(Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8'));if(typeof t.access!=='string'||typeof t.refresh!=='string'||!t.access||!t.refresh||!Number.isSafeInteger(t.expires)||t.refreshExpires!==null&&!Number.isSafeInteger(t.refreshExpires))throw Error('Invalid stored credentials');return t;}
export type OAuthState={nonce:string;auth:string;workspace:string;generation:string;expires:number};
export function signState(c:QboConfig,value:OAuthState){const data=Buffer.from(JSON.stringify({...value,binding:aad(c,value.workspace)})).toString('base64url');return data+'.'+createHmac('sha256',c.key).update(data).digest('base64url');}
export function verifyState(c:QboConfig,cookie:string,nonce:string,auth:string,workspace:string,now=Date.now()){if(cookie.length>3000)throw Error('Invalid QBO callback');const [data,sig,...extra]=cookie.split('.'),expected=createHmac('sha256',c.key).update(data??'').digest(),actual=Buffer.from(sig??'','base64url');if(extra.length||expected.length!==actual.length||!timingSafeEqual(expected,actual))throw Error('Invalid QBO callback');const s=JSON.parse(Buffer.from(data,'base64url').toString('utf8'));if(s.nonce!==nonce||s.auth!==auth||s.workspace!==workspace||s.binding!==aad(c,workspace)||!Number.isSafeInteger(s.expires)||s.expires<now||s.expires>now+600000||typeof s.generation!=='string')throw Error('QBO connection request expired or belongs to another session');return s as OAuthState;}
export function authorizationUrl(c:QboConfig,state:string){return 'https://appcenter.intuit.com/connect/oauth2?'+new URLSearchParams({client_id:c.clientId,response_type:'code',scope:'com.intuit.quickbooks.accounting',redirect_uri:c.origin+'/api/qbo/callback',state});}
export function apiUrl(c:QboConfig,path:string){const host=c.environment==='production'?'https://quickbooks.api.intuit.com':'https://sandbox-quickbooks.api.intuit.com';if(!/^(companyinfo\/\d+|query\?|reports\/ProfitAndLoss\?)/.test(path)||path.includes('..'))throw Error('Invalid QBO read path');return host+'/v3/company/'+c.realm+'/'+path;}
