import {type Data,cents,audit} from './pool';
import {emptyOperations,type TenantEntry} from './operations-model';
import {applyTenantReceipt,chargeProgress} from './accounting-model';
export const PAYMENT_METHODS=['Not provided','Check','Money Order',"Cashier's Check"] as const;
export type PaymentMethod=typeof PAYMENT_METHODS[number];
export type QboPayment={row:number;customer:string;unitNumber:string;date:string;number:string;cents:number;originalAmount:string;sourceKey:string;raw:string[];customerContext?:{row:number;raw:string[]};error:string};
export type QboFile={company:string;headers:string[];payments:QboPayment[];invoiceCount:number;ignored:number};
export type ImportSelection={sourceKey:string;tenantId:string;method:PaymentMethod;chargeId:string;applyCents:number};
export type QboImportBatch={id:string;fileName:string;fileHash:string;company:string;headers:string[];period:string;created:string;rows:{source:QboPayment;tenantId:string;unitId:string;method:PaymentMethod;receiptId:string;chargeId:string;applyCents:number}[]};
function records(text:string){const rows:string[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value='';}else value+=c;}if(quoted)throw Error('Unclosed CSV quote');row.push(value);if(row.some(v=>v.trim()))rows.push(row);return rows;}
function date(value:string){let y=0,m=0,d=0;const us=/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.exec(value.trim()),iso=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value.trim());if(us){m=+us[1];d=+us[2];y=+us[3];}else if(iso){y=+iso[1];m=+iso[2];d=+iso[3];}else throw Error('Invalid payment date');const dt=new Date(Date.UTC(y,m-1,d));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()+1!==m||dt.getUTCDate()!==d)throw Error('Invalid payment date');return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function amount(value:string){let v=value.trim().replace(/^\$/,'');if(/^\(.*\)$/.test(v))v='-'+v.slice(1,-1);if(!/^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d{1,2})?$/.test(v))throw Error('Invalid payment amount');const n=Math.abs(cents(v.replaceAll(',','')));if(!n)throw Error('Zero payment amount');return n;}
function key(p:Pick<QboPayment,'customer'|'date'|'number'|'cents'|'unitNumber'>){return JSON.stringify(['QBO Payment',p.unitNumber?'unit:'+p.unitNumber.toLowerCase():'customer:'+p.customer.trim().replace(/\s+/g,' ').toLowerCase(),p.date,p.number.trim().toLowerCase(),p.cents]);}
function column(headers:string[],name:string){return headers.indexOf(headers.includes(name)?name:name==='Customer'?'Name':name==='Transaction number'?'Num':name);}
export function parseQboPayments(text:string):QboFile{
 if(text.length>5000000)throw Error('CSV exceeds 5 MB');const rows=records(text.replace(/^\uFEFF/,''));if(rows.length>30000)throw Error('Limit this export to one month (maximum 30,000 rows)');
 const required=['Date','Transaction type','Transaction number','Amount'];const index=rows.findIndex(r=>required.every(h=>column(r,h)>=0)&&(column(r,'Customer')>=0||r[0]?.trim()===''));if(index<0)throw Error('QBO header not found. Required: '+required.join(', '));const headers=rows[index];if(required.some(h=>column(headers,h)!==headers.lastIndexOf(headers[column(headers,h)])))throw Error('Duplicate required column');
 const payments:QboPayment[]=[];let invoiceCount=0,ignored=0;const seen=new Set<string>();let context:{row:number;raw:string[]}|undefined;const grouped=column(headers,'Customer')<0;
 for(let i=index+1;i<rows.length;i++){const raw=rows[i],get=(h:string)=>(raw[column(headers,h)]??'').trim();if(grouped&&raw[0]?.trim()&&raw.slice(1).every(v=>!v.trim())){context=/^total\b/i.test(raw[0].trim())?undefined:{row:i+1,raw:[...raw]};ignored++;continue;}if(get('Transaction type')!=='Payment'){if(get('Transaction type')==='Invoice')invoiceCount++;else ignored++;continue;}
  const p:QboPayment={row:i+1,customer:grouped?(context?.raw[0]?.trim()??''):get('Customer'),unitNumber:'',date:'',number:get('Transaction number'),cents:0,originalAmount:get('Amount'),sourceKey:'',raw:[...raw],...(grouped&&context?{customerContext:structuredClone(context)}:{}),error:''};
  try{if(!p.customer||!p.number)throw Error('Customer and transaction number required');p.unitNumber=/^#\s*([\w-]+)(?=\s|$)/.exec(p.customer)?.[1]??'';p.date=date(get('Date'));if(!p.originalAmount)throw Error('Payment amount missing. Export a payment amount from QBO; deposits and invoices are not used to infer receipts.');p.cents=amount(p.originalAmount);p.sourceKey=key(p);if(seen.has(p.sourceKey))throw Error('Duplicate payment row in file');seen.add(p.sourceKey);}catch(e){p.error=(e as Error).message;}payments.push(p);
 }
 if(!payments.length)throw Error('No Payment rows found. Invoice rows are not payment receipts.');return {company:rows[0]?.[0]?.trim()??'',headers,payments,invoiceCount,ignored};
}
export function paymentMatch(d:Data,p:QboPayment){const units=d.units.filter(u=>u.number.toLowerCase()===p.unitNumber.toLowerCase());const tenants=(d.operations?.tenants??[]).filter(t=>units.some(u=>u.id===t.unitId)&&t.start<=p.date&&(!t.end||t.end>=p.date));return {units,tenants};}
export function importedPayment(d:Data,key:string){return (d.qboImports??[]).some(b=>b.rows.some(r=>r.source.sourceKey===key));}
export function importQboPayments(d:Data,file:QboFile,fileName:string,fileHash:string,period:string,selections:ImportSelection[]){
 if(!selections.length)throw Error('Select payment rows to import');if(!d.periods.some(p=>p.month===period))throw Error('Open the accounting month first');if(!fileHash||!fileName.trim())throw Error('File provenance is required');
 const n=structuredClone(d),batch:QboImportBatch={id:crypto.randomUUID(),fileName, fileHash,company:file.company,headers:[...file.headers],period,created:new Date().toISOString(),rows:[]},seen=new Set<string>();n.operations??=emptyOperations();n.operations.tenantEntries??=[];
 for(const selection of selections){const p=file.payments.find(p=>p.sourceKey===selection.sourceKey);if(!p||p.error||p.date.slice(0,7)!==period)throw Error('Invalid or out-of-month payment row');if(seen.has(p.sourceKey)||importedPayment(n,p.sourceKey))throw Error('Duplicate QBO payment');seen.add(p.sourceKey);
  const t=n.operations.tenants?.find(t=>t.id===selection.tenantId);if(!t||t.start>p.date||t.end&&t.end<p.date)throw Error('Select the correct tenant effective on the payment date');if(p.unitNumber&&!n.units.some(u=>u.id===t.unitId&&u.number.toLowerCase()===p.unitNumber.toLowerCase()))throw Error('Tenant/unit does not match source customer');if(p.date<t.openingDate)throw Error('Payment precedes tenant opening date; review opening balances first');if(!PAYMENT_METHODS.includes(selection.method))throw Error('Invalid payment method');
  const receiptId=crypto.randomUUID(),reference='QBO:'+p.sourceKey;if(n.operations.tenantEntries.some(e=>e.kind==='Receipt'&&e.reference===reference))throw Error('Duplicate payment reference');
  const entry:TenantEntry={id:receiptId,tenantId:t.id,date:p.date,kind:'Receipt',description:'QBO payment '+p.number+' · '+p.customer,cents:p.cents,reference,paymentMethod:selection.method,qboImportId:batch.id,qboSourceKey:p.sourceKey};n.operations.tenantEntries.push(entry);
  if(selection.chargeId){const charge=n.operations.tenantEntries.find(e=>e.id===selection.chargeId&&e.tenantId===t.id&&e.kind==='Charge'&&e.category==='Rent');if(!charge||charge.date>p.date||!Number.isSafeInteger(selection.applyCents)||selection.applyCents<=0||selection.applyCents>p.cents||selection.applyCents>chargeProgress(n,charge.id).remaining)throw Error('Invalid rent charge match or amount');applyTenantReceipt(n,receiptId,charge.id,selection.applyCents,'Rent');}else if(selection.applyCents!==0)throw Error('Unapplied receipts must have zero matched amount');
  batch.rows.push({source:structuredClone(p),tenantId:t.id,unitId:t.unitId,method:selection.method,receiptId,chargeId:selection.chargeId,applyCents:selection.applyCents});
 }
 (n.qboImports??=[]).push(batch);audit(n,'QBO tenant payments imported',fileName+' / '+period+' / '+batch.rows.length+' receipts; '+batch.rows.filter(r=>r.chargeId).length+' explicitly matched. No QBO entries changed; assumptions unchanged.');return {data:n,batch};
}
export function validateQboImports(old:Data,next:Data){
 const batches=next.qboImports??[],ids=new Set<string>(),keys=new Set<string>();if(!Array.isArray(batches))throw Error('Invalid QBO import history');
 for(const oldBatch of old.qboImports??[])if(!batches.some(b=>b.id===oldBatch.id&&JSON.stringify(b)===JSON.stringify(oldBatch)))throw Error('Preserve QBO import batches and original source rows');
 for(const b of batches){if(!b.id||ids.has(b.id)||!b.fileName||!b.fileHash||!Array.isArray(b.headers)||!b.rows?.length||!next.periods.some(p=>p.month===b.period))throw Error('Invalid QBO batch');ids.add(b.id);
  for(const r of b.rows){const p=r.source,get=(h:string)=>(p.raw?.[column(b.headers,h)]??'').trim();if(get('Transaction type')!=='Payment'||(column(b.headers,'Customer')>=0?get('Customer'):(p.customerContext?.raw[0]?.trim()??''))!==p.customer||get('Transaction number')!==p.number||get('Amount')!==p.originalAmount||(/^#\s*([\w-]+)(?=\s|$)/.exec(p.customer)?.[1]??'')!==p.unitNumber||date(get('Date'))!==p.date||amount(get('Amount'))!==p.cents)throw Error('QBO original source does not match receipt');if(column(b.headers,'Customer')<0&&(!p.customerContext||!Number.isSafeInteger(p.customerContext.row)||p.customerContext.row>=p.row||p.customerContext.row<1||p.customerContext.raw.slice(1).some(v=>v.trim())||/^total\b/i.test(p.customer)))throw Error('Invalid QBO customer group source');const t=next.operations?.tenants?.find(t=>t.id===r.tenantId),e=next.operations?.tenantEntries?.find(e=>e.id===r.receiptId);if(!p.sourceKey||p.sourceKey!==key(p)||keys.has(p.sourceKey)||p.error||p.date.slice(0,7)!==b.period||!t||t.unitId!==r.unitId||!e||e.kind!=='Receipt'||e.qboImportId!==b.id||e.qboSourceKey!==p.sourceKey||e.cents!==p.cents||e.date!==p.date||e.tenantId!==t.id||e.reference!=='QBO:'+p.sourceKey||e.paymentMethod!==r.method||!PAYMENT_METHODS.includes(r.method))throw Error('Invalid or duplicate QBO receipt/source link');keys.add(p.sourceKey);
   if(!r.chargeId&&r.applyCents!==0)throw Error('Invalid unapplied QBO receipt');
   if(r.chargeId&&!next.accounting?.applications.some(a=>a.receiptId===r.receiptId&&a.chargeId===r.chargeId&&a.cents===r.applyCents&&a.chargeCategory==='Rent'))throw Error('Missing QBO receipt match');
  }
 }
 for(const e of next.operations?.tenantEntries??[])if(e.qboImportId&&!batches.some(b=>b.id===e.qboImportId&&b.rows.some(r=>r.receiptId===e.id)))throw Error('Imported receipt must retain its source batch');
}
