// Provider records are staged for human review; these functions never update an OG ledger.
export type QboKind='accounts'|'customers'|'vendors'|'payments'|'profit-loss';
export const QBO_KINDS:QboKind[]=['accounts','customers','vendors','payments','profit-loss'];
export function monthRange(month:string){if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))throw Error('Select a valid accounting month');const [y,m]=month.split('-').map(Number);return {start:month+'-01',end:month+'-'+new Date(Date.UTC(y,m,0)).getUTCDate()};}
const entity={accounts:'Account',customers:'Customer',vendors:'Vendor',payments:'Payment'} as const;
export function readPath(kind:QboKind,month:string,basis:'Cash'|'Accrual',position=1){const range=monthRange(month);if(!QBO_KINDS.includes(kind)||!['Cash','Accrual'].includes(basis)||!Number.isSafeInteger(position)||position<1)throw Error('Invalid report selection');if(kind==='profit-loss')return 'reports/ProfitAndLoss?'+new URLSearchParams({start_date:range.start,end_date:range.end,accounting_method:basis,summarize_column_by:'Classes'});const where=kind==='payments'?` WHERE TxnDate >= '${range.start}' AND TxnDate <= '${range.end}'`:" WHERE Active IN (true, false)";return 'query?'+new URLSearchParams({query:`SELECT * FROM ${entity[kind]}${where} STARTPOSITION ${position} MAXRESULTS 1000`});}
export function queryRows(kind:Exclude<QboKind,'profit-loss'>,payload:unknown){const p=payload as any;if(p?.Fault||!p?.QueryResponse||typeof p.QueryResponse!=='object')throw Error('QBO returned an invalid record page');const rows=p.QueryResponse[entity[kind]]??[];if(!Array.isArray(rows)||rows.length>1000)throw Error('Invalid QBO record count');return rows;}
function text(v:unknown,label:string){if(typeof v!=='string'||!v.trim()||v.length>2000)throw Error('Missing or invalid QBO '+label);return v;}
function spreadsheetSafe(v:unknown){const value=String(v??'');return typeof v==='string'&&/^[\s]*[=+@-]/.test(value)&&!/^[-+]?\d+(?:\.\d+)?$/.test(value)?"'"+value:value;}
function csv(rows:unknown[][]){return rows.map(r=>r.map(v=>'"'+spreadsheetSafe(v).replaceAll('"','""')+'"').join(',')).join('\r\n')+'\r\n';}
function money(v:unknown){if(typeof v!=='number'||!Number.isFinite(v)||v<=0||!Number.isSafeInteger(Math.round(v*100))||Math.abs(v*100-Math.round(v*100))>0.000001)throw Error('Payments must have a positive amount with at most two decimals; review refunds and voids separately');return v.toFixed(2);}
const types:Record<string,string>={OtherIncome:'Other Income',OtherExpense:'Other Expense',CostOfGoodsSold:'Cost of Goods Sold',OtherCurrentAsset:'Other Current Asset',OtherCurrentLiability:'Other Current Liability',LongTermLiability:'Long Term Liability',FixedAsset:'Fixed Asset',AccountsReceivable:'Accounts Receivable',AccountsPayable:'Accounts Payable',CreditCard:'Credit Card'};
export function reviewCsv(kind:Exclude<QboKind,'profit-loss'>,rows:any[],company:string,month:string,customers:any[]=[]){monthRange(month);text(company,'company');const seen=new Set<string>();for(const r of rows){const id=text(r.Id,'record ID');if(seen.has(id))throw Error('Duplicate QBO record ID');seen.add(id);}
 if(kind==='accounts')return csv([['Account number','Account name','Account type','Detail type','Active','QBO account ID'],...rows.map(r=>{if(typeof r.Active!=='boolean')throw Error('Account active state is missing');const type=text(r.AccountType,'account type');return [r.AcctNum??'',text(r.FullyQualifiedName??r.Name,'account name'),types[type]??type,r.AccountSubType??'',r.Active,r.Id];})]);
 if(kind==='customers'||kind==='vendors')return csv([['QBO ID','Display name','First name','Last name','Company name','Email','Phone','Mobile','Street','Street 2','City','State','Postal code','Country','Active','Parent QBO ID'],...rows.map(r=>[r.Id,text(r.DisplayName,'display name'),r.GivenName??'',r.FamilyName??'',r.CompanyName??'',r.PrimaryEmailAddr?.Address??'',r.PrimaryPhone?.FreeFormNumber??'',r.Mobile?.FreeFormNumber??'',r.BillAddr?.Line1??'',r.BillAddr?.Line2??'',r.BillAddr?.City??'',r.BillAddr?.CountrySubDivisionCode??'',r.BillAddr?.PostalCode??'',r.BillAddr?.Country??'',r.Active??'',r.ParentRef?.value??''])]);
 const names=new Map(customers.map(c=>[text(c.Id,'customer ID'),text(c.DisplayName,'customer display name')]));
 return csv([[company],['QBO payments · '+month],['Customer','Date','Transaction type','Transaction number','Amount','QBO payment ID','QBO customer ID','Currency','Unapplied amount','Original QBO document number'],...rows.filter(r=>r.TotalAmt!==0).map(r=>{const date=text(r.TxnDate,'payment date');const dt=new Date(date+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(dt.getTime())||dt.toISOString().slice(0,10)!==date||date.slice(0,7)!==month)throw Error('Payment is outside the selected month or has an invalid date');const id=text(r.CustomerRef?.value,'payment customer ID'),name=names.get(id);if(!name)throw Error('Payment customer is missing from the complete customer download');const currency=r.CurrencyRef?.value??'USD';if(currency!=='USD')throw Error('Non-USD payments require separate currency review');return [name,date,'Payment','QBO-ID-'+r.Id,money(r.TotalAmt),r.Id,id,currency,r.UnappliedAmt??'',r.DocNumber??''];})]);
}
export function reportCsv(payload:any){if(payload?.Fault||!Array.isArray(payload?.Columns?.Column)||!payload?.Rows)throw Error('QBO report is unavailable; verify your subscription and class settings');const columns=payload.Columns.Column;const rows:unknown[][]=[columns.map((c:any)=>c.ColTitle??'')];let count=0;function walk(block:any,depth:number){if(depth>12||++count>30000||rows.length>30000)throw Error('QBO report exceeds review limits');for(const r of block?.Row??[]){for(const part of [r.Header,r.ColData?{ColData:r.ColData}:null])if(part?.ColData)rows.push(part.ColData.map((c:any)=>c.value??''));if(r.Rows)walk(r.Rows,depth+1);if(r.Summary?.ColData)rows.push(r.Summary.ColData.map((c:any)=>c.value??''));}}walk(payload.Rows,0);return csv(rows);}
