import {undepositedAccount} from './bank-workflow';
import type {Data} from './pool';
import {canonicalRecord} from './workflow-controls';
import {native,bookChart,validateNativeAccounting,type LedgerEntry} from './native-accounting';
export type TenantLedgerLink={id:string;bookId:string;entryId:string;ledgerEntryId:string;receivableKey:string;counterKey:string;reviewer:string;created:string;source:{tenantId:string;unitId:string;kind:'Charge'|'Receipt'|'Credit';date:string;reference:string;description:string;cents:number}};
const incomeTypes=['income','other income'];
export function tenantLedgerLink(d:Data,entryId:string){return (d.accounting?.tenantLedgerLinks??[]).find(l=>l.entryId===entryId);}
export function tenantSourceReferences(d:Data,entryId:string){const source=d.operations?.tenantEntries?.find(e=>e.id===entryId),imported=d.qboImports?.flatMap(b=>b.rows).find(r=>r.receiptId===entryId);return [source?.reference,imported?.source.number].filter((v):v is string=>!!v).map(v=>v.trim().toLowerCase());}
export function tenantPostingCandidates(d:Data,entryId:string,bookId:string,receivableKey:string,counterKey:string){const source=d.operations?.tenantEntries?.find(e=>e.id===entryId),tenant=d.operations?.tenants?.find(t=>t.id===source?.tenantId);if(!source||!tenant)return [];const refs=tenantSourceReferences(d,entryId),sign=source.kind==='Charge'?1:-1;return native(d).entries.filter(e=>e.bookId===bookId&&e.date===source.date&&refs.includes(e.reference.trim().toLowerCase())&&!(d.accounting?.tenantLedgerLinks??[]).some(l=>l.ledgerEntryId===e.id)&&!native(d).entries.some(r=>r.reverses===e.id)&&e.lines.length===2&&e.lines.every(l=>!l.unitId||l.unitId===tenant.unitId)&&e.lines.filter(l=>l.accountKey===receivableKey).reduce((n,l)=>n+l.debit-l.credit,0)===sign*source.cents&&e.lines.filter(l=>l.accountKey===counterKey).reduce((n,l)=>n+l.debit-l.credit,0)===-sign*source.cents);}
export function postTenantSource(d:Data,input:{bookId:string;entryId:string;receivableKey:string;counterKey:string;reviewer:string;verified:boolean;existingLedgerEntryId?:string}){
 const source=d.operations?.tenantEntries?.find(e=>e.id===input.entryId),tenant=d.operations?.tenants?.find(t=>t.id===source?.tenantId),chart=bookChart(d,input.bookId),ar=chart?.accounts.find(a=>a.key===input.receivableKey),counter=chart?.accounts.find(a=>a.key===input.counterKey);
 if(!source||!tenant||!input.verified||!input.reviewer.trim())throw Error('Choose an existing tenant source and verify the company, original entry and reviewer');
 if(!ar?.active||ar.type.toLowerCase()!=='accounts receivable'||!counter?.active||(source.kind==='Receipt'?!(counter.type.toLowerCase()==='bank'||undepositedAccount(counter)):!incomeTypes.includes(counter.type.toLowerCase())))throw Error('Use the company Accounts Receivable GL, and Bank or Undeposited Funds for receipts, Income for charges / credits');
 if(tenantLedgerLink(d,source.id))throw Error('Tenant source is already linked to the ledger');
 const refs=tenantSourceReferences(d,source.id);if(!source.reference.trim())throw Error('Verify a unique original source reference before posting');
 const imported=d.qboImports?.find(b=>b.rows.some(r=>r.receiptId===source.id)),book=native(d).books.find(b=>b.id===input.bookId);if(imported&&imported.company.trim().toLowerCase()!==book?.company.trim().toLowerCase())throw Error('QBO receipt must use the same reviewed company book');
 const existing=input.existingLedgerEntryId?tenantPostingCandidates(d,source.id,input.bookId,input.receivableKey,input.counterKey).find(e=>e.id===input.existingLedgerEntryId):undefined;if(input.existingLedgerEntryId&&!existing)throw Error('Existing journal does not match the original source, accounts, amount and date');
 if(!existing&&source.kind==='Receipt'&&(native(d).entries.some(e=>e.bookId===input.bookId&&refs.includes(e.reference.trim().toLowerCase()))||(d.accounting?.cashPlanning?.manualEntries??[]).some(e=>e.kind==='Deposit'&&refs.includes(e.reference.trim().toLowerCase()))))throw Error('Receipt bank reference is already recorded; link the matching existing posting instead of creating another deposit');
 const next=structuredClone(d),id=crypto.randomUUID(),now=new Date().toISOString(),snapshot={tenantId:source.tenantId,unitId:tenant.unitId,kind:source.kind,date:source.date,reference:source.reference,description:source.description,cents:source.cents};
 const line=(accountKey:string,debit:number,credit:number)=>({accountKey,unitId:tenant.unitId,memo:source.description.slice(0,500),debit,credit});
 const entry:LedgerEntry={id,bookId:input.bookId,date:source.date,reference:'TENANT-'+source.id,memo:source.kind+' · '+tenant.firstName+' '+tenant.lastName+' · '+source.reference,reviewer:input.reviewer.trim(),created:now,reverses:'',recurringId:'',sourceSystem:'OG tenant ledger',externalId:source.id,lines:source.kind==='Charge'?[line(input.receivableKey,source.cents,0),line(input.counterKey,0,source.cents)]:[line(input.counterKey,source.cents,0),line(input.receivableKey,0,source.cents)]};
 if(!existing)next.accounting!.native!.entries.push(entry);(next.accounting!.tenantLedgerLinks??=[]).push({id:crypto.randomUUID(),bookId:input.bookId,entryId:source.id,ledgerEntryId:existing?.id??id,receivableKey:input.receivableKey,counterKey:input.counterKey,reviewer:input.reviewer.trim(),created:now,source:snapshot});validateNativeAccounting(next,d);validateTenantLedgerLinks(next,d);return next;
}
export function validateTenantLedgerLinks(d:Data,old?:Data){const links=d.accounting?.tenantLedgerLinks??[],before=old?.accounting?.tenantLedgerLinks??[];
 if(!Array.isArray(links)||links.length>20000||new Set(links.map(l=>l.id)).size!==links.length||new Set(links.map(l=>l.entryId)).size!==links.length||new Set(links.map(l=>l.ledgerEntryId)).size!==links.length||canonicalRecord(links.slice(0,before.length))!==canonicalRecord(before))throw Error('Tenant ledger source links are immutable and cannot be posted twice');
 for(const link of links){const source=d.operations?.tenantEntries?.find(e=>e.id===link.entryId),tenant=d.operations?.tenants?.find(t=>t.id===source?.tenantId),entry=native(d).entries.find(e=>e.id===link.ledgerEntryId),chart=bookChart(d,link.bookId),ar=chart?.accounts.find(a=>a.key===link.receivableKey),counter=chart?.accounts.find(a=>a.key===link.counterKey);if(!link.id||!link.reviewer.trim()||!Number.isFinite(Date.parse(link.created))||!source||!tenant||!entry||entry.bookId!==link.bookId||!ar?.active||ar.type.toLowerCase()!=='accounts receivable'||!counter?.active||(link.source.kind==='Receipt'?!(counter.type.toLowerCase()==='bank'||undepositedAccount(counter)):!incomeTypes.includes(counter.type.toLowerCase())))throw Error('Verify the tenant source, company and mapped receipt / charge accounts');
  const snapshot={tenantId:source.tenantId,unitId:tenant.unitId,kind:source.kind,date:source.date,reference:source.reference,description:source.description,cents:source.cents};if(canonicalRecord(snapshot)!==canonicalRecord(link.source))throw Error('Posted tenant source is locked; record a separate reviewed credit or correction instead of editing the original');
  if(!before.some(l=>l.id===link.id)){const imported=d.qboImports?.find(b=>b.rows.some(r=>r.receiptId===source.id)),book=native(d).books.find(b=>b.id===link.bookId),refs=tenantSourceReferences(d,source.id);if(imported&&imported.company.trim().toLowerCase()!==book?.company.trim().toLowerCase())throw Error('QBO receipt must use the same reviewed company book');if(native(d).entries.some(e=>e.reverses===entry.id))throw Error('Cannot link a reversed ledger source');if(source.kind==='Receipt'&&entry.sourceSystem==='OG tenant ledger'&&(native(d).entries.some(e=>e.id!==entry.id&&e.bookId===link.bookId&&refs.includes(e.reference.trim().toLowerCase()))||(d.accounting?.cashPlanning?.manualEntries??[]).some(e=>e.kind==='Deposit'&&refs.includes(e.reference.trim().toLowerCase()))))throw Error('Receipt bank reference is already recorded; link the existing posting');}
  const line=(accountKey:string,debit:number,credit:number)=>({accountKey,unitId:link.source.unitId,memo:link.source.description.slice(0,500),debit,credit}),expected=link.source.kind==='Charge'?[line(link.receivableKey,link.source.cents,0),line(link.counterKey,0,link.source.cents)]:[line(link.counterKey,link.source.cents,0),line(link.receivableKey,0,link.source.cents)];if(entry.sourceSystem==='OG tenant ledger'){if(entry.externalId!==source.id||entry.date!==link.source.date||entry.reference!=='TENANT-'+link.entryId||canonicalRecord(entry.lines)!==canonicalRecord(expected)||entry.reverses||entry.recurringId)throw Error('Tenant journal must preserve source date, unit and exact amounts');}else{const refs=tenantSourceReferences(d,source.id),sign=source.kind==='Charge'?1:-1;if(entry.date!==source.date||!refs.includes(entry.reference.trim().toLowerCase())||entry.lines.length!==2||entry.lines.some(l=>l.unitId&&l.unitId!==tenant.unitId)||entry.lines.filter(l=>l.accountKey===link.receivableKey).reduce((n,l)=>n+l.debit-l.credit,0)!==sign*source.cents||entry.lines.filter(l=>l.accountKey===link.counterKey).reduce((n,l)=>n+l.debit-l.credit,0)!==-sign*source.cents)throw Error('Linked existing journal must match the original tenant source');}
 }
 for(const e of native(d).entries.filter(e=>e.sourceSystem==='OG tenant ledger'))if(!links.some(l=>l.ledgerEntryId===e.id))throw Error('Tenant posting requires its original source link');
}
