import type {Data} from './pool';
import {audit} from './pool';
import {canonicalRecord} from './workflow-controls';
import {emptyOperations} from './operations-model';

export type RentMaster={id:string;period:string;fileName:string;fileHash:string;created:string;reviewer:string;source:unknown[][];rows:{unitId:string;tenantId:string;name:string;status:'Occupied'|'Vacant';rent:number;regular:number;regularFrom:string;sourceRows:number[]}[];concessionIds:string[]};
export function masterRent(d:Data,unitId:string,period:string){const b=[...(d.rentMasters??[])].reverse().sort((a,b)=>b.period.localeCompare(a.period)).find(b=>b.period<=period&&b.rows.some(r=>r.unitId===unitId));const row=b?.rows.find(r=>r.unitId===unitId);if(!b||!row)return null;if(period>b.period){const laterLease=d.operations?.leases?.some(l=>l.unitId===unitId&&l.status!=="Draft"&&l.start.slice(0,7)>b.period&&l.start<=period+"-31"&&l.end>=period+"-01");const tenancy=d.operations?.tenants?.find(t=>t.id===row.tenantId);const change=d.operations?.occupancy?.find(o=>o.unitId===unitId&&o.month===period);if(laterLease||row.status==="Occupied"&&(!tenancy||tenancy.end&&tenancy.end<period+"-01"||change?.status==="Vacant")||row.status==="Vacant"&&(change?.status==="Occupied"||d.operations?.tenants?.some(t=>t.unitId===unitId&&t.start.slice(0,7)>b.period&&t.start<=period+"-31"&&(!t.end||t.end>=period+"-01"))))return null;}return {row,b,cents:period>=row.regularFrom?row.regular:row.rent};}
export function prepareRentMaster(d:Data,p:{period:string;fileName:string;fileHash:string;source:unknown[][];specials?:{unit:string;regular:number}[]},reviewer:string):RentMaster{
 if([...(d.closeControls?.events??[])].reverse().find(e=>e.period===p.period)?.kind==='Closed')throw Error('Reopen the month before importing rent');
 if(!d.periods.some(x=>x.month===p.period)||!p.fileName.trim()||!/^([a-f0-9]{64})$/.test(p.fileHash)||!Array.isArray(p.source)||p.source.length>5000||JSON.stringify(p.source[0])!==JSON.stringify(['Unit','Name','Status','Total Amount','Operations Account','Escrow Account']))throw Error('Invalid master sheet or month');
 if(d.rentMasters?.some(b=>b.fileHash===p.fileHash&&b.period===p.period))throw Error('This master sheet was already imported');
 const groups=new Map<string,{raw:unknown[];row:number}[]>();p.source.slice(1).forEach((raw,i)=>{if(!raw[0])return;const u=String(raw[0]);if(!d.units.some(x=>x.number===u))throw Error('Unknown unit '+u);for(const k of [3,4,5])if(typeof raw[k]!=='number'||!Number.isFinite(raw[k])||Number(raw[k])<0||!Number.isSafeInteger(Math.round(Number(raw[k])*100)))throw Error('Invalid amount in source row '+(i+2));if(Math.round(Number(raw[3])*100)!==Math.round((Number(raw[4])+Number(raw[5]))*100))throw Error('Account split does not match source row '+(i+2));const rs=groups.get(u)??[];rs.push({raw,row:i+2});groups.set(u,rs);});
 const first=Number(p.period.slice(5)),year=Number(p.period.slice(0,4));const next=new Date(Date.UTC(year,first,1)).toISOString().slice(0,7);
 const specials=p.specials??[];if(new Set(specials.map(x=>x.unit)).size!==specials.length||specials.some(s=>!groups.has(s.unit)||!Number.isSafeInteger(s.regular)||s.regular<0))throw Error('Invalid regular rent schedule');
 const rows=[...groups].map(([number,rs])=>{const recurring=rs.filter(r=>['Occupied','Vacant'].includes(String(r.raw[2])));if(!recurring.length||new Set(recurring.map(r=>String(r.raw[2])+':'+r.raw[4])).size!==1)throw Error('Conflicting monthly rows for '+number);const raw=recurring.at(-1)!,unit=d.units.find(u=>u.number===number)!;const tenants=(d.operations?.tenants??[]).filter(t=>t.unitId===unit.id&&t.start<=p.period+'-31'&&(!t.end||t.end>=p.period+'-01'));if(tenants.length>1)throw Error('Review tenant identity for '+number);const name=String(raw.raw[1]??'').replace(/\s*\((SEPT|OCT)\)\s*$/i,'').replace(/\s*\/\s*$/,'').trim();if(!name)throw Error('Missing name for '+number);const rent=Math.round(Number(raw.raw[4])*100),special=specials.find(s=>s.unit===number);if(raw.raw[2]==='Vacant'&&rent!==0)throw Error('Vacant unit cannot have monthly rent');return {unitId:unit.id,tenantId:tenants[0]?.id??'',name,status:raw.raw[2] as 'Occupied'|'Vacant',rent,regular:special?.regular??rent,regularFrom:special?next:p.period,sourceRows:rs.map(r=>r.row)};});
 return {id:crypto.randomUUID(),period:p.period,fileName:p.fileName,fileHash:p.fileHash,created:new Date().toISOString(),reviewer,source:structuredClone(p.source),rows,concessionIds:[]};
}
export function importRentMaster(d:Data,p:Parameters<typeof prepareRentMaster>[1],reviewer:string){const n=structuredClone(d),b=prepareRentMaster(d,p,reviewer);n.operations??=emptyOperations();const ops=n.operations;ops.tenants??=[];ops.occupancy??=[];
 for(const r of b.rows){let t=ops.tenants.find(t=>t.id===r.tenantId);if(r.status==='Occupied'){const split=r.name.lastIndexOf(' ');if(split<1)throw Error('Verify tenant name '+r.name);if(!t){t={id:crypto.randomUUID(),unitId:r.unitId,firstName:r.name.slice(0,split),lastName:r.name.slice(split+1),email:'',cell:'',start:b.period+'-01',end:'',signedDate:'',rent:r.regular,rentConfirmed:true,opening:null,openingDate:b.period+'-01',notes:'Opening record from '+b.fileName};ops.tenants.push(t);r.tenantId=t.id;}else{t.firstName=r.name.slice(0,split);t.lastName=r.name.slice(split+1);}t.notes+='\nMaster sheet '+b.fileName+' / '+b.period+' / monthly '+r.rent/100+' / regular '+r.regular/100+' from '+r.regularFrom;}
 const o=ops.occupancy.find(o=>o.unitId===r.unitId&&o.month===b.period);if(o){o.status=r.status;o.notes+='\nVerified from '+b.fileName;}else ops.occupancy.push({id:crypto.randomUUID(),unitId:r.unitId,month:b.period,status:r.status,notes:'Verified from '+b.fileName});
 }
 (n.rentMasters??=[]).push(b);audit(n,'Rent master imported',b.fileName+' / '+b.period+' / '+b.rows.length+' units / escrow and prior balances excluded; dates and payments preserved');return n;}
export function validateRentMasters(old:Data,n:Data){if(new Set((n.rentMasters??[]).map(b=>b.id)).size!==(n.rentMasters??[]).length)throw Error("Duplicate rent master identity");for(const b of old.rentMasters??[])if(!(n.rentMasters??[]).some(x=>x.id===b.id&&canonicalRecord(x)===canonicalRecord(b)))throw Error('Preserve rent master history');for(const b of n.rentMasters??[]){if(old.rentMasters?.some(x=>x.id===b.id))continue;const input={period:b.period,fileName:b.fileName,fileHash:b.fileHash,source:b.source,specials:b.rows.filter(r=>r.regularFrom>b.period).map(r=>({unit:n.units.find(u=>u.id===r.unitId)!.number,regular:r.regular}))};const parsed=prepareRentMaster(old,input,b.reviewer);if(canonicalRecord(parsed.rows.map(({tenantId,...r})=>r))!==canonicalRecord(b.rows.map(({tenantId,...r})=>r)))throw Error('Rent master rows must match source');for(const row of b.rows)if(row.status==='Occupied'&&!n.operations?.tenants?.some(t=>t.id===row.tenantId&&t.unitId===row.unitId))throw Error('Master tenant identity missing');if(b.concessionIds.length)throw Error('Rent master import cannot create financial entries');}}


