import type {Data} from './pool';
import {cents,money} from './pool';
import {parseCSV} from './exports';
import {native,bookChart} from './native-accounting';
import {nativeReport} from './accounting-tools';
import {canonicalRecord} from './workflow-controls';
import {monthBounds} from './tenancy';
export type BudgetPlan={id:string;bookId:string;year:number;name:string;source:string;reviewer:string;created:string;lines:{accountKey:string;months:number[]}[];archived:boolean};
export const budgetHeaders=['account',...Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0'))];
export const isIncome=(type:string)=>['income','other income'].includes(type.toLowerCase());
export const budgetAccount=(type:string)=>isIncome(type)||['expense','expenses','other expense','other expenses','cost of goods sold'].includes(type.toLowerCase());
export function parseBudget(d:Data,bookId:string,text:string){if(text.length>1000000)throw Error('Budget CSV exceeds 1 MB');const rows=parseCSV(text.replace(/^\uFEFF/,''));if(rows.shift()?.join('|')!==budgetHeaders.join('|')||!rows.length||rows.length>500)throw Error('Use the budget template with 1-500 account rows');const chart=bookChart(d,bookId);if(!chart)throw Error('Choose a verified company ledger');const lines=rows.map(row=>{if(row.length!==13)throw Error('Every budget row needs an account and 12 monthly amounts');const matches=chart.accounts.filter(a=>a.active&&budgetAccount(a.type)&&(a.key===row[0].trim()||a.number===row[0].trim()));if(matches.length!==1)throw Error('Choose an unambiguous active income or expense GL account');const months=row.slice(1).map(v=>cents(v.trim()));if(months.some(n=>n<0))throw Error('Enter positive planned income and expenses');return {accountKey:matches[0].key,months};});if(new Set(lines.map(l=>l.accountKey)).size!==lines.length)throw Error('Budget accounts cannot repeat');return lines;}
export function validateBudgetPlans(old:Data,next:Data){const rows=next.budgetPlans??[];if(!Array.isArray(rows)||rows.length>500||new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Invalid budget history');for(const r of rows){const chart=bookChart(next,r.bookId);if(!r.id||!chart||!Number.isInteger(r.year)||r.year<2000||r.year>2200||!r.name?.trim()||r.name.length>100||!r.source?.trim()||r.source.length>2000||!r.reviewer?.trim()||!Number.isFinite(Date.parse(r.created))||typeof r.archived!=='boolean'||!Array.isArray(r.lines)||!r.lines.length||r.lines.length>500||new Set(r.lines.map(l=>l.accountKey)).size!==r.lines.length)throw Error('Enter a valid company budget with original source details');for(const l of r.lines)if(!chart.accounts.some(a=>a.key===l.accountKey&&budgetAccount(a.type))||!Array.isArray(l.months)||l.months.length!==12||l.months.some(n=>!Number.isSafeInteger(n)||n<0||n>100000000000))throw Error('Invalid monthly budget amounts');}for(const p of old.budgetPlans??[]){const r=rows.find(r=>r.id===p.id);if(!r)throw Error('Archive budgets without removing history');const {archived:a,...before}=p,{archived:b,...after}=r;if(canonicalRecord(before)!==canonicalRecord(after)||p.archived&&!r.archived)throw Error('Budget history is immutable; save a revised plan');}}
export function saveBudgetPlan(d:Data,input:Omit<BudgetPlan,'id'|'created'|'archived'|'lines'>,text:string){const next=structuredClone(d);(next.budgetPlans??=[]).push({...input,id:crypto.randomUUID(),created:new Date().toISOString(),archived:false,lines:parseBudget(d,input.bookId,text)});validateBudgetPlans(d,next);return next;}
export function budgetComparison(d:Data,id:string,period:string){
 const plan=d.budgetPlans?.find(p=>p.id===id);monthBounds(period);if(!plan||plan.year!==Number(period.slice(0,4)))throw Error('Choose a budget for this reporting year');
 const book=native(d).books.find(b=>b.id===plan.bookId)!,chart=bookChart(d,plan.bookId)!,m=Number(period.slice(5))-1,{last:end}=monthBounds(period),yearStart=plan.year+'-01-01';
 const actual=end<book.openingDate?null:nativeReport(d,plan.bookId,'Income statement',period+'-01',end),ytd=end<book.openingDate?null:nativeReport(d,plan.bookId,'Income statement',yearStart,end),completeYear=book.openingDate<=yearStart;
 return {headers:['Account','Month budget','Posted month actual','Actual minus budget','Annual budget','Year-to-date budget','Posted year-to-date actual','Year-to-date coverage'],rows:plan.lines.map(l=>{
  const a=chart.accounts.find(a=>a.key===l.accountKey)!,sign=isIncome(a.type)?-1:1,value=actual===null?null:(actual.find(r=>r.accountKey===l.accountKey)?.balance??0)*sign,ytdValue=ytd===null?null:(ytd.find(r=>r.accountKey===l.accountKey)?.balance??0)*sign;
  return [[a.number,a.name].filter(Boolean).join(' · '),money(l.months[m]),value===null?'Before ledger opening':money(value),value===null?'Unavailable':money(value-l.months[m]),money(l.months.reduce((n,v)=>n+v,0)),money(l.months.slice(0,m+1).reduce((n,v)=>n+v,0)),ytdValue===null?'Before ledger opening':money(ytdValue),ytdValue===null?'Unavailable':completeYear?'From January 1':'Partial: verified opening '+book.openingDate];
 }),note:'Planning report only; no ledger entries or payments are created. Income and expense amounts are positive. Actuals contain posted OG transactions only and the budgeted accounts only. A month containing the opening date may have partial coverage. Year-to-date coverage identifies incomplete prior history.'};
}
