import type {Data} from './pool';
import {latest,totals,isParticipating,ownerAt,verifiedVacantUnits} from './pool';
import {incomeRows,depositBalance} from './accounting-model';
import {tenantBalance} from './operations-model';
import {homeownerBalance,validDate} from './people-calendar';
import {maintenanceReportRows} from './maintenance-reports';
import {leasingActivity} from './leasing-model';
import catalog from './report-catalog.json';
export const reportCatalog=catalog;
export type ReportFilters={propertyId:string;from:string;to:string};
export type ReportResult={available:boolean;columns:string[];rows:unknown[][];note:string};
const supported=['Property Directory','Unit Directory','Property Group Directory','Rent Roll','Rent Roll (Itemized)','Rent Roll (Commercial)','Renter Directory','Tenant Directory','Tenant Ledger','Tenant Vehicle Info','Tenant Unpaid Charges','Tenant Unpaid Charges Summary','Tenant Transactions Summary','Receivables Activity','Charge Detail','Resident Financial Activity','Homeowner Directory','Dues Roll','Dues Roll (Itemized)','Homeowner Ledger','Homeowner Delinquency','Homeowner Delinquency (As Of)','Violation Detail','Architectural Review Detail','Board of Directors','Survey Responses','Owner Directory','Owner Statement','Owner Statement (Enhanced)','Bank Account Directory','Bank Account Association','Chart of Accounts','Journal Entry Register','Expense Distribution','Expense Register','Bill Detail','Vendor Ledger','Vendor Ledger (Enhanced)','Check Register','Check Register Detail','Check Register Detail (Enhanced)','Deposit Register','Security Deposit Funds Detail','Work Order','Association Work Order','Work Order Billable Detail','Work Order Labor Summary','Inspection Detail','Unit Inspection','Unit Turn Detail','Project Directory','Purchase Order','Recurring Work Order','Fixed Assets','Inventory Status','Inventory Usage','Guest Card Inquiries','Guest Card Interests','Inactive Guest Card Interests','Lease History','Lease Expiration Detail By Month','Lease Expiration Summary By Month','Leasing Agent Performance','Leasing Funnel Performance','Leasing Summary','Occupancy Summary','Owner Leasing','Prospect Source Tracking','Renewal Summary','Rental Applications','Showings','Unit Vacancy Detail','Gross Potential Rent','Management Fee History','Office Task Register','External Transfer Register'];
export const reportSupported=(name:string)=>supported.includes(name);
const price=(n:number)=>(n/100).toFixed(2);
export function scopeReportData(data:Data,propertyId:string){if(!propertyId)return data;if(!data.properties.some(p=>p.id===propertyId))throw Error('Unknown report property');const d=structuredClone(data),ids=new Set(d.units.filter(u=>u.propertyId===propertyId).map(u=>u.id));d.units=d.units.filter(u=>ids.has(u.id));d.properties=d.properties.filter(p=>p.id===propertyId);d.pools=d.pools.filter(p=>p.propertyId===propertyId);d.statements=d.statements.filter(s=>ids.has(s.unitId));const ownerIds=new Set([...d.units.map(u=>u.ownerId),...d.ownerships.filter(o=>ids.has(o.unitId)).map(o=>o.ownerId)]);d.owners=d.owners.filter(o=>ownerIds.has(o.id));d.ownerships=d.ownerships.filter(o=>ids.has(o.unitId));d.settings=d.settings.filter(s=>d.pools.some(p=>p.id===s.poolId));if(d.operations){const ops=d.operations,tenantIds=new Set((ops.tenants??[]).filter(t=>ids.has(t.unitId)).map(t=>t.id));for(const key of ['tenants','unitVendors','homeowners','workOrders','prospects','leases','rentalApplications','leaseRenewals','showingSlots','vacancyListings','recurringWork','purchaseOrders','fixedAssets'] as const){if(key==='leaseRenewals'){ops.leaseRenewals=ops.leaseRenewals?.filter(r=>ops.leases.some(l=>l.id===r.leaseId&&ids.has(l.unitId)));continue;}if(ops[key]) (ops as any)[key]=(ops[key] as any[]).filter(r=>ids.has(r.unitId));}ops.tenantEntries=ops.tenantEntries?.filter(e=>tenantIds.has(e.tenantId));ops.tenantRecurring=ops.tenantRecurring?.filter(r=>tenantIds.has(r.tenantId));ops.homeownerEntries=ops.homeownerEntries?.filter(e=>ops.homeowners?.some(h=>h.id===e.homeownerId));}if(d.accounting){d.accounting.deposits=d.accounting.deposits.filter(e=>ids.has(e.unitId));d.accounting.settlements=d.accounting.settlements.filter(e=>ownerIds.has(e.ownerId)).map(e=>({...e,lines:e.lines.filter(l=>d.statements.some(s=>s.id===l.statementId))}));}if(d.office){const o=d.office;for(const key of ['profiles','accounts','journals','surveys','compliance','rules','attendance','tasks'] as const)if(o[key])(o as any)[key]=(o[key] as any[]).filter(r=>r.propertyId===propertyId);o.groups=o.groups?.filter(g=>g.propertyIds.includes(propertyId));o.transfers=o.transfers?.filter(t=>o.accounts?.some(a=>a.id===t.fromId)&&o.accounts?.some(a=>a.id===t.toId));}d.procurement=undefined;return d;}
export function buildReport(data:Data,name:string,f:ReportFilters):ReportResult{
 if(!validDate(f.from)||!validDate(f.to)||f.from>f.to)throw Error('Choose a valid report date range');
 if(!reportSupported(name))return {available:false,columns:[],rows:[],note:'Requires complete source records or an external accounting/reporting service. OG does not generate this report from partial records.'};
 const d=scopeReportData(data,f.propertyId),ops=d.operations,month=f.to.slice(0,7),inRange=(date:string)=>!!date&&date>=f.from&&date<=f.to,unit=(id:string)=>d.units.find(u=>u.id===id)?.number??'Not assigned',property=(id:string)=>d.properties.find(p=>p.id===id)?.name??'Not assigned',owner=(id:string)=>d.owners.find(o=>o.id===id)?.name??'Not verified';
 const result=(columns:string[],rows:unknown[][],note='Saved OG records only; not synchronized with AppFolio.')=>({available:true,columns,rows,note});
 const structured=(rows:unknown[][],note:string)=>result(rows[0] as string[],rows.slice(1),note);
 if(name==='Property Directory')return result(['property','classification','address','city','state','zip','contact','phone','email','units'],d.properties.map(p=>[p.name,d.office?.profiles?.find(r=>r.propertyId===p.id)?.kind??'Unclassified',p.address,p.city,p.state,p.zip,p.contactName,p.phone,p.email,d.units.filter(u=>u.propertyId===p.id).length]));
 if(name==='Property Group Directory')return result(['group','properties','active','notes'],(d.office?.groups??[]).map(g=>[g.name,g.propertyIds.map(property).join('; '),g.active,g.notes]));
 if(name==='Unit Directory')return result(['unit_id','unit','property','owner','pool','participation_month','active'],d.units.map(u=>[u.id,u.number,property(u.propertyId),owner(ownerAt(d,u.id,f.to)),d.pools.find(p=>p.id===u.poolId)?.name,month,isParticipating(d,u,month)]));
 if(['Tenant Directory','Renter Directory','Rent Roll','Rent Roll (Itemized)','Rent Roll (Commercial)','Gross Potential Rent'].includes(name))return result(['tenant','unit','email','phone','start','end','contract_rent','as_of','recorded_balance'],(ops?.tenants??[]).filter(t=>name.includes('Directory')||t.start<=f.to&&(!t.end||t.end>=f.from)).map(t=>[t.firstName+' '+t.lastName,unit(t.unitId),t.email,t.cell,t.start,t.end,price(t.rent),f.to,tenantBalance(ops!,t,f.to)===null?'UNCONFIRMED':price(tenantBalance(ops!,t,f.to)!)]),'Contract rates and recorded balances. Unknown opening balances remain unconfirmed. No rent proration or market-rent forecast.');
 if(name==='Tenant Vehicle Info')return result(['tenant','unit','make','year','plate','other'],(ops?.tenants??[]).map(t=>[t.firstName+' '+t.lastName,unit(t.unitId),t.vehicleMake,t.vehicleYear,t.vehiclePlate,t.vehicles]));
 if(['Tenant Ledger','Tenant Transactions Summary','Receivables Activity','Charge Detail','Resident Financial Activity','Deposit Register'].includes(name))return result(['date','tenant','unit','type','category','description','amount','reference'],(ops?.tenantEntries??[]).filter(e=>inRange(e.date)&&(name!=='Charge Detail'||e.kind==='Charge')&&(name!=='Deposit Register'||e.kind==='Receipt')).map(e=>{const t=ops?.tenants?.find(t=>t.id===e.tenantId);return [e.date,t? t.firstName+' '+t.lastName:'Unknown',unit(t?.unitId??''),e.kind,e.category??'Unclassified',e.description,price(e.cents),e.reference];}),'Recorded tenant entries in selected dates. Deposit Register lists external receipts; it is not proof of bank deposits.');
 if(name.startsWith('Tenant Unpaid Charges'))return result(['tenant','unit','charge_date','description','amount','applied_as_of','outstanding_as_of'],(ops?.tenantEntries??[]).filter(e=>e.kind==='Charge'&&e.date<=f.to).map(e=>{const t=ops?.tenants?.find(t=>t.id===e.tenantId),applied=(d.accounting?.applications??[]).filter(a=>a.chargeId===e.id&&ops?.tenantEntries?.some(r=>r.id===a.receiptId&&r.date<=f.to)).reduce((n,a)=>n+a.cents,0);return [t?.firstName+' '+t?.lastName,unit(t?.unitId??''),e.date,e.description,price(e.cents),price(applied),price(Math.max(0,e.cents-applied))];}).filter(r=>r[6]!=='0.00'),'Outstanding recorded charges through the selected date. No assumed due dates or automatic collection notices.');
 if(['Homeowner Directory','Dues Roll','Dues Roll (Itemized)','Homeowner Delinquency','Homeowner Delinquency (As Of)'].includes(name))return result(['homeowner','unit','email','phone','start','end','as_of','balance'],(ops?.homeowners??[]).filter(h=>!name.includes('Delinquency')||(homeownerBalance(ops!,h,f.to)??0)>0).map(h=>[h.name,unit(h.unitId),h.email,h.phone,h.start,h.end,f.to,homeownerBalance(ops!,h,f.to)===null?'UNCONFIRMED':price(homeownerBalance(ops!,h,f.to)!)]),'Recorded homeowner ledger only. Positive balances are not independently aged; unknown opening balances remain unconfirmed.');
 if(name==='Homeowner Ledger')return result(['date','homeowner','unit','type','description','amount','reference'],(ops?.homeownerEntries??[]).filter(e=>inRange(e.date)).map(e=>{const h=ops?.homeowners?.find(h=>h.id===e.homeownerId);return [e.date,h?.name,unit(h?.unitId??''),e.kind,e.description,price(e.cents),e.reference];}));
 if(name==='Violation Detail'||name==='Architectural Review Detail')return result(['date','property','unit','type','title','status','evidence','notes'],(d.office?.compliance??[]).filter(c=>inRange(c.date)&&c.kind===(name==='Violation Detail'?'Violation':'Architectural review')).map(c=>[c.date,property(c.propertyId),unit(c.unitId),c.kind,c.title,c.status,c.reference,c.notes]));
 if(name==='Board of Directors')return result(['property','supplied_board_contact'],(d.office?.profiles??[]).map(p=>[property(p.propertyId),p.boardContact]),'Supplied board contacts only; a full board-member roster has not been imported.');
 if(name==='Survey Responses')return result(['date','property','work_order','respondent','rating','comments','reference'],(d.office?.surveys??[]).filter(s=>inRange(s.date)).map(s=>[s.date,property(s.propertyId),ops?.workOrders.find(w=>w.id===s.workOrderId)?.number,s.respondent,s.rating,s.comments,s.reference]));
 if(name==='Owner Directory')return result(['owner_id','owner','email','phone','address','units'],d.owners.map(o=>[o.id,o.name,o.email,o.phone,o.address,d.units.filter(u=>ownerAt(d,u.id,f.to)===o.id).map(u=>u.number).join('; ')]));
 if(name.startsWith('Owner Statement'))return result(['owner','unit','period','version','status','allocated','deductions','cash_paid','closing'],d.periods.filter(p=>p.month>=f.from.slice(0,7)&&p.month<=month).flatMap(p=>latest(d,p.month).map(s=>[owner(s.ownerId),unit(s.unitId),s.period,s.version,s.status,price(s.allocated),price(totals(s).deductions),price(s.cashPaid??s.paidAmount),price(totals(s).closing)])),'Internal owner distribution summary. Use Owner Statements for versioned PDFs and supporting documents.');
 if(name==='Chart of Accounts')return result(['code','name','type','mapped_qbo_name','active'],(d.office?.glAccounts??[]).map(g=>[g.code,g.name,g.type,g.qboName,g.active]),'Maintained OG mapping directory. It does not overwrite QBO or previously reviewed classifications.');
 if(name.startsWith('Bank Account'))return result(['account','institution','type','property','last_four','external_statement_balance','as_of','source_reference','active'],(d.office?.accounts??[]).map(a=>[a.name,a.institution,a.type,property(a.propertyId),a.last4,a.balance===null?'UNKNOWN':price(a.balance),a.balanceDate,a.reference,a.active]),'Externally supplied balance snapshots; no bank feed or live balance.');
 if(name==='Journal Entry Register')return result(['date','property','description','status','external_reference','GL','debit','credit'],(d.office?.journals??[]).filter(j=>inRange(j.date)).flatMap(j=>j.lines.map(l=>[j.date,property(j.propertyId),j.description,j.status,j.reference,d.office?.glAccounts?.find(g=>g.id===l.glId)?.code,price(l.debit),price(l.credit)])),'Balanced internal review records. External posting status does not post a local general ledger.');
 if(name==='External Transfer Register')return result(['date','from','to','amount','status','reference'],(d.office?.transfers??[]).filter(t=>inRange(t.date)).map(t=>[t.date,d.office?.accounts?.find(a=>a.id===t.fromId)?.name,d.office?.accounts?.find(a=>a.id===t.toId)?.name,price(t.cents),t.status,t.reference]),'Transfer documentation only. No funds are moved or balances updated.');
 if(['Expense Distribution','Expense Register','Bill Detail','Vendor Ledger','Vendor Ledger (Enhanced)','Management Fee History'].includes(name)){const rows=d.periods.filter(p=>p.month>=f.from.slice(0,7)&&p.month<=month).flatMap(p=>incomeRows(d,p.month)).filter(r=>inRange(r.date)&&(name!=='Management Fee History'||r.gl==='80400'));return result(['date','source','description','unit','amount','recipient','GL','account','treatment','reviewed','payment_status','bill_reference'],rows.map(r=>[r.date,r.kind,r.description,r.unit,price(r.cents),r.recipient,r.gl,r.accountName,r.treatment,r.confirmed,r.paymentState,r.invoiceRef]),'Charge and purchase source review, not a complete GL or proof of payment. Property filters exclude unassigned bulk inventory.');}
 if(name.startsWith('Check Register'))return result(['date','owner','unit','reference','cash_paid','status'],d.statements.filter(s=>s.status==='Paid'&&inRange(s.paidDate)).map(s=>[s.paidDate,owner(s.ownerId),unit(s.unitId),s.paymentRef,price(s.cashPaid??s.paidAmount),s.status]),'Externally recorded owner distributions only. Not a bank-wide check register.');
 if(name==='Security Deposit Funds Detail')return result(['date','tenant','unit','type','amount','approved','reference','treatment'],(d.accounting?.deposits??[]).filter(e=>inRange(e.date)).map(e=>[e.date,ops?.tenants?.find(t=>t.id===e.tenantId)?.firstName,unit(e.unitId),e.kind,price(e.cents),e.approved,e.reference,e.treatment]),'Recorded escrow events; bank/trust balance reconciliation is external.');
 const maintenance:Record<string,[any,string]>={'Work Order':['Work Orders','Work Order'],'Association Work Order':['Work Orders','Work Order'],'Work Order Billable Detail':['Work Orders','Billable Detail'],'Work Order Labor Summary':['Work Orders','Labor Summary'],'Inspection Detail':['Inspections','Unit Inspection'],'Unit Inspection':['Inspections','Unit Inspection'],'Unit Turn Detail':['Unit Turns','Unit Inspection'],'Project Directory':['Projects','Work Order'],'Purchase Order':['Purchase Orders','Purchase Order'],'Recurring Work Order':['Work Orders','Recurring Work Order'],'Fixed Assets':['Fixed Assets','Fixed Assets'],'Inventory Status':['Inventory','Inventory Status'],'Inventory Usage':['Inventory','Unit Usage']};
 if(maintenance[name]){const [section,report]=maintenance[name];return structured(maintenanceReportRows(d,section,report),'Current saved maintenance register. Date ranges do not trim undated register records. Property filters exclude unassigned records.');}
 const activity=leasingActivity(ops??{workOrders:[],events:[],communications:[],prospects:[],leases:[],bankRecords:[]},f.from,f.to);
 if(['Guest Card Inquiries','Guest Card Interests','Inactive Guest Card Interests'].includes(name))return result(['created','guest','email','unit','source','agent','stage','tour'],activity.guests.filter(p=>name!=='Inactive Guest Card Interests'||p.stage==='Closed').map(p=>[p.created,p.name,p.email,unit(p.unitId),p.source,p.agent,p.stage,p.tour]),'Dated guest cards only. Undated legacy records are excluded: '+activity.undated);
 if(name==='Prospect Source Tracking'||name==='Leasing Agent Performance')return result([name==='Prospect Source Tracking'?'source':'agent','guest_cards','tours_scheduled'],(name==='Prospect Source Tracking'?activity.sources:activity.agents).map(g=>[g.name,g.guests,g.tours]),'Guest creation-date cohort activity, not conversion rates.');
 if(name==='Leasing Funnel Performance'||name==='Leasing Summary')return result(['stage','count'],[['Guest cards',activity.guests.length],['Tours scheduled',activity.guests.filter(g=>g.tour).length],['Applications',activity.applications.length],['Undated guest cards excluded',activity.undated]],'Saved activity counts. No inferred conversion rates.');
 if(name==='Rental Applications')return result(['date','applicant','unit','email','status','recorded_fee','external_decision_reference'],activity.applications.map(a=>[a.date,a.name,unit(a.unitId),a.email,a.status,price(a.fee),a.decisionReference]),'Recorded application fees are informational and do not post tenant charges.');
 if(name==='Renewal Summary')return result(['tenant','unit','proposed_start','end','rent','status','external_reference'],(ops?.leaseRenewals??[]).filter(r=>inRange(r.start)).map(r=>{const l=ops?.leases.find(l=>l.id===r.leaseId);return [l?.tenant,unit(l?.unitId??''),r.start,r.end,price(r.rent),r.status,r.externalReference];}));
 if(name.startsWith('Lease Expiration')||name==='Lease History')return result(['tenant','unit','start','end','rent','status','signed_date'],(ops?.leases??[]).filter(l=>name==='Lease History'||inRange(l.end)).map(l=>[l.tenant,unit(l.unitId),l.start,l.end,price(l.rent),l.status,l.signedDate]));
 if(name==='Showings')return result(['date','time','unit','agent','status','notes'],(ops?.showingSlots??[]).filter(s=>inRange(s.date)).map(s=>[s.date,s.time,unit(s.unitId),s.agent,s.status,s.notes]),'Saved showing availability. Prospect tours are listed separately in Calendar.');
 if(name==='Unit Vacancy Detail'||name==='Occupancy Summary'||name==='Owner Leasing')return result(['unit','owner','property','month','active_pool','verified_occupancy'],d.units.filter(u=>name!=='Unit Vacancy Detail'||verifiedVacantUnits(d,month).some(v=>v.id===u.id)).map(u=>[u.number,owner(ownerAt(d,u.id,f.to)),property(u.propertyId),month,isParticipating(d,u,month),ops?.occupancy?.find(o=>o.unitId===u.id&&o.month===month)?.status??'Unknown']),'Occupancy is verified per accounting month. Missing leases do not automatically mean vacancy.');
 if(name==='Office Task Register')return result(['date','section','property','task','status','reference','notes'],(d.office?.tasks??[]).filter(t=>inRange(t.date)).map(t=>[t.date,t.section,property(t.propertyId),t.task,t.status,t.reference,t.notes]));
 throw Error('Report implementation unavailable');
}
export function selectReportColumns(result:ReportResult,columns:string[]){if(!columns.length)return result;if(columns.some(c=>!result.columns.includes(c)))throw Error('Saved report columns no longer match this report');return {...result,columns,rows:result.rows.map(row=>columns.map(c=>row[result.columns.indexOf(c)]))};}
