import {type Data,money,latest,totals,isParticipating,ownerAt} from './pool';
import {monthBounds,monthTenants,expectedUnitRent} from './tenancy';
import {tenantArrears,ownerOutstanding} from './month-close';
import {recordState} from './workflow-controls';
import {isOwnerContact} from './contact-directory';
import {laborCost} from './operations-model';
import {partStock} from './procurement-model';
import {native,bookChart} from './native-accounting';
import {payables,payableState,payableTotal,payableAging} from './payables-ledger';
export const operationalReports=[
 ['owners','Owner directory','Owners'],['distributions','Owner distribution register','Owners'],
 ['units','Unit directory & membership','Properties'],['rent-roll','Rent roll','Leasing'],
 ['occupancy','Occupancy & vacancy','Leasing'],['leases','Lease history','Leasing'],['expirations','Lease expirations','Leasing'],
 ['prospects','Guest cards & leasing pipeline','Leasing'],['sources','Prospect source tracking','Leasing'],
 ['applications','Rental applications','Leasing'],['showings','Showings','Leasing'],['renewals','Renewal history','Leasing'],
 ['vehicles','Resident vehicles','Residents'],['keys','Unit & mailbox keys','Properties'],['properties','Property directory','Properties'],
 ['tenants','Tenant directory','Residents'],['unpaid','Tenant unpaid charges','Residents'],['receipts','Tenant receipt register','Residents'],['charges','Tenant charge & credit register','Residents'],
 ['vendors','Vendor directory','Maintenance'],['work','Work order register','Maintenance'],['labor','Work order labor','Maintenance'],['inspections','Inspections & unit turns','Maintenance'],
 ['audit','Account activity','Diagnostics'],
 ['inventory','Inventory status','Properties'],['inventory-usage','Inventory usage','Properties'],['purchases','Stock purchase register','Maintenance'],
 ['calendar','Activities summary','Properties'],['lease-summary','Lease expiration summary','Leasing'],['occupancy-summary','Occupancy summary','Leasing'],
 ['tenant-ledger','Tenant ledger','Residents'],['bills','Bill & credit detail','Accounting'],['aged-payables','Aged payables summary','Accounting'],
 ['chart','Chart of accounts','Accounting'],['banks','Bank account directory','Accounting'],['bank-reconciliations','Bank reconciliation history','Accounting']
] as const;
export type OperationalReportId=typeof operationalReports[number][0];
export type ReportTable={headers:string[];rows:string[][];unitIds:string[];note:string};
export function operationalReport(d:Data,id:OperationalReportId,period:string,propertyId=''):ReportTable{
 if(!operationalReports.some(r=>r[0]===id))throw Error('Choose a supported report');
 const {last:end}=monthBounds(period),start=period+'-01',units=d.units.filter(u=>(!propertyId||u.propertyId===propertyId)&&(!u.addedMonth||u.addedMonth<=period)),ids=new Set(units.map(u=>u.id)),ops=d.operations;
 const number=(id:string)=>units.find(u=>u.id===id)?.number??'Company',owner=(id:string)=>d.owners.find(o=>o.id===ownerAt(d,id,end))?.name??'Not recorded';
 let headers:string[]=[],rows:string[][]=[],unitIds:string[]=[];
 const add=(id:string,values:unknown[])=>{unitIds.push(id);rows.push(values.map(v=>String(v??'')));};
 const leases=(ops?.leases??[]).filter(l=>ids.has(l.unitId)&&l.start<=end);
 const tenants=(ops?.tenants??[]).filter(t=>ids.has(t.unitId)&&t.start<=end&&(!t.end||t.end>=start));
 if(id==='owners'){headers=['Owner','Unit','Email','Phone','Payment preference'];for(const u of units){const o=d.owners.find(o=>o.id===ownerAt(d,u.id,end));add(u.id,[o?.name,number(u.id),o?.email,o?.phone,o?.paymentMethod]);}}
 if(id==='units'){headers=['Unit','Property','Owner','Type','Pool participation'];for(const u of units)add(u.id,[u.number,d.properties.find(p=>p.id===u.propertyId)?.name,owner(u.id),u.type===1?'1/1':'2/2',isParticipating(d,u,period)?'Active':'Excluded']);}
 if(id==='distributions'){headers=['Owner','Unit','Status','Pool allocation','Deductions','Proposed distribution','Recorded payments','Closing balance'];for(const s of latest(d,period).filter(s=>ids.has(s.unitId))){const t=totals(s);add(s.unitId,[d.owners.find(o=>o.id===s.ownerId)?.name,number(s.unitId),s.status,money(s.allocated),money(t.deductions),money(t.available),money(s.paidAmount),money(ownerOutstanding(d,s))]);}}
 if(id==='rent-roll'){headers=['Unit','Tenant','Expected monthly rent','Verification','Tenancy start','Tenancy end'];for(const u of units){const rent=expectedUnitRent(d,u,period),ts=monthTenants(d,u.id,period);add(u.id,[u.number,ts.map(t=>t.firstName+' '+t.lastName).join('; ')||'Not recorded',rent.cents===null?'Unverified':money(rent.cents),rent.source,ts.map(t=>t.start).join('; '),ts.map(t=>t.end||'Active').join('; ')]);}}
 if(id==='occupancy'){headers=['Unit','Owner','Verified occupancy','Marketing status'];for(const u of units){const o=ops?.occupancy?.find(o=>o.unitId===u.id&&o.month===period);add(u.id,[u.number,owner(u.id),o?.status??'Unverified',o?.marketingStatus??'Not recorded']);}}
 if(id==='leases'||id==='expirations'){headers=['Unit','Tenant','Start','End','Contract rent','Status'];for(const l of leases.filter(l=>id==='leases'||l.end>=start&&l.end<=end))add(l.unitId,[number(l.unitId),l.tenant,l.start,l.end,money(l.rent),l.status]);}
 if(id==='prospects'||id==='sources'){headers=['Unit','Prospect','Stage','Source','Tour','Follow-up'];for(const p of ops?.prospects??[])if((ids.has(p.unitId)||!propertyId&&!p.unitId)&&recordState(d,'prospects',p.id)==='Active'&&(!p.tour||p.tour<=end))add(p.unitId,[number(p.unitId),p.name,p.stage,p.source??'Not recorded',p.tour,p.followUp]);}
 if(id==='tenants'){headers=['Unit','Tenant','Email','Phone','Start','End'];for(const t of tenants)add(t.unitId,[number(t.unitId),t.firstName+' '+t.lastName,t.email,t.cell,t.start,t.end||'Active']);}
 if(id==='applications'){headers=['Unit','Applicant','Submitted','Status','Decision date'];for(const a of ops?.rentalApplications??[])if(ids.has(a.unitId)&&a.submitted>=start&&a.submitted<=end)add(a.unitId,[number(a.unitId),ops?.prospects.find(p=>p.id===a.prospectId)?.name,a.submitted,a.status,a.decided]);}
 if(id==='showings'){headers=['Unit','Prospect','Date','Time','Host','Status'];for(const s of ops?.leasingShowings??[])if(ids.has(s.unitId)&&s.date>=start&&s.date<=end)add(s.unitId,[number(s.unitId),ops?.prospects.find(p=>p.id===s.prospectId)?.name,s.date,s.time,s.assignee,s.status]);}
 if(id==='renewals'){headers=['Unit','Tenant','Original lease','Renewal start','End','Rent','Status'];for(const l of leases.filter(l=>l.renewalOf))add(l.unitId,[number(l.unitId),l.tenant,l.renewalOf,l.start,l.end,money(l.rent),l.status]);}
 if(id==='vehicles'){headers=['Unit','Resident','Plate','Make','Year','Second plate','Second make','Second year'];for(const t of tenants)add(t.unitId,[number(t.unitId),t.firstName+' '+t.lastName,t.vehiclePlate,t.vehicleMake,t.vehicleYear,t.secondVehiclePlate,t.secondVehicleMake,t.secondVehicleYear]);}
 if(id==='keys'){headers=['Unit','Resident','Unit key','Mailbox key'];for(const t of tenants)add(t.unitId,[number(t.unitId),t.firstName+' '+t.lastName,t.unitKeyNumber,t.mailKeyNumber]);}
 if(id==='properties'){headers=['Property','Company','Address','City','State','ZIP','Phone','Email'];for(const p of d.properties.filter(p=>!propertyId||p.id===propertyId))add('',[p.name,p.companyName,p.address,p.city,p.state,p.zip,p.phone,p.email]);}
 if(id==='unpaid'){headers=['Unit','Tenant','Charge date','Reference','Charge','Outstanding'];for(const r of tenantArrears(d,period)){const t=ops?.tenants?.find(t=>t.id===r.entry.tenantId);if(t&&ids.has(t.unitId))add(t.unitId,[number(t.unitId),t.firstName+' '+t.lastName,r.entry.date,r.entry.reference,r.entry.description,money(r.remaining)]);}}
 if(id==='receipts'||id==='charges'){headers=['Unit','Tenant','Date','Kind','Reference','Description','Amount'];for(const e of ops?.tenantEntries??[]){const t=ops?.tenants?.find(t=>t.id===e.tenantId);if(t&&ids.has(t.unitId)&&e.date>=start&&e.date<=end&&(id==='receipts'?e.kind==='Receipt':e.kind!=='Receipt'))add(t.unitId,[number(t.unitId),t.firstName+' '+t.lastName,e.date,e.kind,e.reference,e.description,money(e.cents)]);}}
 if(id==='vendors'){headers=['Vendor','Company','Email','Phone','Scope'];for(const v of ops?.vendorContacts??[])if(!propertyId&&!isOwnerContact(d,v))add('',[v.name,v.company,v.email,v.phone,'Shared company contact']);for(const v of ops?.unitVendors??[])if(ids.has(v.unitId)&&v.start<=end&&(!v.end||v.end>=start)&&!isOwnerContact(d,v))add(v.unitId,[v.name,'',v.email,v.cell,'Unit '+number(v.unitId)]);}
 if(['work','labor','inspections'].includes(id)){headers=['Unit','Work order','Title','Status','Assigned','Scheduled','Labor hours','Hourly rate','Labor amount'];for(const w of ops?.workOrders??[])if(ids.has(w.unitId)&&w.created.slice(0,10)<=end&&recordState(d,'workOrders',w.id)==='Active'&&(id!=='inspections'||['Inspection','Unit turn'].includes(w.kind)))add(w.unitId,[number(w.unitId),w.number,w.title,w.status,w.assignee,w.scheduled,(w.hours100/100).toFixed(2),money(w.rate),money(laborCost(w))]);}
 if(id==='audit'){headers=['Date','Action','Detail'];if(!propertyId)for(const a of d.audit.filter(a=>a.at.slice(0,10)>=start&&a.at.slice(0,10)<=end))add('',[a.at,a.action,a.detail]);}
 if(id==='inventory'){headers=['SKU','Part','Measure','Stock','Reorder level','Current unit price','Current status'];if(!propertyId&&d.procurement){const p={...d.procurement,purchases:d.procurement.purchases.filter(r=>r.date<=end),issues:d.procurement.issues.filter(r=>r.date<=end),corrections:d.procurement.corrections?.filter(r=>r.date<=end)};for(const r of p.parts)add('',[r.sku,r.name,r.measure,partStock(p,r.id),r.reorderAt,money(r.listPrice),r.active?'Active':'Disabled']);}}
 if(id==='inventory-usage'){headers=['Unit','Date','SKU','Part','Quantity','Unit price','Total charge','Reference'];for(const r of d.procurement?.issues??[])if(ids.has(r.unitId)&&r.date>=start&&r.date<=end)add(r.unitId,[number(r.unitId),r.date,r.sku,r.partName,r.quantity,money(r.listPrice),money(r.totalCharge),r.reference]);}
 if(id==='purchases'){headers=['Date','Supplier','SKU','Quantity','Acquisition cost','Reference'];if(!propertyId)for(const r of d.procurement?.purchases??[])if(r.date>=start&&r.date<=end)add('',[r.date,r.supplier,d.procurement?.parts.find(p=>p.id===r.partId)?.sku,r.quantity,money(r.totalCost),r.reference]);}
 if(id==='calendar'){headers=['Unit','Date','End','Activity','Kind'];for(const r of ops?.events??[])if((ids.has(r.unitId)||!propertyId&&!r.unitId)&&r.date>=start&&r.date<=end&&recordState(d,'events',r.id)==='Active')add(r.unitId,[number(r.unitId),r.date,r.end,r.title,r.kind]);}
 if(id==='lease-summary'){headers=['Property','Expiring leases','Current active expiring leases'];for(const p of d.properties.filter(p=>!propertyId||p.id===propertyId)){const list=leases.filter(l=>l.end>=start&&l.end<=end&&units.find(u=>u.id===l.unitId)?.propertyId===p.id);add('',[p.name,list.length,list.filter(l=>l.status==='Active').length]);}}
 if(id==='occupancy-summary'){headers=['Property','Units','Occupied','Vacant','Other verified status','Unverified'];for(const p of d.properties.filter(p=>!propertyId||p.id===propertyId)){const list=units.filter(u=>u.propertyId===p.id),states=list.map(u=>ops?.occupancy?.find(o=>o.unitId===u.id&&o.month===period)?.status);add('',[p.name,list.length,states.filter(s=>s==='Occupied').length,states.filter(s=>s==='Vacant').length,states.filter(s=>s&&s!=='Occupied'&&s!=='Vacant').length,states.filter(s=>!s).length]);}}
 if(id==='tenant-ledger'){headers=['Unit','Tenant','Date','Reference','Description','Charge','Receipt','Credit'];for(const e of ops?.tenantEntries??[]){const t=ops?.tenants?.find(t=>t.id===e.tenantId);if(t&&ids.has(t.unitId)&&e.date<=end)add(t.unitId,[number(t.unitId),t.firstName+' '+t.lastName,e.date,e.reference,e.description,money(e.kind==='Charge'?e.cents:0),money(e.kind==='Receipt'?e.cents:0),money(e.kind==='Credit'?e.cents:0)]);}}
 if(id==='bills'){headers=['Company','Vendor','Type','Date','Due','Reference','Unit','Description','Line amount','Scope total (repeated)','Status'];for(const doc of payables(d).documents.filter(r=>r.date<=end)){const book=native(d).books.find(b=>b.id===doc.bookId);for(const line of doc.lines)if(!propertyId||ids.has(line.unitId))add(line.unitId,[book?.company,doc.payee,doc.kind,doc.date,doc.due,doc.reference,number(line.unitId),line.description,money(line.cents),money(propertyId?doc.lines.filter(l=>ids.has(l.unitId)).reduce((n,l)=>n+l.cents,0):payableTotal(doc)),payableState(d,doc,end).status]);}}
 if(id==='aged-payables'){headers=['Company','Vendor','Current','1-30 days','31-60 days','61-90 days','Over 90 days','Outstanding'];if(!propertyId)for(const b of native(d).books)for(const r of payableAging(d,b.id,end))add('',[b.company,r.payee,money(r.current),money(r.days30),money(r.days60),money(r.days90),money(r.older),money(r.total)]);}
 if(['chart','banks'].includes(id)){headers=['Company','GL number','Account','Type','Current status'];if(!propertyId)for(const b of native(d).books)for(const a of bookChart(d,b.id)?.accounts??[])if(id==='chart'||a.type.toLowerCase()==='bank')add('',[b.company,a.number,a.name,a.type,a.active?'Active':'Disabled']);}
 if(id==='bank-reconciliations'){headers=['Company','Bank','From','Through','Beginning','Ending','Matched statement rows','Reviewer'];if(!propertyId)for(const r of native(d).reconciliations.filter(r=>r.end<=end))add('',[native(d).books.find(b=>b.id===r.bookId)?.company,bookChart(d,r.bookId)?.accounts.find(a=>a.key===r.accountKey)?.name,r.start,r.end,money(r.beginning),money(r.ending),r.rows.length,r.reviewer]);}
 return {headers,rows,unitIds,note:propertyId&&['inventory','purchases','aged-payables','chart','banks','bank-reconciliations'].includes(id)?'Company-wide records have no verified property assignment. Clear the property filter to review them.':id==='inventory'?'Stock movements through month end; unit prices, reorder levels and part status reflect current saved settings.':id==='tenant-ledger'?'Recorded transactions through month end. This transaction register excludes opening balances; review the resident profile for the complete balance.':id==='bills'?'Bill lines through month end. Scope totals repeat per line; do not sum repeated totals. Status is calculated as of month end.':id==='distributions'?'Office review only. Includes current saved drafts; approved owner-facing packets are prepared separately.':id==='prospects'||id==='sources'?'Current saved pipeline, filtered by tour cutoff. OG does not reconstruct historical stages.':id==='work'||id==='labor'||id==='inspections'?'Saved work created through month end; current status and rates, not historical snapshots.':id==='audit'&&propertyId?'Company-wide audit details are excluded when filtering one property. Clear the property filter to review authorized company activity.':'Saved OG records for the selected month. Missing records or opening balances do not prove zero balances.'};
}
