export type SettingLink={label:string;target?:string;reason?:string};
export const settingsCatalog:{title:string;links:SettingLink[]}[]=[
{title:'Company & connected services',links:[{label:'Manage Company Settings',target:'properties:Properties'},{label:'Manage My Settings',target:'@personal'},{label:'Manage Integrations',target:'@connections'},{label:'Community Association Bank Settings',target:'accounting:Financial Accounts'}]},
{title:'Accounting',links:[{label:'Manage Accounting Settings',target:'accounting:DLA Analysis'},{label:'Manage Accounting Periods',target:'settings'},{label:'Management Fee Allocation & Contracts',target:'accounting:Pool Allocation & Contracts'},{label:'Vendor Payment Preferences',target:'people:Vendors'},{label:'Accounting Integrations Settings',target:'accounting:QBO Exports'},{label:'Homeowner Delinquency Process Setup',reason:'Automatic notices are not connected. Review receivables in Accounting.'}]},
{title:'Approvals',links:[{label:'Owner Statement Approvals',target:'statements'},{label:'Purchase Order Approvals',target:'maintenance:Purchase Orders'},{label:'Manage Custom Bill Approval Flow',reason:'Custom routing is not configured. Existing approval controls remain in each workflow.'}]},
{title:'Users',links:[{label:'Manage User Roles and Permissions',target:'@roles'},{label:'Manage Users',target:'@users'},{label:'New User',target:'@new-user'},{label:'Manage GL Account Permissions',reason:'GL visibility follows OG role and property access. Per-account permissions are not configured.'}]},
{title:'Property Groups',links:[{label:'Manage Property Groups',target:'properties:Properties'},{label:'New Property Group',target:'properties:Properties'}]},
{title:'Owners',links:[{label:'Management Agreement Records',target:'people:Owners'},{label:'Bulk Portal Actions',reason:'Owner portals are not connected.'}]},
{title:'Residents',links:[{label:'Resident Onboarding',target:'people:Tenants'}]},
{title:'Leasing',links:[{label:'Online Posting Settings',target:'leasing:Vacancies'},{label:'Showings Settings',target:'leasing:Guest Cards'},{label:'Rental Application Settings',target:'leasing:Rental Applications'},{label:'Rental Application Customization & Screening Criteria',target:'leasing:Rental Applications'},{label:'Lease Settings & Templates',target:'leasing:Leases'}]},
{title:'Documents',links:[{label:'PDF Form Template References',target:'leasing:Leases'},{label:'Supporting Documents',target:'documents'}]},
{title:'Maintenance',links:[{label:'Work Order Settings & Notifications',target:'maintenance:Work Orders'},{label:'Work Order Issues',target:'maintenance:Work Orders'},{label:'Scheduling Settings',target:'maintenance:Recurring Work Orders'},{label:'Project Budgeting',reason:'Project budget controls are not implemented. Work-order estimates remain available.'}]},
{title:'Communication',links:[{label:'Automatic Work-order Communication',target:'maintenance:Work Orders'},{label:'Communication Records',target:'communication'},{label:'Survey Settings',target:'reporting:Surveys'},{label:'Texting Settings',reason:'SMS is not connected.'},{label:'Rent & Dues Reminder Settings',reason:'Automatic reminder sending is not connected.'},{label:'Bulk Communication Settings',reason:'Bulk delivery is not connected.'},{label:'Owner Settings',target:'people:Owners'},{label:'Text & Email Templates',reason:'Automated templates are not configured. Work-order notification text uses the DLA workspace rule.'}]},
{title:'Risk Mitigation',links:[{label:'Vendor Compliance Records',target:'people:Vendors'},{label:'Insurance & Security Deposit Alternatives',reason:'External insurance and deposit services are not connected.'}]},
{title:'Tags',links:[{label:'Manage Tags & Amenity Tags',reason:'Tag configuration is not implemented.'}]},
{title:'Affordable Housing',links:[{label:'Subsidy Programs & Affordable Housing Settings',reason:'Subsidy programs and HUD exports are not connected.'}]}
];
