import type {SupabaseRecordConfig} from './supabase-records';
export const DOCUMENT_BUCKET='og-private-documents';
export function supabaseFiles(config:SupabaseRecordConfig,request:typeof fetch=fetch){
 const url=new URL(config.url);if(url.protocol!=='https:'||!url.hostname.endsWith('.supabase.co')||url.pathname!=='/'||url.search||url.hash)throw Error('Invalid Supabase file endpoint');
 const headers={apikey:config.secret,...(config.secret.startsWith('sb_secret_')?{}:{Authorization:'Bearer '+config.secret})};
 const path=(key:string)=>{if(!key||key.split('/').some(p=>!p||p==='.'||p==='..'))throw Error('Invalid document path');return key.split('/').map(encodeURIComponent).join('/');};
 async function call(endpoint:string,init:RequestInit={}){const r=await request(new URL('/storage/v1/'+endpoint,url),{...init,headers:{...headers,...init.headers},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Supabase document operation failed ('+r.status+')');return r;}
 async function ensurePrivate(){let r=await request(new URL('/storage/v1/bucket/'+DOCUMENT_BUCKET,url),{headers,signal:AbortSignal.timeout(15000)});let missing=r.status===404;if(r.status===400){try{const detail=await r.clone().json() as {statusCode?:string;message?:string};missing=detail.statusCode==='404'||detail.message==='Bucket not found';}catch{}}if(missing){await call('bucket',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:DOCUMENT_BUCKET,name:DOCUMENT_BUCKET,public:false,file_size_limit:10000000,allowed_mime_types:['application/pdf','image/jpeg','image/png']})});r=await call('bucket/'+DOCUMENT_BUCKET);}else if(!r.ok)throw Error('Unable to inspect document bucket');const b=await r.json() as {public:boolean};if(b.public!==false)throw Error('Document bucket must be private; setup blocked');}
 return {ensurePrivate,put:async(key:string,bytes:ArrayBuffer,mime:string)=>{await call('object/'+DOCUMENT_BUCKET+'/'+path(key),{method:'POST',headers:{'Content-Type':mime,'x-upsert':'false'},body:bytes});},get:async(key:string)=>call('object/authenticated/'+DOCUMENT_BUCKET+'/'+path(key)),remove:async(key:string)=>{await call('object/'+DOCUMENT_BUCKET,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefixes:[key]})});}};
}
export async function fileHash(value:ArrayBuffer){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',value)),b=>b.toString(16).padStart(2,'0')).join('');}
