import type {Data,Unit} from './pool';
import type {Tenant} from './operations-model';
export function monthBounds(month:string){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('Choose a valid accounting month');return {first:month+'-01',last:new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).toISOString().slice(0,10)};}
export function monthTenants(data:Data,unitId:string,month:string){const {first,last}=monthBounds(month);return (data.operations?.tenants??[]).filter(t=>t.unitId===unitId&&t.start<=last&&(!t.end||t.end>=first));}
export function expectedUnitRent(data:Data,unit:Unit,month:string):{cents:number|null;source:string;tenantId:string;review:string}{
 const {first,last}=monthBounds(month),tenants=monthTenants(data,unit.id,month),occupancy=data.operations?.occupancy?.find(o=>o.unitId===unit.id&&o.month===month),leases=(data.operations?.leases??[]).filter(l=>l.unitId===unit.id&&l.status!=='Draft'&&l.start<=last&&l.end>=first);
 const unknown=(review:string)=>({cents:null,source:'Needs review',tenantId:'',review});
 if(occupancy?.status==='Vacant'){if(tenants.length||leases.length)return unknown('Vacancy conflicts with a tenant or lease for this month');return {cents:0,source:'Verified vacant occupancy',tenantId:'',review:''};}
 if(tenants.length>1||leases.length>1)return unknown('Multiple effective records; review the tenancy or mid-month change');
 if(leases.length){const l=leases[0],t=tenants.find(t=>t.id===l.tenantId);if(!l.tenantId||!t)return unknown('Link the lease to its effective tenant');if(l.start>first||l.end<last)return unknown('Partial-month lease; verify the agreed monthly charge');return {cents:l.rent,source:'Lease '+l.id,tenantId:t.id,review:''};}
 if(tenants.length){const t=tenants[0];if(t.start>first||t.end&&t.end<last)return unknown('Partial-month tenancy; verify the agreed monthly charge');if(t.rentConfirmed===false)return unknown('Verify the tenant rent amount');return {cents:t.rent,source:'Tenant agreement '+t.id,tenantId:t.id,review:''};}
 return unknown('No effective tenant agreement or verified vacancy');
}
export function validateTenancyChanges(old:Data,next:Data){
 const ops=next.operations;if(!ops)return;const before=old.operations;for(const prior of before?.occupancy??[]){const record=ops.occupancy?.find(r=>r.id===prior.id);if(!record||record.unitId!==prior.unitId||record.month!==prior.month)throw Error('Preserve monthly occupancy history and identity');}
 for(const t of ops.tenants??[]){if(t.rentConfirmed!==undefined&&typeof t.rentConfirmed!=='boolean')throw Error('Invalid rent verification');const prior=before?.tenants?.find(p=>p.id===t.id);if(prior&&prior.rentConfirmed!==false&&t.rentConfirmed===false)throw Error('Preserve verified rent evidence; record corrections as a dated lease');if(prior&&prior.rentConfirmed!==false&&t.rent!==prior.rent)throw Error('Preserve verified tenant rent; record a dated lease or renewal for a rent change');if(prior&&prior.unitId!==t.unitId)throw Error('Preserve tenant/unit identity; create a new tenancy for a move');if(!prior||prior.start!==t.start||prior.end!==t.end||prior.unitId!==t.unitId){if((ops.tenants??[]).some(p=>p.id!==t.id&&p.unitId===t.unitId&&p.start<=(t.end||'9999-12-31')&&t.start<=(p.end||'9999-12-31')))throw Error('Tenant terms overlap; use co-tenant contact fields or close the previous tenancy');}}
 for(const l of ops.leases){const previous=before?.leases.find(p=>p.id===l.id);if(previous&&previous.status!=='Draft'){for(const k of ['unitId','tenantId','tenant','start','end','rent','signedDate'] as const)if(previous[k]!==l[k])throw Error('Preserve the original effective lease; create a separate renewal record');if(l.status==='Draft'||previous.status==='Ended'&&l.status!=='Ended')throw Error('A historical lease cannot return to draft or active');}
  if(l.status==='Active'&&(!previous||previous.status==='Draft')){const t=ops.tenants?.find(t=>t.id===l.tenantId&&t.unitId===l.unitId);if(!t)throw Error('An active lease requires its linked tenant');if(t.start>l.start||t.end&&t.end<l.end)throw Error('Lease term must be within the linked tenancy');if(!l.signedDate)throw Error('Record the verified contract signature date before activation');}}
 for(const collection of ['unitVendors','leases'] as const)for(const p of before?.[collection]??[]){const n=ops[collection]?.find(n=>n.id===p.id);if(n&&n.unitId!==p.unitId)throw Error('Preserve '+collection+' unit identity');}
}
