import type {Data} from './pool';
import type {Member} from './access-policy';

export const CONTROL_COLLECTIONS=['events','workOrders','prospects','communications'] as const;
export type ControlCollection=typeof CONTROL_COLLECTIONS[number];
export type RecordState='Active'|'Canceled'|'Deleted';
export type ApprovalRequest={id:string;collection:ControlCollection;recordId:string;label:string;action:RecordState;reason:string;requesterId:string;requesterName:string;created:string;recordSnapshot:unknown;stateSnapshot:RecordState;status:'Pending'|'Approved'|'Rejected'|'Stale'|'Withdrawn';reviewerId?:string;reviewerName?:string;reviewed?:string;comment?:string};
export type RecordStateChange={id:string;collection:ControlCollection;recordId:string;state:RecordState;at:string;actorId:string;actorName:string;approvalId?:string};
export type WorkflowControls={requests:ApprovalRequest[];states:RecordStateChange[]};
export function canonicalRecord(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonicalRecord).join(',')+']';if(value!==null&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonicalRecord((value as Record<string,unknown>)[k])).join(',')+'}';return JSON.stringify(value)??'null';}
export function recordState(data:Data,collection:ControlCollection,id:string):RecordState{return data.workflow?.states.filter(s=>s.collection===collection&&s.recordId===id).at(-1)?.state??'Active';}
const manager=(actor:Member)=>['Global Admin','Management'].includes(actor.role);
function actorAllowed(actor:Member){if(actor.status!=='Active'||actor.must_change_password||!actor.auth_id||!actor.workspace_id||!['Global Admin','Management','Analyst / Agent','Maintenance','Accounting Clerk'].includes(actor.role))throw Error('Workflow access denied');}
function source(data:Data,collection:ControlCollection,id:string){if(!CONTROL_COLLECTIONS.includes(collection))throw Error('This record type cannot be deleted through the approval queue');const r=(data.operations?.[collection]??[]).find(x=>x.id===id);if(!r)throw Error('Record not found');return r;}
function scopedSource(data:Data,actor:Member,collection:ControlCollection,id:string){actorAllowed(actor);const r=source(data,collection,id);if(!allowedCollections(actor).includes(collection))throw Error('Record type outside role permissions');const property=data.units.find(u=>u.id===r.unitId)?.propertyId;if(!manager(actor)&&(!property||!actor.property_ids.includes(property)))throw Error('Record outside assigned properties');return r;}
function controls(data:Data){return data.workflow??=( {requests:[],states:[]} );}
function log(data:Data,actor:Member,action:string,detail:string){data.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),action,detail,...{actor:actor.name,actorId:actor.auth_id}});}
function validAction(action:RecordState){if(!['Active','Canceled','Deleted'].includes(action))throw Error('Invalid record action');}
function canChange(data:Data,collection:ControlCollection,id:string,action:RecordState){validAction(action);if(recordState(data,collection,id)===action)throw Error('Record already has this state');if(action==='Canceled'&&collection!=='events')throw Error('Cancellation is available for calendar events');if(collection==='workOrders'&&action==='Deleted'&&(data.accounting?.laborPosts.some(p=>p.workOrderId===id)||data.procurement?.issues.some(p=>p.workOrderId===id)))throw Error('A financially linked work order must retain its source record');}
export function requestRecordAction(data:Data,actor:Member,collection:ControlCollection,id:string,action:RecordState,reason:string){const r=scopedSource(data,actor,collection,id);canChange(data,collection,id,action);if(typeof reason!=='string'||!reason.trim()||reason.length>2000)throw Error('Enter a reason of 1 to 2000 characters');const c=controls(data);if(c.requests.some(q=>q.status==='Pending'&&q.collection===collection&&q.recordId===id&&q.action===action))throw Error('A matching approval request is already pending');const label='number' in r?r.number:'title' in r?r.title:'subject' in r?r.subject:r.name;const q:ApprovalRequest={id:crypto.randomUUID(),collection,recordId:id,label,action,reason:reason.trim(),requesterId:actor.auth_id,requesterName:actor.name,created:new Date().toISOString(),recordSnapshot:structuredClone(r),stateSnapshot:recordState(data,collection,id),status:'Pending'};c.requests.push(q);log(data,actor,'Approval requested',collection+' / '+id+' / '+action);return q;}
function apply(data:Data,actor:Member,collection:ControlCollection,id:string,action:RecordState,approvalId?:string){scopedSource(data,actor,collection,id);canChange(data,collection,id,action);controls(data).states.push({id:crypto.randomUUID(),collection,recordId:id,state:action,at:new Date().toISOString(),actorId:actor.auth_id,actorName:actor.name,...(approvalId?{approvalId}:{})});log(data,actor,action==='Deleted'?'Record deleted to trash':action==='Active'?'Record restored':'Event canceled',collection+' / '+id+(approvalId?' / approval '+approvalId:''));}
export function changeRecordState(data:Data,actor:Member,collection:ControlCollection,id:string,action:RecordState){if(!manager(actor)&&!(actor.role==='Analyst / Agent'&&collection==='events'&&action==='Canceled'))throw Error('Management approval is required');apply(data,actor,collection,id,action);}
export function reviewRecordRequest(data:Data,actor:Member,id:string,decision:'Approve'|'Reject',comment:string){actorAllowed(actor);if(!manager(actor))throw Error('Only Global Admin or Management can review approvals');if(!['Approve','Reject'].includes(decision)||typeof comment!=='string'||comment.length>2000||!comment.trim())throw Error('Enter a review comment');const q=controls(data).requests.find(q=>q.id===id);if(!q||q.status!=='Pending')throw Error('Approval request is not pending');const r=scopedSource(data,actor,q.collection,q.recordId);if(canonicalRecord(r)!==canonicalRecord(q.recordSnapshot)||recordState(data,q.collection,q.recordId)!==q.stateSnapshot){Object.assign(q,{status:'Stale',reviewerId:actor.auth_id,reviewerName:actor.name,reviewed:new Date().toISOString(),comment:'Record changed after the request. '+comment});log(data,actor,'Approval stale',q.id+' / fresh review required');return q;}
 if(decision==='Approve')apply(data,actor,q.collection,q.recordId,q.action,q.id);Object.assign(q,{status:decision==='Approve'?'Approved':'Rejected',reviewerId:actor.auth_id,reviewerName:actor.name,reviewed:new Date().toISOString(),comment:comment.trim()});log(data,actor,decision==='Approve'?'Approval approved':'Approval rejected',q.id);return q;}
export function withdrawRecordRequest(data:Data,actor:Member,id:string){actorAllowed(actor);const q=controls(data).requests.find(q=>q.id===id);if(!q||q.status!=='Pending'||q.requesterId!==actor.auth_id)throw Error('Only the requester can withdraw a pending request');q.status='Withdrawn';log(data,actor,'Approval withdrawn',q.id);}
export function allowedCollections(actor:Member):readonly ControlCollection[]{return actor.role==='Maintenance'?['workOrders']:actor.role==='Accounting Clerk'?[]:CONTROL_COLLECTIONS;}
export function visibleRequests(data:Data,actor:Member){actorAllowed(actor);return (data.workflow?.requests??[]).filter(q=>{if(manager(actor))return true;const r=source(data,q.collection,q.recordId),property=data.units.find(u=>u.id===r.unitId)?.propertyId;return q.requesterId===actor.auth_id&&allowedCollections(actor).includes(q.collection)&&!!property&&actor.property_ids.includes(property);});}
export function validateWorkflowControls(old:Data,next:Data){const c=next.workflow;if(!c){if(old.workflow)throw Error('Preserve workflow history');return;}if(!Array.isArray(c.requests)||!Array.isArray(c.states)||c.requests.length>20000||c.states.length>50000)throw Error('Invalid workflow history');for(const key of ['requests','states'] as const){if(new Set(c[key].map(x=>x.id)).size!==c[key].length)throw Error('Duplicate workflow ID');}
 for(const s of c.states){source(next,s.collection,s.recordId);validAction(s.state);if(!s.id||!s.actorId||!s.actorName||!Number.isFinite(Date.parse(s.at)))throw Error('Invalid state history');if(s.approvalId&&!c.requests.some(q=>q.id===s.approvalId&&q.status==='Approved'&&q.collection===s.collection&&q.recordId===s.recordId&&q.action===s.state&&q.reviewerId===s.actorId))throw Error('State change requires its matching approved request');}
 for(const prior of old.workflow?.states??[])if(!c.states.some(x=>canonicalRecord(x)===canonicalRecord(prior)))throw Error('State history cannot be rewritten');
 const oldStates=old.workflow?.states??[];if(canonicalRecord(c.states.slice(0,oldStates.length))!==canonicalRecord(oldStates))throw Error('Preserve state history order');
 for(const q of c.requests){source(next,q.collection,q.recordId);validAction(q.action);if(!q.id||!q.requesterId||!q.requesterName||!q.reason?.trim()||q.reason.length>2000||!Number.isFinite(Date.parse(q.created))||!['Pending','Approved','Rejected','Stale','Withdrawn'].includes(q.status)||!q.recordSnapshot||!['Active','Canceled','Deleted'].includes(q.stateSnapshot))throw Error('Invalid approval request');if(['Approved','Rejected','Stale'].includes(q.status)&&(!q.reviewerId||!q.reviewerName||!q.comment?.trim()||!Number.isFinite(Date.parse(q.reviewed??''))))throw Error('A decision requires reviewer evidence');if(q.status==='Approved'&&!c.states.some(s=>s.approvalId===q.id))throw Error('Approval must have applied its record action');}
 for(const prior of old.workflow?.requests??[]){const q=c.requests.find(x=>x.id===prior.id);if(!q)throw Error('Approval history cannot be removed');if(prior.status!=='Pending'&&canonicalRecord(prior)!==canonicalRecord(q))throw Error('Completed approval history is immutable');const base=(x:ApprovalRequest)=>{const {status,reviewerId,reviewerName,reviewed,comment,...rest}=x;return rest;};if(canonicalRecord(base(prior))!==canonicalRecord(base(q)))throw Error('Approval request content is immutable');}
 for(const collection of CONTROL_COLLECTIONS)for(const r of old.operations?.[collection]??[]){if(recordState(old,collection,r.id)!=='Active'&&canonicalRecord(r)!==canonicalRecord(source(next,collection,r.id)))throw Error('Restore the record before editing it');}
}
