import {recordState} from './workflow-controls';
import type {Data} from './pool';
export const WORK_MAILBOX='dla@devonshirecondos.com';
export type WorkNotification={id:string;workId:string;ticket:string;created:string;subject:string;text:string;state:'Pending connection'|'Pending'|'Delivery uncertain'|'Accepted by Outlook'|'Rejected';attemptedAt?:string;error?:string};
export type WorkReply={id:string;workId:string;received:string;from:string;text:string};
export type WorkMail={notifications:WorkNotification[];replies:WorkReply[];cursor?:string;nextLink?:string};
export const canonical=(v:unknown):string=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
export function assertMailUnchanged(old:Data,next:Data){if(canonical(old.workMail??null)!==canonical(next.workMail??null))throw Error('Email queue and replies are server managed');}
export function queueWorkChanges(old:Data,next:Data,connected:boolean,now=new Date().toISOString(),uuid=()=>crypto.randomUUID()){const mail=next.workMail??{notifications:[],replies:[]};for(const w of next.operations?.workOrders??[]){const previous=old.operations?.workOrders.find(r=>r.id===w.id);if(previous&&canonical(previous)===canonical(w)&&recordState(old,'workOrders',w.id)===recordState(next,'workOrders',w.id))continue;const ticket=mail.notifications.find(n=>n.workId===w.id)?.ticket??uuid(),u=next.units.find(u=>u.id===w.unitId);mail.notifications.push({id:uuid(),workId:w.id,ticket,created:now,subject:'[OG-WO:'+ticket+'] '+w.number+' '+(previous?'updated':'opened')+' - '+w.title,text:['OG work order '+(previous?'updated':'opened'),'Number: '+w.number,'Unit: '+(u?.number??'Unassigned'),'Title: '+w.title,'Status: '+w.status,'Record: '+recordState(next,'workOrders',w.id),'Priority: '+w.priority,'Assigned: '+(w.assignee||w.vendor||'Unassigned'),'Scheduled: '+(w.scheduled||'Not scheduled'),'Entry permission: '+(w.permissionToEnter||'Not recorded'),'Request: '+w.description,'Progress: '+w.notes,'','Replies must retain the OG-WO subject marker. Recognized tenant replies are attached to the ticket; they do not change status or charges.'].join('\n'),state:connected?'Pending':'Pending connection'});}if(mail.notifications.length)next.workMail=mail;}
export function acceptWorkReply(d:Data,m:{id:string;subject:string;receivedDateTime:string;from?:{emailAddress?:{address?:string}};body?:{content?:string};bodyPreview?:string}){if(typeof m.id!=='string'||!m.id||typeof m.subject!=='string'||typeof m.receivedDateTime!=='string'||m.from?.emailAddress?.address!==undefined&&typeof m.from.emailAddress.address!=='string'||m.body?.content!==undefined&&typeof m.body.content!=='string'||m.bodyPreview!==undefined&&typeof m.bodyPreview!=='string')return false;const token=m.subject.match(/\[OG-WO:([a-zA-Z0-9-]+)\]/)?.[1],mail=d.workMail;if(!token||!mail||mail.replies.some(r=>r.id===m.id))return false;const notice=mail.notifications.find(n=>n.ticket===token),w=d.operations?.workOrders.find(w=>w.id===notice?.workId),sender=m.from?.emailAddress?.address?.toLowerCase(),date=m.receivedDateTime.slice(0,10);if(!w||!sender||!Number.isFinite(Date.parse(m.receivedDateTime))||Date.parse(m.receivedDateTime)<Date.parse(notice!.created))return false;const match=d.operations?.tenants?.some(t=>t.unitId===w.unitId&&t.start<=date&&(!t.end||t.end>=date)&&[t.email,t.secondEmail].some(e=>e?.trim().toLowerCase()===sender));if(!match)return false;const text=(m.body?.content??m.bodyPreview??'').slice(0,12000);if(!text.trim())return false;mail.replies.push({id:m.id,workId:w.id,received:m.receivedDateTime,from:sender,text});return true;}
