'use client';
import {useCompanyBrand} from './company-brand';
import {emailDomain} from '@/lib/company-accounts';

import {useEffect,useState} from 'react';
import './login.css';
export default function Login({previewName}:{previewName?:string}={}){const [microsoft,setMicrosoft]=useState(false),[setup,setSetup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[confirm,setConfirm]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{if(previewName)return;if(new URLSearchParams(window.location.search).get('microsoft')==='failed')setError('Microsoft sign-in failed or this account has no approved OG access. Use your existing login or contact the administrator.');fetch('/api/auth').then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setSetup(j.setupAvailable);setMicrosoft(j.microsoftEnabled===true);if(j.setupAvailable)setEmail('mmartinez@devonshirecondos.com');}).catch(e=>setError(e.message));},[previewName]);const brand=useCompanyBrand(email);const companyName=previewName||(!brand.company&&emailDomain(email)==='devonshirecondos.com'?'Devonshire Leasing Agency Inc':brand.name);async function submit(e:React.FormEvent){e.preventDefault();setError('');if(setup&&password!==confirm){setError('Passwords do not match');return;}setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:setup?'setup':'login',email,password,token,company:brand.company})}),j=await r.json();if(!r.ok)throw Error(j.error);setPassword('');setToken('');window.location.assign(j.redirect==='/platform'?'/platform':'/workspace');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function microsoftSignIn(){setBusy(true);setError('');try{const r=await fetch('/api/auth/microsoft',{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.error);window.location.assign(j.url);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <main className="og-login"><header className="og-login-header"><a href="/" className="og-login-brand" aria-label="Opervix main page">OPERVIX<span>GROUP</span></a><a href="/">← Back to main page</a></header><div className="og-login-layout"><aside className="og-login-intro"><p>THE OPERVIX EXPERIENCE</p><h2>Exceptional homes.<br/>Connected living.</h2><span>Your property workspace, thoughtfully connected.</span></aside><section className="panel login-card"><img src="/opervix-logo-luxury.webp" alt="Opervix Group" width="80" height="80"/><h1>{setup?'Set up Company Admin':companyName?'Sign in to '+companyName:'Sign in to OG'}</h1><p>Secure Workspace · Property Management</p>{previewName&&<p className="hint">Design preview · sign-in disabled</p>}{setup&&<p>Miguel Martinez · 210-576-1708. SMS authentication is deferred. Enter the setup token configured privately on the server.</p>}<form onSubmit={submit}>{!setup&&brand.domain&&<p className="hint">Account domain: {brand.domain}</p>}<label className="field">Email<input required type="email" autoComplete="username" value={email} readOnly={setup} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Password<input id="login-password" required type={showPassword?'text':'password'} minLength={setup?12:undefined} maxLength={128} autoComplete={setup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="check"><input type="checkbox" style={{width:16,height:16}} checked={showPassword} onChange={e=>setShowPassword(e.target.checked)} aria-controls="login-password"/>Show password</label>{setup&&<><label className="field">Confirm password<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><label className="field">Private setup token<input required type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label></>}{error&&<p role="alert" className="import-errors">{error}</p>}<button disabled={busy||!!previewName}>{busy?'Please wait…':setup?'Create Global Admin':'Sign in'}</button></form>{!setup&&microsoft&&<button disabled={busy} onClick={microsoftSignIn}>Sign in with Microsoft 365</button>}<p className="hint">New company? <a href="/onboarding">Start onboarding</a>. <a href="/forgot-password">Forgot password? Reset by email</a>.</p></section></div></main>;}
