import {queueWorkChanges} from '@/lib/work-mail-model';
import {mailConfigured,processWorkMail} from '@/lib/server/work-mail';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {access,sameOrigin,body} from '@/lib/server/request';
import {load,save} from '@/lib/storage';
import {scopedPortal,scopedUnits} from '@/lib/access-policy';
import {audit,latest,type Data} from '@/lib/pool';
import {emptyOperations,type WorkOrder,type TenantEntry} from '@/lib/operations-model';
import {applyTenantReceipt} from '@/lib/accounting-model';
import {systemLog} from '@/lib/system-log';
export async function GET(){try{const u=access(await getChatGPTUser(),['Maintenance','Accounting Clerk']),snapshot=await load(u.userId);return Response.json({revision:snapshot.revision,...scopedPortal(u.member,snapshot.data)},{headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({error:'Access denied or records unavailable'},{status:403});}}
export async function POST(request:Request){try{sameOrigin(request);const u=access(await getChatGPTUser(),['Maintenance','Accounting Clerk']),p=await body(request,10000),old=await load(u.userId,p.operation);if(old.operationApplied)return Response.json({ok:true,revision:old.revision});if(p.revision!==old.revision)throw Error('CONFLICT: Records changed. Reload before saving.');if(typeof p.operation!=='string'||!p.operation||p.operation.length>100)throw Error('Invalid operation');const next=structuredClone(old.data),units=new Set(scopedUnits(u.member,next).map(x=>x.id));next.operations??=emptyOperations();const now=new Date().toISOString();
 if(u.role==='Maintenance'){if(p.action!=='workOrder'||!p.work||!units.has(p.work.unitId))throw Error('Work order access denied');const w=p.work as WorkOrder;const previous=next.operations.workOrders.find(x=>x.id===w.id);if(previous&&!units.has(previous.unitId))throw Error('Work order access denied');const allowed={id:previous?.id??crypto.randomUUID(),number:previous?.number??'WO-'+crypto.randomUUID().slice(0,8),unitId:previous?.unitId??w.unitId,title:String(w.title??'').slice(0,200),description:String(w.description??'').slice(0,2000),status:w.status,priority:w.priority,kind:w.kind,assignee:String(w.assignee??'').slice(0,200),vendor:previous?.vendor??'',scheduled:String(w.scheduled??''),followUp:previous?.followUp??'',estimate:previous?.estimate??0,hours100:Number(w.hours100??0),rate:previous?.rate??0,materials:previous?.materials??0,ownerApproved:previous?.ownerApproved??false,notes:String(w.notes??'').slice(0,2000),permissionToEnter:w.permissionToEnter,entryInstructions:String(w.entryInstructions??'').slice(0,2000),created:previous?.created??now,updated:now};if(previous)Object.assign(previous,allowed);else next.operations.workOrders.push(allowed);audit(next,'Work order saved',allowed.number+' · '+u.displayName);}
 else if(p.action==='entry'){if(p.kind==='Receipt'&&!['Check','Money Order',"Cashier's Check"].includes(p.paymentMethod))throw Error('Choose Check, Money Order or Cashier’s Check');if(!['Rent','Other'].includes(p.category))throw Error('Choose a charge category');const t=next.operations.tenants?.find(t=>t.id===p.tenantId&&units.has(t.unitId));if(!t)throw Error('Tenant access denied');next.operations.tenantEntries??=[];const e:TenantEntry={id:crypto.randomUUID(),tenantId:t.id,kind:p.kind,date:String(p.date),description:String(p.description??'').slice(0,500),cents:p.cents,reference:String(p.reference??'').slice(0,200),category:p.category,paymentMethod:p.paymentMethod};next.operations.tenantEntries.push(e);audit(next,'Tenant entry posted',t.id+' · '+e.kind+' · '+u.displayName);}
 else if(p.action==='match'){const entries=next.operations.tenantEntries??[],r=entries.find(e=>e.id===p.receiptId&&e.kind==='Receipt'),c=entries.find(e=>e.id===p.chargeId&&e.kind==='Charge');if(!r||!c||r.tenantId!==c.tenantId||!next.operations.tenants?.some(t=>t.id===r.tenantId&&units.has(t.unitId)))throw Error('Receipt matching access denied');applyTenantReceipt(next,r.id,c.id,p.cents,c.category);}
 else if(p.action==='expense'){const s=next.statements.find(s=>s.id===p.statementId&&units.has(s.unitId)&&s.status==='Pending');if(!s||latest(next,s.period).find(x=>x.unitId===s.unitId)?.id!==s.id)throw Error('Use the latest draft statement for an assigned unit');if(typeof p.label!=='string'||typeof p.recipient!=='string'||!p.label.trim()||!p.recipient.trim())throw Error('Enter the expense and recipient');s.expenses.push({id:crypto.randomUUID(),label:p.label.slice(0,200),cents:p.cents,recipient:p.recipient.slice(0,200),classification:String(p.classification??'Confirm classification').slice(0,200),gl:String(p.gl??'').slice(0,20)});audit(next,'Draft unit expense entered',s.unitId+' · '+u.displayName);}
 else throw Error('Accounting Clerk cannot approve, pay, change allocation rules or administer users');
 queueWorkChanges(old.data,next,mailConfigured());
 for(const event of next.audit)if(!old.data.audit.some(x=>x.id===event.id))Object.assign(event,{actor:u.displayName,actorId:u.authId});let result=await save(u.userId,p.revision,p.operation,next);if(u.role==='Maintenance'&&mailConfigured()){try{await processWorkMail(u.userId);}catch{await systemLog(u.userId,u.displayName,'Connection','Error','Work email needs review','Check email queue');}result=await load(u.userId);}await systemLog(u.userId,u.displayName,'Records','Info','Scoped records saved',u.role+' · revision '+result.revision);return Response.json({ok:true,revision:result.revision});
 }catch(e){const error=e instanceof Error?e.message:'Save failed';return Response.json({error},{status:error.startsWith('CONFLICT')?409:400});}}
