import {platformOwner} from '@/lib/server/platform';
import {admin,rpc} from '@/lib/server/supabase';
import {sameOrigin,body,password} from '@/lib/server/request';
import {companyDetails,newCompanyData} from '@/lib/company-accounts';
import {systemLog} from '@/lib/system-log';
export async function GET(){try{if(!await platformOwner())throw Error();const result=await admin().from('og_companies').select('workspace_id,name,login_slug,email_domain,status').order('name');if(result.error)throw Error();return Response.json(result.data,{headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({error:'Platform owner access required'},{status:403});}}
export async function POST(request:Request){try{sameOrigin(request);const owner=await platformOwner();if(!owner)throw Error('Platform owner access required');const p=await body(request),details=companyDetails(p);
 if(p.action==='update'){if(typeof p.workspace_id!=='string'||!['Active','Disabled'].includes(p.status))throw Error('Choose a company and status');const result=await admin().from('og_companies').update({...details,status:p.status,updated:new Date().toISOString()}).eq('workspace_id',p.workspace_id).select('workspace_id').single();if(result.error||!result.data)throw Error('Company update failed');await systemLog(p.workspace_id,owner.email,'Access','Info','Company access updated',details.name+' · '+p.status);return Response.json({ok:true});}
 if(p.action!=='create'||typeof p.adminEmail!=='string'||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.adminEmail)||typeof p.adminName!=='string'||!p.adminName.trim()||p.adminName.length>200)throw Error('Enter administrator details');const reserved=await admin().from('og_platform_owners').select('email').eq('email',p.adminEmail.trim().toLowerCase()).maybeSingle();if(reserved.error||reserved.data)throw Error('Use a separate client administrator email');const payload=newCompanyData(details.name,p.month,crypto.randomUUID()),created=await admin().auth.admin.createUser({email:p.adminEmail.trim().toLowerCase(),password:password(p.password),email_confirm:true,user_metadata:{name:p.adminName.trim()}});if(created.error||!created.data.user)throw Error('Use a new client administrator email; existing accounts are never reassigned');try{await rpc('og_create_company',{p_actor:owner.authId,p_workspace:crypto.randomUUID(),p_name:details.name,p_slug:details.login_slug,p_domain:details.email_domain,p_auth:created.data.user.id,p_email:p.adminEmail.trim().toLowerCase(),p_admin_name:p.adminName.trim(),p_payload:payload});}catch{await admin().auth.admin.deleteUser(created.data.user.id);throw Error('Company creation failed; no existing client account was changed');}return Response.json({ok:true});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Company administration unavailable'},{status:400});}}
