import {getChatGPTUser} from '@/app/chatgpt-auth';
import {admin,rpc,serverConfig} from '@/lib/server/supabase';
import {access,sameOrigin,body,password} from '@/lib/server/request';
import {canManage,type Member} from '@/lib/access-policy';
import {STAFF_ROLES} from '@/lib/staff-users';
export async function GET(){try{const u=access(await getChatGPTUser(),['Global Admin','Management']);const {data,error}=await admin().from('og_app_users').select('*').eq('workspace_id',u.userId).order('created');if(error)throw Error('User directory unavailable');return Response.json(data,{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'User administration access denied'},{status:403});}}
export async function POST(request:Request){try{sameOrigin(request);const u=access(await getChatGPTUser(),['Global Admin','Management']),p=await body(request);if(!['create','update','reset'].includes(p.action))throw Error('Invalid user action');const existing=p.authId?await admin().from('og_app_users').select('*').eq('auth_id',p.authId).eq('workspace_id',u.userId).single():null;const target=existing?.data as Member|null;if(p.action!=='create'&&!target)throw Error('User not found');const role=p.action==='reset'?target!.role:p.role;if(!STAFF_ROLES.includes(role)||!canManage(u.member,target??{auth_id:'new',role},role))throw Error('You cannot manage this user or role');
 if(p.action==='reset'){const next=password(p.password);const {error:lockError}=await admin().from('og_app_users').update({must_change_password:true,updated:new Date().toISOString()}).eq('auth_id',target!.auth_id).eq('workspace_id',u.userId);if(lockError)throw Error('Password reset preparation failed');const revoked=await admin().from('og_app_sessions').update({active:false}).eq('auth_id',target!.auth_id).eq('workspace_id',u.userId);if(revoked.error)throw Error('Unable to revoke existing sessions');const {error}=await admin().auth.admin.updateUserById(target!.auth_id,{password:next});if(error)throw Error('Password reset failed');await (await import('@/lib/system-log')).systemLog(u.userId,u.displayName,'Access','Info','Temporary password reset',target!.name+' must change their password before accessing records');return Response.json({ok:true});}
 const name=typeof p.name==='string'?p.name.trim():'',email=typeof p.email==='string'?p.email.trim().toLowerCase():'';if(!name||name.length>200||!email||email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!Array.isArray(p.propertyIds)||!['Active','Disabled'].includes(p.status)||typeof p.phone!=='string'||p.phone&&!/^\+[1-9]\d{7,14}$/.test(p.phone))throw Error('Enter valid user details and property access');if(target&&email!==target.email)throw Error('Login email is locked; create a separate account for a new email');const reserved=await admin().from('og_platform_owners').select('email').eq('email',email).maybeSingle();if(reserved.error||reserved.data)throw Error('This address is reserved for platform administration');let authId=target?.auth_id,created=false;if(p.action==='create'){const {data,error}=await admin().auth.admin.createUser({email,password:password(p.password),email_confirm:true,user_metadata:{name}});if(error||!data.user)throw Error('Unable to create this account. Duplicate email addresses are rejected.');authId=data.user.id;created=true;}
 try{await rpc('og_manage_member',{p_actor:u.authId,p_workspace:u.userId,p_target:authId!,p_name:name,p_email:email,p_phone:p.phone,p_role:role,p_properties:p.propertyIds,p_status:p.status});}catch(e){if(created)await admin().auth.admin.deleteUser(authId!);throw e;}return Response.json({ok:true});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Unable to save user'},{status:400});}}
