import {createHash} from 'node:crypto';
import {admin,sessionClient,rpc,registerSession} from '@/lib/server/supabase';
import {sameOrigin,body,password} from '@/lib/server/request';
import {companyDetails,newCompanyData,PLATFORM_OWNER_EMAIL} from '@/lib/company-accounts';
import {billingMonth} from '@/lib/subscription';
export async function GET(){try{const client=await sessionClient(),result=await client.auth.getUser();return Response.json({enabled:process.env.OG_PUBLIC_ONBOARDING==='true',verified:!!result.data.user?.email_confirmed_at},{headers:{'Cache-Control':'private, no-store'}});}catch{return Response.json({enabled:false,verified:false},{headers:{'Cache-Control':'no-store'}});}}
export async function POST(request:Request){try{sameOrigin(request);if(process.env.OG_PUBLIC_ONBOARDING!=='true')throw Error('New account registration is not open yet. Contact Opervix for onboarding.');const p=await body(request),client=await sessionClient(),window=Math.floor(Date.now()/900000),ip=createHash('sha256').update(request.headers.get('x-forwarded-for')?.split(',')[0]??'unknown').digest('hex');if(!await rpc('og_auth_attempt',{p_bucket:`onboarding:${window}`,p_limit:100})||!await rpc('og_auth_attempt',{p_bucket:`onboarding:${window}:${ip}`,p_limit:8}))return Response.json({error:'Too many attempts. Try again in 15 minutes.'},{status:429});
 if(['signup','signin','verify'].includes(p.action)){if(typeof p.email!=='string'||p.email.length>254||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))throw Error('Enter a valid email');const email=p.email.trim().toLowerCase();if(email===PLATFORM_OWNER_EMAIL)throw Error('Use the protected Super Admin sign-in');if(p.action==='verify'){if(typeof p.code!=='string'||! /^\d{6,10}$/.test(p.code))throw Error('Enter the verification code');const result=await client.auth.verifyOtp({email,token:p.code,type:'signup'});if(result.error)throw Error('Verification failed. Check your email or request a new account email.');}else if(p.action==='signin'){if(typeof p.password!=='string'||p.password.length>128)throw Error('Enter your password');const result=await client.auth.signInWithPassword({email,password:p.password});if(result.error)throw Error('Unable to sign in. Verify your email first.');}else{const reserved=await admin().from('og_platform_owners').select('email').eq('email',email).maybeSingle();if(reserved.error||reserved.data)throw Error('Use a client email');const result=await client.auth.signUp({email,password:password(p.password),options:{emailRedirectTo:new URL('/onboarding/confirm',process.env.OG_APP_URL).href}});if(result.error)throw Error('Unable to register. Try signing in if you already have an account.');if(result.data.session){await client.auth.signOut({scope:'local'});throw Error('Email confirmation must be enabled before public registration can open.');}return Response.json({ok:true,message:'Check your email to confirm your account, then return here to continue.'});}return Response.json({ok:true});}
 if(p.action!=='create'||p.acknowledged!==true)throw Error('Acknowledge the monthly pricing to continue');const verified=await client.auth.getUser(),user=verified.data.user;if(verified.error||!user?.email_confirmed_at)throw Error('Verify your email before creating a company');if(typeof p.adminName!=='string'||!p.adminName.trim()||p.adminName.length>200)throw Error('Enter your name');const details=companyDetails(p),payload=newCompanyData(details.name,billingMonth(),crypto.randomUUID());await rpc('og_onboard_company',{p_auth:user.id,p_name:details.name,p_slug:details.login_slug,p_domain:details.email_domain,p_admin_name:p.adminName.trim(),p_payload:payload});const session=await registerSession(client,user.id);return Response.json({ok:true,redirect:session.redirect});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Onboarding unavailable'},{status:400});}}
