import {documentBytes,writeDocument,removeUnlinkedDocument,listDocuments} from '@/lib/document-storage';
import {load} from '@/lib/storage';
import {admin} from '@/lib/server/supabase';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {access,sameOrigin} from '@/lib/server/request';
import {documentAllowed,reviewers} from '@/lib/access-policy';
import {systemLog} from '@/lib/system-log';
export async function GET(request:Request){try{const u=access(await getChatGPTUser()),{data}=await load(u.userId);const docs=(await listDocuments(u.userId)).filter(d=>documentAllowed(u.member,data,d.statement_id));const id=new URL(request.url).searchParams.get('id');if(!id)return Response.json(docs.map(d=>({id:d.id,statementId:d.statement_id,expenseId:d.expense_id,name:d.name,mime:d.mime,size:d.size,created:d.created})),{headers:{'Cache-Control':'private, no-store'}});const doc=docs.find(d=>d.id===id);if(!doc)return new Response('Document not found',{status:404});return new Response(await documentBytes(u.userId,doc),{headers:{'Content-Type':doc.mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(doc.name),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}catch{return Response.json({error:'Document access denied or storage unavailable'},{status:403});}}
export async function POST(request:Request){try{sameOrigin(request);const u=access(await getChatGPTUser());if(reviewers(u.role))throw Error('Read-only role');if(Number(request.headers.get('content-length')??0)>11000000)throw Error('File is too large');const form=await request.formData(),file=form.get('file');if(!(file instanceof File)||file.size<1||file.size>10000000||!['application/pdf','image/jpeg','image/png'].includes(file.type)||file.name.length>200)throw Error('Upload a PDF, JPG or PNG up to 10 MB');const {data}=await load(u.userId);let statementId=String(form.get('statementId')),expenseId=String(form.get('expenseId'));const type=String(form.get('linkType')??''),link=String(form.get('linkId')??'');if(type){const exists=type==='purchase'?data.procurement?.purchases.some(x=>x.id===link):type==='deposit'?data.accounting?.deposits.some(x=>x.id===link):type==='lease'?data.operations?.leases.some(x=>x.id===link):type==='work'?data.operations?.workOrders.some(x=>x.id===link):false;if(!exists)throw Error('Unknown document association');statementId=type+':'+link;expenseId=link;}else{const s=data.statements.find(s=>s.id===statementId);if(!s||s.status!=='Pending'||!s.expenses.some(e=>e.id===expenseId))throw Error('Attach documents to a saved draft expense');}if(!documentAllowed(u.member,data,statementId))throw Error('Document access denied');const id=crypto.randomUUID(),key=u.userId+'/'+id,bytes=await file.arrayBuffer(),stored=await writeDocument(u.userId,key,bytes,file.type);const {error}=await admin().from('og_app_documents').insert({id,workspace_id:u.userId,statement_id:statementId,expense_id:expenseId,name:file.name,mime:file.type,size:file.size,key,sha256:stored.sha256});if(error){await removeUnlinkedDocument(u.userId,key);throw Error('Document metadata save failed');}await systemLog(u.userId,u.displayName,'Records','Info','Document attached','Document '+id+' · '+statementId);return Response.json({id,name:file.name});}catch(e){return Response.json({error:e instanceof Error?e.message:'Upload failed'},{status:400});}}
