import {createHash} from 'node:crypto';
import {cookies} from 'next/headers';
import {admin,rpc,sessionClient,serverConfig} from '@/lib/server/supabase';
import {sameOrigin,body,password} from '@/lib/server/request';
import {validRecoveryProof} from '@/lib/password-recovery';
export async function POST(request:Request){try{sameOrigin(request);if(process.env.OG_PASSWORD_RECOVERY!=='true')return Response.json({error:'Email password recovery is awaiting administrator email setup. Contact your company administrator.'},{status:503});const p=await body(request),client=await sessionClient(),window=Math.floor(Date.now()/900000),hash=(v:string)=>createHash('sha256').update(v).digest('hex');if(!await rpc('og_auth_attempt',{p_bucket:`recovery:${window}`,p_limit:100})||!await rpc('og_auth_attempt',{p_bucket:`recovery:${window}:${hash(request.headers.get('x-forwarded-for')?.split(',')[0]??'unknown')}`,p_limit:8}))return Response.json({error:'Too many attempts. Try again in 15 minutes.'},{status:429});
if(p.action==='request'){if(typeof p.email!=='string'||p.email.length>254||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))throw Error('Enter a valid email');const email=p.email.trim().toLowerCase();if(!await rpc('og_auth_attempt',{p_bucket:`recovery-email:${window}:${hash(email)}`,p_limit:3}))return Response.json({ok:true,message:'If an eligible account exists, a password reset link will be sent. Check your inbox and spam folder.'});const origin=new URL(process.env.OG_APP_URL??'');if(origin.protocol!=='https:')throw Error('Recovery configuration unavailable');const result=await client.auth.resetPasswordForEmail(email,{redirectTo:new URL('/auth/recovery',origin).href});if(result.error)return Response.json({error:'Password recovery email is unavailable. Please try later or contact your administrator.'},{status:503});return Response.json({ok:true,message:'If an eligible account exists, a password reset link will be sent. Open it in this browser. Check your inbox and spam folder.'});}
if(p.action!=='reset')throw Error('Unknown recovery action');const store=await cookies(),user=await client.auth.getUser(),claims=await client.auth.getClaims(),sid=claims.data?.claims.session_id;if(user.error||!user.data.user?.email_confirmed_at||claims.error||typeof sid!=='string'||!validRecoveryProof(store.get('og-password-recovery')?.value??'',user.data.user.id,sid,serverConfig().secret))throw Error('Reset link expired. Request a new email.');const authId=user.data.user.id,db=admin();const owner=await db.from('og_platform_owners').select('auth_id').eq('auth_id',authId).eq('active',true).maybeSingle();const member=await db.from('og_app_users').select('workspace_id,status').eq('auth_id',authId).maybeSingle();if(owner.error||member.error)throw Error('Account verification unavailable');if(!owner.data){if(member.data?.status!=='Active')throw Error('No active company access');const company=await db.from('og_companies').select('status').eq('workspace_id',member.data.workspace_id).single();if(company.error||company.data?.status!=='Active')throw Error('No active company access');}const next=password(p.password);for(const table of ['og_app_sessions','og_platform_sessions']){const revoked=await db.from(table).update({active:false}).eq('auth_id',authId);if(revoked.error)throw Error('Session security update failed');}const updated=await client.auth.updateUser({password:next});if(updated.error)throw Error('Password update failed. Request a new reset link.');if(member.data){const cleared=await db.from('og_app_users').update({must_change_password:false,updated:new Date().toISOString()}).eq('auth_id',authId);if(cleared.error)throw Error('Password changed. Contact your administrator to confirm account access.');}store.delete('og-password-recovery');await client.auth.signOut({scope:'global'});return Response.json({ok:true,message:'Password changed. Sign in with your new password.'});
}catch(e){return Response.json({error:e instanceof Error?e.message:'Password recovery unavailable'},{status:400,headers:{'Cache-Control':'no-store'}});}}
